✅ BARCODE SCHEMAS — FULL AND FINAL UNIVERSE (ALL SYMBOLOGIES)

⸻

A. RETAIL / GLOBAL TRADE (GS1)
	1.	BARCODE-UPCA SCHEMA
	2.	BARCODE-UPCE SCHEMA
	3.	BARCODE-EAN8 SCHEMA
	4.	BARCODE-EAN13 SCHEMA
	5.	BARCODE-GTIN8 SCHEMA
	6.	BARCODE-GTIN12 SCHEMA
	7.	BARCODE-GTIN13 SCHEMA
	8.	BARCODE-GTIN14 SCHEMA
	9.	BARCODE-GS1-128 SCHEMA
	10.	BARCODE-GS1-DATABAR-LIMITED SCHEMA
	11.	BARCODE-GS1-DATABAR-EXPANDED SCHEMA
	12.	BARCODE-GS1-DATABAR-STACKED SCHEMA
	13.	BARCODE-SSCC SCHEMA (Serial Shipping Container Code)
	14.	BARCODE-GSIN SCHEMA
	15.	BARCODE-GRIN SCHEMA

⸻

B. PRODUCT / BOOK / MEDIA IDENTIFIERS
	16.	BARCODE-ISBN10 SCHEMA
	17.	BARCODE-ISBN13 SCHEMA
	18.	BARCODE-ISSN SCHEMA
	19.	BARCODE-ISMN SCHEMA
	20.	BARCODE-ISRC SCHEMA
	21.	BARCODE-UPC-COMPATIBLE-ISBN SCHEMA

⸻

C. HEALTHCARE / PHARMACEUTICAL
	22.	BARCODE-HIBC-LIC SCHEMA
	23.	BARCODE-HIBC-UIC SCHEMA
	24.	BARCODE-GS1-HRI SCHEMA
	25.	BARCODE-NDC11 SCHEMA (National Drug Code)
	26.	BARCODE-UDI-DI SCHEMA (FDA UDI Device Identifier)
	27.	BARCODE-UDI-PI SCHEMA (Production Identifier)
	28.	BARCODE-UDI-COMPOSITE SCHEMA

⸻

D. LOGISTICS / SHIPPING / MANUFACTURING
	29.	BARCODE-CODE128 SCHEMA
	30.	BARCODE-CODE39 SCHEMA
	31.	BARCODE-CODE39-FULLASCII SCHEMA
	32.	BARCODE-CODE93 SCHEMA
	33.	BARCODE-ITF14 SCHEMA
	34.	BARCODE-DUN14 SCHEMA
	35.	BARCODE-MSI SCHEMA
	36.	BARCODE-PLESSEY SCHEMA
	37.	BARCODE-POSTNET SCHEMA
	38.	BARCODE-IMB SCHEMA (Intelligent Mail Barcode)
	39.	BARCODE-RM4SCC SCHEMA (Royal Mail)
	40.	BARCODE-AUSTRALIA-POST SCHEMA
	41.	BARCODE-JAPAN-POST SCHEMA
	42.	BARCODE-KIX SCHEMA (Netherlands Post)

⸻

E. TWO-DIMENSIONAL / MATRIX / HIGH-CAPACITY BARCODES
	43.	BARCODE-QR SCHEMA
	44.	BARCODE-MICROQR SCHEMA
	45.	BARCODE-DATAMATRIX SCHEMA
	46.	BARCODE-PDF417 SCHEMA
	47.	BARCODE-MICROPDF417 SCHEMA
	48.	BARCODE-AZTEC SCHEMA
	49.	BARCODE-MAXICODE SCHEMA
	50.	BARCODE-HANXIN SCHEMA
	51.	BARCODE-GRIDMATRIX SCHEMA

⸻

F. ENCODING / ERROR CORRECTION / PAYLOAD
	52.	BARCODE-BINARYPAYLOAD SCHEMA
	53.	BARCODE-ALPHANUMERIC-PAYLOAD SCHEMA
	54.	BARCODE-ECLEVEL SCHEMA (QR EC L/M/Q/H)
	55.	BARCODE-STRUCTURED-APPEND SCHEMA
	56.	BARCODE-VARIABLE-LENGTH SCHEMA
	57.	BARCODE-FIXED-LENGTH SCHEMA

⸻

G. BARCODE INPUT VALIDATION & COERCION
	58.	BARCODE-AUTO-DETECT SCHEMA (detect type from pattern)
	59.	BARCODE-CHECKDIGIT-VERIFY SCHEMA
	60.	BARCODE-CHECKDIGIT-CALCULATE SCHEMA
	61.	BARCODE-NORMALIZE SCHEMA (remove hyphens/spaces)
	62.	BARCODE-PARSE-COMPOSITE SCHEMA (GS1 AI parsing)
	63.	BARCODE-GS1-AI SCHEMA (Application Identifier validator)
	64.	BARCODE-RAW-BITS SCHEMA (low-level decoder validation)

⸻

H. SPECIALIZED INDUSTRIAL / LEGACY
	65.	BARCODE-CODABAR SCHEMA
	66.	BARCODE-CODE11 SCHEMA
	67.	BARCODE-TELEPEN SCHEMA
	68.	BARCODE-PHARMA-CODE SCHEMA
	69.	BARCODE-PHARMA-CODE-COLOR SCHEMA
	70.	BARCODE-BPO SCHEMA (Brazilian Postal Object code)

⸻

I. SECURITY / AUTHENTICATION BARCODES
	71.	BARCODE-SECURE-QR SCHEMA
	72.	BARCODE-QR-ECDSA SCHEMA (signed QR)
	73.	BARCODE-QR-PAYMENT SCHEMA (EMVCo, UPI, etc.)
	74.	BARCODE-TOTP-QR SCHEMA
	75.	BARCODE-CRYPTO-TAG SCHEMA (blockchain anti-fraud)

⸻

J. UX / WEB / MOBILE
	76.	BARCODE-URL-QR SCHEMA
	77.	BARCODE-DEEPLINK-QR SCHEMA
	78.	BARCODE-CONTACT-QR SCHEMA (vCard/meCard)
	79.	BARCODE-WIFI-QR SCHEMA
	80.	BARCODE-LOCATION-QR SCHEMA
	81.	BARCODE-APP-LAUNCH-QR SCHEMA
	82.	BARCODE-EMAIL-QR SCHEMA

⸻

K. IMAGE / DECODING / PREPROCESSING
	83.	BARCODE-IMAGE-BITMAP SCHEMA
	84.	BARCODE-IMAGE-BINARYMAP SCHEMA
	85.	BARCODE-IMAGE-GRAYSCALE SCHEMA
	86.	BARCODE-IMAGE-LUMINANCE SCHEMA
	87.	BARCODE-IMAGE-CLEANED SCHEMA
	88.	BARCODE-IMAGE-BOUNDINGBOX SCHEMA
