/*
    TODO:

1. HEIGHT SCHEMAS
	1.	HEIGHT-CM SCHEMA
	2.	HEIGHT-M SCHEMA
	3.	HEIGHT-FTIN SCHEMA (feet + inches)
	4.	HEIGHT-IN SCHEMA
	5.	HEIGHT-MM SCHEMA
	6.	HEIGHT-IMPERIAL-STRING SCHEMA (“5’11””, “6ft2in”)
	7.	HEIGHT-COERCE SCHEMA (normalize from any unit)
	8.	HEIGHT-NORMALIZED SCHEMA (canonical cm output)
	9.	HEIGHT-RANGE SCHEMA
	10.	HEIGHT-PERCENTILE SCHEMA (CDC/WHO tables)

⸻

2. WEIGHT SCHEMAS
	11.	WEIGHT-KG SCHEMA
	12.	WEIGHT-LB SCHEMA
	13.	WEIGHT-G SCHEMA
	14.	WEIGHT-OZ SCHEMA
	15.	WEIGHT-STONE SCHEMA
	16.	WEIGHT-COERCE SCHEMA (kg/lb/g/oz → kg)
	17.	WEIGHT-NORMALIZED SCHEMA (canonical kg)
	18.	WEIGHT-RANGE SCHEMA
	19.	WEIGHT-PERCENTILE SCHEMA

⸻

3. BODY CIRCUMFERENCE / GIRTH MEASUREMENTS

(Used in tailoring, sizing charts, compression wear, health metrics)
	20.	CHEST-CM SCHEMA
	21.	CHEST-IN SCHEMA
	22.	WAIST-CM SCHEMA
	23.	WAIST-IN SCHEMA
	24.	HIP-CM SCHEMA
	25.	HIP-IN SCHEMA
	26.	NECK-CM SCHEMA
	27.	NECK-IN SCHEMA
	28.	THIGH-CM SCHEMA
	29.	THIGH-IN SCHEMA
	30.	CALF-CM SCHEMA
	31.	CALF-IN SCHEMA
	32.	BICEP-CM SCHEMA
	33.	BICEP-IN SCHEMA
	34.	WRIST-CM SCHEMA
	35.	WRIST-IN SCHEMA

⸻

4. BODY LENGTH MEASUREMENTS
	36.	INSEAM-CM SCHEMA
	37.	INSEAM-IN SCHEMA
	38.	OUTSEAM-CM SCHEMA
	39.	OUTSEAM-IN SCHEMA
	40.	ARM-LENGTH-CM SCHEMA
	41.	ARM-LENGTH-IN SCHEMA
	42.	TORSO-LENGTH-CM SCHEMA
	43.	TORSO-LENGTH-IN SCHEMA
	44.	SHOULDER-WIDTH-CM SCHEMA
	45.	SHOULDER-WIDTH-IN SCHEMA
	46.	BACK-LENGTH-CM SCHEMA
	47.	BACK-LENGTH-IN SCHEMA

⸻

5. GENERAL BODY METRIC SCHEMAS
	48.	BMI SCHEMA (height+weight → numeric)
	49.	BSA SCHEMA (Body Surface Area)
	50.	WHR SCHEMA (Waist–Hip Ratio)
	51.	WTHR SCHEMA (Waist-to-Height)
	52.	BODY-FAT-PERCENT SCHEMA
	53.	LEAN-MASS SCHEMA
	54.	VISCERAL-FAT SCHEMA
	55.	SKELETAL-MUSCLE-PERCENT SCHEMA

⸻

6. CLOTHING SIZE — TOPS (Universal)
	56.	SIZE-ALPHA-TOPS SCHEMA (XS–XXXL)
	57.	SIZE-NUMERIC-TOPS SCHEMA (0–30 US)
	58.	SIZE-CM-TOPS SCHEMA
	59.	SIZE-EU-TOPS SCHEMA
	60.	SIZE-UK-TOPS SCHEMA
	61.	SIZE-JP-TOPS SCHEMA
	62.	SIZE-KR-TOPS SCHEMA

⸻

7. CLOTHING SIZE — BOTTOMS (Pants, shorts, jeans)
	63.	SIZE-PANTS-WAIST-IN SCHEMA
	64.	SIZE-PANTS-WAIST-CM SCHEMA
	65.	SIZE-PANTS-INSEAM-IN SCHEMA
	66.	SIZE-PANTS-INSEAM-CM SCHEMA
	67.	SIZE-JEANS-US SCHEMA (W/L format)
	68.	SIZE-JEANS-EU SCHEMA
	69.	SIZE-JEANS-UK SCHEMA
	70.	SIZE-JEANS-MXS SCHEMA (vanity/offset sizing)

⸻

8. CLOTHING SIZE — SHOES
	71.	SHOE-SIZE-US-MEN SCHEMA
	72.	SHOE-SIZE-US-WOMEN SCHEMA
	73.	SHOE-SIZE-US-YOUTH SCHEMA
	74.	SHOE-SIZE-EU SCHEMA
	75.	SHOE-SIZE-UK SCHEMA
	76.	SHOE-SIZE-JP SCHEMA (cm)
	77.	SHOE-SIZE-MONDO SCHEMA (ski boots)
	78.	SHOE-SIZE-CHINA SCHEMA
	79.	SHOE-SIZE-KOREA SCHEMA
	80.	SHOE-SIZE-MEXICO SCHEMA

⸻

9. CLOTHING SIZE — BRAS
	81.	BRA-BAND-SIZE SCHEMA
	82.	BRA-CUP-SIZE SCHEMA
	83.	BRA-SIZE-FULL SCHEMA (band + cup normalization)
	84.	BRA-SISTER-SIZES SCHEMA

⸻

10. CLOTHING SIZE — UNDERWEAR / LINGERIE
	85.	SIZE-UNDERWEAR-ALPHA SCHEMA
	86.	SIZE-UNDERWEAR-NUMERIC SCHEMA
	87.	SIZE-PANTY-CM SCHEMA
	88.	SIZE-PANTY-IN SCHEMA

⸻

11. CLOTHING SIZE — CHILDREN / INFANTS
	89.	SIZE-KIDS-US SCHEMA
	90.	SIZE-KIDS-EU SCHEMA
	91.	SIZE-KIDS-UK SCHEMA
	92.	SIZE-KIDS-JP SCHEMA
	93.	SIZE-INFANT-MONTHS SCHEMA (0–24)
	94.	SIZE-TODDLER SCHEMA
	95.	SIZE-YOUTH SCHEMA

⸻

12. AVATAR / VR / BODY-SCAN / ANTHROPOLOGY
	96.	BODY-MEASUREMENT-3D-VECTOR SCHEMA
	97.	BODY-MEASUREMENT-POINT-CLOUD SCHEMA
	98.	BODY-MEASUREMENT-POSE SCHEMA
	99.	BODY-MEASUREMENT-FULL-SET SCHEMA
	100.	BODY-PROPORTION-RATIO SET SCHEMA

⸻

13. TAILORING / GARMENT CONSTRUCTION
	101.	TAILOR-NECK-TO-WAIST SCHEMA
	102.	TAILOR-ARMHOLE SCHEMA
	103.	TAILOR-RISE SCHEMA
	104.	TAILOR-FRONT-LENGTH SCHEMA
	105.	TAILOR-BACK-LENGTH SCHEMA
	106.	TAILOR-HIP-DEPTH SCHEMA
	107.	TAILOR-CROTCH-DEPTH SCHEMA
	108.	TAILOR-SHOULDER-SLOPE SCHEMA

⸻

14. FULL UNIFIED SIZE PROFILE SCHEMA
	109.	SIZE-PROFILE-BASIC SCHEMA
	110.	SIZE-PROFILE-ADVANCED SCHEMA
	111.	SIZE-PROFILE-FULL-BODY SCHEMA
	112.	SIZE-PROFILE-FIT-PREFERENCE SCHEMA
	113.	SIZE-PROFILE-COMPUTED SCHEMA (auto fits for all garment categories)

1. Body Posture / Ergonomics (You missed all of these)

Required for: occupational health, ergonomic risk scoring, VR/AR avatars, injury prevention.
	•	POSTURE-SITTING-ANGLE SCHEMA
	•	POSTURE-STANDING-ALIGNMENT SCHEMA
	•	POSTURE-SHOULDER-ASYMMETRY SCHEMA
	•	POSTURE-PELVIC-TILT SCHEMA
	•	POSTURE-SPINAL-CURVATURE SCHEMA (kyphosis/lordosis degrees)
	•	POSTURE-HEAD-FORWARD-ANGLE SCHEMA
	•	GAIT-STRIDE-LENGTH SCHEMA
	•	GAIT-CADENCE SCHEMA
	•	GAIT-ASYMMETRY SCHEMA

⸻

2. Biomechanics (NOT in any previous list)

Used by sports science, PT, rehab.
	•	BIOMECH-JOINT-ANGLE SCHEMA (hip/knee/elbow/ankle)
	•	BIOMECH-JOINT-RANGE-OF-MOTION SCHEMA
	•	BIOMECH-FORCE-OUTPUT SCHEMA
	•	BIOMECH-POWER-OUTPUT SCHEMA
	•	BIOMECH-REPETITION-QUALITY SCHEMA
	•	BIOMECH-SYMMETRY-SCORE SCHEMA

⸻

3. Shoe Fit & Foot Anatomy (Not included)

E-commerce + orthopedics + sports.
	•	FOOT-LENGTH-MM SCHEMA
	•	FOOT-WIDTH-MM SCHEMA
	•	FOOT-ARCH-HEIGHT SCHEMA
	•	FOOT-PRONATION-TYPE SCHEMA (neutral, over, under)
	•	SHOE-WIDTH-SCHEMA (2A, B, D, 2E, 4E, etc.)
	•	SHOE-LAST-TYPE SCHEMA

⸻

4. Hand Measurements (Missed)

Required for gloves, VR controllers, hand-tracking hardware.
	•	HAND-LENGTH-CM SCHEMA
	•	HAND-WIDTH-CM SCHEMA
	•	HAND-CIRCUMFERENCE SCHEMA
	•	GLOVE-SIZE SCHEMA (XS–XXL)

⸻

5. Extended Head / Helmet Sizing (Missing)

Used in safety gear, cycling, sports, VR HMD fitting.
	•	HEAD-LENGTH SCHEMA
	•	HEAD-WIDTH SCHEMA
	•	HEAD-HEIGHT SCHEMA
	•	HEAD-SHAPE SCHEMA (round, oval, long oval)
	•	HELMET-SIZE CM SCHEMA
	•	HELMET-FIT-RATING SCHEMA

⸻

6. “Soft Body” Measurements (Not in your list)

Used in lingerie, shapewear, body scanning, tailoring.
	•	UNDERBUST-CM SCHEMA
	•	OVERBUST-CM SCHEMA
	•	FRONT-RISE-CM SCHEMA
	•	BACK-RISE-CM SCHEMA
	•	LOW-HIP-CIRCUMFERENCE SCHEMA

⸻

7. Compression Wear / Medical Garment Metrics (Missing)
	•	COMPRESSION-CLASS SCHEMA (I, II, III, IV)
	•	COMPRESSION-PRESSURE-MMHG SCHEMA
	•	COMPRESSION-LIMB-CIRCUMFERENCE SCHEMA
	•	COMPRESSION-LENGTH SCHEMA

⸻

8. Body Shape Classification (Not listed)

Used in e-commerce, fashion, 3D avatars.
	•	BODY-SHAPE-CATEGORY SCHEMA
(hourglass, pear, apple, rectangle, inverted-triangle, etc.)
	•	BODY-SHAPE-RATIO SCHEMA
(torso:leg ratio, limb proportion scores)

⸻

9. Motion Capture / XR Avatar Morphology (Not listed)
	•	BODY-LANDMARK-SET SCHEMA
	•	SKELETON-JOINT-POSITION SCHEMA
	•	SKELETON-JOINT-ROTATION SCHEMA
	•	BODY-MORPH-TARGETS SCHEMA
	•	AVATAR-SCALE-PROFILE SCHEMA
	•	AVATAR-SIZE-CATEGORY SCHEMA

⸻

10. Thermal Comfort / Suit Sizing (Not listed)

Used in UX, environment health, clothing design.
	•	THERMAL-COMFORT-INDEX SCHEMA
	•	THERMAL-SWEAT-RATE SCHEMA
	•	THERMAL-INSULATION-CLO SCHEMA (ASHRAE standard)
	•	THERMAL-METABOLIC-RATE SCHEMA
	•	SUIT-SIZE-CM SCHEMA
	•	SUIT-DROP-SIZE SCHEMA (drop 6, drop 8)

⸻

11. Occupational PPE Sizing (Missing)

Required in safety, construction, industrial.
	•	GLOVE-SIZE-ANSI SCHEMA
	•	HELMET-SIZE-ANSI SCHEMA
	•	RESPIRATOR-SIZE SCHEMA
	•	HIGH-VISIBILITY-SIZE SCHEMA

⸻

12. Additional Clothing Size Systems (Not listed)

More regions:
	•	SIZE-EUROPE-WIDE SCHEMA
	•	SIZE-RU SCHEMA
	•	SIZE-BR SCHEMA
	•	SIZE-AU SCHEMA

More garment types:
	•	SIZE-JACKETS-CHEST SCHEMA
	•	SIZE-SUIT-EU SCHEMA
	•	SIZE-DRESS-US SCHEMA
	•	SIZE-DRESS-UK SCHEMA
	•	SIZE-DRESS-EU SCHEMA
	•	SIZE-SKIRT-WAIST SCHEMA
	•	SIZE-SKIRT-HIP SCHEMA

⸻

13. Additional Bra / Underwear Fit Schemas (Missing)
	•	BRA-UNDERBUST-CM SCHEMA
	•	BRA-OVERBUST-CM SCHEMA
	•	BRA-PROJECTION SCHEMA
	•	BRA-SHAPE SCHEMA (full, shallow, projected, etc.)
	•	BRA-WIRE-HEIGHT SCHEMA
	•	UNDERWEAR-RISE SCHEMA
	•	UNDERWEAR-STRETCH-RATIO SCHEMA

    */