A. Temperature & Thermal Metrics

CLIMATE-TEMPERATURE-C
CLIMATE-TEMPERATURE-F
CLIMATE-TEMPERATURE-K
CLIMATE-TEMPERATURE-MAX-C
CLIMATE-TEMPERATURE-MIN-C
CLIMATE-TEMPERATURE-MEAN-C
CLIMATE-TEMPERATURE-ANOMALY
CLIMATE-DEW-POINT-C
CLIMATE-DEW-POINT-F
CLIMATE-WET-BULB-C
CLIMATE-WET-BULB-F
CLIMATE-HEAT-INDEX-C
CLIMATE-HEAT-INDEX-F
CLIMATE-APPARENT-TEMPERATURE
CLIMATE-FEELS-LIKE-C

⸻

B. Humidity & Atmospheric Moisture

CLIMATE-HUMIDITY-RELATIVE
CLIMATE-HUMIDITY-ABSOLUTE
CLIMATE-HUMIDITY-SPECIFIC
CLIMATE-VAPOR-PRESSURE
CLIMATE-VAPOR-PRESSURE-DEFICIT
CLIMATE-DEWPOINT-SPREAD
CLIMATE-SATURATION-PRESSURE

⸻

C. Air Pressure, Density, Stability

CLIMATE-AIR-PRESSURE-HPA
CLIMATE-AIR-PRESSURE-KPA
CLIMATE-AIR-PRESSURE-MSLP
CLIMATE-AIR-DENSITY
CLIMATE-STABILITY-INDEX
CLIMATE-LAPSE-RATE
CLIMATE-CAPES (Convective Available Potential Energy)
CLIMATE-CIN (Convective Inhibition)

⸻

D. Wind & Atmospheric Motion

CLIMATE-WIND-SPEED-MS
CLIMATE-WIND-SPEED-KMH
CLIMATE-WIND-SPEED-MPH
CLIMATE-WIND-GUST-SPEED
CLIMATE-WIND-DIRECTION-DEGREE
CLIMATE-WIND-SHEAR
CLIMATE-WIND-VECTOR-2D
CLIMATE-WIND-VECTOR-3D
CLIMATE-JETSTREAM-SPEED
CLIMATE-TURBULENCE-INDEX

⸻

E. Solar, UV & Radiation

CLIMATE-SOLAR-RADIATION
CLIMATE-SOLAR-INSOLATION
CLIMATE-UV-INDEX
CLIMATE-UV-A-LEVEL
CLIMATE-UV-B-LEVEL
CLIMATE-SOLAR-ANGLE
CLIMATE-LONGWAVE-RADIATION
CLIMATE-SHORTWAVE-RADIATION

⸻

F. Precipitation & Hydrology

CLIMATE-PRECIPITATION-MM
CLIMATE-PRECIPITATION-IN
CLIMATE-PRECIPITATION-TYPE
CLIMATE-PRECIPITATION-PROBABILITY
CLIMATE-PRECIPITATION-RATE
CLIMATE-RAINFALL-INTENSITY
CLIMATE-DRIZZLE-PROBABILITY
CLIMATE-HAIL-PROBABILITY
CLIMATE-ICE-ACCUMULATION
CLIMATE-SNOW-DEPTH-CM
CLIMATE-SNOW-DEPTH-IN
CLIMATE-SNOW-WATER-EQUIVALENT
CLIMATE-SNOW-RATIO
CLIMATE-RIVER-LEVEL
CLIMATE-RIVER-FLOW
CLIMATE-FLOOD-RISK

⸻

G. Cloud & Visibility

CLIMATE-CLOUD-COVER-PERCENT
CLIMATE-CLOUD-BASE-HEIGHT
CLIMATE-CLOUD-TOP-HEIGHT
CLIMATE-CLOUD-THICKNESS
CLIMATE-VISIBILITY-KM
CLIMATE-VISIBILITY-MI
CLIMATE-FOG-PRESENCE
CLIMATE-MIST-PRESENCE
CLIMATE-HAZE-LEVEL

⸻

H. Severe Weather Indices

CLIMATE-STORM-INTENSITY
CLIMATE-LIGHTNING-PROBABILITY
CLIMATE-TORNADO-PROBABILITY
CLIMATE-HURRICANE-CATEGORY
CLIMATE-HURRICANE-WIND-SPEED
CLIMATE-STORM-SURGE-RISK
CLIMATE-HAIL-RISK
CLIMATE-MICROBURST-RISK

⸻

I. Air Quality & Pollutants

CLIMATE-AIR-QUALITY-INDEX
CLIMATE-POLLUTANT-PM25
CLIMATE-POLLUTANT-PM10
CLIMATE-POLLUTANT-CO
CLIMATE-POLLUTANT-NO2
CLIMATE-POLLUTANT-SO2
CLIMATE-POLLUTANT-O3
CLIMATE-POLLUTANT-VOC
CLIMATE-POLLUTANT-LEAD
CLIMATE-SMOKE-INDEX
CLIMATE-ASH-CONCENTRATION

⸻

J. Ocean & Marine Climate

CLIMATE-SST-SEA-SURFACE-TEMP
CLIMATE-OCEAN-HEAT-CONTENT
CLIMATE-SEA-LEVEL-RISE
CLIMATE-SEA-LEVEL-PRESSURE
CLIMATE-SALINITY
CLIMATE-WAVES-HEIGHT
CLIMATE-WAVES-PERIOD
CLIMATE-WAVES-DIRECTION
CLIMATE-CURRENTS-SPEED
CLIMATE-TIDE-LEVEL
CLIMATE-TIDE-RANGE

⸻

K. Drought, Aridity, Agriculture

CLIMATE-DROUGHT-INDEX
CLIMATE-FIRE-WEATHER-INDEX
CLIMATE-SOIL-MOISTURE-PERCENT
CLIMATE-SOIL-MOISTURE-DEPTH
CLIMATE-SOIL-TEMPERATURE-C
CLIMATE-SOIL-TEMPERATURE-F
CLIMATE-CHILL-HOURS
CLIMATE-GROWING-DEGREE-DAYS
CLIMATE-HEATING-DEGREE-DAYS
CLIMATE-COOLING-DEGREE-DAYS

⸻

L. Seasonal & Astronomical

CLIMATE-SUNRISE-TIME
CLIMATE-SUNSET-TIME
CLIMATE-DAYLENGTH
CLIMATE-SEASON-INDEX
CLIMATE-DAY-OF-YEAR-INSOLATION

⸻

M. Climate Oscillations / Global Indices

CLIMATE-ELNINO-INDEX
CLIMATE-LANINA-INDEX
CLIMATE-ENSO-NEUTRAL-PROBABILITY
CLIMATE-PDO-INDEX
CLIMATE-AMO-INDEX
CLIMATE-NAO-INDEX
CLIMATE-AO-INDEX
CLIMATE-MJO-PHASE
CLIMATE-SAO-INDEX

⸻

N. Greenhouse Gas & Emissions

CLIMATE-EMISSIONS-CO2
CLIMATE-EMISSIONS-CH4
CLIMATE-EMISSIONS-N2O
CLIMATE-EMISSIONS-HFC
CLIMATE-EMISSIONS-PFC
CLIMATE-EMISSIONS-SF6
CLIMATE-CARBON-INTENSITY

⸻

O. Biological / Seasonal Allergens

CLIMATE-POLLEN-INDEX
CLIMATE-POLLEN-TREE
CLIMATE-POLLEN-GRASS
CLIMATE-POLLEN-WEED
CLIMATE-SPORE-COUNT

⸻

P. Remote Sensing / Satellite Climate

CLIMATE-SATELLITE-CLOUD-OPTICAL-DEPTH
CLIMATE-SATELLITE-LAND-SURFACE-TEMP
CLIMATE-SATELLITE-NDVI
CLIMATE-SATELLITE-SMOKE-PLUME-DENSITY
CLIMATE-SATELLITE-ICE-COVER
CLIMATE-SATELLITE-SNOW-ALBEDO

⸻

Q. Derived Climate Risk

CLIMATE-HEAT-RISK-SCORE
CLIMATE-FREEZE-RISK
CLIMATE-FROST-RISK
CLIMATE-FIRE-RISK
CLIMATE-LIGHTNING-RISK
CLIMATE-WIND-RISK
CLIMATE-FLOOD-RISK-SCORE
CLIMATE-URBAN-HEAT-ISLAND-SCORE

⸻

R. Unified Climate Objects

CLIMATE-CURRENT-CONDITIONS
CLIMATE-HOURLY-FORECAST
CLIMATE-DAILY-FORECAST
CLIMATE-AIR-QUALITY-PANEL
CLIMATE-EXTREME-WEATHER-PANEL
CLIMATE-SEASONAL-OUTLOOK
CLIMATE-HISTORICAL-RECORD
CLIMATE-NORMALS-PANEL
CLIMATE-RISK-ASSESSMENT
