A. Core Cookie Value Schemas

COOKIE-NAME
COOKIE-VALUE
COOKIE-PAIR (name=value)
COOKIE-ENCODED
COOKIE-DECODED
COOKIE-SIGNED
COOKIE-ENCRYPTED
COOKIE-JSON
COOKIE-NUMERIC
COOKIE-FLAG (boolean cookie)
COOKIE-EMPTY
COOKIE-NONEMPTY

⸻

B. Cookie Attribute Schemas

COOKIE-PATH
COOKIE-DOMAIN
COOKIE-SAMESITE
COOKIE-SAMESITE-STRICT
COOKIE-SAMESITE-LAX
COOKIE-SAMESITE-NONE
COOKIE-SECURE-FLAG
COOKIE-HTTPONLY-FLAG
COOKIE-EXPIRES-DATE
COOKIE-MAX-AGE
COOKIE-PRIORITY
COOKIE-PARTITIONED
COOKIE-DISABLED-FOR-THIRD-PARTY

⸻

C. Cookie Size & Limits

COOKIE-SIZE-BYTES
COOKIE-SIZE-MAX-4096
COOKIE-SIZE-MIN
COOKIE-COUNT-PER-DOMAIN
COOKIE-STORAGE-LIMIT
COOKIE-OVER-LIMIT-FLAG

⸻

D. Structured Cookie Objects

COOKIE-OBJECT
COOKIE-SET-HEADER
COOKIE-SET-MULTI
COOKIE-PARSE-HEADER
COOKIE-REQUEST-COOKIE-OBJECT
COOKIE-RESPONSE-COOKIE-OBJECT
COOKIE-METADATA-OBJECT

⸻

E. Cookie Coercion Schemas

COOKIE-FROM-HEADER
COOKIE-FROM-STRING
COOKIE-FROM-OBJECT
COOKIE-FROM-RECORD
COOKIE-TO-STRING
COOKIE-TO-HEADER
COOKIE-TO-OBJECT

⸻

F. Cookie Type Classification

COOKIE-FIRST-PARTY
COOKIE-THIRD-PARTY
COOKIE-CROSS-SITE
COOKIE-SAME-SITE
COOKIE-PERSISTENT
COOKIE-SESSION
COOKIE-HOST-ONLY
COOKIE-SUPERCOOKIE-RISK (public suffix detection)
COOKIE-TRACKING
COOKIE-NON-TRACKING
COOKIE-NON-ESSENTIAL
COOKIE-ESSENTIAL

⸻

G. Consent, CMP, TCF v2.2 Cookies

COOKIE-TCF-CONSENT-STRING
COOKIE-TCF-VENDOR-CONSENT
COOKIE-TCF-PURPOSE-CONSENT
COOKIE-TCF-SPECIAL-FEATURE-OPTIN
COOKIE-TCF-STACK-PURPOSES
COOKIE-TCF-PUBLISHER-CONSENT
COOKIE-TCF-ADDENDUM
COOKIE-CMP-STATE
COOKIE-CMP-TIMESTAMP
COOKIE-TCF-US-PRIVACY-STRING
COOKIE-GPC-FLAG

⸻

H. Major CMP / Consent Framework Cookies

COOKIE-GOOGLE-CONSENT
COOKIE-GOOGLE-ANALYTICS-CONSENT
COOKIE-FACEBOOK-CONSENT
COOKIE-TIKTOK-CONSENT
COOKIE-HUBSPOT-CONSENT
COOKIE-SHOPIFY-CONSENT
COOKIE-ONESIGNAL-CONSENT
COOKIE-SEGMENT-CONSENT
COOKIE-COOKIEYES
COOKIE-COOKIEBOT
COOKIE-IUBENDA-CONSENT
COOKIE-ONE-TRUST-CONSENT
COOKIE-OSANO-CONSENT
COOKIE-CONVERTKIT-CONSENT
COOKIE-GTAG-CONSENT-MODE
COOKIE-GTM-CONSENT-STATE
COOKIE-GTM-AUTO-BLOCKING

⸻

I. Per-Category Consent Cookies

COOKIE-CONSENT-PREFERENCES
COOKIE-CONSENT-ANALYTICS
COOKIE-CONSENT-MARKETING
COOKIE-CONSENT-FUNCTIONAL
COOKIE-CONSENT-NECESSARY
COOKIE-CONSENT-PERSONALIZATION
COOKIE-CONSENT-ADVERTISING
COOKIE-CONSENT-RETARGETING
COOKIE-CONSENT-ABTESTING
COOKIE-CONSENT-LOCATION

⸻

J. Legal Compliance / Regional Enforcement Cookies

COOKIE-GDPR-STATE
COOKIE-CCPA-STATE
COOKIE-CPRA-STATE
COOKIE-LGPD-STATE
COOKIE-PIPEDA-STATE
COOKIE-PECR-STATE
COOKIE-APP-TRACKING-TRANSPARENCY
COOKIE-DNT-ENABLED
COOKIE-GPC ENABLED

⸻

K. Cookie Detection / Fingerprinting Schemas

COOKIE-PRESENT
COOKIE-READABLE
COOKIE-WRITABLE
COOKIE-DETECT-THIRD-PARTY
COOKIE-DETECT-BLOCKING
COOKIE-DETECT-BROWSER-RESTRICTION
COOKIE-DETECT-STORAGE-POLICY
COOKIE-DETECT-TCF-CMP
COOKIE-DETECT-PRECONSENT
COOKIE-DETECT-POSTCONSENT
COOKIE-NAVIGATOR-COOKIE-ENABLED

⸻

L. Security & Integrity Schemas

COOKIE-SIGNATURE
COOKIE-HMAC
COOKIE-INTEGRITY
COOKIE-TAMPER-DETECTED
COOKIE-JWT-PAYLOAD
COOKIE-JWT-HEADER
COOKIE-JWT-FULL
COOKIE-JWT-EXPIRATION
COOKIE-ROTATION-STATE

⸻

M. Analytics, Marketing & Tracking Cookies

COOKIE-GA
COOKIE-GA4
COOKIE-GTM
COOKIE-FB-P
COOKIE-FB-C
COOKIE-TIKTOK-PX
COOKIE-LINKEDIN-INSIGHT
COOKIE-HOTJAR
COOKIE-OPTIMIZELY
COOKIE-ABTASTY
COOKIE-MIXPANEL
COOKIE-AMPLITUDE
COOKIE-PINTEREST
COOKIE-SNAPCHAT-PX

⸻

N. E-commerce / Personalization Cookies

COOKIE-CART-ID
COOKIE-SESSION-ID
COOKIE-VISITOR-ID
COOKIE-USER-PREFERENCES
COOKIE-LOCALE
COOKIE-CURRENCY
COOKIE-AB-TEST-GROUP
COOKIE-RECOMMENDER-STATE
COOKIE-LAST-VISITED
COOKIE-RECENTLY-VIEWED
COOKIE-LOYALTY-SESSION

⸻

O. Server-Side Cookie Handling (unified)

COOKIE-SERVER-SET
COOKIE-SERVER-DELETE
COOKIE-SERVER-UPDATE
COOKIE-SERVER-ENCODED
COOKIE-SERVER-DECODED
COOKIE-SERVER-SECURE-REQUIRED
COOKIE-SERVER-STRICT-MODE

⸻

P. Browser Compatibility / Behavior

COOKIE-IOS-SAFARI-COMPAT
COOKIE-IOS-WEBVIEW-COMPAT
COOKIE-CHROME-PARTITIONED
COOKIE-FIREFOX-TOTAL-COOKIE-PROTECTION
COOKIE-SAFARI-ITP
COOKIE-EDGE-CHRONIC-MIGRATION

⸻

Q. Unified Cookie Objects

COOKIE-METADATA
COOKIE-STATE-OBJECT
COOKIE-CONSENT-STATE
COOKIE-PREFERENCES-OBJECT
COOKIE-BROWSER-CAPABILITIES
COOKIE-IMPLICIT-CONSENT-STATE
COOKIE-EXPLICIT-CONSENT-STATE
COOKIE-FULL-PROFILE