A. ISO 3166-1 Country Code Schemas (official global standards)

COUNTRY-ISO2
COUNTRY-ISO3
COUNTRY-NUMERIC
COUNTRY-ALPHA2
COUNTRY-ALPHA3
COUNTRY-NUMERIC-STRING
COUNTRY-OFFICIAL-NAME
COUNTRY-SHORT-NAME
COUNTRY-FULL-NAME
COUNTRY-COERCE (auto-detect 2/3/num → ISO2)

⸻

B. Deprecated / Legacy / Historical ISO Country Codes

COUNTRY-ISO2-LEGACY
COUNTRY-ISO3-LEGACY
COUNTRY-NUMERIC-LEGACY
COUNTRY-DISSOLVED-CODES (SU, TP, YU, ZR…)
COUNTRY-TRANSITION-CODES (e.g., “FX”, “BU”)

⸻

C. ISO 3166-2 Subdivision Codes

COUNTRY-SUBDIVISION-CODE
COUNTRY-SUBDIVISION-CODE-FULL (XX-YYY)
COUNTRY-SUBDIVISION-COERCE
COUNTRY-SUBDIVISION-ALPHA
COUNTRY-SUBDIVISION-NUMERIC

⸻

D. Internet / Networking Country Codes

COUNTRY-CC-TLD (Top-level domain)
COUNTRY-CC-TLD-ACTIVE
COUNTRY-CC-TLD-RESERVED
COUNTRY-GEONAME-ID
COUNTRY-UN-M49-CODE
COUNTRY-RIR-REGION (ARIN/RIPE/APNIC/LACNIC/AfriNIC)
COUNTRY-IP-LOCATION
COUNTRY-CLOUDFLARE-REGION
COUNTRY-CLOUDFLARE-COUNTRY-CODE (CF = always ISO2 but normalized via CF rules)

⸻

E. Payment & Commerce Country Codes (industry-specific)

COUNTRY-PAYMENTS-CODE
COUNTRY-SHIPPING-CODE (FedEx/UPS/DHL variants)
COUNTRY-TAX-JURISDICTION
COUNTRY-VAT-AREA
COUNTRY-STRIPE-CODE
COUNTRY-PAYPAL-CODE
COUNTRY-APPLE-PAY-REGION
COUNTRY-GOOGLE-PAY-REGION
COUNTRY-SHOPIFY-MARKET
COUNTRY-ITIN-TAX-REGION
COUNTRY-EORI-REGION

⸻

F. Telecom & SIM Card Country Codes

COUNTRY-ITU-M49
COUNTRY-ITU-MCC (Mobile Country Code)
COUNTRY-ITU-MNC-REGION
COUNTRY-E.164-COUNTRY-CODE
COUNTRY-PHONE-CALLING-CODE
COUNTRY-PHONE-COERCE (parse +00xxx, +xx, xx)
COUNTRY-SMS-REGION
COUNTRY-RCS-REGION

⸻

G. Locale & Internationalization Codes

COUNTRY-IETF-BCP47-REGION (e.g., “US”, “CA”, “GB”)
COUNTRY-LOCALE-COMPONENT
COUNTRY-LOCALE-REGION (en-US → US)
COUNTRY-LANGUAGE-COUNTRY-COMBINATION
COUNTRY-UAX35-REGION
COUNTRY-CLDR-REGION
COUNTRY-REGION-DISPLAY-NAME

⸻

H. Geopolitical & UN-Specific Codes

COUNTRY-UN-ALPHA3
COUNTRY-UN-NUMERIC
COUNTRY-UN-MEMBER-STATE
COUNTRY-UN-OBSERVING-STATE
COUNTRY-UN-REGION (Africa, Americas, Europe…)
COUNTRY-UN-SUBREGION
COUNTRY-WHO-REGION
COUNTRY-WTO-MEMBER-CODE

⸻

I. Security, Compliance & Sanctions Codes

COUNTRY-OFAC-SANCTIONED
COUNTRY-EU-SANCTIONED
COUNTRY-RESTRICTED-EXPORT
COUNTRY-AML-HIGH-RISK
COUNTRY-KYC-ALLOWED
COUNTRY-KYC-RESTRICTED
COUNTRY-FINTRAC-REGION
COUNTRY-PEP-RISK-SCORE

⸻

J. Logistics, Shipping & Address-Centric Codes

COUNTRY-POSTAL-ADDRESS-CODE
COUNTRY-POSTAL-NORMALIZED
COUNTRY-WORLDWIDE-SHIP-ALLOWED
COUNTRY-WORLDWIDE-SHIP-RESTRICTED
COUNTRY-DHL-CODE
COUNTRY-FEDEX-CODE
COUNTRY-UPS-CODE
COUNTRY-AIRPORT-COUNTRY-CODE (IATA → country)
COUNTRY-MARITIME-ISO3166 (ship registry country code)

⸻

K. Web / Analytics / UX Classification Codes

COUNTRY-BROWSER-LOCALE
COUNTRY-DEVICE-LOCALE
COUNTRY-ACCEPT-LANGUAGE-REGION
COUNTRY-GEOIP-PARSE
COUNTRY-GEOIP-CONFIRMED
COUNTRY-REGION-FALLBACK
COUNTRY-INFERRED-FROM-CURRENCY
COUNTRY-INFERRED-FROM-TIMEZONE
COUNTRY-INFERRED-FROM-LANGUAGE

⸻

L. Market / Business / Segmentation Codes

COUNTRY-ECONOMIC-REGION
COUNTRY-LATAM-GROUP
COUNTRY-NORTHAMERICA
COUNTRY-APAC
COUNTRY-EMEA
COUNTRY-G7
COUNTRY-G20
COUNTRY-OECD
COUNTRY-BRICS
COUNTRY-EMERGING-MARKET

⸻

M. Travel & Identity Codes

COUNTRY-PASSPORT-ISSUER
COUNTRY-PASSPORT-NATIONALITY
COUNTRY-VISA-REQUIRED
COUNTRY-VISA-FREE
COUNTRY-VISA-E-VISA
COUNTRY-BORDER-CONTROL
COUNTRY-NATIONALITY-CODE (ICAO)
COUNTRY-ICAO-STATE-CODE

⸻

N. Specialized / Rare Code Categories

COUNTRY-SPORTS-IOC-CODE
COUNTRY-FIFA-CODE
COUNTRY-OLYMPIC-CODE
COUNTRY-UNESCO-CODE
COUNTRY-WMO-CODE (World Meteorological Org.)
COUNTRY-IBAN-COUNTRY-CODE
COUNTRY-SWIFT-COUNTRY-CODE
COUNTRY-AIRLINE-COUNTRY-CODE
COUNTRY-VEHICLE-REGISTRATION-CODE (license plate country code)

⸻

O. Unified Country Schemas

COUNTRY-ANY-CODE
COUNTRY-ANY-OFFICIAL
COUNTRY-ANY-RESOLVED
COUNTRY-VALIDATE-ALL
COUNTRY-UNIFIED-NORMALIZED
COUNTRY-FULL-PROFILE (all codes + metadata)
