A. Core CSS Structural Schemas

CSS-PROPERTY
CSS-PROPERTY-NAME
CSS-PROPERTY-VALUE
CSS-RULE
CSS-RULESET
CSS-DECLARATION
CSS-DECLARATION-LIST
CSS-SELECTOR
CSS-SELECTOR-GROUP
CSS-AT-RULE
CSS-MEDIA-RULE
CSS-SUPPORTS-RULE
CSS-FONT-FACE-RULE
CSS-KEYFRAMES-RULE
CSS-IMPORT-RULE
CSS-LAYER-RULE
CSS-CASCADE-LAYER
CSS-CUSTOM-PROPERTY
CSS-VARIABLE
CSS-COMPUTED-STYLE
CSS-CASCADED-VALUE
CSS-SPECIFICITY

⸻

B. CSS Value Type Schemas (the core grammar types)

CSS-LENGTH
CSS-PERCENT
CSS-NUMBER
CSS-INTEGER
CSS-ANGLE
CSS-TIME
CSS-FREQUENCY
CSS-FLEX
CSS-GRID-FRACTION
CSS-RESOLUTION
CSS-URL
CSS-STRING
CSS-IDENT
CSS-COLOR
CSS-IMAGE
CSS-FUNCTION
CSS-CALC
CSS-MINMAX
CSS-CLAMP
CSS-TRANSFORM-FUNCTION
CSS-KEYWORD
CSS-TOKEN
CSS-DIMENSION
CSS-RATIO
CSS-MATRIX

⸻

C. CSS Color Schemas

CSS-COLOR-HEX
CSS-COLOR-RGB
CSS-COLOR-RGBA
CSS-COLOR-HSL
CSS-COLOR-HSLA
CSS-COLOR-HWB
CSS-COLOR-LAB
CSS-COLOR-LCH
CSS-COLOR-OKLAB
CSS-COLOR-OKLCH
CSS-COLOR-DISPLAY-P3
CSS-COLOR-NAMED
CSS-COLOR-SPOT
CSS-COLOR-FUNCTION
CSS-COLOR-COERCE
CSS-COLOR-ANY

⸻

D. CSS Shadow / Filter Value Schemas

CSS-BOX-SHADOW
CSS-TEXT-SHADOW
CSS-FILTER
CSS-FILTER-FUNCTION
CSS-BLUR
CSS-DROP-SHADOW

⸻

E. CSS Layout Schemas

CSS-DISPLAY
CSS-POSITION
CSS-FLOAT
CSS-CLEAR
CSS-ZINDEX
CSS-MARGIN
CSS-PADDING
CSS-BORDER
CSS-BORDER-RADIUS
CSS-SIZE
CSS-WIDTH
CSS-HEIGHT
CSS-ASPECT-RATIO
CSS-OVERFLOW
CSS-CONTAIN
CSS-CONTAINER-NAME
CSS-CONTAINER-TYPE
CSS-CONTAINER-QUERY
CSS-CONTAINER-UNIT
CSS-BOX-SIZING
CSS-ALIGN
CSS-JUSTIFY
CSS-GAP
CSS-GRID-TEMPLATE
CSS-GRID-AREA
CSS-GRID-LINE
CSS-GRID-AUTO
CSS-FLEX-DIRECTION
CSS-FLEX-WRAP
CSS-FLEX-GROW
CSS-FLEX-SHRINK
CSS-FLEX-BASIS
CSS-FLEX-FLOW

⸻

F. Typography Schemas

CSS-FONT-SIZE
CSS-FONT-WEIGHT
CSS-FONT-STYLE
CSS-FONT-VARIANT
CSS-FONT-FAMILY
CSS-FONT-FEATURE
CSS-FONT-OPTICAL-SIZING
CSS-LINE-HEIGHT
CSS-LETTER-SPACING
CSS-WORD-SPACING
CSS-TEXT-TRANSFORM
CSS-TEXT-DECORATION
CSS-TEXT-ALIGN
CSS-TEXT-JUSTIFY
CSS-TEXT-OVERFLOW
CSS-WHITE-SPACE
CSS-WRITING-MODE
CSS-DIRECTION

⸻

G. CSS Animation Schemas

CSS-ANIMATION-NAME
CSS-ANIMATION-DURATION
CSS-ANIMATION-TIMING-FUNCTION
CSS-ANIMATION-DELAY
CSS-ANIMATION-ITERATION-COUNT
CSS-ANIMATION-DIRECTION
CSS-ANIMATION-FILL-MODE
CSS-ANIMATION-PLAY-STATE
CSS-KEYFRAME-OFFSET
CSS-KEYFRAME-SELECTOR

⸻

H. CSS Transition Schemas

CSS-TRANSITION-PROPERTY
CSS-TRANSITION-DURATION
CSS-TRANSITION-TIMING-FUNCTION
CSS-TRANSITION-DELAY

⸻

I. CSS Transform Schemas

CSS-TRANSFORM
CSS-TRANSFORM-ORIGIN
CSS-TRANSFORM-STYLE
CSS-PERSPECTIVE
CSS-PERSPECTIVE-ORIGIN
CSS-MATRIX-2D
CSS-MATRIX-3D
CSS-ROTATE
CSS-SCALE
CSS-TRANSLATE
CSS-SKEW

⸻

J. CSS Background & Image Schemas

CSS-BACKGROUND
CSS-BACKGROUND-COLOR
CSS-BACKGROUND-IMAGE
CSS-BACKGROUND-SIZE
CSS-BACKGROUND-POSITION
CSS-BACKGROUND-ATTACHMENT
CSS-BACKGROUND-CLIP
CSS-BACKGROUND-ORIGIN
CSS-BACKGROUND-REPEAT
CSS-IMAGE-GRADIENT
CSS-LINEAR-GRADIENT
CSS-RADIAL-GRADIENT
CSS-CONIC-GRADIENT
CSS-GRADIENT-INTERPOLATION-METHOD

⸻

K. CSS Border / Outline Schemas

CSS-BORDER-WIDTH
CSS-BORDER-STYLE
CSS-BORDER-COLOR
CSS-BORDER-RADIUS
CSS-BORDER-CORNER
CSS-OUTLINE-WIDTH
CSS-OUTLINE-STYLE
CSS-OUTLINE-COLOR
CSS-OUTLINE-OFFSET

⸻

L. CSS Media Query Schemas

CSS-MEDIA-FEATURE
CSS-MEDIA-RESOLUTION
CSS-MEDIA-COLOR-GAMUT
CSS-MEDIA-PREFERS-COLOR-SCHEME
CSS-MEDIA-PREFERS-REDUCED-MOTION
CSS-MEDIA-PREFERS-CONTRAST
CSS-MEDIA-HOVER
CSS-MEDIA-POINTER
CSS-MEDIA-ORIENTATION
CSS-MEDIA-ASPECT-RATIO
CSS-MEDIA-WIDTH
CSS-MEDIA-HEIGHT

⸻

M. CSS Logical Properties Schemas

CSS-INSET
CSS-INSET-BLOCK
CSS-INSET-INLINE
CSS-MARGIN-BLOCK
CSS-PADDING-BLOCK
CSS-BORDER-BLOCK
CSS-SIZE-BLOCK
CSS-SIZE-INLINE
CSS-FLOW-RELATIVE-DIRECTION

⸻

N. CSS Printing / Page Schemas

CSS-PAGE
CSS-PAGE-SIZE
CSS-PAGE-MARGIN
CSS-PRINT-MARKS
CSS-PAGE-ORIENTATION

⸻

O. CSS Variables / Tokens / Design System Schemas

CSS-TOKEN-COLOR
CSS-TOKEN-SPACING
CSS-TOKEN-TYPOGRAPHY
CSS-TOKEN-RADIUS
CSS-TOKEN-SHADOW
CSS-TOKEN-ZINDEX
CSS-TOKEN-ANIMATION
CSS-TOKEN-GRID
CSS-TOKEN-FONT
CSS-TOKEN-BORDER
CSS-TOKEN-OPACITY
CSS-TOKEN-SCALE
CSS-TOKEN-DEPTH
CSS-TOKEN-BREAKPOINT
CSS-TOKEN-THEME-MODE
CSS-THEME
CSS-THEME-MAP
CSS-THEME-RESOLVED

⸻

P. CSS Parsing / Validation Schemas

CSS-PARSER-TOKEN
CSS-PARSER-TOKEN-STREAM
CSS-PARSER-AST
CSS-PARSER-AST-NODE
CSS-SYNTAX-CHECK
CSS-SYNTAX-RULE
CSS-SYNTAX-VALUE
CSS-SYNTAX-FUNCTION
CSS-VALIDATION-ERROR
CSS-VALIDATION-WARNINGS
CSS-LINT-RULE

⸻

Q. CSS Framework / Utility Integration (Tailwind, Bootstrap, etc.)

CSS-UTILITY-CLASS
CSS-UTILITY-GROUP
CSS-UTILITY-PREFIX
CSS-UTILITY-MODIFIER
CSS-UTILITY-VARIANT
CSS-BREAKPOINT
CSS-SPACING-SCALE
CSS-COLOR-SCALE
CSS-RADIUS-SCALE
CSS-SHADOW-SCALE
CSS-TYPO-SCALE
CSS-MAPPING-UTILITY-TO-CSS
CSS-TAILWIND-CLASS
CSS-TAILWIND-RESPONSIVE
CSS-TAILWIND-ARBITRARY-VALUE

⸻

R. CSS Custom Engines (CSS-in-JS)

CSS-IN-JS-PROPERTY
CSS-IN-JS-VARIABLE
CSS-IN-JS-RULE
CSS-IN-JS-CSS-OBJECT
CSS-IN-JS-AT-RULE
CSS-IN-JS-SHORTHAND
CSS-IN-JS-STYLED-COMPONENT
CSS-IN-JS-THEME
CSS-IN-JS-SYSTEM-PROP

⸻

S. CSS Metadata / Performance Schemas

CSS-SPECIFICITY-SCORE
CSS-SIZE-BYTES
CSS-FILE-SIZE-LIMIT
CSS-RULE-COUNT
CSS-RENDER-COST
CSS-COMPUTE-TIME
CSS-CRITICAL-PATH
CSS-ABOVE-THE-FOLD
CSS-PERF-BUDGET

⸻

T. Unified CSS Schemas

CSS-VALUE-ANY
CSS-PROPERTY-ANY
CSS-RULE-ANY
CSS-FULL-DECLARATION
CSS-FULL-STYLESHEET
CSS-FULL-COMPUTED-STYLE
CSS-FULL-THEME
CSS-FULL-PARSER-OUTPUT