✅ SECTION 1 — BASE DATA RATE UNITS (ABSOLUTE FUNDAMENTALS)

These are fundamental:
	1.	BIT-PER-SECOND SCHEMA (bps)
	2.	KILOBIT-PER-SECOND SCHEMA (kbps / kbit/s)
	3.	MEGABIT-PER-SECOND SCHEMA (Mbps / Mbit/s)
	4.	GIGABIT-PER-SECOND SCHEMA (Gbps)
	5.	TERABIT-PER-SECOND SCHEMA (Tbps)
	6.	PETABIT-PER-SECOND SCHEMA (Pbps)
	7.	BYTE-PER-SECOND SCHEMA (B/s)
	8.	KILOBYTE-PER-SECOND SCHEMA (kB/s)
	9.	MEGABYTE-PER-SECOND SCHEMA (MB/s)
	10.	GIGABYTE-PER-SECOND SCHEMA (GB/s)
	11.	TERABYTE-PER-SECOND SCHEMA (TB/s)
	12.	OCTET-PER-SECOND SCHEMA
	13.	DATA-RATE-COERCE SCHEMA (any → bps)
	14.	DATA-RATE-NORMALIZED SCHEMA (canonical bps)

⸻

✅ SECTION 2 — NETWORKING + TELECOM (REAL-WORLD THROUGHPUT TYPES)

These represent actual networking measurement categories:
	15.	THROUGHPUT-THEORETICAL SCHEMA
	16.	THROUGHPUT-ACTUAL SCHEMA
	17.	THROUGHPUT-EFFECTIVE SCHEMA
	18.	GOODPUT SCHEMA (useful payload rate)
	19.	LATENCY-ADJUSTED-THROUGHPUT SCHEMA
	20.	JITTER-ADJUSTED-RATE SCHEMA
	21.	RETRANSMIT-LOSS-ADJUSTED-RATE SCHEMA
	22.	LINK-RATE SCHEMA (L1 raw signaling)
	23.	NET-DATA-RATE SCHEMA (L2 after FEC)
	24.	PAYLOAD-RATE SCHEMA (L3+)
	25.	WIRELESS-NOMINAL-RATE SCHEMA
	26.	WIRELESS-MCS-RATE SCHEMA (Wi-Fi MCS index)
	27.	SPECTRAL-EFFICIENCY SCHEMA (bps/Hz)
	28.	AIR-INTERFACE-RATE SCHEMA
	29.	SPREADING-FACTOR-RATE SCHEMA (LoRa)
	30.	SATELLITE-DOWNLINK-RATE SCHEMA
	31.	SATELLITE-UPLINK-RATE SCHEMA
	32.	BACKHAUL-RATE SCHEMA
	33.	FRONTHAUL-RATE SCHEMA
	34.	CELLULAR-BANDWIDTH-RATE SCHEMA (NR/LTE Category)
	35.	NR-THROUGHPUT-SCHEMA (5G NR theoretical)
	36.	LTE-CATEGORY-RATE SCHEMA
	37.	LTE-CARRIER-AGG-RATE SCHEMA

⸻

✅ SECTION 3 — STORAGE + MEMORY + BUS DATA RATES
	38.	DISK-SEQUENTIAL-READ-RATE SCHEMA
	39.	DISK-SEQUENTIAL-WRITE-RATE SCHEMA
	40.	DISK-RANDOM-READ-RATE SCHEMA
	41.	DISK-RANDOM-WRITE-RATE SCHEMA
	42.	NVME-READ-RATE SCHEMA
	43.	NVME-WRITE-RATE SCHEMA
	44.	RAM-DATA-RATE SCHEMA (DDR MT/s)
	45.	DDR-CHANNEL-RATE SCHEMA
	46.	DDR-EFFECTIVE-RATE SCHEMA
	47.	PCIe-LINK-RATE SCHEMA (GT/s)
	48.	PCIE-PAYLOAD-RATE SCHEMA (after encoding)
	49.	USB-EFFECTIVE-RATE SCHEMA
	50.	USB-SIGNALING-RATE SCHEMA
	51.	SATA-LINK-RATE SCHEMA
	52.	SAS-LINK-RATE SCHEMA
	53.	I2C-BUS-RATE SCHEMA (standard, fast, HS)
	54.	SPI-BUS-RATE SCHEMA
	55.	UART-BAUD-RATE SCHEMA (yes this is a data rate!)
	56.	CAN-BUS-RATE SCHEMA
	57.	LIN-BUS-RATE SCHEMA
	58.	ETHERNET-LINK-RATE SCHEMA
	59.	ETHERNET-PAYLOAD-RATE SCHEMA (after interframe gaps)

⸻

✅ SECTION 4 — COMPRESSED / ENCODED MEDIA RATES (A/V)
	60.	BITRATE-AUDIO SCHEMA
	61.	BITRATE-AUDIO-VBR SCHEMA
	62.	BITRATE-AUDIO-ABR SCHEMA
	63.	BITRATE-AUDIO-CBR SCHEMA
	64.	BITRATE-VIDEO SCHEMA
	65.	BITRATE-VIDEO-VBR SCHEMA
	66.	BITRATE-VIDEO-CBR SCHEMA
	67.	BITRATE-VIDEO-2PASS SCHEMA
	68.	BITRATE-VIDEO-EFFECTIVE SCHEMA
	69.	BITRATE-VIDEO-PEAK SCHEMA
	70.	CODEC-BITRATE-H264 SCHEMA
	71.	CODEC-BITRATE-H265 SCHEMA
	72.	CODEC-BITRATE-AV1 SCHEMA
	73.	CODEC-BITRATE-VP9 SCHEMA
	74.	CODEC-BITRATE-MPEG2 SCHEMA

⸻

✅ SECTION 5 — STREAMING / CDN / APPLICATION LAYER
	75.	CDN-EDGE-THROUGHPUT SCHEMA
	76.	CDN-ORIGIN-THROUGHPUT SCHEMA
	77.	BUFFERED-BITRATE SCHEMA
	78.	ADAPTIVE-STREAMING-RATE SCHEMA (ABR)
	79.	LIVE-INGEST-RATE SCHEMA
	80.	MEDIA-PLAYBACK-EFFECTIVE-RATE SCHEMA

⸻

✅ SECTION 6 — IoT, RF, SENSOR + EMBEDDED
	81.	LORA-DATARATE SCHEMA
	82.	BLE-DATARATE SCHEMA
	83.	ZIGBEE-DATARATE SCHEMA
	84.	THREAD-DATARATE SCHEMA
	85.	ULTRASONIC-LINK-RATE SCHEMA
	86.	NFC-DATARATE SCHEMA
	87.	RF-MODULATION-DATARATE SCHEMA
	88.	SYMBOL-RATE SCHEMA (baud)
	89.	BITS-PER-SYMBOL SCHEMA
	90.	SPREAD-SPECTRUM-RATE SCHEMA
	91.	FHSS-RATE SCHEMA
	92.	DSSS-RATE SCHEMA

⸻

✅ SECTION 7 — CLOUD / COMPUTE THROUGHPUT
	93.	CLOUD-NETWORK-THROUGHPUT SCHEMA
	94.	CLOUD-DISK-THROUGHPUT SCHEMA
	95.	CLOUD-INSTANCE-EBS-RATE SCHEMA
	96.	CLOUD-FUNCTION-IO-RATE SCHEMA
	97.	CLOUD-STORAGE-API-RATE SCHEMA (GCS/S3/CF/R2)
	98.	KAFKA-PRODUCER-RATE SCHEMA
	99.	KAFKA-CONSUMER-RATE SCHEMA
	100.	MESSAGE-QUEUE-RATE SCHEMA

⸻

✅ SECTION 8 — SPECIAL SCIENTIFIC & NARROW DOMAINS
	101.	BITS-PER-PIXEL-PER-SECOND SCHEMA
	102.	COMPUTATIONAL-THROUGHPUT-RATE SCHEMA (model I/O)
	103.	DSP-SAMPLE-THROUGHPUT SCHEMA
	104.	FFT-DATA-RATE SCHEMA
	105.	RADIO-TELESCOPE-DATA-RATE SCHEMA
	106.	PARTICLE-DETECTOR-DATA-RATE SCHEMA
	107.	GENOMICS-SEQUENCER-DATA-RATE SCHEMA


⸻

🔵 SECTION 9 — MEASUREMENT / STATISTICAL VARIANTS
	108.	DATA-RATE-AVERAGE SCHEMA
	109.	DATA-RATE-MIN SCHEMA
	110.	DATA-RATE-MAX SCHEMA
	111.	DATA-RATE-P95 SCHEMA (95th-percentile)
	112.	DATA-RATE-P99 SCHEMA
	113.	DATA-RATE-STDDEV SCHEMA
	114.	DATA-RATE-VARIANCE SCHEMA
	115.	DATA-RATE-TREND SCHEMA (time-series regression)
	116.	DATA-RATE-DELTA SCHEMA (change since last sample)

⸻

🟣 SECTION 10 — PROTOCOL / APPLICATION-LAYER RATES
	117.	HTTP-THROUGHPUT SCHEMA (bytes / sec over TCP/QUIC)
	118.	TLS-RECORD-RATE SCHEMA
	119.	WEBSOCKET-MESSAGE-RATE SCHEMA
	120.	GRPC-MESSAGE-RATE SCHEMA
	121.	MQTT-MESSAGE-RATE SCHEMA
	122.	AMQP-THROUGHPUT SCHEMA
	123.	DNS-QUERY-RATE SCHEMA
	124.	API-REQUEST-RATE SCHEMA (REST/GraphQL)
	125.	DATABASE-QUERY-RATE SCHEMA (SQL ops / s)
	126.	CACHE-HIT-RATE SCHEMA (fraction × throughput)
	127.	STREAM-EVENT-RATE SCHEMA (Kafka/EventBus)

⸻

🟢 SECTION 11 — ENERGY / EFFICIENCY DERIVATIVES
	128.	ENERGY-PER-BIT SCHEMA (J/bit)
	129.	ENERGY-PER-BYTE SCHEMA (J/B)
	130.	THROUGHPUT-PER-WATT SCHEMA (Gbps/W)
	131.	DATA-RATE-EFFICIENCY SCHEMA (% of link utilization)

⸻

🟠 SECTION 12 — SECURITY / ENCRYPTION THROUGHPUT
	132.	ENCRYPTION-THROUGHPUT SCHEMA
	133.	DECRYPTION-THROUGHPUT SCHEMA
	134.	HASH-RATE SCHEMA (cryptographic H/s)
	135.	SIGNATURE-THROUGHPUT SCHEMA (ops/s)
	136.	TLS-HANDSHAKE-RATE SCHEMA

⸻

🔴 SECTION 13 — FILE TRANSFER / APPLICATION METRICS
	137.	UPLOAD-RATE SCHEMA
	138.	DOWNLOAD-RATE SCHEMA
	139.	FILE-SYNC-RATE SCHEMA
	140.	P2P-TRANSFER-RATE SCHEMA (BitTorrent etc.)
	141.	CLOUD-BACKUP-RATE SCHEMA
	142.	OBJECT-REPLICATION-RATE SCHEMA

⸻

⚫ SECTION 14 — HARDWARE / PERIPHERAL INTERFACES (MISSING EARLIER)
	143.	THUNDERBOLT-LINK-RATE SCHEMA
	144.	DISPLAYPORT-LINK-RATE SCHEMA
	145.	HDMI-SIGNAL-RATE SCHEMA
	146.	SDIO-BUS-RATE SCHEMA
	147.	EIDE-DATA-RATE SCHEMA
	148.	FIBRE-CHANNEL-RATE SCHEMA
	149.	INFIBAND-LINK-RATE SCHEMA
	150.	NVLINK-RATE SCHEMA
	151.	SERDES-LANE-RATE SCHEMA

⸻

🟤 SECTION 15 — TIME-DERIVED COMPOUND RATES
	152.	DATA-RATE-PER-CORE SCHEMA
	153.	DATA-RATE-PER-THREAD SCHEMA
	154.	DATA-RATE-PER-PROCESS SCHEMA
	155.	DATA-RATE-PER-SESSION SCHEMA
	156.	DATA-RATE-PER-USER SCHEMA
	157.	DATA-RATE-PER-DEVICE SCHEMA
	158.	DATA-RATE-PER-CLUSTER SCHEMA

⸻

⚪ SECTION 16 — MIXED-UNIT / COERCION / VALIDATION
	159.	DATA-RATE-ANY-UNIT SCHEMA
	160.	DATA-RATE-UNIT-COERCE SCHEMA
	161.	DATA-RATE-NORMALIZE-BPS SCHEMA
	162.	DATA-RATE-FROM-STRING SCHEMA (“100 MB/s”)
	163.	DATA-RATE-FROM-JSON SCHEMA
	164.	DATA-RATE-TO-HUMAN-STRING SCHEMA
	165.	DATA-RATE-TO-IEC-STRING SCHEMA
	166.	DATA-RATE-PRECISION-SCHEMA (significant digits / tolerance)