A. Core DataView Schemas

DATAVIEW
DATAVIEW-STRICT
DATAVIEW-NONEMPTY
DATAVIEW-NULLABLE
DATAVIEW-OPTIONAL
DATAVIEW-IMMUTABLE
DATAVIEW-FROZEN
DATAVIEW-FROM-BUFFER
DATAVIEW-FROM-TYPEDARRAY
DATAVIEW-TO-BUFFER
DATAVIEW-TO-TYPEDARRAY

⸻

B. DataView Structure & Metadata

DATAVIEW-BYTESIZE
DATAVIEW-BYTEOFFSET
DATAVIEW-BYTEOFFSET-RANGE
DATAVIEW-BYTESIZE-RANGE
DATAVIEW-BOUNDS-CHECK
DATAVIEW-VALID-SLICE
DATAVIEW-METADATA
DATAVIEW-VIEW-INFO
DATAVIEW-BUFFER-METADATA

⸻

C. DataView Range Schemas

DATAVIEW-RANGE
DATAVIEW-RANGE-START
DATAVIEW-RANGE-END
DATAVIEW-RANGE-BYTES
DATAVIEW-RANGE-BITS
DATAVIEW-RANGE-CLAMPED

⸻

D. DataView Type Read Schemas (get methods)

DATAVIEW-GET-INT8
DATAVIEW-GET-UINT8
DATAVIEW-GET-INT16
DATAVIEW-GET-UINT16
DATAVIEW-GET-INT32
DATAVIEW-GET-UINT32
DATAVIEW-GET-FLOAT32
DATAVIEW-GET-FLOAT64
DATAVIEW-GET-BIGINT64
DATAVIEW-GET-BIGUINT64
DATAVIEW-GET-BYTE
DATAVIEW-GET-WORD
DATAVIEW-GET-DWORD
DATAVIEW-GET-QWORD
DATAVIEW-GET-VECTOR

⸻

E. DataView Type Write Schemas (set methods)

DATAVIEW-SET-INT8
DATAVIEW-SET-UINT8
DATAVIEW-SET-INT16
DATAVIEW-SET-UINT16
DATAVIEW-SET-INT32
DATAVIEW-SET-UINT32
DATAVIEW-SET-FLOAT32
DATAVIEW-SET-FLOAT64
DATAVIEW-SET-BIGINT64
DATAVIEW-SET-BIGUINT64
DATAVIEW-SET-BYTE
DATAVIEW-SET-WORD
DATAVIEW-SET-QWORD
DATAVIEW-SET-VECTOR

⸻

F. DataView Endianness Schemas

DATAVIEW-LITTLE-ENDIAN
DATAVIEW-BIG-ENDIAN
DATAVIEW-ENDIAN-DETECT
DATAVIEW-ENDIAN-COERCE
DATAVIEW-ENDIAN-SAFE
DATAVIEW-ENDIAN-SWAP

⸻

G. DataView Encoding / Decoding Schemas

DATAVIEW-TO-HEX
DATAVIEW-TO-BASE64
DATAVIEW-TO-UTF8
DATAVIEW-TO-UTF16
DATAVIEW-TO-STRING
DATAVIEW-TO-JSON
DATAVIEW-FROM-HEX
DATAVIEW-FROM-BASE64
DATAVIEW-FROM-UTF8
DATAVIEW-FROM-STRING
DATAVIEW-FROM-OBJECT
DATAVIEW-FROM-STRUCTURE

⸻

H. DataView Conversion / Coercion Schemas

DATAVIEW-COERCE
DATAVIEW-COERCE-FROM-ARRAYBUFFER
DATAVIEW-COERCE-FROM-NODE-BUFFER
DATAVIEW-COERCE-FROM-TYPEDARRAY
DATAVIEW-COERCE-FROM-JSON
DATAVIEW-COERCE-FROM-BASE64
DATAVIEW-COERCE-FROM-STRING
DATAVIEW-COERCE-FROM-ARRAY

⸻

I. DataView Safety & Validation

DATAVIEW-DETACHED
DATAVIEW-NOT-DETACHED
DATAVIEW-VALIDATE-DETACHED
DATAVIEW-MUTABLE
DATAVIEW-NOT-MUTABLE
DATAVIEW-BOUNDS-VALID
DATAVIEW-SAFE-ACCESS
DATAVIEW-VALIDATE-OFFSET
DATAVIEW-VALIDATE-RANGE
DATAVIEW-VALIDATE-BUFFER

⸻

J. DataView Serialization Schemas

DATAVIEW-SERIALIZE-BASE64
DATAVIEW-SERIALIZE-HEX
DATAVIEW-SERIALIZE-JSON
DATAVIEW-SERIALIZE-BINARY
DATAVIEW-DESERIALIZE-BASE64
DATAVIEW-DESERIALIZE-HEX
DATAVIEW-DESERIALIZE-BINARY
DATAVIEW-DESERIALIZE-JSON

⸻

K. Node.js & Platform Integration

DATAVIEW-NODE-BUFFER
DATAVIEW-NODE-BUFFER-COERCE
DATAVIEW-WEBASSEMBLY-MEMORY
DATAVIEW-WEBCRYPTO-KEYDATA
DATAVIEW-BLOB
DATAVIEW-FILE-CHUNK
DATAVIEW-FETCH-RESPONSE-BODY
DATAVIEW-STREAM-CHUNK

⸻

L. Web & Browser Compatibility

DATAVIEW-BROWSER-SAFE
DATAVIEW-WORKER-COMPAT
DATAVIEW-SHAREDARRAYBUFFER-SAFE
DATAVIEW-WEBCRYPTO-COMPAT
DATAVIEW-BLOB-URL-COMPAT
DATAVIEW-WEBGL-COMPAT

⸻

M. DataView Math & Struct Schemas

DATAVIEW-STRUCT
DATAVIEW-STRUCT-DEFINE
DATAVIEW-STRUCT-READ
DATAVIEW-STRUCT-WRITE
DATAVIEW-STRUCT-PARSE
DATAVIEW-STRUCT-ALIGN
DATAVIEW-STRUCT-OFFSET
DATAVIEW-STRUCT-TABLE
DATAVIEW-STRUCT-LAYOUT
DATAVIEW-STRUCT-MAP
DATAVIEW-STRUCT-ARRAY
DATAVIEW-STRUCT-UNION

⸻

N. Debug & Inspection Schemas

DATAVIEW-DUMP
DATAVIEW-DUMP-HEX
DATAVIEW-DUMP-ASCII
DATAVIEW-DUMP-STRUCT
DATAVIEW-INSPECT
DATAVIEW-METRICS
DATAVIEW-TRACE
DATAVIEW-LOG

⸻

O. Unified DataView Schemas

DATAVIEW-ANY
DATAVIEW-FULL-PROFILE
DATAVIEW-READONLY-PROFILE
DATAVIEW-WRITABLE-PROFILE
DATAVIEW-METADATA-PROFILE
DATAVIEW-STRUCT-PROFILE
DATAVIEW-COMPOSITE-PROFILE
DATAVIEW-UNIFIED