✅ SECTION 1 — CORE DECIMAL SCHEMAS (GENERIC NUMERIC)
	1.	DECIMAL SCHEMA
	2.	DECIMAL-STRICT SCHEMA (no scientific notation, must contain “.”)
	3.	DECIMAL-POSITIVE SCHEMA
	4.	DECIMAL-NEGATIVE SCHEMA
	5.	DECIMAL-NONNEGATIVE SCHEMA
	6.	DECIMAL-NONPOSITIVE SCHEMA
	7.	DECIMAL-NONZERO SCHEMA
	8.	DECIMAL-ZERO-ALLOWED SCHEMA
	9.	DECIMAL-ZERO-DISALLOWED SCHEMA
	10.	DECIMAL-NULLABLE SCHEMA
	11.	DECIMAL-OPTIONAL SCHEMA
	12.	DECIMAL-DEFAULT SCHEMA (assign default value if missing)

⸻

✅ SECTION 2 — RANGE / BOUND SCHEMAS
13.  DECIMAL-MIN SCHEMA
14.  DECIMAL-MAX SCHEMA
15.  DECIMAL-RANGE SCHEMA (min ≤ x ≤ max)
16.  DECIMAL-STRICT-RANGE SCHEMA (min < x < max)
17.  DECIMAL-ABSOLUTE-RANGE SCHEMA (|x| ≤ limit)
18.  DECIMAL-TOLERANCE SCHEMA (±ε precision band)

⸻

✅ SECTION 3 — PRECISION / SCALE CONTROL
19.  DECIMAL-PRECISION SCHEMA (total digits)
20.  DECIMAL-SCALE SCHEMA (digits after decimal)
21.  DECIMAL-FIXED SCHEMA (fixed decimal places)
22.  DECIMAL-SIGNIFICANT-FIGURES SCHEMA
23.  DECIMAL-ROUNDING-MODE SCHEMA (up/down/bankers)
24.  DECIMAL-TRUNCATED SCHEMA
25.  DECIMAL-NORMALIZED SCHEMA (trim trailing zeros)
26.  DECIMAL-COERCE-PRECISION SCHEMA (auto-adjust)

⸻

✅ SECTION 4 — REPRESENTATION / FORMAT
27.  DECIMAL-STRING SCHEMA (“123.45”)
28.  DECIMAL-NUMERIC SCHEMA (Number type)
29.  DECIMAL-BIGINT-COMPAT SCHEMA (convert BigInt → Decimal)
30.  DECIMAL-BIGDECIMAL SCHEMA (arbitrary precision)
31.  DECIMAL-RATIONAL SCHEMA (fractional form numerator/denominator)
32.  DECIMAL-FORMATTED SCHEMA (locale-sensitive string)
33.  DECIMAL-PARSEABLE SCHEMA (from localized string)
34.  DECIMAL-SERIALIZED SCHEMA (for JSON)

⸻

✅ SECTION 5 — COERCION / INTEROP
35.  DECIMAL-COERCE SCHEMA (any → Decimal)
36.  DECIMAL-FROM-STRING SCHEMA
37.  DECIMAL-FROM-INTEGER SCHEMA
38.  DECIMAL-FROM-FLOAT SCHEMA
39.  DECIMAL-FROM-BIGINT SCHEMA
40.  DECIMAL-FROM-CURRENCY SCHEMA
41.  DECIMAL-FROM-PERCENT SCHEMA
42.  DECIMAL-FROM-RATIO SCHEMA
43.  DECIMAL-TO-STRING SCHEMA
44.  DECIMAL-TO-FLOAT SCHEMA
45.  DECIMAL-TO-BIGINT SCHEMA

⸻

✅ SECTION 6 — VALIDATION / SANITY
46.  DECIMAL-VALID SCHEMA (syntactically valid)
47.  DECIMAL-FINITE SCHEMA (not NaN/Infinity)
48.  DECIMAL-NOT-INF SCHEMA
49.  DECIMAL-NOT-NAN SCHEMA
50.  DECIMAL-PARSE-ERROR-SAFE SCHEMA
51.  DECIMAL-CLAMP SCHEMA (auto-clip to range)
52.  DECIMAL-SAFE-MATH SCHEMA (bounded arithmetic)

⸻

✅ SECTION 7 — DOMAIN-SPECIFIC NUMERIC TYPES
53.  DECIMAL-MONEY-AMOUNT SCHEMA
54.  DECIMAL-MONEY-RATE SCHEMA (interest, tax %)
55.  DECIMAL-PERCENT SCHEMA (0–100)
56.  DECIMAL-RATIO SCHEMA (0–1 normalized)
57.  DECIMAL-SCORE SCHEMA (bounded, e.g. 0–10)
58.  DECIMAL-PROBABILITY SCHEMA
59.  DECIMAL-TEMPERATURE SCHEMA (C/F/K)
60.  DECIMAL-PRESSURE SCHEMA
61.  DECIMAL-PH SCHEMA (0–14)
62.  DECIMAL-DENSITY SCHEMA
63.  DECIMAL-CONCENTRATION SCHEMA
64.  DECIMAL-ANGLE-DEG SCHEMA
65.  DECIMAL-ANGLE-RAD SCHEMA
66.  DECIMAL-VOLTAGE SCHEMA
67.  DECIMAL-CURRENT SCHEMA
68.  DECIMAL-RESISTANCE SCHEMA
69.  DECIMAL-POWER SCHEMA
70.  DECIMAL-ENERGY SCHEMA

⸻

✅ SECTION 8 — COMPUTATIONAL / MATH UTILITIES
71.  DECIMAL-ABS SCHEMA
72.  DECIMAL-SIGN SCHEMA
73.  DECIMAL-EXP SCHEMA
74.  DECIMAL-LOG SCHEMA
75.  DECIMAL-SQRT SCHEMA
76.  DECIMAL-POW SCHEMA
77.  DECIMAL-SUM SCHEMA
78.  DECIMAL-AVERAGE SCHEMA
79.  DECIMAL-STDDEV SCHEMA
80.  DECIMAL-VARIANCE SCHEMA
81.  DECIMAL-AGGREGATE-ARRAY SCHEMA
82.  DECIMAL-COMPARE SCHEMA (equality/ordering)

⸻

✅ SECTION 9 — FINANCIAL / ACCOUNTING SPECIALIZED
83.  DECIMAL-CURRENCY-CODE SCHEMA (USD/CAD/EUR)
84.  DECIMAL-CURRENCY-AMOUNT SCHEMA
85.  DECIMAL-CURRENCY-PAIR SCHEMA (exchange rates)
86.  DECIMAL-INTEREST-RATE SCHEMA
87.  DECIMAL-TAX-RATE SCHEMA
88.  DECIMAL-DISCOUNT-RATE SCHEMA
89.  DECIMAL-PRICE-PER-UNIT SCHEMA
90.  DECIMAL-ASSET-VALUE SCHEMA
91.  DECIMAL-DEPRECIATION-RATE SCHEMA
92.  DECIMAL-YIELD-RATE SCHEMA
93.  DECIMAL-ROI SCHEMA
94.  DECIMAL-PNL-SCHEMA (Profit / Loss)
95.  DECIMAL-EXCHANGE-FEE SCHEMA

⸻

✅ SECTION 10 — PRESENTATION / LOCALIZATION / HUMAN-READABLE
96.  DECIMAL-LOCALE-STRING SCHEMA (Intl.NumberFormat)
97.  DECIMAL-GROUPED-STRING SCHEMA (“1,234.56”)
98.  DECIMAL-LOCALE-COERCE SCHEMA (parse locale string)
99.  DECIMAL-SI-PREFIX SCHEMA (1.23 k, 1.23 M)
100.  DECIMAL-HUMAN-READABLE SCHEMA (“12.3 million”)

⸻

✅ SECTION 11 — STRUCTURED / COLLECTION TYPES
101.  DECIMAL-ARRAY SCHEMA
102.  DECIMAL-MAP SCHEMA
103.  DECIMAL-SET SCHEMA
104.  DECIMAL-FIELD SCHEMA
105.  DECIMAL-MATRIX SCHEMA
106.  DECIMAL-TIME-SERIES SCHEMA
107.  DECIMAL-RANGE-OBJECT SCHEMA (start/end/step)

⸻

✅ SECTION 12 — SPECIAL FORMATS / STANDARDS INTEGRATION
108.  DECIMAL-IEEE-754-SCHEMA (float64 bitwise)
109.  DECIMAL-DEC64-SCHEMA (decimal64 encoding)
110.  DECIMAL-BCD-SCHEMA (binary coded decimal)
111.  DECIMAL-ARBITRARY-PRECISION-LIB SCHEMA (e.g. Big.js, Decimal.js)
112.  DECIMAL-SQL-DECIMAL SCHEMA (DB precision + scale)
113.  DECIMAL-JSON-SCHEMA-COMPAT SCHEMA
114.  DECIMAL-AVRO-DECIMAL SCHEMA (precision, scale)

⸻

✅ SECTION 13 — VALIDATION & AUDIT EXTENSIONS
115.  DECIMAL-CHANGE-THRESHOLD SCHEMA (detect delta > x %)
116.  DECIMAL-CONSISTENCY-SCHEMA (cross-field checks)
117.  DECIMAL-TREND-SCHEMA (increasing/decreasing)
118.  DECIMAL-SIGNAL-STABILITY-SCHEMA (sensor drift)
119.  DECIMAL-ERROR-BOUNDS-SCHEMA (± σ confidence)
120.  DECIMAL-UNCERTAINTY-SCHEMA

⸻

✅ SECTION 14 — DERIVED / META
121.  DECIMAL-DERIVED-UNIT-SCHEMA (computed from other units)
122.  DECIMAL-NORMALIZED-RATIO-SCHEMA
123.  DECIMAL-UNITLESS-SCHEMA
124.  DECIMAL-ANY-SCHEMA (union of all decimal types)