✅ SECTION 1 — CORE PRODUCT SCHEMAS
	1.	PRODUCT-ID-SCHEMA
	2.	PRODUCT-SKU-SCHEMA
	3.	PRODUCT-BARCODE-SCHEMA (UPC/EAN/JAN/ISBN)
	4.	PRODUCT-GTIN-SCHEMA
	5.	PRODUCT-NAME-SCHEMA
	6.	PRODUCT-DESCRIPTION-SCHEMA
	7.	PRODUCT-SHORT-DESCRIPTION-SCHEMA
	8.	PRODUCT-TAGS-SCHEMA
	9.	PRODUCT-CATEGORY-SCHEMA
	10.	PRODUCT-SUBCATEGORY-SCHEMA
	11.	PRODUCT-BRAND-SCHEMA
	12.	PRODUCT-COLLECTION-SCHEMA
	13.	PRODUCT-FEATURES-LIST-SCHEMA
	14.	PRODUCT-SPECIFICATION-SCHEMA
	15.	PRODUCT-MODEL-NUMBER-SCHEMA
	16.	PRODUCT-STYLE-CODE-SCHEMA
	17.	PRODUCT-MPN-SCHEMA (Manufacturer Part Number)
	18.	PRODUCT-IDENTIFIER-MULTI-SCHEMA (mpn/gtin/sku/etc.)
	19.	PRODUCT-TYPE-SCHEMA
	20.	PRODUCT-STATUS-SCHEMA (active/disabled/etc.)

⸻

✅ SECTION 2 — INVENTORY & STOCK SCHEMAS
	21.	INVENTORY-QUANTITY-SCHEMA
	22.	INVENTORY-RESERVED-STOCK-SCHEMA
	23.	INVENTORY-AVAILABLE-STOCK-SCHEMA
	24.	INVENTORY-SAFETY-STOCK-SCHEMA
	25.	INVENTORY-REORDER-POINT-SCHEMA
	26.	INVENTORY-LEAD-TIME-DAYS-SCHEMA
	27.	INVENTORY-LOCATION-ID-SCHEMA
	28.	INVENTORY-WAREHOUSE-SCHEMA
	29.	INVENTORY-MULTI-LOCATION-SCHEMA
	30.	INVENTORY-STOCK-STATUS-SCHEMA (in/out/backorder)
	31.	INVENTORY-BATCH-NUMBER-SCHEMA
	32.	INVENTORY-EXPIRY-DATE-SCHEMA
	33.	INVENTORY-SERIAL-NUMBER-SCHEMA
	34.	INVENTORY-STOCK-HISTORY-EVENT-SCHEMA
	35.	INVENTORY-ADJUSTMENT-SCHEMA

⸻

✅ SECTION 3 — PRICING & MONEY SCHEMAS
	36.	PRICE-AMOUNT-SCHEMA
	37.	PRICE-CURRENCY-SCHEMA
	38.	PRICE-FORMATTED-SCHEMA
	39.	PRICE-COMPARE-AT-SCHEMA
	40.	PRICE-DISCOUNT-AMOUNT-SCHEMA
	41.	PRICE-DISCOUNT-PERCENT-SCHEMA
	42.	PRICE-TAX-AMOUNT-SCHEMA
	43.	PRICE-TAX-RATE-SCHEMA
	44.	PRICE-FIXED-SCHEMA
	45.	PRICE-DYNAMIC-SCHEMA
	46.	PRICE-MULTI-CURRENCY-SCHEMA
	47.	PRICE-TIERED-SCHEMA
	48.	PRICE-BULK-RATE-SCHEMA
	49.	PRICE-MIN-MAX-SCHEMA (range)
	50.	PRICE-COERCE-SCHEMA

⸻

✅ SECTION 4 — PRODUCT VARIANT SCHEMAS
	51.	VARIANT-ID-SCHEMA
	52.	VARIANT-NAME-SCHEMA
	53.	VARIANT-OPTION-SCHEMA
	54.	VARIANT-OPTION-GROUP-SCHEMA
	55.	VARIANT-SKU-SCHEMA
	56.	VARIANT-GTIN-SCHEMA
	57.	VARIANT-BARCODE-SCHEMA
	58.	VARIANT-PRICE-SCHEMA
	59.	VARIANT-INVENTORY-SCHEMA
	60.	VARIANT-IMAGE-SCHEMA
	61.	VARIANT-METAFIELDS-SCHEMA
	62.	VARIANT-ATTRIBUTE-SET-SCHEMA
	63.	VARIANT-SWATCH-SCHEMA (color/pattern/etc.)
	64.	VARIANT-RELATION-SCHEMA
	65.	VARIANT-BUNDLE-PART-SCHEMA

⸻

✅ SECTION 5 — PRODUCT MEDIA SCHEMAS
	66.	MEDIA-IMAGE-URL-SCHEMA
	67.	MEDIA-IMAGE-ALT-TEXT-SCHEMA
	68.	MEDIA-IMAGE-SET-SCHEMA
	69.	MEDIA-VIDEO-URL-SCHEMA
	70.	MEDIA-VIDEO-THUMBNAIL-SCHEMA
	71.	MEDIA-3D-MODEL-SCHEMA
	72.	MEDIA-GALLERY-SCHEMA
	73.	MEDIA-SWATCH-IMAGE-SCHEMA
	74.	MEDIA-PRIMARY-IMAGE-SCHEMA
	75.	MEDIA-MULTI-FORMAT-SCHEMA

⸻

✅ SECTION 6 — PRODUCT DIMENSION & PHYSICAL ATTRIBUTE SCHEMAS
	76.	PRODUCT-WEIGHT-SCHEMA
	77.	PRODUCT-LENGTH-SCHEMA
	78.	PRODUCT-WIDTH-SCHEMA
	79.	PRODUCT-HEIGHT-SCHEMA
	80.	PRODUCT-DIMENSIONS-SCHEMA
	81.	PRODUCT-VOLUME-SCHEMA
	82.	PRODUCT-PACKAGE-DIMENSIONS-SCHEMA
	83.	PRODUCT-MATERIAL-SCHEMA
	84.	PRODUCT-COLOR-SCHEMA
	85.	PRODUCT-SIZE-SCHEMA
	86.	PRODUCT-SHAPE-SCHEMA
	87.	PRODUCT-HAZMAT-SCHEMA
	88.	PRODUCT-COUNTRY-OF-ORIGIN-SCHEMA

⸻

✅ SECTION 7 — ORDER SCHEMAS
	89.	ORDER-ID-SCHEMA
	90.	ORDER-STATUS-SCHEMA
	91.	ORDER-LINE-ITEM-SCHEMA
	92.	ORDER-LINE-ITEM-LIST-SCHEMA
	93.	ORDER-CURRENCY-SCHEMA
	94.	ORDER-TOTAL-SCHEMA
	95.	ORDER-SUBTOTAL-SCHEMA
	96.	ORDER-TAX-TOTAL-SCHEMA
	97.	ORDER-DISCOUNT-TOTAL-SCHEMA
	98.	ORDER-SHIPPING-TOTAL-SCHEMA
	99.	ORDER-REFUND-TOTAL-SCHEMA
	100.	ORDER-PAYMENT-STATUS-SCHEMA
	101.	ORDER-FULFILLMENT-STATUS-SCHEMA
	102.	ORDER-SOURCE-SCHEMA (web/app/pos/etc.)
	103.	ORDER-CREATION-DATE-SCHEMA
	104.	ORDER-UPDATE-DATE-SCHEMA
	105.	ORDER-TAGS-SCHEMA

⸻

✅ SECTION 8 — CART / CHECKOUT SCHEMAS
	106.	CART-ID-SCHEMA
	107.	CART-LINE-ITEM-SCHEMA
	108.	CART-LINE-ITEM-QUANTITY-SCHEMA
	109.	CART-TOTAL-SCHEMA
	110.	CART-DISCOUNT-SCHEMA
	111.	CART-VOUCHER-SCHEMA
	112.	CART-COUPON-SCHEMA
	113.	CART-SHIPPING-OPTION-SCHEMA
	114.	CART-PAYMENT-METHOD-SCHEMA
	115.	CART-SESSION-SCHEMA
	116.	CART-ABANDONED-SCHEMA
	117.	CHECKOUT-SESSION-SCHEMA
	118.	CHECKOUT-PAYMENT-STATE-SCHEMA

⸻

✅ SECTION 9 — CUSTOMER SCHEMAS
	119.	CUSTOMER-ID-SCHEMA
	120.	CUSTOMER-NAME-SCHEMA
	121.	CUSTOMER-EMAIL-SCHEMA
	122.	CUSTOMER-PHONE-SCHEMA
	123.	CUSTOMER-ADDRESS-SCHEMA
	124.	CUSTOMER-IP-SCHEMA
	125.	CUSTOMER-SEGMENT-SCHEMA
	126.	CUSTOMER-PREFERENCES-SCHEMA
	127.	CUSTOMER-REWARD-POINTS-SCHEMA
	128.	CUSTOMER-LOYALTY-TIER-SCHEMA
	129.	CUSTOMER-FLAGS-SCHEMA (VIP/fraud/etc.)
	130.	CUSTOMER-ACCOUNT-STATUS-SCHEMA
	131.	CUSTOMER-ORDER-HISTORY-METADATA-SCHEMA

⸻

✅ SECTION 10 — ADDRESS & SHIPPING SCHEMAS
	132.	ADDRESS-LINE1-SCHEMA
	133.	ADDRESS-LINE2-SCHEMA
	134.	ADDRESS-CITY-SCHEMA
	135.	ADDRESS-REGION-SCHEMA
	136.	ADDRESS-COUNTRY-SCHEMA
	137.	ADDRESS-POSTAL-CODE-SCHEMA
	138.	ADDRESS-FORMATTED-SCHEMA
	139.	ADDRESS-VALIDATION-SCHEMA
	140.	SHIPPING-RATE-SCHEMA
	141.	SHIPPING-CARRIER-SCHEMA
	142.	SHIPPING-SERVICE-LEVEL-SCHEMA
	143.	SHIPPING-TRACKING-NUMBER-SCHEMA
	144.	SHIPPING-TRACKING-URL-SCHEMA
	145.	SHIPPING-LABEL-SCHEMA
	146.	SHIPPING-PACKAGE-SCHEMA

⸻

✅ SECTION 11 — PAYMENT SCHEMAS
	147.	PAYMENT-ID-SCHEMA
	148.	PAYMENT-METHOD-SCHEMA (card/paypal/etc.)
	149.	PAYMENT-INTENT-SCHEMA (Stripe-style)
	150.	PAYMENT-STATUS-SCHEMA
	151.	PAYMENT-AMOUNT-SCHEMA
	152.	PAYMENT-CURRENCY-SCHEMA
	153.	PAYMENT-PROVIDER-SCHEMA
	154.	PAYMENT-CARD-LAST4-SCHEMA
	155.	PAYMENT-CARD-BRAND-SCHEMA
	156.	PAYMENT-EXPIRY-SCHEMA
	157.	PAYMENT-AUTH-CODE-SCHEMA
	158.	PAYMENT-REFUND-SCHEMA
	159.	PAYMENT-FRAUD-RISK-SCHEMA

⸻

✅ SECTION 12 — COUPONS, DISCOUNTS & PROMOTIONS
	160.	COUPON-CODE-SCHEMA
	161.	COUPON-DISCOUNT-AMOUNT-SCHEMA
	162.	COUPON-DISCOUNT-PERCENT-SCHEMA
	163.	COUPON-USAGE-LIMIT-SCHEMA
	164.	COUPON-EXPIRY-DATE-SCHEMA
	165.	COUPON-MINIMUM-ORDER-AMOUNT-SCHEMA
	166.	COUPON-APPLICABLE-PRODUCTS-SCHEMA
	167.	PROMOTION-RULE-SCHEMA
	168.	PROMOTION-CONDITION-SCHEMA
	169.	PROMOTION-EFFECT-SCHEMA
	170.	PROMOTION-CAMPAIGN-SCHEMA

⸻

✅ SECTION 13 — TAX SCHEMAS
	171.	TAX-RATE-SCHEMA
	172.	TAX-JURISDICTION-SCHEMA
	173.	TAX-VAT-CATEGORY-SCHEMA
	174.	TAX-HST-GST-SCHEMA
	175.	TAX-LINE-ITEM-SCHEMA
	176.	TAX-INCLUSIVE-SCHEMA
	177.	TAX-EXCLUSIVE-SCHEMA
	178.	TAX-EXEMPTION-SCHEMA
	179.	TAX-NEXUS-SCHEMA
	180.	TAX-CODE-SCHEMA

⸻

✅ SECTION 14 — FULFILLMENT SCHEMAS
	181.	FULFILLMENT-ID-SCHEMA
	182.	FULFILLMENT-STATUS-SCHEMA
	183.	FULFILLMENT-LINE-ITEM-SCHEMA
	184.	FULFILLMENT-TRACKING-SCHEMA
	185.	FULFILLMENT-CARRIER-SCHEMA
	186.	FULFILLMENT-SCAN-HISTORY-SCHEMA
	187.	FULFILLMENT-LOCATION-SCHEMA
	188.	FULFILLMENT-PACKAGING-SCHEMA
	189.	FULFILLMENT-ETA-SCHEMA

⸻

✅ SECTION 15 — REVIEWS, RATINGS & FEEDBACK
	190.	REVIEW-ID-SCHEMA
	191.	REVIEW-RATING-SCHEMA
	192.	REVIEW-TEXT-SCHEMA
	193.	REVIEW-CREATION-DATE-SCHEMA
	194.	REVIEW-AUTHOR-SCHEMA
	195.	REVIEW-IMAGES-SCHEMA
	196.	REVIEW-VERIFIED-PURCHASE-SCHEMA
	197.	REVIEW-HELPFUL-VOTES-SCHEMA

⸻

✅ SECTION 16 — ANALYTICS & TRACKING
	198.	ECOM-SESSION-ID-SCHEMA
	199.	ECOM-UTM-PARAMS-SCHEMA
	200.	ECOM-EVENT-VIEW-PRODUCT-SCHEMA
	201.	ECOM-EVENT-ADD-TO-CART-SCHEMA
	202.	ECOM-EVENT-BEGIN-CHECKOUT-SCHEMA
	203.	ECOM-EVENT-PURCHASE-SCHEMA
	204.	ECOM-EVENT-SEARCH-SCHEMA
	205.	ECOM-EVENT-FUNNEL-STEP-SCHEMA
	206.	ECOM-EVENT-SOURCE-SCHEMA
	207.	ECOM-EVENT-ATTRIBUTION-SCHEMA

⸻

✅ SECTION 17 — SECURITY & FRAUD SCHEMAS
	208.	FRAUD-RISK-SCORE-SCHEMA
	209.	FRAUD-FLAG-SCHEMA
	210.	FRAUD-RULE-SCHEMA
	211.	FRAUD-ADDRESS-MISMATCH-SCHEMA
	212.	FRAUD-IP-RISK-SCHEMA
	213.	FRAUD-CARD-RISK-SCHEMA
	214.	FRAUD-DEVICE-FINGERPRINT-SCHEMA
