✅ SECTION 1 — FUEL TYPE SCHEMAS (IDENTIFIERS)

These validate which fuel we’re dealing with.
	1.	FUEL-TYPE SCHEMA
	2.	FUEL-TYPE-LIQUID SCHEMA
	3.	FUEL-TYPE-GAS SCHEMA
	4.	FUEL-TYPE-BIOMASS SCHEMA
	5.	FUEL-TYPE-ELECTROCHEMICAL SCHEMA
	6.	FUEL-TYPE-AVIATION SCHEMA
	7.	FUEL-TYPE-MARINE SCHEMA
	8.	FUEL-TYPE-NUCLEAR SCHEMA
	9.	FUEL-TYPE-EXPERIMENTAL SCHEMA

⸻

✅ SECTION 2 — SPECIFIC FUEL NAMES (DISCRETE ENUMS)
	10.	FUEL-GASOLINE-GRADE SCHEMA (87/89/91/93)
	11.	FUEL-DIESEL-GRADE SCHEMA (#1, #2, ULSD)
	12.	FUEL-BIODIESEL-GRADE SCHEMA (B5, B20, B99)
	13.	FUEL-ETHANOL-GRADE SCHEMA (E10, E15, E85)
	14.	FUEL-JETFUEL-SCHEMA (Jet A, Jet A-1, JP-8, JP-5)
	15.	FUEL-AVGAS-SCHEMA (100LL, UL94)
	16.	FUEL-PROPANE-GRADE SCHEMA
	17.	FUEL-BUTANE-GRADE SCHEMA
	18.	FUEL-LNG-GRADE SCHEMA
	19.	FUEL-LPG-GRADE SCHEMA
	20.	FUEL-HYDROGEN-GRADE SCHEMA (fuel cell purity)
	21.	FUEL-AMMONIA-SCHEMA
	22.	FUEL-METHANOL-SCHEMA
	23.	FUEL-SYNTHETIC-SCHEMA (e-fuel / Fischer-Tropsch)

⸻

✅ SECTION 3 — FUEL QUANTITY SCHEMAS
	24.	FUEL-VOLUME-LITER SCHEMA (L)
	25.	FUEL-VOLUME-GALLON SCHEMA (US gal)
	26.	FUEL-VOLUME-IMPERIAL-GALLON SCHEMA
	27.	FUEL-VOLUME-BARREL SCHEMA (bbl)
	28.	FUEL-MASS-KG SCHEMA
	29.	FUEL-MASS-LB SCHEMA
	30.	FUEL-MOLE SCHEMA
	31.	FUEL-QUANTITY-PERCENT SCHEMA (tank level)
	32.	FUEL-QUANTITY-COERCE SCHEMA (any → canonical)

⸻

✅ SECTION 4 — FUEL ENERGY CONTENT SCHEMAS (CALORIFIC VALUES)
	33.	FUEL-LHV SCHEMA (Lower Heating Value)
	34.	FUEL-HHV SCHEMA (Higher Heating Value)
	35.	FUEL-ENERGY-DENSITY-MJ-KG SCHEMA
	36.	FUEL-ENERGY-DENSITY-MJ-L SCHEMA
	37.	FUEL-OCTANE-RATING SCHEMA
	38.	FUEL-CETANE-RATING SCHEMA

⸻

✅ SECTION 5 — FUEL COMPOSITION SCHEMAS
	39.	FUEL-CHEMICAL-COMPOSITION SCHEMA (molecular breakdown)
	40.	FUEL-CARBON-CONTENT SCHEMA (percentage)
	41.	FUEL-SULFUR-CONTENT SCHEMA
	42.	FUEL-OXYGEN-CONTENT SCHEMA
	43.	FUEL-ASH-CONTENT SCHEMA
	44.	FUEL-MOISTURE-CONTENT SCHEMA (biomass)
	45.	FUEL-AROMATICS-CONTENT SCHEMA
	46.	FUEL-ALKYLATE-RATIO SCHEMA

⸻

✅ SECTION 6 — FUEL QUALITY CONTROL SCHEMAS
	47.	FUEL-PURITY SCHEMA
	48.	FUEL-CONTAMINATION-PARTICULATE SCHEMA
	49.	FUEL-CONTAMINATION-WATER SCHEMA
	50.	FUEL-MICROBIAL-CONTAMINATION SCHEMA (diesel bacteria)
	51.	FUEL-VISCOSITY SCHEMA
	52.	FUEL-FREEZE-POINT SCHEMA (aviation)
	53.	FUEL-CLOUD-POINT SCHEMA
	54.	FUEL-FLASH-POINT SCHEMA
	55.	FUEL-DENSITY-SCHEMA
	56.	FUEL-CONDUCTIVITY SCHEMA

⸻

✅ SECTION 7 — FUEL STORAGE / TANK SCHEMAS
	57.	FUEL-TANK-CAPACITY SCHEMA (L/gal)
	58.	FUEL-TANK-MATERIAL SCHEMA
	59.	FUEL-TANK-PRESSURE-RATING SCHEMA
	60.	FUEL-TANK-TEMPERATURE-RANGE SCHEMA
	61.	FUEL-TANK-LEVEL SCHEMA (float / percent / sensor)
	62.	FUEL-TANK-VENTING SCHEMA
	63.	FUEL-TANK-INTEGRITY SCHEMA
	64.	FUEL-TANK-ID SCHEMA (serial)

⸻

✅ SECTION 8 — FUEL DELIVERY SYSTEM SCHEMAS
	65.	FUEL-PRESSURE SCHEMA (kPa / psi)
	66.	FUEL-FLOW-RATE SCHEMA (L/h, kg/s)
	67.	FUEL-INJECTOR-FLOW SCHEMA
	68.	FUEL-PUMP-RATING SCHEMA
	69.	FUEL-FILTER-STATE SCHEMA
	70.	FUEL-PIPE-DIAMETER SCHEMA

⸻

✅ SECTION 9 — FUEL ECONOMY + PERFORMANCE SCHEMAS
	71.	FUEL-CONSUMPTION-L100KM SCHEMA
	72.	FUEL-CONSUMPTION-MPG SCHEMA
	73.	FUEL-CONSUMPTION-MPGE SCHEMA
	74.	FUEL-CONSUMPTION-GPH SCHEMA (aviation)
	75.	FUEL-RANGE-ESTIMATE SCHEMA (km/mi)
	76.	FUEL-EFFICIENCY-SCORE SCHEMA
	77.	FUEL-BURN-RATE SCHEMA
	78.	FUEL-COST-PER-DISTANCE SCHEMA

⸻

✅ SECTION 10 — FUEL SAFETY & HAZMAT SCHEMAS
	79.	FUEL-DOT-HAZMAT-CODE SCHEMA
	80.	FUEL-UN-NUMBER SCHEMA (UN1203, UN1075…)
	81.	FUEL-MATERIAL-CLASS SCHEMA (flammable liquid/gas)
	82.	FUEL-SPILL-VOLUME SCHEMA
	83.	FUEL-IGNITION-TEMPERATURE SCHEMA
	84.	FUEL-STORAGE-ZONE-CODE SCHEMA

⸻

✅ SECTION 11 — ENGINE / DEVICE FUEL USAGE SCHEMAS
	85.	ENGINE-FUEL-TYPE SCHEMA
	86.	ENGINE-FUEL-RATING SCHEMA
	87.	ENGINE-FUEL-MODE SCHEMA (dual fuel, hybrid)
	88.	ENGINE-FUEL-MIXTURE SCHEMA (A/F ratio)
	89.	ENGINE-IDLE-FUEL SCHEMA
	90.	ENGINE-MAX-FUEL-FLOW SCHEMA
	✅ SECTION 12 — EMISSIONS & ENVIRONMENTAL IMPACT SCHEMAS
	91. FUEL-CO2-EMISSION-FACTOR SCHEMA (kg CO₂ / L or / MJ)
	92. FUEL-NOX-EMISSION-FACTOR SCHEMA
	93. FUEL-SOX-EMISSION-FACTOR SCHEMA
	94. FUEL-PARTICULATE-EMISSION-FACTOR SCHEMA
	95. FUEL-GHG-INTENSITY-SCHEMA (g CO₂-eq / MJ — life-cycle)
	96. FUEL-CARBON-INTENSITY-SCHEMA (CI score / LCFS credit)
	97. FUEL-LCA-SCHEMA (Life-Cycle Assessment metadata)
	98. FUEL-WELL-TO-TANK-EFFICIENCY SCHEMA
	99. FUEL-TANK-TO-WHEEL-EFFICIENCY SCHEMA
	100. FUEL-CARBON-OFFSET-SCHEMA (offset credits applied)
	
	⸻
	
	✅ SECTION 13 — FUEL PROCESSING / REFINING SCHEMAS
	101. FUEL-REFINERY-SOURCE SCHEMA
	102. FUEL-REFINING-PROCESS SCHEMA (cracking, reforming, hydro-treating)
	103. FUEL-BLENDING-RATIO-SCHEMA (mix of feedstocks)
	104. FUEL-ADDITIVE-PACKAGE-SCHEMA
	105. FUEL-ANTIKNOCK-ADDITIVE-SCHEMA (MMT, ethanol, etc.)
	106. FUEL-DETERGENT-ADDITIVE-SCHEMA
	107. FUEL-OXIDATION-STABILITY-SCHEMA
	108. FUEL-STORAGE-AGE-SCHEMA (shelf life / oxidation hours)
	
	⸻
	
	✅ SECTION 14 — FUEL CERTIFICATION / STANDARDS SCHEMAS
	109. FUEL-ASTM-STANDARD-SCHEMA (D975, D1655, D4806 …)
	110. FUEL-ISO-STANDARD-SCHEMA (8217, 14214 …)
	111. FUEL-EN-STANDARD-SCHEMA (EN 590, EN 228 …)
	112. FUEL-REGULATORY-COMPLIANCE-SCHEMA (EPA / CARB / IMO MARPOL)
	113. FUEL-CERTIFICATION-DOCUMENT-SCHEMA (CoA or lab report)
	114. FUEL-BATCH-LOT-SCHEMA (tracking / traceability ID)
	
	⸻
	
	✅ SECTION 15 — ALTERNATIVE / FUTURE FUELS SCHEMAS
	115. FUEL-ELECTROLYTIC-HYDROGEN-SCHEMA (Green H₂)
	116. FUEL-BLUE-HYDROGEN-SCHEMA (CCS capture)
	117. FUEL-SYNTHETIC-KEROSENE-SCHEMA (SAF / Power-to-Liquid)
	118. FUEL-BIO-METHANE-SCHEMA (RNG / biogas)
	119. FUEL-BIO-OIL-SCHEMA (pyrolysis)
	120. FUEL-HYDROGEN-CARRIER-SCHEMA (ammonia / LOHC)
	121. FUEL-NUCLEAR-ISOTOPE-SCHEMA (U-235 %, Th-232, Pu-239)
	122. FUEL-FUSION-TARGET-SCHEMA (D-T, D-He3)
	
	⸻
	
	✅ SECTION 16 — THERMAL & COMBUSTION CHARACTERISTIC SCHEMAS
	123. FUEL-AIR-RATIO-SCHEMA (stoichiometric A/F)
	124. FUEL-FLAME-TEMPERATURE-SCHEMA
	125. FUEL-IGNITION-DELAY-SCHEMA (diesel / rocket engines)
	126. FUEL-BURNING-VELOCITY-SCHEMA
	127. FUEL-LAMBDA-VALUE-SCHEMA (equivalence ratio)
	128. FUEL-COMBUSTION-EFFICIENCY-SCHEMA
	129. FUEL-EXHAUST-TEMPERATURE-SCHEMA
	130. FUEL-PRESSURE-RATIO-SCHEMA (engine cycle)
	131. FUEL-STOICHIOMETRIC-INDEX-SCHEMA
	
	⸻
	
	✅ SECTION 17 — ROCKET / SPACE PROPULSION FUELS SCHEMAS
	132. FUEL-ROCKET-TYPE-SCHEMA (liquid, solid, hybrid)
	133. FUEL-ROCKET-COMPONENT-SCHEMA (fuel / oxidizer)
	134. FUEL-OXIDIZER-TYPE-SCHEMA (LOX, N₂O₄, H₂O₂)
	135. FUEL-SPECIFIC-IMPULSE-SCHEMA (Isp)
	136. FUEL-MIXTURE-RATIO-SCHEMA (O/F)
	137. FUEL-CHAMBER-PRESSURE-SCHEMA
	138. FUEL-THRUST-COEFFICIENT-SCHEMA
	
	⸻
	
	✅ SECTION 18 — LOGISTICS / SUPPLY CHAIN SCHEMAS
	139. FUEL-SUPPLIER-SCHEMA
	140. FUEL-DELIVERY-BATCH-SCHEMA
	141. FUEL-TRANSPORT-MODE-SCHEMA (pipeline, tanker, rail)
	142. FUEL-DELIVERY-TEMPERATURE-SCHEMA
	143. FUEL-CUSTOMS-DOCUMENT-SCHEMA (import/export)
	144. FUEL-INVENTORY-SCHEMA
	145. FUEL-RETENTION-SAMPLE-SCHEMA (quality control)
	
	⸻
	
	✅ SECTION 19 — ANALYTICS / PERFORMANCE MODEL SCHEMAS
	146. FUEL-COST-INDEX-SCHEMA (aviation ops)
	147. FUEL-ECONOMY-CYCLE-SCHEMA (WLTP, EPA, NEDC)
	148. FUEL-EFFICIENCY-MAP-SCHEMA (engine load × rpm)
	149. FUEL-BURN-CURVE-SCHEMA (time series)
	150. FUEL-DEGRADATION-MODEL-SCHEMA
	151. FUEL-THERMAL-LOSS-SCHEMA
	152. FUEL-PERFORMANCE-INDEX-SCHEMA
	
	⸻
	
	✅ SECTION 20 — DATA MODEL / UTILITY SCHEMAS
	153. FUEL-ARRAY-SCHEMA
	154. FUEL-MAP-SCHEMA
	155. FUEL-SET-SCHEMA
	156. FUEL-OPTIONAL-SCHEMA
	157. FUEL-NULLABLE-SCHEMA
	158. FUEL-DEFAULT-SCHEMA
	159. FUEL-ANY-SCHEMA
	