/*
    TODO:

    1. VITAL SIGNS
	1.	VITAL-HEART-RATE SCHEMA
	2.	VITAL-RESPIRATORY-RATE SCHEMA
	3.	VITAL-BLOOD-PRESSURE-SYSTOLIC SCHEMA
	4.	VITAL-BLOOD-PRESSURE-DIASTOLIC SCHEMA
	5.	VITAL-BLOOD-PRESSURE-MAP SCHEMA (Mean arterial pressure)
	6.	VITAL-OXYGEN-SATURATION SCHEMA (SpO₂)
	7.	VITAL-TEMPERATURE-C SCHEMA
	8.	VITAL-TEMPERATURE-F SCHEMA
	9.	VITAL-HEART-RHYTHM SCHEMA (sinus, AFib, PAC, PVC)
	10.	VITAL-PEAK-FLOW SCHEMA

⸻

2. BODY COMPOSITION / FITNESS
	11.	BODY-WEIGHT-KG SCHEMA
	12.	BODY-WEIGHT-LB SCHEMA
	13.	BODY-FAT-PERCENT SCHEMA
	14.	LEAN-MASS-KG SCHEMA
	15.	SKELETAL-MUSCLE-PERCENT SCHEMA
	16.	VISCERAL-FAT-LEVEL SCHEMA
	17.	BONE-MASS SCHEMA
	18.	HYDRATION-PERCENT SCHEMA
	19.	BASAL-METABOLIC-RATE SCHEMA (BMR)
	20.	METABOLIC-AGE SCHEMA

⸻

3. ANTHROPOMETRICS
	21.	HEIGHT-CM SCHEMA
	22.	HEIGHT-M SCHEMA
	23.	HEIGHT-IN SCHEMA
	24.	WEIGHT-NORMALIZED SCHEMA
	25.	BMI SCHEMA (Body Mass Index)
	26.	BSA SCHEMA (Body Surface Area)
	27.	WHR SCHEMA (Waist-Hip Ratio)
	28.	WTHR SCHEMA (Waist-to-Height Ratio)
	29.	HEAD-CIRCUMFERENCE SCHEMA
	30.	CHEST-CIRCUMFERENCE SCHEMA
	31.	WAIST-CIRCUMFERENCE SCHEMA
	32.	HIP-CIRCUMFERENCE SCHEMA

⸻

4. LAB RESULTS — BLOOD CHEMISTRY
	33.	LAB-GLUCOSE-FASTING SCHEMA
	34.	LAB-GLUCOSE-RANDOM SCHEMA
	35.	LAB-HBA1C SCHEMA
	36.	LAB-INSULIN-FASTING SCHEMA
	37.	LAB-LIPID-HDL SCHEMA
	38.	LAB-LIPID-LDL SCHEMA
	39.	LAB-LIPID-TRIGLYCERIDES SCHEMA
	40.	LAB-LIPID-TOTAL-CHOLESTEROL SCHEMA
	41.	LAB-CHOLESTEROL-RATIO SCHEMA
	42.	LAB-CRP SCHEMA (C-Reactive Protein)
	43.	LAB-ESR SCHEMA
	44.	LAB-FERRITIN SCHEMA
	45.	LAB-IRON SCHEMA
	46.	LAB-TSH SCHEMA
	47.	LAB-T3 SCHEMA
	48.	LAB-T4 SCHEMA
	49.	LAB-ELECTROLYTES-SODIUM SCHEMA
	50.	LAB-ELECTROLYTES-POTASSIUM SCHEMA
	51.	LAB-ELECTROLYTES-CHLORIDE SCHEMA
	52.	LAB-CALCIUM SCHEMA
	53.	LAB-MAGNESIUM SCHEMA
	54.	LAB-VITAMIN-D25 SCHEMA
	55.	LAB-VITAMIN-B12 SCHEMA
	56.	LAB-FOLATE SCHEMA

⸻

5. LAB RESULTS — HEMATOLOGY
	57.	LAB-HEMOGLOBIN SCHEMA
	58.	LAB-HEMATOCRIT SCHEMA
	59.	LAB-RBC-COUNT SCHEMA
	60.	LAB-WBC-COUNT SCHEMA
	61.	LAB-PLATELET-COUNT SCHEMA
	62.	LAB-DIFFERENTIAL-NEUTROPHILS SCHEMA
	63.	LAB-DIFFERENTIAL-LYMPHOCYTES SCHEMA
	64.	LAB-DIFFERENTIAL-MONOCYTES SCHEMA
	65.	LAB-DIFFERENTIAL-EOSINOPHILS SCHEMA
	66.	LAB-DIFFERENTIAL-BASOPHILS SCHEMA

⸻

6. LAB RESULTS — LIVER
	67.	LAB-AST SCHEMA
	68.	LAB-ALT SCHEMA
	69.	LAB-GGT SCHEMA
	70.	LAB-ALK-PHOS SCHEMA
	71.	LAB-BILIRUBIN-TOTAL SCHEMA
	72.	LAB-BILIRUBIN-DIRECT SCHEMA

⸻

7. LAB RESULTS — KIDNEY
	73.	LAB-CREATININE SCHEMA
	74.	LAB-BUN SCHEMA
	75.	LAB-EGFR SCHEMA

⸻

8. CARDIORESPIRATORY FUNCTION
	76.	VO2MAX SCHEMA
	77.	VCO2 SCHEMA
	78.	O2-UPTAKE-KINETICS SCHEMA
	79.	VENTILATION-THRESHOLD SCHEMA
	80.	MAX-HEART-RATE SCHEMA
	81.	HRV SCHEMA (Heart Rate Variability)
	82.	PULSE-WAVE-VELOCITY SCHEMA
	83.	BLOOD-OXYGEN-CONTINUOUS SCHEMA (wearables)

⸻

9. ENDOCRINE & HORMONAL
	84.	CORTISOL-AM SCHEMA
	85.	CORTISOL-PM SCHEMA
	86.	TESTOSTERONE-TOTAL SCHEMA
	87.	TESTOSTERONE-FREE SCHEMA
	88.	ESTRADIOL SCHEMA
	89.	PROGESTERONE SCHEMA
	90.	PROLACTIN SCHEMA
	91.	LH SCHEMA
	92.	FSH SCHEMA

⸻

10. GENETICS
	93.	GENE-VARIANT-ID SCHEMA
	94.	GENOTYPE-CALL SCHEMA
	95.	SNP-RESULT SCHEMA
	96.	POLYGENIC-RISK-SCORE SCHEMA

⸻

11. LIFESTYLE / HABITS
	97.	SLEEP-DURATION SCHEMA
	98.	SLEEP-QUALITY SCHEMA
	99.	STEPS-PER-DAY SCHEMA
	100.	CALORIES-IN SCHEMA
	101.	CALORIES-OUT SCHEMA
	102.	WATER-INTAKE-LITERS SCHEMA
	103.	ALCOHOL-UNITS SCHEMA
	104.	CAFFEINE-MG SCHEMA

⸻

12. NUTRITION
	105.	MACRO-CARBS-G SCHEMA
	106.	MACRO-PROTEIN-G SCHEMA
	107.	MACRO-FAT-G SCHEMA
	108.	FIBER-G SCHEMA
	109.	SODIUM-MG SCHEMA
	110.	ADDED-SUGAR-G SCHEMA
	111.	CALCIUM-MG SCHEMA
	112.	POTASSIUM-MG SCHEMA

⸻

13. MENTAL HEALTH / PSYCHOLOGY
	113.	MOOD-RATING SCHEMA
	114.	STRESS-SCORE SCHEMA
	115.	ANXIETY-SCORE SCHEMA
	116.	DEPRESSION-SCORE PHQ9 SCHEMA
	117.	GAD7-SCORE SCHEMA
	118.	SLEEP-DISTRESS-SCALE SCHEMA
	119.	PAIN-SCALE SCHEMA

⸻

14. IMMUNE FUNCTION
	120.	IMMUNO-MARKER-IGA SCHEMA
	121.	IMMUNO-MARKER-IGG SCHEMA
	122.	IMMUNO-MARKER-IGM SCHEMA
	123.	HS-CRP IMMUNE SCHEMA
	124.	CYTOKINE-IL6 SCHEMA
	125.	CYTOKINE-TNF-ALPHA SCHEMA

⸻

15. DISEASE RISK SCORES
	126.	DIABETES-RISK-SCORE SCHEMA
	127.	CARDIO-RISK-SCORE SCHEMA
	128.	STROKE-RISK-SCORE SCHEMA
	129.	OBESITY-RISK-SCORE SCHEMA
	130.	LIVER-DISEASE-RISK-SCORE SCHEMA
	131.	KIDNEY-DISEASE-RISK-SCORE SCHEMA

⸻

16. RESPIRATORY HEALTH
	132.	FEV1 SCHEMA
	133.	FVC SCHEMA
	134.	FEV1-FVC-RATIO SCHEMA
	135.	PEF SCHEMA (Peak Expiratory Flow)
	136.	ASTHMA-SEVERITY SCHEMA

⸻

17. REPRODUCTIVE HEALTH
	137.	MENSTRUAL-CYCLE-DAY SCHEMA
	138.	MENSTRUAL-FLOW-LEVEL SCHEMA
	139.	OVULATION-PREDICTION-SCORE SCHEMA
	140.	SPERM-COUNT SCHEMA
	141.	SPERM-MOTILITY SCHEMA

⸻

18. WEARABLE DEVICE DATA
	142.	HRV-TIME-DOMAIN SCHEMA
	143.	HRV-FREQUENCY-DOMAIN SCHEMA
	144.	SKIN-TEMPERATURE SCHEMA
	145.	ECG-RAW-SIGNAL SCHEMA
	146.	PPG-SIGNAL SCHEMA
	147.	ACCELEROMETER-3D SCHEMA
	148.	GYROSCOPE-3D SCHEMA

⸻

19. LONGEVITY / AGE MARKERS
	149.	BIOLOGICAL-AGE SCHEMA
	150.	EPIGENETIC-AGE SCHEMA
	151.	TELOMERE-LENGTH SCHEMA
	152.	OXIDATIVE-STRESS-SCORE SCHEMA
	153.	GLYCATION-SCORE SCHEMA

⸻

20. FULL HEALTH PROFILES
	154.	HEALTH-PROFILE-BASIC SCHEMA
	155.	HEALTH-PROFILE-CARDIO SCHEMA
	156.	HEALTH-PROFILE-METABOLIC SCHEMA
	157.	HEALTH-PROFILE-LONGEVITY SCHEMA
	158.	HEALTH-PROFILE-FULL SCHEMA (everything unified)

🔴 1. BLOOD TYPE (YOU MISSED ALL OF THESE)

BLOOD GROUP
	•	BLOOD-TYPE-ABO SCHEMA
(“A”, “B”, “AB”, “O”)
	•	BLOOD-TYPE-RH SCHEMA
(“+” or “−”)
	•	BLOOD-TYPE-COMPLETE SCHEMA
(“A+”, “A−”, “B+”, “B−”, “AB+”, “AB−”, “O+”, “O−”)

ANTIGENS
	•	BLOOD-ANTIGEN-A SCHEMA
	•	BLOOD-ANTIGEN-B SCHEMA
	•	BLOOD-ANTIGEN-RHD SCHEMA
	•	BLOOD-ANTIGEN-MATRIX SCHEMA
(boolean map of A/B/RhD)

TRANSFUSION / COMPATIBILITY
	•	BLOOD-COMPATIBILITY-DONOR SCHEMA
	•	BLOOD-COMPATIBILITY-RECIPIENT SCHEMA

You missed the entire “blood type” class.

⸻

🔴 2. ALLERGEN / SENSITIVITY SCHEMAS (YOU MISSED ALL OF THESE)
	•	ALLERGY-FOOD SCHEMA
	•	ALLERGY-DRUG SCHEMA
	•	ALLERGY-ENVIRONMENTAL SCHEMA
	•	ALLERGY-SEVERITY SCHEMA
	•	ALLERGY-REACTION-TYPE SCHEMA
	•	INTOLERANCE-LACTOSE SCHEMA
	•	INTOLERANCE-GLUTEN SCHEMA
	•	INTOLERANCE-HISTAMINE SCHEMA
	•	INTOLERANCE-FRUCTOSE SCHEMA

⸻

🔴 3. IMMUNIZATION / VACCINE SCHEMAS (YOU MISSED ALL)
	•	VACCINE-CODE SCHEMA
	•	VACCINE-NAME SCHEMA
	•	VACCINE-LOT-NUMBER SCHEMA
	•	VACCINE-MANUFACTURER SCHEMA
	•	VACCINE-DOSE-NUMBER SCHEMA
	•	VACCINE-DATE SCHEMA
	•	VACCINE-SERIES-COMPLETION SCHEMA
	•	VACCINE-STATUS SCHEMA
(up-to-date, overdue, incomplete)

⸻

🔴 4. MEDICATION / PRESCRIPTION SCHEMAS (ALL MISSING)
	•	MEDICATION-NAME SCHEMA
	•	MEDICATION-DOSE-MG SCHEMA
	•	MEDICATION-FORM SCHEMA (tablet, capsule, injection, etc.)
	•	MEDICATION-FREQUENCY SCHEMA
	•	MEDICATION-ROUTE SCHEMA (oral, IV, subcutaneous, etc.)
	•	MEDICATION-DURATION SCHEMA
	•	MEDICATION-REFILL-COUNT SCHEMA
	•	MEDICATION-START-DATE SCHEMA
	•	MEDICATION-END-DATE SCHEMA
	•	MEDICATION-ACTIVE-STATUS SCHEMA

⸻

🔴 5. CLINICAL DIAGNOSIS SCHEMAS (ALL MISSING)
	•	ICD10-CODE SCHEMA
	•	ICD11-CODE SCHEMA
	•	SNOMED-CODE SCHEMA
	•	DIAGNOSIS-NAME SCHEMA
	•	DIAGNOSIS-SEVERITY SCHEMA
	•	DIAGNOSIS-ONSET-DATE SCHEMA
	•	DIAGNOSIS-RESOLUTION-DATE SCHEMA

⸻

🔴 6. PROCEDURE / SURGERY SCHEMAS (ALL MISSING)
	•	PROCEDURE-CODE SCHEMA (CPT, SNOMED)
	•	PROCEDURE-NAME SCHEMA
	•	PROCEDURE-DATE SCHEMA
	•	PROCEDURE-STATUS SCHEMA
	•	SURGERY-TYPE SCHEMA
	•	SURGERY-RISK-SCORE SCHEMA

⸻

🔴 7. DISABILITY / FUNCTIONAL STATUS (ALL MISSING)
	•	FUNCTIONAL-MOBILITY-SCORE SCHEMA
	•	ACTIVITIES-OF-DAILY-LIVING SCHEMA
	•	INSTRUMENTAL-ADL SCHEMA
	•	PAIN-DISABILITY-INDEX SCHEMA

⸻

🔴 8. EXPOSURE / ENVIRONMENTAL HEALTH (ALL MISSING)
	•	SMOKING-STATUS SCHEMA
	•	SMOKING-PACK-YEARS SCHEMA
	•	SECONDHAND-SMOKE-EXPOSURE SCHEMA
	•	AIR-QUALITY-EXPOSURE SCHEMA (PM2.5)
	•	UV-EXPOSURE SCHEMA
	•	NOISE-EXPOSURE SCHEMA

⸻

🔴 9. CLINICAL RISK FACTORS (ALL MISSING)
	•	FAMILY-HISTORY-DISEASE SCHEMA
	•	GENETIC-RISK-FACTOR SCHEMA
	•	CARDIAC-RISK-FACTOR SCHEMA
	•	METABOLIC-RISK-FACTOR SCHEMA
	•	IMMUNE-RISK-FACTOR SCHEMA

⸻

🔴 10. MEDICAL DEVICE DATA (ALL MISSING)
	•	DEVICE-ID SCHEMA
	•	DEVICE-MANUFACTURER SCHEMA
	•	DEVICE-FIRMWARE-VERSION SCHEMA
	•	DEVICE-READING-TIMESTAMP SCHEMA
	•	DEVICE-SIGNAL-QUALITY SCHEMA

⸻

🔴 11. CLINICAL NOTES / OBSERVATION SCHEMAS (ALL MISSING)
	•	CLINICAL-NOTE-TEXT SCHEMA
	•	CLINICAL-NOTE-TYPE SCHEMA
	•	CLINICAL-OBSERVATION SCHEMA
	•	CHIEF-COMPLAINT SCHEMA
	•	HISTORY-OF-PRESENT-ILLNESS SCHEMA
	•	REVIEW-OF-SYSTEMS SCHEMA
	•	PHYSICAL-EXAM-FINDING SCHEMA

⸻

🔴 12. CARE PLAN / TREATMENT (ALL MISSING)
	•	CARE-PLAN-GOAL SCHEMA
	•	CARE-PLAN-STATUS SCHEMA
	•	FOLLOW-UP-INTERVAL SCHEMA
	•	TREATMENT-ADHERENCE SCHEMA
	•	TREATMENT-RESPONSE SCHEMA

⸻

🔴 13. INSURANCE / BILLING (IF HEALTH SYSTEMS)

(You missed these entirely.)
	•	INSURANCE-PAYER-ID SCHEMA
	•	INSURANCE-POLICY-NUMBER SCHEMA
	•	INSURANCE-GROUP-NUMBER SCHEMA
	•	CLAIM-COST SCHEMA
	•	CLAIM-STATUS SCHEMA

    1. BLOOD TYPE ANTIGEN SYSTEMS (BEYOND ABO/RH)

ABO + Rh is not the full blood typing system.

You are missing all these:
	•	BLOOD-TYPE-KELL SCHEMA (K, k)
	•	BLOOD-TYPE-DUFFY SCHEMA (Fyᵃ, Fyᵇ)
	•	BLOOD-TYPE-KIDD SCHEMA (Jkᵃ, Jkᵇ)
	•	BLOOD-TYPE-MNS SCHEMA
	•	BLOOD-TYPE-LUTHERAN SCHEMA
	•	BLOOD-TYPE-P1PK SCHEMA
	•	BLOOD-TYPE-Lewis SCHEMA
	•	BLOOD-TYPE-EXTENDED-PANEL SCHEMA (boolean map of all 36 antigen systems)

These are mandatory in transfusion medicine.

⸻

2. MEDICAL IMAGING SCHEMAS (NOT IN YOUR LIST)

You missed imaging completely:
	•	IMAGING-MODALITY SCHEMA
(X-ray, CT, MRI, Ultrasound, PET, SPECT)
	•	IMAGING-FINDING SCHEMA
	•	IMAGING-ACQUISITION-DATE SCHEMA
	•	IMAGING-DICOM-ID SCHEMA
	•	IMAGING-RADIATION-DOSE SCHEMA
	•	IMAGING-REPORT-TEXT SCHEMA

⸻

3. INFECTIONS & MICROBIOLOGY (MISSING ENTIRELY)
	•	MICROBE-SPECIES SCHEMA
	•	CULTURE-RESULT SCHEMA
	•	ANTIBIOTIC-SENSITIVITY SCHEMA (S/I/R)
	•	VIRAL-LOAD SCHEMA
	•	PCR-CYCLE-THRESHOLD SCHEMA
	•	RAPID-TEST-RESULT SCHEMA

⸻

4. IMMUNOLOGY / AUTOIMMUNE MARKERS (NOT YET LISTED)

You only listed IgA/IgG/IgM. Missing dozens:
	•	AUTOANTIBODY-ANA SCHEMA
	•	AUTOANTIBODY-RF SCHEMA
	•	AUTOANTIBODY-ANTI-CCP SCHEMA
	•	AUTOANTIBODY-ANTI-TPO SCHEMA
	•	AUTOANTIBODY-ANTI-dsDNA SCHEMA

These are essential in autoimmune diagnostics.

⸻

5. ONCOLOGY / CANCER-SPECIFIC SCHEMAS (COMPLETELY MISSING)
	•	TUMOR-STAGE-TNM SCHEMA
	•	TUMOR-GRADE SCHEMA
	•	ONCOGENE-MUTATION SCHEMA (EGFR, KRAS, BRAF…)
	•	CANCER-MARKER-PSA SCHEMA
	•	CANCER-MARKER-CEA SCHEMA
	•	CANCER-MARKER-CA125 SCHEMA

⸻

6. INFERTILITY & MATERNAL HEALTH (NOT LISTED)

You have menstrual/fertility, but missing core obstetric schemas:
	•	PREGNANCY-STATUS SCHEMA
	•	PREGNANCY-WEEK SCHEMA
	•	PREGNANCY-GRAVIDA SCHEMA
	•	PREGNANCY-PARA SCHEMA
	•	GESTATIONAL-DIABETES-SCREEN SCHEMA
	•	ULTRASOUND-FETAL-HEART-RATE SCHEMA

⸻

7. PEDIATRIC-SPECIFIC SCHEMAS (MISSING)
	•	APGAR-SCORE SCHEMA
	•	PEDIATRIC-GROWTH-PERCENTILE SCHEMA
	•	HEAD-CIRCUMFERENCE-PERCENTILE SCHEMA
	•	WEIGHT-FOR-AGE-Z-SCORE SCHEMA
	•	HEIGHT-FOR-AGE-Z-SCORE SCHEMA

⸻

8. DENTAL HEALTH (NOT INCLUDED)
	•	ORAL-HEALTH-SCORE SCHEMA
	•	DMFT-INDEX SCHEMA (Decayed, Missing, Filled Teeth)
	•	PERIODONTAL-POCKET-DEPTH SCHEMA
	•	TOOTH-NUMBER SCHEMA

⸻

9. VISION & HEARING (MISSING)
	•	VISUAL-ACUITY SCHEMA (20/20, 20/40…)
	•	COLOR-VISION SCHEMA
	•	HEARING-THRESHOLD-DB SCHEMA
	•	AUDIOGRAM-SCORE SCHEMA

⸻

10. FALL RISK & FRAILTY (GERIATRIC HEALTH)

Missing all these:
	•	FRAILTY-INDEX SCHEMA
	•	FALL-RISK-SCORE SCHEMA
	•	GAIT-SPEED SCHEMA
	•	BALANCE-ASSESSMENT SCHEMA

⸻

11. HOSPITAL / ACUTE CARE (MISSING)
	•	TRIAGE-SEVERITY-SCORE SCHEMA
	•	GLASGOW-COMA-SCALE SCHEMA
	•	NEWS2-SCORE SCHEMA
	•	SOFA-SCORE SCHEMA (sepsis)

⸻

12. SPECIALTY SCORES (YOU MISSED A TON)

Cardiology
	•	CHA2DS2-VASc SCORE SCHEMA
	•	HAS-BLED SCORE SCHEMA

Pain
	•	PAIN-LOCATION SCHEMA
	•	PAIN-DURATION SCHEMA

Pulmonary
	•	COPD-GOLD-STAGE SCHEMA
	•	ASTHMA-CONTROL-SCORE SCHEMA (different from severity)

Sleep Medicine
	•	APNEA-HYPOPNEA-INDEX SCHEMA (AHI)

⸻

13. EXPANDED LAB PANELS (YOU MISSED THESE)
	•	D-DIMER SCHEMA
	•	TROPONIN SCHEMA
	•	BNP/NT-proBNP SCHEMA
	•	LDH SCHEMA
	•	LIPASE SCHEMA
	•	AMYLASE SCHEMA

⸻

14. NUTRITION / DIETARY (EXTRA)

You missed:
	•	OMEGA-3-INDEX SCHEMA
	•	GLYCEMIC-LOAD SCHEMA
	•	MICRONUTRIENT-ZINC SCHEMA
	•	MICRONUTRIENT-COPPER SCHEMA
	•	MICRONUTRIENT-SELENIUM SCHEMA

⸻

15. MENTAL HEALTH (EXTRA)

Missing foundational schemas:
	•	MENTAL-STATUS-EXAM SCHEMA
	•	SUICIDE-RISK-SCORE SCHEMA (C-SSRS)
	•	ADHD-RATING-SCALE SCHEMA
	•	PTSD-SCORE (PCL-5) SCHEMA

⸻

16. EPIDEMIOLOGY / PUBLIC HEALTH

Missing:
	•	INFECTION-RISK-LEVEL SCHEMA
	•	EXPOSURE-SCORE SCHEMA
	•	CONTACT-TRACING-RISK SCHEMA
	•	OUTBREAK-SEVERITY-SCORE SCHEMA

⸻

17. HEALTHCARE OPERATIONS

Missing:
	•	APPOINTMENT-STATUS SCHEMA
	•	PROVIDER-ID SCHEMA
	•	CARE-TEAM-MEMBER SCHEMA
	•	MEDICAL-FACILITY-TYPE SCHEMA

    Missing schemas:
	•	SDOH-INCOME-LEVEL SCHEMA
	•	SDOH-EMPLOYMENT-STATUS SCHEMA
	•	SDOH-HOUSING-STABILITY SCHEMA
	•	SDOH-FOOD-INSECURITY SCHEMA
	•	SDOH-TRANSPORTATION-ACCESS SCHEMA
	•	SDOH-EDUCATION-LEVEL SCHEMA
	•	SDOH-SOCIAL-SUPPORT SCHEMA
	•	SDOH-HOUSING-CONDITION SCHEMA
	•	SDOH-PHONE-ACCESS SCHEMA
	•	SDOH-DIGITAL-LITERACY SCHEMA
	•	SDOH-HEALTH-LITERACY SCHEMA
	•	SDOH-NEIGHBORHOOD-SAFETY SCHEMA
	•	SDOH-HOUSEHOLD-SIZE SCHEMA
	•	SDOH-IMMIGRATION-STATUS SCHEMA
	•	SDOH-LANGUAGE-PROFICIENCY SCHEMA
    */

	🔴 SECTION 21 — BLOOD TYPE / TRANSFUSION
	159.	BLOOD-TYPE-ABO SCHEMA
	160.	BLOOD-TYPE-RH SCHEMA
	161.	BLOOD-TYPE-COMPLETE SCHEMA
	162.	BLOOD-ANTIGEN-A SCHEMA
	163.	BLOOD-ANTIGEN-B SCHEMA
	164.	BLOOD-ANTIGEN-RHD SCHEMA
	165.	BLOOD-ANTIGEN-MATRIX SCHEMA
	166.	BLOOD-COMPATIBILITY-DONOR SCHEMA
	167.	BLOOD-COMPATIBILITY-RECIPIENT SCHEMA
	168.	BLOOD-TYPE-KELL SCHEMA
	169.	BLOOD-TYPE-DUFFY SCHEMA
	170.	BLOOD-TYPE-KIDD SCHEMA
	171.	BLOOD-TYPE-MNS SCHEMA
	172.	BLOOD-TYPE-LUTHERAN SCHEMA
	173.	BLOOD-TYPE-P1PK SCHEMA
	174.	BLOOD-TYPE-LEWIS SCHEMA
	175.	BLOOD-TYPE-EXTENDED-PANEL SCHEMA

⸻

🔴 SECTION 22 — ALLERGY / INTOLERANCE
	176.	ALLERGY-FOOD SCHEMA
	177.	ALLERGY-DRUG SCHEMA
	178.	ALLERGY-ENVIRONMENTAL SCHEMA
	179.	ALLERGY-SEVERITY SCHEMA
	180.	ALLERGY-REACTION-TYPE SCHEMA
	181.	INTOLERANCE-LACTOSE SCHEMA
	182.	INTOLERANCE-GLUTEN SCHEMA
	183.	INTOLERANCE-HISTAMINE SCHEMA
	184.	INTOLERANCE-FRUCTOSE SCHEMA

⸻

🔴 SECTION 23 — IMMUNIZATION / VACCINE
	185.	VACCINE-CODE SCHEMA
	186.	VACCINE-NAME SCHEMA
	187.	VACCINE-LOT-NUMBER SCHEMA
	188.	VACCINE-MANUFACTURER SCHEMA
	189.	VACCINE-DOSE-NUMBER SCHEMA
	190.	VACCINE-DATE SCHEMA
	191.	VACCINE-SERIES-COMPLETION SCHEMA
	192.	VACCINE-STATUS SCHEMA

⸻

🔴 SECTION 24 — MEDICATION / PRESCRIPTION
	193.	MEDICATION-NAME SCHEMA
	194.	MEDICATION-DOSE-MG SCHEMA
	195.	MEDICATION-FORM SCHEMA
	196.	MEDICATION-FREQUENCY SCHEMA
	197.	MEDICATION-ROUTE SCHEMA
	198.	MEDICATION-DURATION SCHEMA
	199.	MEDICATION-REFILL-COUNT SCHEMA
	200.	MEDICATION-START-DATE SCHEMA
	201.	MEDICATION-END-DATE SCHEMA
	202.	MEDICATION-ACTIVE-STATUS SCHEMA

⸻

🔴 SECTION 25 — CLINICAL DIAGNOSIS
	203.	ICD10-CODE SCHEMA
	204.	ICD11-CODE SCHEMA
	205.	SNOMED-CODE SCHEMA
	206.	DIAGNOSIS-NAME SCHEMA
	207.	DIAGNOSIS-SEVERITY SCHEMA
	208.	DIAGNOSIS-ONSET-DATE SCHEMA
	209.	DIAGNOSIS-RESOLUTION-DATE SCHEMA

⸻

🔴 SECTION 26 — PROCEDURE / SURGERY
	210.	PROCEDURE-CODE SCHEMA
	211.	PROCEDURE-NAME SCHEMA
	212.	PROCEDURE-DATE SCHEMA
	213.	PROCEDURE-STATUS SCHEMA
	214.	SURGERY-TYPE SCHEMA
	215.	SURGERY-RISK-SCORE SCHEMA

⸻

🔴 SECTION 27 — DISABILITY / FUNCTIONAL STATUS
	216.	FUNCTIONAL-MOBILITY-SCORE SCHEMA
	217.	ACTIVITIES-OF-DAILY-LIVING SCHEMA
	218.	INSTRUMENTAL-ADL SCHEMA
	219.	PAIN-DISABILITY-INDEX SCHEMA

⸻

🔴 SECTION 28 — EXPOSURE / ENVIRONMENTAL HEALTH
	220.	SMOKING-STATUS SCHEMA
	221.	SMOKING-PACK-YEARS SCHEMA
	222.	SECONDHAND-SMOKE-EXPOSURE SCHEMA
	223.	AIR-QUALITY-EXPOSURE SCHEMA
	224.	UV-EXPOSURE SCHEMA
	225.	NOISE-EXPOSURE SCHEMA

⸻

🔴 SECTION 29 — CLINICAL RISK FACTORS
	226.	FAMILY-HISTORY-DISEASE SCHEMA
	227.	GENETIC-RISK-FACTOR SCHEMA
	228.	CARDIAC-RISK-FACTOR SCHEMA
	229.	METABOLIC-RISK-FACTOR SCHEMA
	230.	IMMUNE-RISK-FACTOR SCHEMA

⸻

🔴 SECTION 30 — MEDICAL DEVICE DATA
	231.	DEVICE-ID SCHEMA
	232.	DEVICE-MANUFACTURER SCHEMA
	233.	DEVICE-FIRMWARE-VERSION SCHEMA
	234.	DEVICE-READING-TIMESTAMP SCHEMA
	235.	DEVICE-SIGNAL-QUALITY SCHEMA

⸻

🔴 SECTION 31 — CLINICAL NOTES / OBSERVATIONS
	236.	CLINICAL-NOTE-TEXT SCHEMA
	237.	CLINICAL-NOTE-TYPE SCHEMA
	238.	CLINICAL-OBSERVATION SCHEMA
	239.	CHIEF-COMPLAINT SCHEMA
	240.	HISTORY-OF-PRESENT-ILLNESS SCHEMA
	241.	REVIEW-OF-SYSTEMS SCHEMA
	242.	PHYSICAL-EXAM-FINDING SCHEMA

⸻

🔴 SECTION 32 — CARE PLAN / TREATMENT
	243.	CARE-PLAN-GOAL SCHEMA
	244.	CARE-PLAN-STATUS SCHEMA
	245.	FOLLOW-UP-INTERVAL SCHEMA
	246.	TREATMENT-ADHERENCE SCHEMA
	247.	TREATMENT-RESPONSE SCHEMA

⸻

🔴 SECTION 33 — INSURANCE / BILLING
	248.	INSURANCE-PAYER-ID SCHEMA
	249.	INSURANCE-POLICY-NUMBER SCHEMA
	250.	INSURANCE-GROUP-NUMBER SCHEMA
	251.	CLAIM-COST SCHEMA
	252.	CLAIM-STATUS SCHEMA

⸻

🔴 SECTION 34 — MEDICAL IMAGING
	253.	IMAGING-MODALITY SCHEMA
	254.	IMAGING-FINDING SCHEMA
	255.	IMAGING-ACQUISITION-DATE SCHEMA
	256.	IMAGING-DICOM-ID SCHEMA
	257.	IMAGING-RADIATION-DOSE SCHEMA
	258.	IMAGING-REPORT-TEXT SCHEMA

⸻

🔴 SECTION 35 — MICROBIOLOGY / INFECTION
	259.	MICROBE-SPECIES SCHEMA
	260.	CULTURE-RESULT SCHEMA
	261.	ANTIBIOTIC-SENSITIVITY SCHEMA
	262.	VIRAL-LOAD SCHEMA
	263.	PCR-CYCLE-THRESHOLD SCHEMA
	264.	RAPID-TEST-RESULT SCHEMA

⸻

🔴 SECTION 36 — IMMUNOLOGY / AUTOIMMUNE
	265.	AUTOANTIBODY-ANA SCHEMA
	266.	AUTOANTIBODY-RF SCHEMA
	267.	AUTOANTIBODY-ANTI-CCP SCHEMA
	268.	AUTOANTIBODY-ANTI-TPO SCHEMA
	269.	AUTOANTIBODY-ANTI-DSDNA SCHEMA

⸻

🔴 SECTION 37 — ONCOLOGY / CANCER
	270.	TUMOR-STAGE-TNM SCHEMA
	271.	TUMOR-GRADE SCHEMA
	272.	ONCOGENE-MUTATION SCHEMA
	273.	CANCER-MARKER-PSA SCHEMA
	274.	CANCER-MARKER-CEA SCHEMA
	275.	CANCER-MARKER-CA125 SCHEMA

⸻

🔴 SECTION 38 — MATERNAL / INFERTILITY
	276.	PREGNANCY-STATUS SCHEMA
	277.	PREGNANCY-WEEK SCHEMA
	278.	PREGNANCY-GRAVIDA SCHEMA
	279.	PREGNANCY-PARA SCHEMA
	280.	GESTATIONAL-DIABETES-SCREEN SCHEMA
	281.	ULTRASOUND-FETAL-HEART-RATE SCHEMA

⸻

🔴 SECTION 39 — PEDIATRIC
	282.	APGAR-SCORE SCHEMA
	283.	PEDIATRIC-GROWTH-PERCENTILE SCHEMA
	284.	HEAD-CIRCUMFERENCE-PERCENTILE SCHEMA
	285.	WEIGHT-FOR-AGE-Z-SCORE SCHEMA
	286.	HEIGHT-FOR-AGE-Z-SCORE SCHEMA

⸻

🔴 SECTION 40 — DENTAL
	287.	ORAL-HEALTH-SCORE SCHEMA
	288.	DMFT-INDEX SCHEMA
	289.	PERIODONTAL-POCKET-DEPTH SCHEMA
	290.	TOOTH-NUMBER SCHEMA

⸻

🔴 SECTION 41 — VISION / HEARING
	291.	VISUAL-ACUITY SCHEMA
	292.	COLOR-VISION SCHEMA
	293.	HEARING-THRESHOLD-DB SCHEMA
	294.	AUDIOGRAM-SCORE SCHEMA

⸻

🔴 SECTION 42 — GERIATRIC / FRAILTY
	295.	FRAILTY-INDEX SCHEMA
	296.	FALL-RISK-SCORE SCHEMA
	297.	GAIT-SPEED SCHEMA
	298.	BALANCE-ASSESSMENT SCHEMA

⸻

🔴 SECTION 43 — ACUTE / HOSPITAL SCORES
	299.	TRIAGE-SEVERITY-SCORE SCHEMA
	300.	GLASGOW-COMA-SCALE SCHEMA
	301.	NEWS2-SCORE SCHEMA
	302.	SOFA-SCORE SCHEMA

⸻

🔴 SECTION 44 — SPECIALTY SCORES
	303.	CHA2DS2-VASc SCORE SCHEMA
	304.	HAS-BLED SCORE SCHEMA
	305.	PAIN-LOCATION SCHEMA
	306.	PAIN-DURATION SCHEMA
	307.	COPD-GOLD-STAGE SCHEMA
	308.	ASTHMA-CONTROL-SCORE SCHEMA
	309.	APNEA-HYPOPNEA-INDEX SCHEMA

⸻

🔴 SECTION 45 — EXPANDED LAB PANELS
	310.	D-DIMER SCHEMA
	311.	TROPONIN SCHEMA
	312.	BNP/NT-proBNP SCHEMA
	313.	LDH SCHEMA
	314.	LIPASE SCHEMA
	315.	AMYLASE SCHEMA

⸻

🔴 SECTION 46 — EXTENDED NUTRITION
	316.	OMEGA-3-INDEX SCHEMA
	317.	GLYCEMIC-LOAD SCHEMA
	318.	MICRONUTRIENT-ZINC SCHEMA
	319.	MICRONUTRIENT-COPPER SCHEMA
	320.	MICRONUTRIENT-SELENIUM SCHEMA

⸻

🔴 SECTION 47 — MENTAL HEALTH (EXTENDED)
	321.	MENTAL-STATUS-EXAM SCHEMA
	322.	SUICIDE-RISK-SCORE SCHEMA
	323.	ADHD-RATING-SCALE SCHEMA
	324.	PTSD-SCORE SCHEMA

⸻

🔴 SECTION 48 — EPIDEMIOLOGY / PUBLIC HEALTH
	325.	INFECTION-RISK-LEVEL SCHEMA
	326.	EXPOSURE-SCORE SCHEMA
	327.	CONTACT-TRACING-RISK SCHEMA
	328.	OUTBREAK-SEVERITY-SCORE SCHEMA

⸻

🔴 SECTION 49 — HEALTHCARE OPERATIONS
	329.	APPOINTMENT-STATUS SCHEMA
	330.	PROVIDER-ID SCHEMA
	331.	CARE-TEAM-MEMBER SCHEMA
	332.	MEDICAL-FACILITY-TYPE SCHEMA

⸻

🔴 SECTION 50 — SDOH (SOCIAL DETERMINANTS OF HEALTH)
	333.	SDOH-INCOME-LEVEL SCHEMA
	334.	SDOH-EMPLOYMENT-STATUS SCHEMA
	335.	SDOH-HOUSING-STABILITY SCHEMA
	336.	SDOH-FOOD-INSECURITY SCHEMA
	337.	SDOH-TRANSPORTATION-ACCESS SCHEMA
	338.	SDOH-EDUCATION-LEVEL SCHEMA
	339.	SDOH-SOCIAL-SUPPORT SCHEMA
	340.	SDOH-HOUSING-CONDITION SCHEMA
	341.	SDOH-PHONE-ACCESS SCHEMA
	342.	SDOH-DIGITAL-LITERACY SCHEMA
	343.	SDOH-HEALTH-LITERACY SCHEMA
	344.	SDOH-NEIGHBORHOOD-SAFETY SCHEMA
	345.	SDOH-HOUSEHOLD-SIZE SCHEMA
	346.	SDOH-IMMIGRATION-STATUS SCHEMA
	347.	SDOH-LANGUAGE-PROFICIENCY SCHEMA