✅ SECTION 1 — CORE HOLIDAY SCHEMAS
	1.	HOLIDAY-NAME-SCHEMA
	2.	HOLIDAY-DATE-SCHEMA (YYYY-MM-DD)
	3.	HOLIDAY-DATETIME-SCHEMA
	4.	HOLIDAY-ISO8601-SCHEMA
	5.	HOLIDAY-CANONICAL-SCHEMA
	6.	HOLIDAY-COERCE-SCHEMA (string → date)
	7.	HOLIDAY-NORMALIZED-SCHEMA
	8.	HOLIDAY-OPTIONAL-SCHEMA
	9.	HOLIDAY-NULLABLE-SCHEMA
	10.	HOLIDAY-LOCALE-AWARE-SCHEMA
	11.	HOLIDAY-DESCRIPTION-SCHEMA
	12.	HOLIDAY-CATEGORY-SCHEMA (public/religious/cultural/etc.)

⸻

✅ SECTION 2 — RECURRING HOLIDAY SCHEMAS
	13.	HOLIDAY-RECURRING-SCHEMA
	14.	HOLIDAY-ANNUAL-FIXED-SCHEMA (e.g., Jan 1)
	15.	HOLIDAY-ANNUAL-MOVEABLE-SCHEMA (e.g., Easter)
	16.	HOLIDAY-NTH-WEEKDAY-SCHEMA (3rd Monday of Feb)
	17.	HOLIDAY-RRULE-SCHEMA (iCalendar recurrence rule)
	18.	HOLIDAY-OCCURRENCE-SCHEMA (nth occurrence per year)
	19.	HOLIDAY-EVERY-N-YEARS-SCHEMA
	20.	HOLIDAY-SUNSET-RANGE-SCHEMA (holiday that ends in year X)
	21.	HOLIDAY-SOLAR-LUNAR-BASED-SCHEMA
	22.	HOLIDAY-ASTRONOMICAL-CALC-SCHEMA
	23.	HOLIDAY-OBSERVED-RULE-SCHEMA (shift weekend → weekday)
	24.	HOLIDAY-SUBSTITUTED-DATE-SCHEMA (UK “substitute day”)

⸻

✅ SECTION 3 — PUBLIC HOLIDAY SCHEMAS (GOVERNMENT / NATIONAL)
	25.	HOLIDAY-PUBLIC-SCHEMA
	26.	HOLIDAY-NATIONAL-SCHEMA
	27.	HOLIDAY-STATE-PROVINCE-SCHEMA
	28.	HOLIDAY-MUNICIPAL-SCHEMA
	29.	HOLIDAY-FEDERAL-SCHEMA
	30.	HOLIDAY-STATUTORY-SCHEMA
	31.	HOLIDAY-BANK-HOLIDAY-SCHEMA (UK, EU)
	32.	HOLIDAY-GOVERNMENT-OFFICE-SCHEMA
	33.	HOLIDAY-SCHOOL-CLOSURE-SCHEMA
	34.	HOLIDAY-COURT-CLOSURE-SCHEMA
	35.	HOLIDAY-PUBLIC-SECTOR-SCHEMA
	36.	HOLIDAY-EMERGENCY-CLOSURE-SCHEMA (declared emergencies)

⸻

✅ SECTION 4 — RELIGIOUS HOLIDAY SCHEMAS
	37.	HOLIDAY-CHRISTIAN-SCHEMA
	38.	HOLIDAY-JEWISH-SCHEMA
	39.	HOLIDAY-ISLAMIC-SCHEMA
	40.	HOLIDAY-BUDDHIST-SCHEMA
	41.	HOLIDAY-HINDU-SCHEMA
	42.	HOLIDAY-SIKH-SCHEMA
	43.	HOLIDAY-BAHAI-SCHEMA
	44.	HOLIDAY-ORTHODOX-CALENDAR-SCHEMA
	45.	HOLIDAY-LUNAR-CALENDAR-SCHEMA
	46.	HOLIDAY-EAST-ASIAN-FESTIVAL-SCHEMA (e.g., Qingming)
	47.	HOLIDAY-ZOROASTRIAN-SCHEMA
	48.	HOLIDAY-PAGAN-SCHEMA
	49.	HOLIDAY-RELIGIOUS-OBSERVANCE-LEVEL-SCHEMA (major/minor/fasting)

⸻

✅ SECTION 5 — CULTURAL / REGIONAL OBSERVANCE SCHEMAS
	50.	HOLIDAY-CULTURAL-SCHEMA
	51.	HOLIDAY-ETHNIC-GROUP-SCHEMA
	52.	HOLIDAY-FOLK-FESTIVAL-SCHEMA
	53.	HOLIDAY-HERITAGE-DAY-SCHEMA
	54.	HOLIDAY-LANGUAGE-GROUP-SCHEMA
	55.	HOLIDAY-TRIBAL-HOLIDAY-SCHEMA
	56.	HOLIDAY-LOCAL-FESTIVAL-SCHEMA
	57.	HOLIDAY-PARADE-DAY-SCHEMA
	58.	HOLIDAY-FAIR-MARKET-SCHEMA

⸻

✅ SECTION 6 — BUSINESS / WORKFORCE / HR HOLIDAY SCHEMAS
	59.	HOLIDAY-COMPANY-POLICY-SCHEMA
	60.	HOLIDAY-PAID-HOLIDAY-SCHEMA
	61.	HOLIDAY-UNPAID-HOLIDAY-SCHEMA
	62.	HOLIDAY-HR-OBSERVED-SCHEMA
	63.	HOLIDAY-VACATION-BLOCKOUT-SCHEMA
	64.	HOLIDAY-BLACKOUT-DATES-SCHEMA (peak periods)
	65.	HOLIDAY-CLOSURE-SCHEDULE-SCHEMA
	66.	HOLIDAY-WORKING-HOURS-ADJUSTMENT-SCHEMA
	67.	HOLIDAY-PAY-BOOST-SCHEMA (time-and-a-half, double-time)
	68.	HOLIDAY-OVERTIME-RULE-SCHEMA
	69.	HOLIDAY-SHIFT-EXCEPTION-SCHEMA
	70.	HOLIDAY-REMOTE-WORK-ALLOWED-SCHEMA
	71.	HOLIDAY-HR-APPROVAL-SCHEMA

⸻

✅ SECTION 7 — FINANCIAL / TRADING / BANKING HOLIDAY SCHEMAS
	72.	HOLIDAY-MARKET-CLOSURE-SCHEMA
	73.	HOLIDAY-STOCK-EXCHANGE-SCHEMA (NYSE/NASDAQ/etc.)
	74.	HOLIDAY-CLEARING-HOUSE-SCHEMA
	75.	HOLIDAY-BANK-SETTLEMENT-SCHEMA
	76.	HOLIDAY-FOREX-MARKET-SCHEMA
	77.	HOLIDAY-CRYPTO-EXCHANGE-SCHEMA
	78.	HOLIDAY-FEDWIRE-SCHEMA
	79.	HOLIDAY-PAYROLL-CUTOFF-SCHEMA
	80.	HOLIDAY-DIRECT-DEPOSIT-DELAY-SCHEMA
	81.	HOLIDAY-TAX-DEADLINE-SHIFT-SCHEMA
	82.	HOLIDAY-BILLING-ROLL-FORWARD-SCHEMA

⸻

✅ SECTION 8 — LOGISTICS / SHIPPING / SUPPLY CHAIN
	83.	HOLIDAY-SHIPPING-DELAY-SCHEMA
	84.	HOLIDAY-LAST-MILE-IMPACT-SCHEMA
	85.	HOLIDAY-COURIER-SCHEDULE-SCHEMA
	86.	HOLIDAY-FREIGHT-CARRIER-CLOSURE-SCHEMA
	87.	HOLIDAY-AIRPORT-LOAD-FACTOR-SCHEMA
	88.	HOLIDAY-PORT-CLOSURE-SCHEMA
	89.	HOLIDAY-RAIL-CLOSURE-SCHEMA
	90.	HOLIDAY-TRUCKING-RESTRICTION-SCHEMA
	91.	HOLIDAY-CUSTOMS-DELAY-SCHEMA

⸻

✅ SECTION 9 — TRAVEL / HOSPITALITY / TOURISM
	92.	HOLIDAY-PEAK-TRAVEL-SCHEMA
	93.	HOLIDAY-HOTEL-SURGE-SCHEMA
	94.	HOLIDAY-FLIGHT-SURGE-SCHEMA
	95.	HOLIDAY-VISA-CLOSURE-SCHEMA
	96.	HOLIDAY-TOURISM-SEASON-SCHEMA
	97.	HOLIDAY-CROWD-LEVEL-SCHEMA
	98.	HOLIDAY-PUBLIC-TRANSPORT-REDUCED-SERVICE-SCHEMA
	99.	HOLIDAY-ATTRACTION-HOURS-SCHEMA

⸻

✅ SECTION 10 — SCHEDULING / CALENDAR SYSTEMS
	100.	HOLIDAY-CALENDAR-EVENT-SCHEMA
	101.	HOLIDAY-ICS-SCHEMA
	102.	HOLIDAY-GCAL-SCHEMA
	103.	HOLIDAY-OUTLOOK-SCHEMA
	104.	HOLIDAY-FULLCALENDAR-SCHEMA
	105.	HOLIDAY-TIMEZONE-AWARE-SCHEMA
	106.	HOLIDAY-ALL-DAY-SCHEMA
	107.	HOLIDAY-MULTI-DAY-SCHEMA
	108.	HOLIDAY-WEEK-LONG-SCHEMA
	109.	HOLIDAY-DURATION-SCHEMA
	110.	HOLIDAY-EXCEPTIONS-SCHEMA
	111.	HOLIDAY-OCCURRENCE-LIST-SCHEMA
	112.	HOLIDAY-NEXT-OCCURRENCE-SCHEMA
	113.	HOLIDAY-PREVIOUS-OCCURRENCE-SCHEMA

⸻

✅ SECTION 11 — GOVERNMENT & CIVIC EVENTS
	114.	HOLIDAY-CIVIC-OBSERVANCE-SCHEMA
	115.	HOLIDAY-MEMORIAL-DAY-SCHEMA
	116.	HOLIDAY-ELECTION-DAY-SCHEMA
	117.	HOLIDAY-CENSUS-DAY-SCHEMA
	118.	HOLIDAY-LABOR-ACTION-SCHEMA
	119.	HOLIDAY-GOVERNMENT-ANNIVERSARY-SCHEMA
	120.	HOLIDAY-MILITARY-OBSERVANCE-SCHEMA

⸻

✅ SECTION 12 — EDUCATION / ACADEMIC CALENDAR
	121.	HOLIDAY-SCHOOL-HOLIDAY-SCHEMA
	122.	HOLIDAY-UNIVERSITY-BREAK-SCHEMA
	123.	HOLIDAY-SEMESTER-START-SCHEMA
	124.	HOLIDAY-SEMESTER-END-SCHEMA
	125.	HOLIDAY-EXAM-BLACKOUT-SCHEMA
	126.	HOLIDAY-STUDENT-OBSERVANCE-SCHEMA
	127.	HOLIDAY-FACULTY-STAFF-HOLIDAY-SCHEMA

⸻

✅ SECTION 13 — RETAIL / E-COMMERCE
	128.	HOLIDAY-SALES-EVENT-SCHEMA
	129.	HOLIDAY-PROMO-SEASON-SCHEMA
	130.	HOLIDAY-BLACK-FRIDAY-SCHEMA
	131.	HOLIDAY-CYBER-MONDAY-SCHEMA
	132.	HOLIDAY-SHIPPING-CUTOFF-SCHEMA
	133.	HOLIDAY-RETURNS-EXTENSION-SCHEMA
	134.	HOLIDAY-INVENTORY-RUSH-SCHEMA
	135.	HOLIDAY-GIFT-PEAK-SCHEMA
	136.	HOLIDAY-RETAIL-CLOSURE-SCHEMA

⸻

✅ SECTION 14 — ANALYTICS / INSIGHTS
	137.	HOLIDAY-IMPACT-SCORE-SCHEMA
	138.	HOLIDAY-TRAFFIC-CHANGE-SCHEMA
	139.	HOLIDAY-CONVERSION-DROP-SCHEMA
	140.	HOLIDAY-CONVERSION-SURGE-SCHEMA
	141.	HOLIDAY-SEASONALITY-SCHEMA
	142.	HOLIDAY-DOWNTIME-PROBABILITY-SCHEMA
	143.	HOLIDAY-WEEKDAY-DISTRIBUTION-SCHEMA
	144.	HOLIDAY-COMPARISON-YOY-SCHEMA

⸻

✅ SECTION 15 — STRUCTURAL & UTILITY SCHEMAS
	145.	HOLIDAY-LIST-SCHEMA
	146.	HOLIDAY-MAP-SCHEMA (country → holidays[])
	147.	HOLIDAY-RECORD-SCHEMA
	148.	HOLIDAY-UNION-SCHEMA
	149.	HOLIDAY-ENUM-SCHEMA
	150.	HOLIDAY-ID-SCHEMA
	151.	HOLIDAY-DATASET-SCHEMA
	152.	HOLIDAY-PAYLOAD-SCHEMA
	153.	HOLIDAY-FILTER-SCHEMA
	154.	HOLIDAY-QUERY-SCHEMA
	155.	HOLIDAY-SEARCH-PARAMS-SCHEMA
	156.	HOLIDAY-PARSER-SCHEMA
	157.	HOLIDAY-COERCION-FUNCTION-SCHEMA
	158.	HOLIDAY-VALIDATION-ERROR-SCHEMA
	159.	HOLIDAY-SERIALIZATION-SCHEMA
	160.	HOLIDAY-DESERIALIZATION-SCHEMA
	161.	HOLIDAY-API-SCHEMA
	162.	HOLIDAY-DB-STORAGE-SCHEMA
	163.	HOLIDAY-RESOLVER-SCHEMA
	164.	HOLIDAY-MERGE-POLICY-SCHEMA
	165.	HOLIDAY-OVERRIDE-POLICY-SCHEMA
	166.	HOLIDAY-VERSION-SCHEMA
	167.	HOLIDAY-METADATA-SCHEMA
