✅ SECTION 1 — CORE STATUS CODE SCHEMAS
	1.	HTTP-STATUS-CODE SCHEMA
	2.	HTTP-STATUS-CODE-STRING SCHEMA
	3.	HTTP-STATUS-CODE-NUMERIC SCHEMA
	4.	HTTP-STATUS-CODE-COERCE SCHEMA (string → int)
	5.	HTTP-STATUS-CODE-NORMALIZED SCHEMA (canonical int form)
	6.	HTTP-STATUS-CODE-ARRAY SCHEMA
	7.	HTTP-STATUS-CODE-MAP SCHEMA
	8.	HTTP-STATUS-CODE-FIELD SCHEMA
	9.	HTTP-STATUS-CODE-RANGE SCHEMA (100–599)
	10.	HTTP-STATUS-CODE-CUSTOM SCHEMA (non-standard 6xx/9xx)

⸻

✅ SECTION 2 — GROUPED CATEGORIES (RFC 9110)
11. HTTP-STATUS-1XX-INFORMATIONAL SCHEMA
12. HTTP-STATUS-2XX-SUCCESS SCHEMA
13. HTTP-STATUS-3XX-REDIRECTION SCHEMA
14. HTTP-STATUS-4XX-CLIENT-ERROR SCHEMA
15. HTTP-STATUS-5XX-SERVER-ERROR SCHEMA

⸻

✅ SECTION 3 — INFORMATIONAL (1xx)
16. HTTP-STATUS-100-CONTINUE SCHEMA
17. HTTP-STATUS-101-SWITCHING-PROTOCOLS SCHEMA
18. HTTP-STATUS-102-PROCESSING SCHEMA (WebDAV)
19. HTTP-STATUS-103-EARLY-HINTS SCHEMA

⸻

✅ SECTION 4 — SUCCESS (2xx)
20. HTTP-STATUS-200-OK SCHEMA
21. HTTP-STATUS-201-CREATED SCHEMA
22. HTTP-STATUS-202-ACCEPTED SCHEMA
23. HTTP-STATUS-203-NON-AUTHORITATIVE SCHEMA
24. HTTP-STATUS-204-NO-CONTENT SCHEMA
25. HTTP-STATUS-205-RESET-CONTENT SCHEMA
26. HTTP-STATUS-206-PARTIAL-CONTENT SCHEMA
27. HTTP-STATUS-207-MULTI-STATUS SCHEMA (WebDAV)
28. HTTP-STATUS-208-ALREADY-REPORTED SCHEMA
29. HTTP-STATUS-226-IM-USED SCHEMA (DAV)

⸻

✅ SECTION 5 — REDIRECTION (3xx)
30. HTTP-STATUS-300-MULTIPLE-CHOICES SCHEMA
31. HTTP-STATUS-301-MOVED-PERMANENTLY SCHEMA
32. HTTP-STATUS-302-FOUND SCHEMA
33. HTTP-STATUS-303-SEE-OTHER SCHEMA
34. HTTP-STATUS-304-NOT-MODIFIED SCHEMA
35. HTTP-STATUS-305-USE-PROXY SCHEMA (deprecated)
36. HTTP-STATUS-307-TEMPORARY-REDIRECT SCHEMA
37. HTTP-STATUS-308-PERMANENT-REDIRECT SCHEMA

⸻

✅ SECTION 6 — CLIENT ERROR (4xx)
38. HTTP-STATUS-400-BAD-REQUEST SCHEMA
39. HTTP-STATUS-401-UNAUTHORIZED SCHEMA
40. HTTP-STATUS-402-PAYMENT-REQUIRED SCHEMA
41. HTTP-STATUS-403-FORBIDDEN SCHEMA
42. HTTP-STATUS-404-NOT-FOUND SCHEMA
43. HTTP-STATUS-405-METHOD-NOT-ALLOWED SCHEMA
44. HTTP-STATUS-406-NOT-ACCEPTABLE SCHEMA
45. HTTP-STATUS-407-PROXY-AUTHENTICATION-REQUIRED SCHEMA
46. HTTP-STATUS-408-REQUEST-TIMEOUT SCHEMA
47. HTTP-STATUS-409-CONFLICT SCHEMA
48. HTTP-STATUS-410-GONE SCHEMA
49. HTTP-STATUS-411-LENGTH-REQUIRED SCHEMA
50. HTTP-STATUS-412-PRECONDITION-FAILED SCHEMA
51. HTTP-STATUS-413-PAYLOAD-TOO-LARGE SCHEMA
52. HTTP-STATUS-414-URI-TOO-LONG SCHEMA
53. HTTP-STATUS-415-UNSUPPORTED-MEDIA-TYPE SCHEMA
54. HTTP-STATUS-416-RANGE-NOT-SATISFIABLE SCHEMA
55. HTTP-STATUS-417-EXPECTATION-FAILED SCHEMA
56. HTTP-STATUS-418-I-AM-A-TEAPOT SCHEMA (RFC 2324)
57. HTTP-STATUS-421-MISDIRECTED-REQUEST SCHEMA
58. HTTP-STATUS-422-UNPROCESSABLE-ENTITY SCHEMA
59. HTTP-STATUS-423-LOCKED SCHEMA
60. HTTP-STATUS-424-FAILED-DEPENDENCY SCHEMA
61. HTTP-STATUS-425-TOO-EARLY SCHEMA
62. HTTP-STATUS-426-UPGRADE-REQUIRED SCHEMA
63. HTTP-STATUS-428-PRECONDITION-REQUIRED SCHEMA
64. HTTP-STATUS-429-TOO-MANY-REQUESTS SCHEMA
65. HTTP-STATUS-431-REQUEST-HEADER-FIELDS-TOO-LARGE SCHEMA
66. HTTP-STATUS-451-UNAVAILABLE-FOR-LEGAL-REASONS SCHEMA

⸻

✅ SECTION 7 — SERVER ERROR (5xx)
67. HTTP-STATUS-500-INTERNAL-SERVER-ERROR SCHEMA
68. HTTP-STATUS-501-NOT-IMPLEMENTED SCHEMA
69. HTTP-STATUS-502-BAD-GATEWAY SCHEMA
70. HTTP-STATUS-503-SERVICE-UNAVAILABLE SCHEMA
71. HTTP-STATUS-504-GATEWAY-TIMEOUT SCHEMA
72. HTTP-STATUS-505-HTTP-VERSION-NOT-SUPPORTED SCHEMA
73. HTTP-STATUS-506-VARIANT-ALSO-NEGOTIATES SCHEMA
74. HTTP-STATUS-507-INSUFFICIENT-STORAGE SCHEMA
75. HTTP-STATUS-508-LOOP-DETECTED SCHEMA
76. HTTP-STATUS-510-NOT-EXTENDED SCHEMA
77. HTTP-STATUS-511-NETWORK-AUTHENTICATION-REQUIRED SCHEMA

⸻

✅ SECTION 8 — EXTENDED / NON-STANDARD CODES
78. HTTP-STATUS-598-NETWORK-READ-TIMEOUT SCHEMA
79. HTTP-STATUS-599-NETWORK-CONNECT-TIMEOUT SCHEMA
80. HTTP-STATUS-444-NO-RESPONSE SCHEMA (Nginx)
81. HTTP-STATUS-494-REQUEST-HEADER-TOO-LARGE SCHEMA (Nginx)
82. HTTP-STATUS-499-CLIENT-CLOSED-REQUEST SCHEMA (Nginx)
83. HTTP-STATUS-520-WEB-SERVER-UNKNOWN-ERROR SCHEMA (Cloudflare)
84. HTTP-STATUS-521-WEB-SERVER-DOWN SCHEMA (Cloudflare)
85. HTTP-STATUS-522-CONNECTION-TIMEOUT SCHEMA (Cloudflare)
86. HTTP-STATUS-523-ORIGIN-UNREACHABLE SCHEMA (Cloudflare)
87. HTTP-STATUS-524-A-TIMEOUT-OCCURRED SCHEMA (Cloudflare)
88. HTTP-STATUS-525-SSL-HANDSHAKE-FAILED SCHEMA (Cloudflare)
89. HTTP-STATUS-526-INVALID-SSL-CERTIFICATE SCHEMA (Cloudflare)
90. HTTP-STATUS-527-RAILGUN-ERROR SCHEMA (Cloudflare)
91. HTTP-STATUS-530-ORIGIN-DNS-ERROR SCHEMA (Cloudflare)
92. HTTP-STATUS-598-PROXY-READ-TIMEOUT SCHEMA (AWS API GW)
93. HTTP-STATUS-599-PROXY-CONNECT-TIMEOUT SCHEMA (AWS API GW)
94. HTTP-STATUS-777-DEBUG-INTERNAL SCHEMA (Custom debug)
95. HTTP-STATUS-999-RATE-LIMIT SCHEMA (Private APIs)

⸻

✅ SECTION 9 — META / UTILITIES
96. HTTP-STATUS-CATEGORY SCHEMA (enum: “informational”, “success”, “redirect”, “client-error”, “server-error”)
97. HTTP-STATUS-DESCRIPTION SCHEMA (string, per RFC)
98. HTTP-STATUS-RETRYABLE SCHEMA (boolean helper)
99. HTTP-STATUS-TRANSIENT SCHEMA (boolean helper)
100. HTTP-STATUS-SEVERITY SCHEMA (enum : “ok”, “warning”, “error”, “critical”)

⸻

✅ SECTION 10 — OBSERVABILITY / ANALYTICS
101. HTTP-STATUS-METRIC-NAME SCHEMA
102. HTTP-STATUS-METRIC-LABELS SCHEMA
103. HTTP-STATUS-DISTRIBUTION SCHEMA (histogram)
104. HTTP-STATUS-COUNT-AGGREGATE SCHEMA
105. HTTP-STATUS-PERCENTILE SCHEMA (p50/p95/p99)