✅ SECTION 1 — CORE SI ILLUMINANCE SCHEMAS

These are the true illuminance units.
	1.	ILLUMINANCE-LUX SCHEMA (lx)
	2.	ILLUMINANCE-MILLILUX SCHEMA (mlx)
	3.	ILLUMINANCE-MICROLUX SCHEMA (μlx)
	4.	ILLUMINANCE-KILOLUX SCHEMA (klx)
	5.	ILLUMINANCE-PHOT SCHEMA (ph)
	6.	ILLUMINANCE-NO-PHOT SCHEMA (nph) (rare but real)
	7.	ILLUMINANCE-FC SCHEMA (foot-candle)
	8.	ILLUMINANCE-COERCE SCHEMA (any → lux)
	9.	ILLUMINANCE-CANONICAL SCHEMA (always returns N standard lux)

⸻

✅ SECTION 2 — PHOTOGRAPHY / CINEMATOGRAPHY–RELATED ILLUMINANCE

These are industry standards.
	10.	ILLUMINANCE-EXPOSURE-VALUE SCHEMA (EV → lux)
	11.	ILLUMINANCE-T-STOPS SCHEMA
	12.	ILLUMINANCE-F-STOPS SCHEMA (indirect)
	13.	ILLUMINANCE-LIGHT-METER-ASA SCHEMA
	14.	ILLUMINANCE-LIGHT-METER-DIN SCHEMA
	15.	ILLUMINANCE-METROLOGY-EXPOSURE SCHEMA (lux·s)
	16.	ILLUMINANCE-INCIDENT-LIGHT SCHEMA
	17.	ILLUMINANCE-REFLECTED-LIGHT SCHEMA

⸻

✅ SECTION 3 — ARCHITECTURAL / BUILDING STANDARDS (ISO/CIE)
	18.	ILLUMINANCE-TASK-LIGHTING SCHEMA
	19.	ILLUMINANCE-AMBIENT-LIGHT SCHEMA
	20.	ILLUMINANCE-EMERGENCY-LIGHT SCHEMA (ISO 30061)
	21.	ILLUMINANCE-DAYLIGHT-FACTOR SCHEMA (DF%)
	22.	ILLUMINANCE-UDI SCHEMA (Useful Daylight Illuminance)
	23.	ILLUMINANCE-DGP SCHEMA (glare probability) (derived from illuminance)
	24.	ILLUMINANCE-ROOM-AVERAGE SCHEMA
	25.	ILLUMINANCE-DESKTOP-WORKPLANE SCHEMA (lux at 0.8m)

⸻

✅ SECTION 4 — HUMAN VISION / HMI / DISPLAY ILLUMINANCE
	26.	ILLUMINANCE-AMBIENT-SCREEN SCHEMA
	27.	ILLUMINANCE-HDR-ENVIRONMENT SCHEMA
	28.	ILLUMINANCE-READABILITY SCHEMA (contrast threshold)
	29.	ILLUMINANCE-DISPLAY-HMI-LIGHTLEVEL SCHEMA
	30.	ILLUMINANCE-VISUAL-FATIGUE SCHEMA (illum. → ergonomic score)

⸻

✅ SECTION 5 — OUTDOOR / ASTRONOMY / NATURAL LIGHT SCHEMAS
	31.	ILLUMINANCE-SUNLIGHT-DIRECT SCHEMA
	32.	ILLUMINANCE-SUNLIGHT-DIFFUSE SCHEMA
	33.	ILLUMINANCE-MOONLIGHT SCHEMA
	34.	ILLUMINANCE-STARS-SKY-BRIGHTNESS SCHEMA (astronomical)
	35.	ILLUMINANCE-TWILIGHT SCHEMA
	36.	ILLUMINANCE-DAWN-DUSK SCHEMA
	37.	ILLUMINANCE-WEATHER-CORRECTED SCHEMA (cloud + fog)

⸻

✅ SECTION 6 — WORKPLACE / SAFETY / INDUSTRIAL LIGHTING
	38.	ILLUMINANCE-MACHINE-VISION SCHEMA
	39.	ILLUMINANCE-INSPECTION-LIGHT SCHEMA
	40.	ILLUMINANCE-HAZARD-AREA SCHEMA
	41.	ILLUMINANCE-MINING-LIGHT SCHEMA
	42.	ILLUMINANCE-TRANSPORT-LIGHT SCHEMA (rail/aviation)

⸻

✅ SECTION 7 — SENSOR & DEVICE ENGINEERING METRICS
	43.	ILLUMINANCE-SENSOR-RAW SCHEMA (ADC → lux)
	44.	ILLUMINANCE-SENSOR-LINEARIZED SCHEMA
	45.	ILLUMINANCE-ALS-SENSOR-TYPE SCHEMA (photodiode, RGB, IR-comp)
	46.	ILLUMINANCE-PHOTOCELL-RESISTANCE SCHEMA (lux derived)
	47.	ILLUMINANCE-CALIBRATION-CURVE SCHEMA
	48.	ILLUMINANCE-SENSOR-SATURATION SCHEMA
	49.	ILLUMINANCE-SENSOR-NOISE SCHEMA

⸻

🟩 SECTION 8 — ADVANCED SCIENTIFIC ILLUMINANCE (LAB/RESEARCH)
	50.	ILLUMINANCE-RADIOMETRIC-CONVERSION SCHEMA (W/m² → lux)
	51.	ILLUMINANCE-CIE-SPECTRAL-WEIGHTED SCHEMA (V(λ))
	52.	ILLUMINANCE-MESOPIC-LIGHT-SCHEMA (CIE 191:2010)
	53.	ILLUMINANCE-SCOTOPIC-SCHEMA
	54.	ILLUMINANCE-S/P-RATIO SCHEMA (scotopic/photopic)
	55.	ILLUMINANCE-UV-CORRECTED SCHEMA
	56.	ILLUMINANCE-HYPERSPECTRAL SCHEMA
	•	ILLUMINANCE-DAYLIGHT-AUTONOMY SCHEMA (DA%) → derived from your ILLUMINANCE-UDI
	•	ILLUMINANCE-CIRCADIAN-EQUIVALENT-LUX SCHEMA → derivative of your ILLUMINANCE-MESOPIC-LIGHT-SCHEMA
	•	ILLUMINANCE-PLANT-GROW-LIGHT-PPFD SCHEMA (μmol/m²/s) → strictly photosynthetic photon flux density, which is radiometric, not illuminance (so correctly excluded here)