✅ SECTION 1 — CORE SI MASS SCHEMAS (ALL)
These are the foundational physical units.
	1.	MASS-KILOGRAM SCHEMA (kg)
	2.	MASS-GRAM SCHEMA (g)
	3.	MASS-MILLIGRAM SCHEMA (mg)
	4.	MASS-MICROGRAM SCHEMA (µg)
	5.	MASS-NANOGRAM SCHEMA (ng)
	6.	MASS-PICOGRAM SCHEMA (pg)
	7.	MASS-TONNE SCHEMA (t = 1000 kg)
	8.	MASS-MEGAGRAM SCHEMA (Mg)
	9.	MASS-YOCTOGRAM → YOTTAGRAM SCHEMAS (all SI prefixes both ways)
	10.	MASS-ATOMIC-MASS-UNIT SCHEMA (u / amu)
	11.	MASS-DALTON SCHEMA (Da = u)
	12.	MASS-SI-COERCE SCHEMA (any → kg)
	13.	MASS-CANONICAL SCHEMA (normalized output)

⸻

✅ SECTION 2 — IMPERIAL / U.S. CUSTOMARY MASS SCHEMAS
	14.	MASS-OUNCE SCHEMA (oz)
	15.	MASS-POUND SCHEMA (lb)
	16.	MASS-STONE SCHEMA (st)
	17.	MASS-SHORT-TON SCHEMA (U.S.)
	18.	MASS-LONG-TON SCHEMA (U.K.)
	19.	MASS-GRAIN SCHEMA (gr)
	20.	MASS-DRAM SCHEMA (dr)
	21.	MASS-HUNDREDWEIGHT SCHEMA (cwt)
	22.	MASS-IMPERIAL-COERCE SCHEMA (any → lb)

⸻

✅ SECTION 3 — CHEMISTRY / MOLECULAR MASS SCHEMAS
	23.	MASS-MOLECULAR-WEIGHT SCHEMA (Da / g mol⁻¹)
	24.	MASS-MOLAR-MASS SCHEMA (g mol⁻¹)
	25.	MASS-RELATIVE-ATOMIC-MASS SCHEMA (Aᵣ)
	26.	MASS-MOLAR-CONCENTRATION-DERIVED SCHEMA (g/L)
	27.	MASS-ISOTOPIC-MASS SCHEMA
	28.	MASS-PROTON-MASS SCHEMA
	29.	MASS-NEUTRON-MASS SCHEMA
	30.	MASS-ELECTRON-MASS SCHEMA

⸻

✅ SECTION 4 — PHYSICS / ASTRONOMY MASS SCHEMAS
	31.	MASS-PLANETARY-MASS SCHEMA (kg)
	32.	MASS-EARTH-MASS SCHEMA (M⊕)
	33.	MASS-SOLAR-MASS SCHEMA (M☉)
	34.	MASS-JUPITER-MASS SCHEMA (Mⱼ)
	35.	MASS-CHANDRASEKHAR-LIMIT SCHEMA
	36.	MASS-GALACTIC-MASS SCHEMA
	37.	MASS-BLACK-HOLE-ESTIMATED SCHEMA
	38.	MASS-DARK-MATTER-EQUIVALENT SCHEMA
	39.	MASS-BARYONIC-MASS SCHEMA

⸻

✅ SECTION 5 — BIOLOGY / MEDICAL MASS SCHEMAS
	40.	MASS-BODY-WEIGHT-KG SCHEMA
	41.	MASS-BODY-FAT-MASS SCHEMA
	42.	MASS-LEAN-BODY-MASS SCHEMA
	43.	MASS-MUSCLE-MASS SCHEMA
	44.	MASS-ORGAN-MASS SCHEMA (liver, heart, brain etc.)
	45.	MASS-BLOOD-MASS SCHEMA
	46.	MASS-CELL-MASS SCHEMA
	47.	MASS-DNA-SAMPLE SCHEMA (ng/µL)
	48.	MASS-TISSUE-SAMPLE SCHEMA
	49.	MASS-DOSE-WEIGHT SCHEMA (mg/kg)

⸻

✅ SECTION 6 — FOOD / NUTRITION / COOKING MASS SCHEMAS
	50.	MASS-INGREDIENT-GRAM SCHEMA
	51.	MASS-PORTION-SIZE SCHEMA
	52.	MASS-SERVING-SIZE SCHEMA
	53.	MASS-NET-WEIGHT SCHEMA
	54.	MASS-GROSS-WEIGHT SCHEMA
	55.	MASS-PACKAGE-WEIGHT SCHEMA
	56.	MASS-MEASURED-ON-SCALE SCHEMA
	57.	MASS-BAKING-LOSS-SCHEMA (weight change %)
	58.	MASS-WATER-LOSS-SCHEMA
	59.	MASS-YIELD-SCHEMA (post-cook mass)

⸻

✅ SECTION 7 — MANUFACTURING / ENGINEERING / INDUSTRIAL MASS SCHEMAS
	60.	MASS-COMPONENT-SCHEMA
	61.	MASS-ASSEMBLY-SCHEMA
	62.	MASS-RAW-MATERIAL-SCHEMA
	63.	MASS-FINISHED-PART-SCHEMA
	64.	MASS-BALANCE-SCHEMA (process in/out)
	65.	MASS-TOLERANCE-SCHEMA (± g)
	66.	MASS-MEASURED-BY-LOADCELL SCHEMA
	67.	MASS-BATCH-MASS SCHEMA
	68.	MASS-TRANSPORT-PAYLOAD SCHEMA
	69.	MASS-FUEL-LOAD SCHEMA (vehicle/rocket)

⸻

✅ SECTION 8 — TRANSPORT / AEROSPACE MASS SCHEMAS
	70.	MASS-VEHICLE-CURB-WEIGHT SCHEMA
	71.	MASS-GROSS-VEHICLE-WEIGHT-RATING SCHEMA (GVWR)
	72.	MASS-PAYLOAD-CAPACITY SCHEMA
	73.	MASS-MAX-TAKEOFF-WEIGHT SCHEMA (MTOW)
	74.	MASS-DRY-MASS SCHEMA (spacecraft)
	75.	MASS-PROPELLANT-MASS SCHEMA
	76.	MASS-STAGE-SEPARATION-MASS SCHEMA
	77.	MASS-LANDING-WEIGHT SCHEMA
	78.	MASS-BALANCE-CENTER-OF-GRAVITY SCHEMA

⸻

✅ SECTION 9 — MATERIALS SCIENCE / DENSITY-RELATED SCHEMAS
	79.	MASS-PER-UNIT-AREA SCHEMA (g/m²)
	80.	MASS-PER-UNIT-LENGTH SCHEMA (g/m)
	81.	MASS-PER-UNIT-VOLUME SCHEMA (density relation)
	82.	MASS-SPECIFIC-GRAVITY-SCHEMA (ratio)
	83.	MASS-SURFACE-DENSITY SCHEMA
	84.	MASS-AREAL-DENSITY SCHEMA
	85.	MASS-BULK-MATERIAL-SCHEMA (kg/m³)
	86.	MASS-SHEET-METAL-SCHEMA (gauge → mass per m²)

⸻

✅ SECTION 10 — PRECIOUS METALS / JEWELRY MASS SCHEMAS
	87.	MASS-CARAT SCHEMA (ct = 0.2 g)
	88.	MASS-TROY-OUNCE SCHEMA (ozt = 31.1035 g)
	89.	MASS-PENNYWEIGHT SCHEMA (dwt = 1.555 g)
	90.	MASS-GRAIN-SCHEMA (duplicate for bullion)
	91.	MASS-JEWELRY-WEIGHT-SCHEMA
	92.	MASS-PRECIOUS-METAL-COERCE SCHEMA

⸻

✅ SECTION 11 — PHARMACEUTICAL / MEDICATION MASS SCHEMAS
	93.	MASS-DOSE-MG SCHEMA
	94.	MASS-DOSE-UG SCHEMA
	95.	MASS-TABLET-MASS SCHEMA
	96.	MASS-INJECTION-DOSE-SCHEMA (mg/mL × mL)
	97.	MASS-COMPOUND-MIX-SCHEMA
	98.	MASS-PRESCRIPTION-BATCH-SCHEMA
	99.	MASS-VIAL-CONTENT-SCHEMA
	100.	MASS-MEDICATION-FILL-WEIGHT-SCHEMA

⸻

✅ SECTION 12 — ENVIRONMENTAL / ATMOSPHERIC MASS SCHEMAS
	101.	MASS-AIR-COLUMN-SCHEMA (kg/m²)
	102.	MASS-POLLUTANT-CONCENTRATION-SCHEMA (µg/m³)
	103.	MASS-DUST-LOAD-SCHEMA
	104.	MASS-AEROSOL-PARTICLE-SCHEMA
	105.	MASS-WATER-VAPOR-SCHEMA
	106.	MASS-PRECIPITATION-RATE-SCHEMA (kg/m² s)
	107.	MASS-ATMOSPHERIC-CO₂-SCHEMA (ppm ↔ mass conversion)

⸻

✅ SECTION 13 — NUCLEAR / PARTICLE PHYSICS MASS SCHEMAS
	108.	MASS-REST-ENERGY-EQUIVALENT SCHEMA (E = mc²)
	109.	MASS-ELECTRON-VOLT-EQUIVALENT SCHEMA (eV/c²)
	110.	MASS-NEUTRINO-ESTIMATE-SCHEMA
	111.	MASS-QUARK-EFFECTIVE-SCHEMA
	112.	MASS-NUCLEAR-BINDING-DEFECT-SCHEMA
	113.	MASS-BARYON-MASS-SCHEMA
	114.	MASS-HADRON-MASS-SCHEMA
	115.	MASS-ATOM-NUCLIDE-SCHEMA

⸻

✅ SECTION 14 — DIGITAL / VIRTUAL / SIMULATION MASS SCHEMAS
	116.	MASS-GAME-OBJECT-MASS SCHEMA
	117.	MASS-RIGID-BODY-MASS SCHEMA
	118.	MASS-PHYSICS-ENGINE-COERCE SCHEMA (any → simulation kg)
	119.	MASS-VR-AVATAR-BODY-MASS SCHEMA
	120.	MASS-VIRTUAL-PAYLOAD-SCHEMA
	121.	MASS-SOFT-BODY-MASS-SCHEMA

⸻

✅ SECTION 15 — ECONOMIC / TRADE / LOGISTICS MASS SCHEMAS
	122.	MASS-SHIPPING-WEIGHT SCHEMA
	123.	MASS-BILLABLE-WEIGHT SCHEMA
	124.	MASS-GROSS-MASS-SCHEMA
	125.	MASS-TARE-MASS-SCHEMA
	126.	MASS-NET-MASS-SCHEMA
	127.	MASS-FREIGHT-CARGO-MASS-SCHEMA
	128.	MASS-WAREHOUSE-LOT-MASS-SCHEMA
	129.	MASS-INVENTORY-ITEM-MASS-SCHEMA
	130.	MASS-TRADE-UNIT-MASS-SCHEMA (kg/pc)

⸻

✅ SECTION 16 — STRUCTURAL / CIVIL ENGINEERING MASS SCHEMAS
	131.	MASS-STRUCTURAL-ELEMENT-SCHEMA (beam/slab)
	132.	MASS-CONCRETE-VOLUME-MASS-SCHEMA (density × m³)
	133.	MASS-STEEL-REINFORCEMENT-SCHEMA
	134.	MASS-FOUNDATION-BLOCK-SCHEMA
	135.	MASS-LIVE-LOAD-EQUIVALENT-SCHEMA
	136.	MASS-DEAD-LOAD-EQUIVALENT-SCHEMA
	137.	MASS-MOMENT-OF-INERTIA-SCHEMA (derived from mass)

⸻

✅ SECTION 17 — AGRICULTURE / COMMODITIES MASS SCHEMAS
	138.	MASS-HARVEST-YIELD-SCHEMA (kg/ha)
	139.	MASS-GRAIN-SAMPLE-SCHEMA
	140.	MASS-FERTILIZER-APPLICATION-SCHEMA (kg/ha)
	141.	MASS-ANIMAL-BODY-MASS SCHEMA
	142.	MASS-MILK-YIELD-SCHEMA
	143.	MASS-LIVESTOCK-FEED-INTAKE-SCHEMA
	144.	MASS-WOOL-CLIP-SCHEMA
	145.	MASS-CROP-DRY-MATTER-SCHEMA

⸻

✅ SECTION 18 — MISC / SPECIALTY / DERIVED SCHEMAS
	146.	MASS-SPECIFIC-MASS-FLOW SCHEMA (kg/s)
	147.	MASS-SPECIFIC-IMPULSE-SCHEMA (s × g₀ relationship)
	148.	MASS-CENTER-OF-MASS-VECTOR SCHEMA
	149.	MASS-REDUCED-MASS-SCHEMA
	150.	MASS-EQUIVALENT-WEIGHT-SCHEMA
	151.	MASS-DENSITY-DERIVED-SCHEMA (ρ × V)
	152.	MASS-COERCE-ANY-SYSTEM-SCHEMA

"mass" schemas