✅ ALL POSSIBLE “ACCOUNTING” SCHEMA NAMES

1. CORE ACCOUNTING IDENTIFIERS
	1.	ACCOUNT-ID SCHEMA
	2.	LEDGER-ID SCHEMA
	3.	JOURNAL-ID SCHEMA
	4.	ENTRY-ID SCHEMA
	5.	TRANSACTION-ID SCHEMA
	6.	INVOICE-ID SCHEMA
	7.	RECEIPT-ID SCHEMA
	8.	VENDOR-ID SCHEMA
	9.	CLIENT-ID SCHEMA
	10.	ACCOUNT-CODE SCHEMA (Chart of Accounts)

⸻

2. CHART OF ACCOUNTS CLASSIFICATIONS
	11.	ACCOUNT-TYPE SCHEMA
(“asset”, “liability”, “equity”, “revenue”, “expense”)
	12.	ACCOUNT-SUBTYPE SCHEMA
(current asset, long-term liability, COGS, operating expense, etc.)
	13.	ACCOUNT-NORMAL-BALANCE SCHEMA (“debit” | “credit”)
	14.	ACCOUNT-CATEGORY SCHEMA (GAAP/IFRS mapped categories)

⸻

3. JOURNAL / LEDGER STRUCTURES
	15.	JOURNAL-ENTRY SCHEMA
	16.	JOURNAL-ENTRY-LINE SCHEMA
	17.	JOURNAL-DATE SCHEMA
	18.	JOURNAL-SOURCE SCHEMA (manual, system, API)
	19.	LEDGER-BALANCE SCHEMA
	20.	LEDGER-POSTING SCHEMA

⸻

4. TRANSACTIONAL ACCOUNTING
	21.	TRANSACTION-AMOUNT SCHEMA
	22.	TRANSACTION-CURRENCY SCHEMA
	23.	TRANSACTION-DATE SCHEMA
	24.	TRANSACTION-DESCRIPTION SCHEMA
	25.	TRANSACTION-TYPE SCHEMA (sale, refund, payment, adjustment)
	26.	TRANSACTION-METHOD SCHEMA (ACH, wire, CC, cash)
	27.	DEBIT-AMOUNT SCHEMA
	28.	CREDIT-AMOUNT SCHEMA
	29.	DOUBLE-ENTRY SCHEMA (debits = credits validation)

⸻

5. FINANCIAL STATEMENTS

Balance Sheet
	30.	BALANCE-ASSETS SCHEMA
	31.	BALANCE-LIABILITIES SCHEMA
	32.	BALANCE-EQUITY SCHEMA
	33.	BALANCE-SHEET-INTEGRITY SCHEMA (Assets = Liabilities + Equity)

Income Statement
	34.	INCOME-REVENUE SCHEMA
	35.	INCOME-EXPENSE SCHEMA
	36.	INCOME-COGS SCHEMA
	37.	INCOME-GROSS-PROFIT SCHEMA
	38.	INCOME-NET-INCOME SCHEMA

Cash Flow
	39.	CASHFLOW-OPERATING SCHEMA
	40.	CASHFLOW-INVESTING SCHEMA
	41.	CASHFLOW-FINANCING SCHEMA

⸻

6. TAX ACCOUNTING
	42.	TAX-RATE SCHEMA
	43.	TAX-CODE SCHEMA
	44.	TAX-AMOUNT SCHEMA
	45.	TAX-JURISDICTION SCHEMA
	46.	VAT-RATE SCHEMA
	47.	GST-RATE SCHEMA
	48.	SALES-TAX-NEXUS SCHEMA
	49.	WITHHOLDING-TAX SCHEMA

⸻

7. PAYROLL ACCOUNTING
	50.	PAYROLL-GROSS SCHEMA
	51.	PAYROLL-NET SCHEMA
	52.	PAYROLL-DEDUCTIONS SCHEMA
	53.	PAYROLL-TAXES SCHEMA
	54.	PAYROLL-PERIOD SCHEMA
	55.	PAYROLL-RATE SCHEMA (hourly, salary)
	56.	PAYROLL-HOURS SCHEMA

⸻

8. INVENTORY / COGS ACCOUNTING
	57.	INVENTORY-ITEM-ID SCHEMA
	58.	INVENTORY-QUANTITY SCHEMA
	59.	INVENTORY-VALUATION-METHOD SCHEMA (FIFO, LIFO, weighted)
	60.	INVENTORY-COST SCHEMA
	61.	INVENTORY-ADJUSTMENT SCHEMA
	62.	COGS-CALCULATION SCHEMA
	63.	COGS-PERIOD SCHEMA

⸻

9. DEPRECIATION / AMORTIZATION
	64.	ASSET-LIFESPAN-YEARS SCHEMA
	65.	ASSET-SALVAGE-VALUE SCHEMA
	66.	ASSET-DEPRECIATION-METHOD SCHEMA (straight-line, declining)
	67.	ASSET-DEPRECIATION-AMOUNT SCHEMA
	68.	AMORTIZATION-SCHEDULE SCHEMA

⸻

10. REVENUE RECOGNITION
	69.	REVENUE-METHOD SCHEMA (point-in-time, over-time)
	70.	REVENUE-DEFERRED SCHEMA
	71.	REVENUE-UNBILLED SCHEMA
	72.	REVENUE-RECOGNIZED SCHEMA

⸻

11. EXPENSE CATEGORIES
	73.	EXPENSE-TYPE SCHEMA (travel, payroll, utilities…)
	74.	EXPENSE-REIMBURSEMENT SCHEMA
	75.	EXPENSE-ALLOCATION SCHEMA

⸻

12. AUDIT / COMPLIANCE
	76.	AUDIT-TRAIL-EVENT SCHEMA
	77.	AUDIT-USER-ID SCHEMA
	78.	AUDIT-TIMESTAMP SCHEMA
	79.	AUDIT-ACTION SCHEMA
	80.	AUDIT-SIGNATURE SCHEMA

⸻

13. RECONCILIATION
	81.	RECONCILIATION-STATUS SCHEMA
	82.	RECONCILIATION-DIFFERENCE SCHEMA
	83.	BANK-STATEMENT-LINE SCHEMA
	84.	BANK-MATCH-RULE SCHEMA
	85.	BANK-RECONCILIATION-PERIOD SCHEMA

⸻

14. ACCOUNTS RECEIVABLE / PAYABLE
	86.	AR-INVOICE-AMOUNT SCHEMA
	87.	AR-DUE-DATE SCHEMA
	88.	AR-STATUS SCHEMA
	89.	AP-INVOICE-AMOUNT SCHEMA
	90.	AP-DUE-DATE SCHEMA
	91.	AP-STATUS SCHEMA

⸻

15. ACCOUNTING RATIOS
	92.	RATIO-CURRENT SCHEMA
	93.	RATIO-QUICK SCHEMA
	94.	RATIO-DEBT-TO-EQUITY SCHEMA
	95.	RATIO-GROSS-MARGIN SCHEMA
	96.	RATIO-RETURN-ON-ASSETS SCHEMA
	97.	RATIO-RETURN-ON-EQUITY SCHEMA

⸻

16. MULTI-CURRENCY ACCOUNTING
	98.	FOREX-RATE SCHEMA
	99.	CURRENCY-CODE SCHEMA (ISO 4217)
	100.	CURRENCY-AMOUNT SCHEMA
	101.	FOREX-GAIN-LOSS SCHEMA

⸻

17. ERP / SYSTEM STRUCTURES
	102.	ACCOUNTING-PERIOD SCHEMA
	103.	FISCAL-YEAR SCHEMA
	104.	FISCAL-QUARTER SCHEMA
	105.	PERIOD-STATUS SCHEMA (open, closed, locked)
	106.	SETTLEMENT-BATCH-ID SCHEMA

    ✅ REMAINING ACCOUNTING SCHEMAS YOU HAVEN’T LISTED (THE TRUE FINAL SET)

    A. CONSOLIDATION & GROUP ACCOUNTING
        1.	CONSOLIDATION-METHOD SCHEMA (full, equity, proportionate)
        2.	OWNERSHIP-PERCENT SCHEMA
        3.	NON-CONTROLLING-INTEREST SCHEMA
        4.	INTERCOMPANY-TRANSACTION SCHEMA
        5.	INTERCOMPANY-ELIMINATION SCHEMA
    
    ⸻
    
    B. COST ACCOUNTING (ADVANCED)
        6.	COST-STANDARD SCHEMA
        7.	COST-ACTUAL SCHEMA
        8.	COST-VARIANCE SCHEMA
        9.	COST-OVERHEAD-RATE SCHEMA
        10.	COST-ABSORPTION SCHEMA
        11.	COST-CENTER-ID SCHEMA
        12.	PROFIT-CENTER-ID SCHEMA
    
    ⸻
    
    C. BUDGETING / FP&A
        13.	BUDGET-AMOUNT SCHEMA
        14.	BUDGET-VARIANCE SCHEMA
        15.	FORECAST-VALUE SCHEMA
        16.	FORECAST-METHOD SCHEMA
        17.	FINANCIAL-MODEL-VERSION SCHEMA
    
    ⸻
    
    D. IFRS / GAAP DISCLOSURES
        18.	DISCLOSURE-NOTE-ID SCHEMA
        19.	DISCLOSURE-TEXT SCHEMA
        20.	CONTINGENT-LIABILITY SCHEMA
        21.	SUBSEQUENT-EVENT SCHEMA
        22.	RELATED-PARTY-TRANSACTION SCHEMA
    
    ⸻
    
    E. NONPROFIT ACCOUNTING
        23.	FUND-ID SCHEMA
        24.	FUND-TYPE SCHEMA (restricted, unrestricted)
        25.	GRANT-ID SCHEMA
        26.	GRANT-AMOUNT SCHEMA
        27.	DONATION-AMOUNT SCHEMA
        28.	DONOR-ID SCHEMA
    
    ⸻
    
    F. GOVERNMENT / PUBLIC SECTOR ACCOUNTING
        29.	APPROPRIATION-ID SCHEMA
        30.	PROGRAM-ID SCHEMA
        31.	ENCUMBRANCE-AMOUNT SCHEMA
        32.	ALLOTMENT-AMOUNT SCHEMA
    
    ⸻
    
    G. TREASURY & CASH MANAGEMENT
        33.	CASH-POSITION SCHEMA
        34.	BANK-ACCOUNT-ID SCHEMA
        35.	BANK-ROUTING-NUMBER SCHEMA
        36.	LIQUIDITY-RATIO SCHEMA
        37.	CASH-SWEEP-RULE SCHEMA
    
    ⸻
    
    H. LEASE ACCOUNTING (ASC 842 / IFRS 16)
        38.	LEASE-ID SCHEMA
        39.	LEASE-TYPE SCHEMA (finance, operating)
        40.	LEASE-TERM-MONTHS SCHEMA
        41.	LEASE-DISCOUNT-RATE SCHEMA
        42.	LEASE-RIGHT-OF-USE-ASSET SCHEMA
        43.	LEASE-LIABILITY SCHEMA
    
    ⸻
    
    I. FINANCIAL INSTRUMENTS / DERIVATIVES
        44.	DERIVATIVE-TYPE SCHEMA (swap, forward, option)
        45.	FAIR-VALUE SCHEMA
        46.	HEDGE-DESIGNATION SCHEMA
        47.	HEDGE-EFFECTIVENESS SCHEMA
    
    ⸻
    
    J. INVESTMENTS / CAP TABLE
        48.	EQUITY-CLASS SCHEMA
        49.	SHARE-COUNT SCHEMA
        50.	OPTION-GRANT-ID SCHEMA
        51.	VESTING-SCHEDULE SCHEMA
        52.	VALUATION-METHOD SCHEMA (409A, DCF, comparables)
    
    ⸻
    
    K. AUDIT / FORENSIC ACCOUNTING (ADVANCED)
        53.	FORENSIC-FLAG SCHEMA
        54.	FRAUD-RISK-SCORE SCHEMA
        55.	MATERIALITY-THRESHOLD SCHEMA
        56.	SAMPLING-METHOD SCHEMA
        57.	WORKPAPER-ID SCHEMA
    
    ⸻
    
    L. BANKING / REGULATORY ACCOUNTING
        58.	CAPITAL-RATIO SCHEMA (Tier 1, CET1)
        59.	LOAN-LOSS-PROVISION SCHEMA
        60.	RISK-WEIGHT SCHEMA
        61.	AML-FLAG SCHEMA
        62.	KYC-STATUS SCHEMA
    