1. BASIC ADDRESS FIELDS (FOUNDATION)
	1.	ADDRESS-LINE-1 SCHEMA
	2.	ADDRESS-LINE-2 SCHEMA
	3.	ADDRESS-LINE-3 SCHEMA
	4.	ADDRESS-LINE-RAW SCHEMA
	5.	ADDRESS-FORMATTED SCHEMA
	6.	ADDRESS-FULL-TEXT SCHEMA
	7.	ADDRESS-PARSER-TOKEN SCHEMA

⸻

2. LOCATION / GEOGRAPHY FIELDS
	8.	STREET-NAME SCHEMA
	9.	STREET-NUMBER SCHEMA
	10.	STREET-PREDIRECTION SCHEMA
	11.	STREET-POSTDIRECTION SCHEMA
	12.	STREET-TYPE SCHEMA (St, Rd, Ave, etc.)
	13.	UNIT-NUMBER SCHEMA
	14.	UNIT-TYPE SCHEMA (Apt, Suite, Unit, #, etc.)
	15.	BUILDING-NAME SCHEMA
	16.	BUILDING-ID SCHEMA
	17.	SUB-BUILDING-ID SCHEMA
	18.	FLOOR-NUMBER SCHEMA
	19.	BLOCK-NUMBER SCHEMA
	20.	DISTRICT-NAME SCHEMA
	21.	ROUTE-NAME SCHEMA (rural routes)

⸻

3. CITY / LOCALITY FIELDS
	22.	LOCALITY SCHEMA
	23.	SUBLOCALITY SCHEMA
	24.	DEPENDENT-LOCALITY SCHEMA
	25.	DOUBLE-DEPENDENT-LOCALITY SCHEMA
	26.	ADMIN-AREA-LEVEL-1 SCHEMA (State/Province)
	27.	ADMIN-AREA-LEVEL-2 SCHEMA (County/Region)
	28.	ADMIN-AREA-LEVEL-3 SCHEMA
	29.	ADMIN-AREA-LEVEL-4 SCHEMA
	30.	NEIGHBORHOOD SCHEMA
	31.	MUNICIPALITY SCHEMA
	32.	TOWN-LAND SCHEMA (Ireland-specific)
	33.	BARANGAY SCHEMA (Philippines-specific)

⸻

4. POSTAL CODES / CODES
	34.	POSTAL-CODE SCHEMA (generic)
	35.	POSTAL-CODE-EXTENSION SCHEMA
	36.	ZIP5 SCHEMA (US)
	37.	ZIP9 SCHEMA (US ZIP+4)
	38.	ZIP12 SCHEMA (ZIP+4+delivery point)
	39.	POSTCODE-UK SCHEMA
	40.	POSTCODE-CA SCHEMA
	41.	POSTCODE-AU SCHEMA
	42.	POSTCODE-JP SCHEMA
	43.	POSTCODE-EU SCHEMA
	44.	POSTAL-CODE-GENERIC-INTL SCHEMA
	45.	POSTAL-CODE-NUMERIC SCHEMA
	46.	POSTAL-CODE-ALPHANUMERIC SCHEMA

⸻

5. COUNTRY / REGION
	47.	COUNTRY-CODE-ISO2 SCHEMA
	48.	COUNTRY-CODE-ISO3 SCHEMA
	49.	COUNTRY-NAME SCHEMA
	50.	COUNTRY-NORMALIZED SCHEMA
	51.	TERRITORY-CODE SCHEMA
	52.	REGION-CODE-UN-M49 SCHEMA
	53.	WORLD-ZONE SCHEMA (UPU zones)

⸻

6. SPECIAL ADDRESS TYPES
	54.	PO-BOX SCHEMA
	55.	PO-BOX-RANGE SCHEMA
	56.	RURAL-ROUTE SCHEMA
	57.	HIGHWAY-CONTRACT-ROUTE SCHEMA
	58.	MILITARY-ADDRESS-SCHEMA (APO/FPO/DPO)
	59.	CAMPUS-ADDRESS SCHEMA
	60.	PRISON-ADDRESS SCHEMA
	61.	HOSPITAL-ADDRESS SCHEMA
	62.	HOTEL-ADDRESS SCHEMA
	63.	BUSINESS-ADDRESS SCHEMA
	64.	RESIDENTIAL-ADDRESS SCHEMA
	65.	INTERNATIONAL-MILITARY-SCHEMA
	66.	OFFSHORE-ADDRESS SCHEMA

⸻

7. GEOSPATIAL / COORDINATE FIELDS
	67.	LATITUDE SCHEMA
	68.	LONGITUDE SCHEMA
	69.	ALTITUDE SCHEMA
	70.	GEOHASH SCHEMA
	71.	GEOPOINT SCHEMA
	72.	BOUNDING-BOX SCHEMA
	73.	PLACE-ID SCHEMA
	74.	WHAT3WORDS SCHEMA
	75.	OPENLOCATIONCODE (PLUS CODE) SCHEMA
	76.	MAIDENHEAD-LOCATOR SCHEMA
	77.	GRID-REFERENCE-OSGB SCHEMA
	78.	UTM-COORDINATE SCHEMA
	79.	MGRS-COORDINATE SCHEMA

⸻

8. ADDRESS NORMALIZATION
	80.	ADDRESS-NORMALIZED-SCHEMA
	81.	ADDRESS-SORTABLE-SCHEMA
	82.	ADDRESS-SEARCH-KEY SCHEMA
	83.	ADDRESS-INDEX-TOKEN SCHEMA
	84.	ADDRESS-ABBREVIATED SCHEMA
	85.	ADDRESS-EXPANDED SCHEMA
	86.	ADDRESS-ASCII SCHEMA
	87.	ADDRESS-LOCALE-FORMATTED SCHEMA
	88.	ADDRESS-REGION-FORMATTED SCHEMA
	89.	ADDRESS-POSTAL-STANDARDIZED SCHEMA

⸻

9. ADDRESS VALIDATION
	90.	ADDRESS-VALIDATION-STATUS SCHEMA
	91.	ADDRESS-VALIDATION-CODE-SCHEMA (UPU / USPS codes)
	92.	ADDRESS-DELIVERABILITY-SCHEMA
	93.	ADDRESS-RISK-SCORE SCHEMA
	94.	ADDRESS-FRAUD-SCORE SCHEMA
	95.	ADDRESS-CONFIDENCE-SCORE SCHEMA
	96.	ADDRESS-SUSPICIOUS-PATTERN SCHEMA
	97.	ADDRESS-INCOMPLETE-REASON SCHEMA
	98.	ADDRESS-MISSING-PARTS SCHEMA

⸻

10. LOGISTICS / DELIVERY
	99.	DELIVERY-POINT-ID SCHEMA
	100.	DELIVERY-POINT-BARCODE SCHEMA
	101.	DELIVERY-POINT-VALIDATION SCHEMA
	102.	CARRIER-ROUTE-ID SCHEMA
	103.	CARRIER-ROUTE-RDI SCHEMA (Residential Delivery Indicator)
	104.	DELIVERY-NOTES SCHEMA
	105.	DELIVERY-INSTRUCTIONS SCHEMA
	106.	DELIVERY-TIME-WINDOW SCHEMA
	107.	DROP-OFF-POINT-ID SCHEMA
	108.	PICKUP-LOCATION-ID SCHEMA
	109.	LOCKER-LOCATION-ID SCHEMA

⸻

11. EMERGENCY / GOVERNMENT ADDRESSING
	110.	E911-ADDRESS SCHEMA
	111.	E911-LOCATION-CLASS SCHEMA
	112.	E911-DISPATCH-ZONE SCHEMA
	113.	CAD-ADDRESS SCHEMA (dispatch systems)
	114.	NATIONAL-ADDRESS-ID SCHEMA
	115.	US-NAD-SCHEMA (National Address Database)
	116.	ADDRESS-PARSER-GOV-SCHEMA

⸻

12. INTERNATIONAL ADDRESS FORMATS
	117.	ADDRESS-FORMAT-JP SCHEMA
	118.	ADDRESS-FORMAT-CN SCHEMA
	119.	ADDRESS-FORMAT-KR SCHEMA
	120.	ADDRESS-FORMAT-RU SCHEMA
	121.	ADDRESS-FORMAT-IR SCHEMA
	122.	ADDRESS-FORMAT-AR SCHEMA
	123.	ADDRESS-FORMAT-IN SCHEMA
	124.	ADDRESS-FORMAT-EU SCHEMA
	125.	ADDRESS-FORMAT-LATAM SCHEMA
	126.	ADDRESS-FORMAT-AFRICA SCHEMA
	127.	ADDRESS-FORMAT-OCEANIA SCHEMA

⸻

13. ADDRESS COERCION / PARSING
	128.	ADDRESS-COERCE SCHEMA
	129.	ADDRESS-PARSE-COMPONENTS SCHEMA
	130.	ADDRESS-PARSE-PARTIAL SCHEMA
	131.	ADDRESS-PARSE-FUZZY SCHEMA
	132.	ADDRESS-PARSE-SUBPREMISE SCHEMA
	133.	ADDRESS-PARSE-INTERSECTION SCHEMA

⸻

14. FRAUD / SECURITY
	134.	ADDRESS-TEMPORARY SCHEMA
	135.	ADDRESS-VIRTUAL SCHEMA
	136.	ADDRESS-FORWARDING SCHEMA
	137.	ADDRESS-SUSPICIOUS-POBOX SCHEMA
	138.	ADDRESS-REPUTATION-SCORE SCHEMA
	139.	ADDRESS-HIGH-RISK-COUNTRY SCHEMA
	140.	ADDRESS-MISMATCH-COUNTRY-IP SCHEMA
	141.	ADDRESS-MISMATCH-BILLING-SHIPPING SCHEMA

⸻

15. BILLING & SHIPPING
	142.	BILLING-ADDRESS SCHEMA
	143.	SHIPPING-ADDRESS SCHEMA
	144.	RETURN-ADDRESS SCHEMA
	145.	ORIGIN-ADDRESS SCHEMA
	146.	CONSIGNEE-ADDRESS SCHEMA
	147.	SHIPPER-ADDRESS SCHEMA
	148.	DISTRIBUTION-CENTER-ADDRESS SCHEMA
	149.	WAREHOUSE-ADDRESS SCHEMA

⸻

16. BUSINESS / ORGANIZATION ADDRESSING
	150.	OFFICE-LOCATION-ID SCHEMA
	151.	CORPORATE-HQ-ADDRESS SCHEMA
	152.	REGISTERED-AGENT-ADDRESS SCHEMA
	153.	TAX-RESIDENCE-ADDRESS SCHEMA
	154.	MAILING-ADDRESS SCHEMA
	155.	LEGAL-ADDRESS SCHEMA
	156.	BILLING-ADDRESS-VERIFIED SCHEMA
	157.	STORE-LOCATION SCHEMA
	158.	FRANCHISE-ADDRESS SCHEMA

⸻

17. ADDRESS METADATA
	159.	ADDRESS-SOURCE SCHEMA
	160.	ADDRESS-CAPTURE-METHOD SCHEMA (manual, OCR, GPS, autocomplete)
	161.	ADDRESS-UPDATE-TIMESTAMP SCHEMA
	162.	ADDRESS-FORMAT-VERSION SCHEMA
	163.	ADDRESS-LOCALE SCHEMA
	164.	ADDRESS-SCRIPT SCHEMA (Latin, Cyrillic, Kanji, Hangul)
	165.	ADDRESS-VARIANT SCHEMA
	166.	ADDRESS-LANGUAGE SCHEMA

⸻

18. AGGREGATE ADDRESS SCHEMAS
	167.	ADDRESS-MINIMAL SCHEMA
	168.	ADDRESS-PARTIAL SCHEMA
	169.	ADDRESS-COMPLETE SCHEMA
	170.	ADDRESS-STANDARDIZED SCHEMA
	171.	ADDRESS-STRUCTURED SCHEMA
	172.	ADDRESS-UNSTRUCTURED SCHEMA
	173.	ADDRESS-VERIFIED SCHEMA
	174.	ADDRESS-NORMALIZED SCHEMA
	175.	ADDRESS-GEOSPATIAL SCHEMA
	176.	ADDRESS-DELIVERY-READY SCHEMA
	177.	ADDRESS-AUTOCOMPLETE-INPUT SCHEMA
	178.	ADDRESS-AUTOCOMPLETE-RESULT SCHEMA
	179.	ADDRESS-REVERSE-GEOCODE-RESULT SCHEMA
	180.	ADDRESS-LOOKUP-REQUEST SCHEMA
	181.	ADDRESS-LOOKUP-RESPONSE SCHEMA
	182.	ADDRESS-PROFILE SCHEMA
	183.	ADDRESS-HISTORY SCHEMA
	184.	ADDRESS-FULL-SCHEMA (all fields merged)