1. PURE MATHEMATICAL AREA UNITS

(Every unit that exists in SI, imperial, customary, survey, and hybrid standards)

Base SI / Metric
	•	AREA-SQM SCHEMA (square meters)
	•	AREA-SQCM SCHEMA
	•	AREA-SQMM SCHEMA
	•	AREA-SQKM SCHEMA
	•	AREA-HECTARE SCHEMA
	•	AREA-ARE SCHEMA

Imperial / US Customary
	•	AREA-SQIN SCHEMA
	•	AREA-SQFT SCHEMA
	•	AREA-SQYD SCHEMA
	•	AREA-ACRE SCHEMA
	•	AREA-SQMILE SCHEMA
	•	AREA-ROOD SCHEMA
	•	AREA-PERCH SCHEMA

Obscure / Historical
	•	AREA-BARN SCHEMA (nuclear physics)
	•	AREA-SOUTH-ASIAN-BIGHAA SCHEMA
	•	AREA-SOUTH-ASIAN-KATTHA SCHEMA
	•	AREA-ARAB-DUNAM SCHEMA
	•	AREA-CHINESE-MU SCHEMA

Conversions
	•	AREA-COERCE SCHEMA
	•	AREA-NORMALIZED SCHEMA
	•	AREA-UNIT-SCHEMA (unions of all)

⸻

2. GEOMETRIC SHAPE AREA SCHEMAS

(Validation + structure for shape parameters)

2D Shapes
	•	AREA-RECTANGLE SCHEMA
	•	AREA-SQUARE SCHEMA
	•	AREA-TRIANGLE SCHEMA
	•	AREA-CIRCLE SCHEMA
	•	AREA-ELLIPSE SCHEMA
	•	AREA-PARALLELOGRAM SCHEMA
	•	AREA-TRAPEZOID SCHEMA
	•	AREA-RHOMBUS SCHEMA
	•	AREA-KITE SCHEMA
	•	AREA-REGULAR-POLYGON SCHEMA
	•	AREA-IRREGULAR-POLYGON SCHEMA (vertex coordinate array)

Polygons
	•	AREA-POLYGON-COORDINATES SCHEMA
	•	AREA-POLYGON-GEOJSON SCHEMA
	•	AREA-MULTIPOLYGON SCHEMA
	•	AREA-SHOELACE-INPUT SCHEMA (coordinate pairs)

Parametric
	•	AREA-PARAMETRIC-FUNCTION SCHEMA
	•	AREA-CALCULUS-INTEGRAL SCHEMA

⸻

3. LAND, REAL ESTATE, SURVEYING

Land & Real Estate Units
	•	AREA-LOT-SIZE SCHEMA
	•	AREA-BUILDING-FOOTPRINT SCHEMA
	•	AREA-USABLE-FLOOR SCHEMA
	•	AREA-GROSS-FLOOR SCHEMA
	•	AREA-LIVABLE-SQUARE-FOOTAGE SCHEMA
	•	AREA-FARMLAND SCHEMA
	•	AREA-PARCEL-ID SCHEMA
	•	AREA-CADASTRAL-VECTOR SCHEMA

Surveying
	•	AREA-SURVEY-ACRE SCHEMA
	•	AREA-SURVEY-CHAIN SCHEMA
	•	AREA-SURVEY-LINK SCHEMA
	•	AREA-SURVEY-GUNTHA SCHEMA

Mapping
	•	AREA-GIS-RASTER SCHEMA
	•	AREA-TOPOLOGY-POLYGON SCHEMA
	•	AREA-LAT-LONG-BBOX SCHEMA
	•	AREA-UARED SCHEMA (Universal Area Reference)

⸻

4. PHYSICS / ENGINEERING AREA QUANTITIES

Physical Surface Areas
	•	AREA-CROSS-SECTIONAL SCHEMA
	•	AREA-SURFACE-SQM SCHEMA
	•	AREA-EFFECTIVE-SURFACE SCHEMA
	•	AREA-THERMAL-EXCHANGE SCHEMA (m² heat transfer)
	•	AREA-SOLAR-ABSORPTION SCHEMA
	•	AREA-FRICTIONAL-CONTACT SCHEMA
	•	AREA-AERODYNAMIC-PROFILE SCHEMA
	•	AREA-HYDRAULIC-PROFILE SCHEMA

⸻

5. COMPUTING / GRAPHICS / UI/UX

Computer Graphics
	•	AREA-PIXELS SCHEMA
	•	AREA-SCREEN-PERCENT SCHEMA
	•	AREA-VIEWPORT-VW-VH SCHEMA
	•	AREA-CANVAS-REGION SCHEMA
	•	AREA-BOUNDING-RECT SCHEMA

Web/CSS Units
	•	AREA-REM-SQUARED SCHEMA
	•	AREA-EM-SQUARED SCHEMA
	•	AREA-PERCENT-CSS SCHEMA
	•	AREA-VW-SQUARED SCHEMA
	•	AREA-VH-SQUARED SCHEMA

UI Design
	•	AREA-TOUCH-TARGET SCHEMA
	•	AREA-HITBOX SCHEMA
	•	AREA-INTERACTIVE-REGION SCHEMA

⸻

6. AGRICULTURE / ENVIRONMENTAL
	•	AREA-CROP-PLOT SCHEMA
	•	AREA-GREENHOUSE SCHEMA
	•	AREA-CANOPY-COVER SCHEMA
	•	AREA-LAKE-SURFACE SCHEMA
	•	AREA-WETLAND-SIZE SCHEMA
	•	AREA-DEFORESTATION SCHEMA
	•	AREA-PARK-LANDSCAPE SCHEMA
	•	AREA-ANIMAL-HABITAT SCHEMA

⸻

7. MANUFACTURING / PRODUCTION
	•	AREA-MATERIAL-SHEET SCHEMA
	•	AREA-METAL-PLATE SCHEMA
	•	AREA-CUTTING-PATTERN SCHEMA
	•	AREA-FOOD-SURFACE-CONTACT SCHEMA (for food-safety industry)
	•	AREA-COATING-COVERAGE SCHEMA
	•	AREA-PAINT-COVERAGE SCHEMA
	•	AREA-PRINT-BED SCHEMA (3D printing)

⸻

8. ADVANCED / SCIENTIFIC DOMAINS

Astronomy
	•	AREA-SOLAR-DISK SCHEMA
	•	AREA-PLANETARY-SURFACE SCHEMA

Biology
	•	AREA-CELL-MEMBRANE SCHEMA
	•	AREA-TISSUE-CROSS-SECTION SCHEMA
	•	AREA-LEAF-AREA-INDEX SCHEMA (LAI)

Oceanography
	•	AREA-SEA-ICE-COVERAGE SCHEMA

Meteorology
	•	AREA-STORM-FRONT SCHEMA
	•	AREA-RAINFALL-WATERSHED SCHEMA

⸻

9. STATISTICAL / ABSTRACT AREAS

Analytic / Calculus
	•	AREA-UNDER-CURVE SCHEMA
	•	AREA-BETWEEN-CURVES SCHEMA
	•	AREA-MULTIVARIATE-REGION SCHEMA

Probability / Integration
	•	AREA-PROBABILITY-MASS SCHEMA
	•	AREA-PROBABILITY-DENSITY-INTEGRAL SCHEMA

⸻

10. FULL UNIFIED AREA SYSTEMS
	•	AREA-VALUE SCHEMA
	•	AREA-WITH-UNIT SCHEMA
	•	AREA-CONVERSION-TABLE SCHEMA
	•	AREA-RANGE SCHEMA
	•	AREA-LIMIT SCHEMA
	•	AREA-BOUNDED-REGION SCHEMA
	•	AREA-DATASET SCHEMA
	•	AREA-PROFILE SCHEMA (all metadata + breakdowns)