✅ ARRAY BUFFER SCHEMAS — COMPLETE LIST

A. Core Binary Buffer Schemas
	1.	ARRAYBUFFER SCHEMA
	2.	ARRAYBUFFER-NONEMPTY SCHEMA
	3.	ARRAYBUFFER-MAXSIZE SCHEMA
	4.	ARRAYBUFFER-MINSIZE SCHEMA
	5.	ARRAYBUFFER-RANGE SCHEMA

⸻

B. TypedArray Schemas (JS built-in views)
	6.	TYPEDARRAY SCHEMA (generic)
	7.	INT8ARRAY SCHEMA
	8.	UINT8ARRAY SCHEMA
	9.	UINT8CLAMPEDARRAY SCHEMA
	10.	INT16ARRAY SCHEMA
	11.	UINT16ARRAY SCHEMA
	12.	INT32ARRAY SCHEMA
	13.	UINT32ARRAY SCHEMA
	14.	FLOAT32ARRAY SCHEMA
	15.	FLOAT64ARRAY SCHEMA
	16.	BIGINT64ARRAY SCHEMA
	17.	BIGUINT64ARRAY SCHEMA

⸻

C. TypedArray Structure / Shape
	18.	TYPEDARRAY-LENGTH SCHEMA
	19.	TYPEDARRAY-LENGTH-RANGE SCHEMA
	20.	TYPEDARRAY-BYTESIZE SCHEMA
	21.	TYPEDARRAY-BYTESIZE-RANGE SCHEMA
	22.	TYPEDARRAY-BYTEOFFSET SCHEMA

⸻

D. BufferSource schemas (union types)
	23.	BUFFERSOURCE SCHEMA (ArrayBuffer | ArrayBufferView)
	24.	ARRAYBUFFERVIEW SCHEMA (any TypedArray or DataView)

⸻

E. DataView schemas
	25.	DATAVIEW SCHEMA
	26.	DATAVIEW-BYTEOFFSET SCHEMA
	27.	DATAVIEW-BYTESIZE SCHEMA
	28.	DATAVIEW-RANGE SCHEMA
	29.	DATAVIEW-ENDIAN-SAFE SCHEMA (requires explicit endian input)

⸻

F. ArrayBuffer coercion schemas
	30.	ARRAYBUFFER-FROM-BASE64 SCHEMA
	31.	ARRAYBUFFER-FROM-HEX SCHEMA
	32.	ARRAYBUFFER-FROM-UTF8 SCHEMA
	33.	ARRAYBUFFER-FROM-STRING SCHEMA (auto detect encoding)
	34.	ARRAYBUFFER-FROM-OBJECT SCHEMA (structured clone)

⸻

G. TypedArray coercion schemas
	35.	TYPEDARRAY-FROM-ARRAY SCHEMA
	36.	TYPEDARRAY-FROM-BUFFER SCHEMA
	37.	TYPEDARRAY-FROM-BASE64 SCHEMA
	38.	TYPEDARRAY-FROM-HEX SCHEMA
	39.	TYPEDARRAY-FROM-UTF8 SCHEMA

⸻

H. Serialization / Encoding schemas
	40.	ARRAYBUFFER-BASE64 SCHEMA
	41.	ARRAYBUFFER-HEX SCHEMA
	42.	ARRAYBUFFER-BINARYSTRING SCHEMA
	43.	ARRAYBUFFER-UTF8STRING SCHEMA
	44.	ARRAYBUFFER-JSONSTRING SCHEMA (must be valid UTF-8 JSON)

⸻

I. Memory & Safety Schemas
	45.	ARRAYBUFFER-IMMUTABLE SCHEMA (freezing typed arrays)
	46.	ARRAYBUFFER-DEEP-FREEZE SCHEMA
	47.	ARRAYBUFFER-DETACHED SCHEMA (browser-only detection)
	48.	ARRAYBUFFER-NOT-DETACHED SCHEMA

⸻

J. Structural / Type-Guard Schemas
	49.	IS-ARRAYBUFFER SCHEMA
	50.	IS-TYPEDARRAY SCHEMA
	51.	IS-BUFFERSOURCE SCHEMA
	52.	IS-DATAVIEW SCHEMA

⸻

K. Platform-specialized
	53.	NODE-BUFFER SCHEMA (Buffer → ArrayBuffer validation)
	54.	NODE-BUFFER-COERCE SCHEMA
	55.	WASM-MEMORY-BUFFER SCHEMA (ArrayBuffer from WebAssembly.Memory)
	56.	WEB-CRYPTO-KEYDATA SCHEMA (ArrayBuffer restrictions)

⸻

L. ArrayBuffer view specialization
	57.	UNION-TYPEDARRAY SCHEMA
	58.	FLOAT-TYPEDARRAY SCHEMA
	59.	INTEGER-TYPEDARRAY SCHEMA
	60.	BIGINT-TYPEDARRAY SCHEMA
