/*
1. Ingredient Schemas
	•	INGREDIENT-NAME SCHEMA
	•	INGREDIENT-QUANTITY SCHEMA
	•	INGREDIENT-UNIT SCHEMA
	•	INGREDIENT-FORM SCHEMA (chopped, minced, crushed, diced…)
	•	INGREDIENT-PROCESSING SCHEMA (smoked, cured, fermented)
	•	INGREDIENT-STATE SCHEMA (fresh, frozen, dried)
	•	INGREDIENT-QUALITY-GRADE SCHEMA (prime, choice, A, AA…)
	•	INGREDIENT-ORIGIN SCHEMA (country/region)
	•	INGREDIENT-BRAND SCHEMA
	•	INGREDIENT-ALLERGEN-FLAGS SCHEMA
	•	INGREDIENT-SUBSTITUTIONS SCHEMA
	•	INGREDIENT-SEASONALITY SCHEMA
	•	INGREDIENT-PAIRING-PROFILE SCHEMA
	•	INGREDIENT-SHELF-LIFE SCHEMA
	•	INGREDIENT-STORAGE-CONDITION SCHEMA

⸻

2. Measurement & Units
	•	UNIT-VOLUME SCHEMA (tsp, tbsp, cup…)
	•	UNIT-WEIGHT SCHEMA (g, kg, oz, lb)
	•	UNIT-LENGTH SCHEMA (inch, cm—for cuts)
	•	UNIT-TEMPERATURE-C SCHEMA
	•	UNIT-TEMPERATURE-F SCHEMA
	•	UNIT-TIME SCHEMA (sec, min, hr)
	•	UNIT-RELATIVE SCHEMA (pinch, dash, handful)
	•	UNIT-RATIO SCHEMA (1:1, 60% hydration)
	•	UNIT-COUNT SCHEMA (eggs, cloves)

⸻

3. Temperature Schemas
	•	COOK-TEMP-OVEN-C SCHEMA
	•	COOK-TEMP-OVEN-F SCHEMA
	•	COOK-TEMP-GRILL SCHEMA
	•	COOK-TEMP-SOUS-VIDE SCHEMA
	•	COOK-TEMP-TARGET-MEAT SCHEMA (doneness)
	•	STORAGE-TEMP-SAFE SCHEMA
	•	SERVING-TEMP SCHEMA
	•	CARAMELIZATION-TEMP SCHEMA
	•	FERMENTATION-TEMP SCHEMA
	•	BAKING-TEMP SCHEMA

⸻

4. Time & Timing Schemas
	•	COOK-TIME-TOTAL SCHEMA
	•	COOK-TIME-ACTIVE SCHEMA
	•	REST-TIME SCHEMA
	•	MARINADE-TIME SCHEMA
	•	FERMENTATION-TIME SCHEMA
	•	RISE-TIME SCHEMA
	•	PROOF-TIME SCHEMA
	•	BAKE-TIME SCHEMA
	•	SIMMER-TIME SCHEMA
	•	REDUCTION-TIME SCHEMA

⸻

5. Cooking Method Schemas
	•	COOK-METHOD SCHEMA (boil, braise, fry…)
	•	HEAT-LEVEL SCHEMA (low, medium, high)
	•	HEAT-TYPE SCHEMA (dry, moist, radiant)
	•	COOK-TECHNIQUE SCHEMA (sear, deglaze, blanch…)
	•	COOK-STYLE SCHEMA (rustic, fine-dining, home-style)
	•	COOKING-MOTION SCHEMA (fold, whisk, fold-in, aerate)
	•	MIXING-METHOD SCHEMA
	•	KNEADING-METHOD SCHEMA
	•	CUTTING-TECHNIQUE SCHEMA (julienne, brunoise, chiffonade)

⸻

6. Food Safety Schemas
	•	SAFE-COOK-TEMP SCHEMA
	•	SAFE-STORAGE-TIME SCHEMA
	•	CROSS-CONTAMINATION-LEVEL SCHEMA
	•	PATHOGEN-RISK SCHEMA
	•	RAW-MEAT-HANDLING SCHEMA
	•	EXPIRY-DATE SCHEMA
	•	USE-BY-DATE SCHEMA
	•	FOOD-SPOILAGE-INDICATOR SCHEMA

⸻

7. Nutrition Schemas
	•	NUTRITION-CALORIES SCHEMA
	•	NUTRITION-PROTEIN SCHEMA
	•	NUTRITION-FAT SCHEMA
	•	NUTRITION-SATURATED-FAT SCHEMA
	•	NUTRITION-CARBS SCHEMA
	•	NUTRITION-FIBER SCHEMA
	•	NUTRITION-SUGAR SCHEMA
	•	NUTRITION-SODIUM SCHEMA
	•	NUTRITION-VITAMINS SCHEMA
	•	NUTRITION-MINERALS SCHEMA
	•	NUTRITION-GLYCEMIC-INDEX SCHEMA
	•	NUTRITION-ALLERGEN-INFO SCHEMA

⸻

8. Recipe Structure Schemas
	•	RECIPE-NAME SCHEMA
	•	RECIPE-AUTHOR SCHEMA
	•	RECIPE-YIELD SCHEMA
	•	RECIPE-SERVINGS SCHEMA
	•	RECIPE-CATEGORY SCHEMA
	•	RECIPE-CUISINE SCHEMA
	•	RECIPE-DIET-TYPE SCHEMA (vegan, paleo, low-FODMAP)
	•	RECIPE-DIFFICULTY SCHEMA
	•	RECIPE-TIME SCHEMA
	•	RECIPE-STEPS SCHEMA
	•	RECIPE-INSTRUCTIONS SCHEMA
	•	RECIPE-NOTES SCHEMA
	•	RECIPE-TAGS SCHEMA
	•	RECIPE-IMAGE-URL SCHEMA
	•	RECIPE-VIDEO-URL SCHEMA
	•	RECIPE-RATING SCHEMA
	•	RECIPE-META SCHEMA

⸻

9. Pantry / Inventory Schemas
	•	PANTRY-ITEM SCHEMA
	•	PANTRY-QUANTITY SCHEMA
	•	PANTRY-LOCATION SCHEMA (fridge, freezer, dry)
	•	PANTRY-EXPIRY SCHEMA
	•	PANTRY-REORDER-LEVEL SCHEMA
	•	PANTRY-CATEGORY SCHEMA (spice, oil, protein, dairy)

⸻

10. Shopping & Grocery Schemas
	•	GROCERY-ITEM SCHEMA
	•	GROCERY-QUANTITY SCHEMA
	•	GROCERY-LIST SCHEMA
	•	GROCERY-STORE SCHEMA
	•	GROCERY-BRAND SCHEMA
	•	GROCERY-CATEGORY SCHEMA
	•	GROCERY-SUBSTITUTION SCHEMA

⸻

11. Flavor / Sensory Science Schemas
	•	FLAVOR-PROFILE SCHEMA (sweet, umami…)
	•	FLAVOR-STRENGTH SCHEMA
	•	TEXTURE-PROFILE SCHEMA
	•	AROMA-PROFILE SCHEMA
	•	TASTE-BALANCE SCHEMA
	•	SPICE-LEVEL SCHEMA
	•	MOUTHFEEL SCHEMA
	•	PAIRING-COMPATIBILITY SCHEMA

⸻

12. Cuisine Classification Schemas
	•	CUISINE-REGION SCHEMA
	•	CUISINE-SUBREGION SCHEMA
	•	CUISINE-TECHNIQUE SCHEMA
	•	CUISINE-SPICE-PATTERN SCHEMA
	•	CUISINE-FLAVOR-ARCHETYPE SCHEMA

⸻

13. Equipment & Tools Schemas
	•	EQUIPMENT-NAME SCHEMA
	•	EQUIPMENT-SIZE SCHEMA
	•	EQUIPMENT-MATERIAL SCHEMA
	•	EQUIPMENT-CAPACITY SCHEMA
	•	EQUIPMENT-TEMPERATURE-RATING SCHEMA
	•	EQUIPMENT-POWER-SCHEMA
	•	KNIFE-TYPE SCHEMA
	•	BAKEWARE-SIZE SCHEMA

⸻

14. Dough / Baking Science Schemas
	•	DOUGH-HYDRATION-PERCENT SCHEMA
	•	DOUGH-STIFFNESS SCHEMA
	•	DOUGH-GLUTEN-DEVELOPMENT SCHEMA
	•	FERMENTATION-STAGE SCHEMA
	•	STARTER-FEED-RATIO SCHEMA
	•	BAKE-CRUST-COLOR SCHEMA
	•	CRUMB-STRUCTURE SCHEMA
	•	BAKING-PAN-SIZE SCHEMA

⸻

15. Fermentation Schemas
	•	FERMENTATION-TEMP SCHEMA
	•	FERMENTATION-TIME SCHEMA
	•	FERMENTATION-PH SCHEMA
	•	FERMENTATION-CO2-LEVEL SCHEMA
	•	FERMENTATION-STATE SCHEMA

⸻

16. Beverage / Cocktail Schemas
	•	COCKTAIL-INGREDIENT SCHEMA
	•	COCKTAIL-METHOD SCHEMA
	•	COCKTAIL-GLASS SCHEMA
	•	COCKTAIL-ICE-TYPE SCHEMA
	•	COCKTAIL-GARNISH SCHEMA
	•	COCKTAIL-ABV SCHEMA
	•	COCKTAIL-DILUTION-PERCENT SCHEMA
	•	COFFEE-GRIND-SIZE SCHEMA
	•	BREWING-METHOD SCHEMA
	•	TEA-STEEP-TIME SCHEMA
	•	TEA-WATER-TEMP SCHEMA

⸻

17. Serving / Plating Schemas
	•	PLATING-STYLE SCHEMA
	•	PORTION-SIZE SCHEMA
	•	GARNISH-TYPE SCHEMA
	•	SERVING-VESSEL SCHEMA
	•	SERVING-TEMP SCHEMA

⸻

18. Menu / Chef Workflow Schemas
	•	MENU-SECTION SCHEMA
	•	MENU-ITEM SCHEMA
	•	MENU-PRICE SCHEMA
	•	MENU-COST SCHEMA
	•	PREP-TIME SCHEMA
	•	PREP-STATION SCHEMA
	•	PREP-LIST SCHEMA
	•	PREP-BATCH SCHEMA
	•	SERVICE-WINDOW SCHEMA
	•	KITCHEN-WORKFLOW-STEP SCHEMA

⸻

19. Meal Planning Schemas
	•	MEAL-TYPE SCHEMA
	•	MEAL-CALENDAR-DATE SCHEMA
	•	MEAL-PLAN SCHEMA
	•	WEEKLY-MEAL-SCHEDULE SCHEMA
	•	MACRO-TARGET SCHEMA
	•	CALORIE-TARGET SCHEMA

⸻

20. Shopping Automation / Recipe App Schemas
	•	RECIPE-ID SCHEMA
	•	INGREDIENT-ID SCHEMA
	•	SHOPPING-CATEGORY SCHEMA
	•	AUTO-SUBSTITUTION-RULE SCHEMA
	•	PRICE-PER-UNIT SCHEMA
	•	COST-PER-SERVING SCHEMA

⸻

21. Food Science Schemas (Advanced)
	•	MAILLARD-REACTION-INTENSITY SCHEMA
	•	MELTING-POINT SCHEMA
	•	SMOKE-POINT SCHEMA
	•	WATER-ACTIVITY SCHEMA
	•	STARCH-GELATINIZATION-TEMP SCHEMA
	•	PROTEIN-DENATURATION-TEMP SCHEMA

    1. Food Supply Chain / Traceability Schemas
	•	FOOD-LOT-NUMBER SCHEMA
	•	FOOD-BATCH-ID SCHEMA
	•	FOOD-TRACEBACK-ID SCHEMA
	•	FARM-ORIGIN SCHEMA
	•	GROWER-ID SCHEMA
	•	HARVEST-DATE SCHEMA
	•	HARVEST-METHOD SCHEMA
	•	FOOD-IRRADIATION-STATUS SCHEMA
	•	FOOD-CERTIFICATION-TYPE SCHEMA (Organic, FairTrade, Kosher, Halal)

⸻

2. Sustainability / Environmental Impact Schemas
	•	CARBON-FOOTPRINT SCHEMA
	•	WATER-USAGE SCHEMA
	•	PACKAGING-MATERIAL SCHEMA
	•	PACKAGING-RECYCLABILITY SCHEMA
	•	FOOD-WASTE-LEVEL SCHEMA
	•	SUSTAINABILITY-SCORE SCHEMA

⸻

3. Smart Appliance / IoT Cooking Schemas
	•	IOT-DEVICE-ID SCHEMA
	•	APPLIANCE-MODE SCHEMA (steam, convection, broil…)
	•	APPLIANCE-POWER-LEVEL SCHEMA
	•	APPLIANCE-TARGET-TEMP SCHEMA
	•	SENSOR-READING-TEMP SCHEMA
	•	SENSOR-READING-HUMIDITY SCHEMA
	•	SENSOR-READING-WEIGHT SCHEMA
	•	COOKING-PROGRAM-ID SCHEMA

⸻

4. Food Physics / Chemical Reaction Schemas
	•	EMULSIFICATION-STABILITY SCHEMA
	•	GELATION-POINT SCHEMA
	•	VISCOSITY-SCORE SCHEMA
	•	FOAM-STABILITY SCHEMA
	•	THERMAL-DIFFUSIVITY SCHEMA
	•	HEAT-TRANSFER-RATE SCHEMA
	•	BROWNING-INDEX SCHEMA
	•	CRISPINESS-INDEX SCHEMA

⸻

5. Advanced Sensory Evaluation / Food Tasting Schemas
	•	SENSORY-PANEL-ID SCHEMA
	•	SENSORY-AROMA-SCORE SCHEMA
	•	SENSORY-TEXTURE-SCORE SCHEMA
	•	SENSORY-AFTERTASTE-SCORE SCHEMA
	•	SENSORY-UMAMI-SCORE SCHEMA
	•	SENSORY-PROFILE-VECTOR SCHEMA
	•	SENSORY-DEVIATION SCHEMA (consistency between testers)

*/