A. Core Currency Identity Schemas
	1.	CURRENCY-CODE-ISO4217 SCHEMA
	2.	CURRENCY-NUMERIC-CODE SCHEMA
	3.	CURRENCY-NAME SCHEMA
	4.	CURRENCY-SYMBOL SCHEMA
	5.	CURRENCY-ALPHA3 SCHEMA
	6.	CURRENCY-ALPHA3-STRICT SCHEMA
	7.	CURRENCY-ALPHA2 (legacy/rare but used in banking) SCHEMA
	8.	CURRENCY-IS-ACTIVE SCHEMA
	9.	CURRENCY-IS-LEGACY SCHEMA
	10.	CURRENCY-IS-FIAT SCHEMA
	11.	CURRENCY-IS-CRYPTO SCHEMA
	12.	CURRENCY-REGION SCHEMA (maps currency to countries)

⸻

B. Currency Formatting & Locale Schemas
	13.	CURRENCY-LOCALE-SYMBOL SCHEMA
	14.	CURRENCY-LOCALE-GROUPING SCHEMA
	15.	CURRENCY-LOCALE-DECIMAL SCHEMA
	16.	CURRENCY-LOCALE-FORMAT SCHEMA
	17.	CURRENCY-LOCALE-PATTERN SCHEMA
	18.	CURRENCY-DISPLAY-NARROW-SYMBOL SCHEMA
	19.	CURRENCY-DISPLAY-CODE SCHEMA
	20.	CURRENCY-DISPLAY-NAME-LONG SCHEMA
	21.	CURRENCY-DISPLAY-NAME-SHORT SCHEMA

⸻

C. Currency Precision & Rounding Schemas
	22.	CURRENCY-DECIMAL-DIGITS SCHEMA
	23.	CURRENCY-CENTS-SCALE SCHEMA
	24.	CURRENCY-MINOR-UNIT SCHEMA
	25.	CURRENCY-MAJOR-UNIT SCHEMA
	26.	CURRENCY-ROUNDING-MODE SCHEMA (banker’s, floor, ceil, half-up, etc.)
	27.	CURRENCY-ROUNDING-STEP SCHEMA
	28.	CURRENCY-QUANTITY-PRECISION SCHEMA
	29.	CURRENCY-WHOLE-ONLY SCHEMA (JPY, KRW, etc.)

⸻

D. Monetary Value Schemas
	30.	MONEY-AMOUNT SCHEMA
	31.	MONEY-AMOUNT-POSITIVE SCHEMA
	32.	MONEY-AMOUNT-NEGATIVE SCHEMA
	33.	MONEY-AMOUNT-NONNEGATIVE SCHEMA
	34.	MONEY-AMOUNT-DECIMAL SCHEMA
	35.	MONEY-AMOUNT-INTEGER SCHEMA
	36.	MONEY-AMOUNT-COERCE SCHEMA
	37.	MONEY-AMOUNT-FORMATTED SCHEMA
	38.	MONEY-RANGE SCHEMA
	39.	MONEY-RANGE-STRICT SCHEMA

⸻

E. Multi-Currency Money Object Schemas
	40.	MONEY-OBJECT SCHEMA (amount + currency)
	41.	MONEY-OBJECT-STRICT SCHEMA
	42.	MONEY-OBJECT-COERCE SCHEMA
	43.	MONEY-OBJECT-LOCALE SCHEMA
	44.	MONEY-OBJECT-NORMALIZED SCHEMA
	45.	MONEY-LIST SCHEMA
	46.	MONEY-MAP SCHEMA
	47.	MONEY-FIELD SCHEMA

⸻

F. FX (Foreign Exchange) Schemas
	48.	FX-RATE SCHEMA
	49.	FX-RATE-PAIR SCHEMA (“USD/CAD”)
	50.	FX-RATE-BID SCHEMA
	51.	FX-RATE-ASK SCHEMA
	52.	FX-RATE-MID SCHEMA
	53.	FX-RATE-SOURCE SCHEMA (ECB, XE, Oanda, bank feed)
	54.	FX-RATE-TIMESTAMP SCHEMA
	55.	FX-RATE-HISTORICAL SCHEMA
	56.	FX-CONVERSION SCHEMA
	57.	FX-CONVERSION-STRICT SCHEMA
	58.	FX-CONVERSION-TABLE SCHEMA
	59.	FX-VOLATILITY-SCORE SCHEMA

⸻

G. Payment & Gateway Schemas
	60.	PAYMENT-AMOUNT SCHEMA
	61.	PAYMENT-CURRENCY SCHEMA
	62.	PAYMENT-EXCHANGE-RATE SCHEMA
	63.	PAYMENT-TOTAL SCHEMA
	64.	PAYMENT-FEE SCHEMA
	65.	PAYMENT-PROCESSOR-CURRENCY SCHEMA
	66.	PAYMENT-DISPLAY-CURRENCY SCHEMA
	67.	PAYMENT-SETTLEMENT-CURRENCY SCHEMA
	68.	PAYMENT-LOCAL-CURRENCY SCHEMA
	69.	PAYMENT-CONVERSION-COST SCHEMA

⸻

H. E-Commerce Price Schemas
	70.	PRICE-LIST SCHEMA
	71.	PRICE-ORIGINAL SCHEMA
	72.	PRICE-SALE SCHEMA
	73.	PRICE-DISCOUNT SCHEMA
	74.	PRICE-DISCOUNT-PERCENT SCHEMA
	75.	PRICE-EFFECTIVE SCHEMA
	76.	PRICE-FINAL SCHEMA
	77.	PRICE-CURRENCY SCHEMA
	78.	PRICE-PER-UNIT SCHEMA
	79.	PRICE-PER-QUANTITY SCHEMA
	80.	PRICE-TAX-INCLUDED SCHEMA
	81.	PRICE-TAX-EXCLUDED SCHEMA
	82.	PRICE-TAX-RATE SCHEMA

⸻

I. Tax Schemas (currency-dependent)
	83.	TAX-RATE SCHEMA
	84.	TAX-AMOUNT SCHEMA
	85.	TAX-CURRENCY SCHEMA
	86.	TAX-JURISDICTION SCHEMA
	87.	TAX-TABLE SCHEMA
	88.	TAX-CALCULATION SCHEMA
	89.	TAX-CALCULATION-DETAIL SCHEMA
	90.	TAX-INCLUSIVE SCHEMA
	91.	TAX-EXCLUSIVE SCHEMA

⸻

J. Ledger / Accounting Schemas
	92.	LEDGER-AMOUNT SCHEMA
	93.	LEDGER-ENTRY SCHEMA
	94.	LEDGER-CURRENCY SCHEMA
	95.	LEDGER-BALANCE SCHEMA
	96.	LEDGER-DEBIT SCHEMA
	97.	LEDGER-CREDIT SCHEMA
	98.	LEDGER-POSTING SCHEMA
	99.	LEDGER-MULTI-CURRENCY-ENTRY SCHEMA
	100.	LEDGER-MULTI-CURRENCY-BALANCE SCHEMA
	101.	LEDGER-EXCHANGE-GAIN SCHEMA
	102.	LEDGER-EXCHANGE-LOSS SCHEMA

⸻

K. Banking Schemas
	103.	BANK-CURRENCY SCHEMA
	104.	BANK-TRANSFER-AMOUNT SCHEMA
	105.	BANK-TRANSFER-CURRENCY SCHEMA
	106.	BANK-SETTLEMENT-CURRENCY SCHEMA
	107.	BANK-STATEMENT-CURRENCY SCHEMA
	108.	BANK-INTEREST-CURRENCY SCHEMA
	109.	BANK-FEE-CURRENCY SCHEMA
	110.	BANK-FX-MARKUP SCHEMA

⸻

L. Cryptocurrency Schemas
	111.	CRYPTO-CURRENCY-CODE SCHEMA (BTC/ETH/etc.)
	112.	CRYPTO-NETWORK SCHEMA
	113.	CRYPTO-CONTRACT-ADDRESS SCHEMA
	114.	CRYPTO-DECIMALS SCHEMA
	115.	CRYPTO-AMOUNT SCHEMA
	116.	CRYPTO-AMOUNT-COERCE SCHEMA
	117.	CRYPTO-AMOUNT-NORMALIZED SCHEMA
	118.	CRYPTO-TOKEN-ID SCHEMA
	119.	CRYPTO-PRICE SCHEMA
	120.	CRYPTO-MARKET-CAP SCHEMA
	121.	CRYPTO-EXCHANGE-RATE SCHEMA
	122.	CRYPTO-FIAT-PAIR SCHEMA

⸻

M. Validation & Parsing Schemas
	123.	CURRENCY-PARSE SCHEMA
	124.	CURRENCY-DETECT SCHEMA (extract from messy strings)
	125.	CURRENCY-FUZZY-MATCH SCHEMA
	126.	CURRENCY-STRICT-MATCH SCHEMA
	127.	CURRENCY-FORMAT-PARSE SCHEMA
	128.	CURRENCY-AMOUNT-PARSE SCHEMA
	129.	CURRENCY-AMOUNT-SAFE SCHEMA
	130.	CURRENCY-AMOUNT-PRECISE SCHEMA

⸻

N. Coercion Schemas
	131.	CURRENCY-COERCE SCHEMA
	132.	CURRENCY-CODE-COERCE SCHEMA
	133.	MONEY-COERCE-FROM-STRING SCHEMA
	134.	MONEY-COERCE-FROM-NUMBER SCHEMA
	135.	MONEY-COERCE-FROM-OBJECT SCHEMA
	136.	FX-RATE-COERCE SCHEMA

⸻

O. Security / Compliance Schemas
	137.	CURRENCY-KYC-ALLOWED SCHEMA
	138.	CURRENCY-SANCTIONS-CHECK SCHEMA
	139.	CURRENCY-SUPPORTED-REGION SCHEMA
	140.	CURRENCY-COMPLIANCE-FLAG SCHEMA
	141.	CURRENCY-RISK-SCORE SCHEMA

⸻

P. Unified Currency & Money Schemas
	142.	CURRENCY-ANY SCHEMA
	143.	MONEY-ANY SCHEMA
	144.	MONEY-FULL SCHEMA
	145.	FX-FULL SCHEMA
	146.	PRICING-FULL SCHEMA
	147.	ACCOUNTING-FULL SCHEMA
	148.	CRYPTO-FULL SCHEMA