✅ SECTION 1 — CORE DATA URI STRUCTURE
	1.	DATA-URI SCHEMA (generic data:[mime];base64,...)
	2.	DATA-URI-STRICT SCHEMA (RFC 2397 compliance)
	3.	DATA-URI-NULLABLE SCHEMA
	4.	DATA-URI-OPTIONAL SCHEMA
	5.	DATA-URI-REQUIRED SCHEMA
	6.	DATA-URI-NONEMPTY SCHEMA
	7.	DATA-URI-IMMUTABLE SCHEMA
	8.	DATA-URI-NORMALIZED SCHEMA (lower-case scheme, trimmed whitespace)
	9.	DATA-URI-COERCE SCHEMA (any → data URI string)
	10.	DATA-URI-FROM-STRING SCHEMA (parse raw input)

⸻

✅ SECTION 2 — COMPONENT PARTS SCHEMAS
	11.	DATA-URI-MIME-TYPE SCHEMA
	12.	DATA-URI-MEDIA-TYPE SCHEMA
	13.	DATA-URI-ENCODING-TYPE SCHEMA (base64, utf8, percent)
	14.	DATA-URI-PAYLOAD-STRING SCHEMA
	15.	DATA-URI-PAYLOAD-BINARY SCHEMA
	16.	DATA-URI-CHARSET SCHEMA
	17.	DATA-URI-FILENAME SCHEMA (name= parameter)
	18.	DATA-URI-BOUNDARY-SCHEMA (for multipart)

⸻

✅ SECTION 3 — DECODE / ENCODE TRANSFORMATIONS
	19.	DATA-URI-DECODE SCHEMA (data URI → Uint8Array)
	20.	DATA-URI-ENCODE SCHEMA (bytes → data URI)
	21.	DATA-URI-FROM-ARRAYBUFFER SCHEMA
	22.	DATA-URI-FROM-TYPEDARRAY SCHEMA
	23.	DATA-URI-FROM-BLOB SCHEMA
	24.	DATA-URI-FROM-FILE SCHEMA
	25.	DATA-URI-TO-BLOB SCHEMA
	26.	DATA-URI-TO-FILE SCHEMA
	27.	DATA-URI-TO-ARRAYBUFFER SCHEMA
	28.	DATA-URI-TO-STRING SCHEMA (UTF-8 decode)
	29.	DATA-URI-TO-BASE64 SCHEMA (extract payload)
	30.	DATA-URI-FROM-BASE64 SCHEMA (build URI from base64 string)

⸻

✅ SECTION 4 — VALIDATION / SANITIZATION
	31.	DATA-URI-VALIDATE SCHEMA (syntax + header check)
	32.	DATA-URI-VALIDATE-MIME SCHEMA (whitelist MIME types)
	33.	DATA-URI-VALIDATE-SAFE-IMAGE SCHEMA (allow png/jpeg/gif/svg+xml only)
	34.	DATA-URI-VALIDATE-SVG-SECURE SCHEMA (no script tags)
	35.	DATA-URI-VALIDATE-LENGTH SCHEMA (max size limit)
	36.	DATA-URI-VALIDATE-CHARSET SCHEMA
	37.	DATA-URI-VALIDATE-BASE64 SCHEMA
	38.	DATA-URI-VALIDATE-HEX SCHEMA
	39.	DATA-URI-VALIDATE-UTF8 SCHEMA
	40.	DATA-URI-SAFE-FOR-HTML SCHEMA (XSS-clean)

⸻

✅ SECTION 5 — TYPE-SPECIFIC SCHEMAS
	41.	DATA-URI-IMAGE-SCHEMA
	42.	DATA-URI-IMAGE-PNG-SCHEMA
	43.	DATA-URI-IMAGE-JPEG-SCHEMA
	44.	DATA-URI-IMAGE-GIF-SCHEMA
	45.	DATA-URI-IMAGE-WEBP-SCHEMA
	46.	DATA-URI-IMAGE-SVG-SCHEMA
	47.	DATA-URI-AUDIO-SCHEMA
	48.	DATA-URI-AUDIO-MP3-SCHEMA
	49.	DATA-URI-AUDIO-OGG-SCHEMA
	50.	DATA-URI-AUDIO-WAV-SCHEMA
	51.	DATA-URI-VIDEO-SCHEMA
	52.	DATA-URI-VIDEO-MP4-SCHEMA
	53.	DATA-URI-VIDEO-WEBM-SCHEMA
	54.	DATA-URI-TEXT-SCHEMA
	55.	DATA-URI-TEXT-HTML-SCHEMA
	56.	DATA-URI-TEXT-CSS-SCHEMA
	57.	DATA-URI-TEXT-CSV-SCHEMA
	58.	DATA-URI-TEXT-PLAIN-SCHEMA
	59.	DATA-URI-FONT-SCHEMA (WOFF/TTF/OTF)
	60.	DATA-URI-JSON-SCHEMA
	61.	DATA-URI-XML-SCHEMA
	62.	DATA-URI-PDF-SCHEMA
	63.	DATA-URI-ZIP-SCHEMA

⸻

✅ SECTION 6 — SECURITY / POLICY / CONTENT-SECURITY
	64.	DATA-URI-CSP-SAFE-SCHEMA (enforce CSP data: policy)
	65.	DATA-URI-XSS-SAFE-SCHEMA
	66.	DATA-URI-SANITIZE-SCHEMA (remove unapproved MIME)
	67.	DATA-URI-ESCAPE-SCHEMA (encode non-safe chars)
	68.	DATA-URI-WHITELIST-SCHEMA
	69.	DATA-URI-BLACKLIST-SCHEMA

⸻

✅ SECTION 7 — COERCION / UTILITIES
	70.	DATA-URI-FROM-URL SCHEMA (fetch → data URI)
	71.	DATA-URI-FROM-CANVAS SCHEMA (canvas.toDataURL)
	72.	DATA-URI-FROM-IMAGE-ELEMENT SCHEMA
	73.	DATA-URI-FROM-AUDIO-BUFFER SCHEMA
	74.	DATA-URI-FROM-VIDEO-FRAME SCHEMA
	75.	DATA-URI-FROM-OBJECT-URL SCHEMA
	76.	DATA-URI-TO-OBJECT-URL SCHEMA
	77.	DATA-URI-CROSS-CONVERT SCHEMA (MIME → alternate MIME)

⸻

✅ SECTION 8 — VALIDATION FOR STORAGE / TRANSPORT
	78.	DATA-URI-MAX-LENGTH-SCHEMA (limit for localStorage/JSON)
	79.	DATA-URI-INLINE-SAFE-SCHEMA (for HTML/CSS embed)
	80.	DATA-URI-TRANSPORT-SAFE-SCHEMA (for HTTP headers)
	81.	DATA-URI-WEBCRYPTO-COMPAT-SCHEMA (ArrayBuffer conversion)
	82.	DATA-URI-FETCH-COMPAT-SCHEMA (Request/Response body)
	83.	DATA-URI-SERVICEWORKER-CACHE-SCHEMA

⸻

✅ SECTION 9 — METADATA / INSPECTION
	84.	DATA-URI-PARSE-METADATA-SCHEMA (mime, encoding, size)
	85.	DATA-URI-INSPECT-SCHEMA (structured fields)
	86.	DATA-URI-SUMMARY-SCHEMA (hash, length, type)
	87.	DATA-URI-HASH-SCHEMA (SHA-256 of payload)
	88.	DATA-URI-FINGERPRINT-SCHEMA (identical dedup key)
	89.	DATA-URI-SIGNATURE-SCHEMA (for signed blobs)

⸻

✅ SECTION 10 — ADVANCED / DERIVED / SPECIALIZED
	90.	DATA-URI-RANGE-SCHEMA (partial data slice)
	91.	DATA-URI-MULTIPART-SCHEMA (multipart/mixed encoding)
	92.	DATA-URI-CHUNKED-SCHEMA (large splits w/ sequence ID)
	93.	DATA-URI-STREAM-SCHEMA (live base64 streaming)
	94.	DATA-URI-INLINE-ASSET-SCHEMA (embedded fonts/images)
	95.	DATA-URI-CACHE-KEY-SCHEMA (hash-based caching)
	96.	DATA-URI-INTEGRITY-SCHEMA (SRI hash check)
	97.	DATA-URI-ACCESSIBILITY-SCHEMA (has alt text)
	98.	DATA-URI-PERFORMANCE-SCHEMA (measure load impact)
	99.	DATA-URI-METRIC-SCHEMA (size, decode time)
	100.	DATA-URI-ANY SCHEMA (canonical union for validation)
    1.	DATA-URI-FROM-QR-CODE SCHEMA — for embedded QR payloads decoded into data URIs (rare but used in mobile/web hybrid apps).
	2.	DATA-URI-FROM-CLIPBOARD SCHEMA — for paste-event data URIs (e.g., images copied into a WYSIWYG editor).
