📅 SECTION 1 — ABSOLUTE DATE SCHEMAS
	1.	DATE-ISO8601 SCHEMA
	2.	DATE-YYYY-MM-DD SCHEMA
	3.	DATE-MM-DD-YYYY SCHEMA
	4.	DATE-DD-MM-YYYY SCHEMA
	5.	DATE-RFC3339 SCHEMA
	6.	DATE-RFC2822 SCHEMA
	7.	DATE-EPOCH-MILLISECONDS SCHEMA
	8.	DATE-EPOCH-SECONDS SCHEMA
	9.	DATE-UNIX-TIMESTAMP SCHEMA
	10.	DATE-UTC-STRING SCHEMA
	11.	DATE-UTC-ZONED SCHEMA
	12.	DATE-ONLY SCHEMA (no time)
	13.	DATE-TIME COMBINED SCHEMA
	14.	DATE-EXTENDED SCHEMA (with subsecond precision)
	15.	DATE-COMPACT SCHEMA (YYYYMMDD)
	16.	DATE-ORDINAL SCHEMA (YYYY-DDD)
	17.	DATE-WEEKDATE SCHEMA (YYYY-Www-D)
	18.	DATE-RAW-STRING SCHEMA (non-strict input, normalized)
	19.	DATE-COERCIBLE SCHEMA (accepts string or number)
	20.	DATE-MICROSECOND SCHEMA
	21.	DATE-NANOSECOND SCHEMA
	22.	DATE-MAX SAFE JS SCHEMA
	23.	DATE-MIN SAFE JS SCHEMA
	24.	DATE-DEFAULT NOW SCHEMA
	25.	DATE-DEFAULT NULLABLE SCHEMA

⸻

🗓️ SECTION 2 — LOCALIZED & HUMANIZED DATE SCHEMAS
	26.	DATE-LOCALE-EN SCHEMA
	27.	DATE-LOCALE-FR SCHEMA
	28.	DATE-LOCALE-DE SCHEMA
	29.	DATE-LOCALE-ES SCHEMA
	30.	DATE-LOCALE-ZH-CN SCHEMA
	31.	DATE-LOCALE-JA-JP SCHEMA
	32.	DATE-LOCALE-KO-KR SCHEMA
	33.	DATE-LOCALE-HI-IN SCHEMA
	34.	DATE-LOCALE-AR SCHEMA
	35.	DATE-LOCALE-RU SCHEMA
	36.	DATE-HUMAN-FRIENDLY SCHEMA (e.g., “Jan 1, 2025”)
	37.	DATE-WITH-AMPM SCHEMA
	38.	DATE-HOUR12 SCHEMA
	39.	DATE-HOUR24 SCHEMA
	40.	DATE-VERBOSE-LONGFORM SCHEMA (e.g., “Monday, January 1, 2025”)
	41.	DATE-CULTURE-SENSITIVE SCHEMA
	42.	DATE-WITH-SUFFIXES SCHEMA (e.g., “1st Jan”)
	43.	DATE-VERBAL SCHEMA (e.g., “next Tuesday”)
	44.	DATE-RELATIVE INPUT SCHEMA (e.g., “2 weeks ago”)
	45.	DATE-FUZZY NATURAL SCHEMA

⸻

🌐 SECTION 3 — TIMEZONE & OFFSET SCHEMAS
	46.	DATE-WITH-TZOFFSET SCHEMA
	47.	DATE-WITH-ZONED-ID SCHEMA (e.g., “America/Vancouver”)
	48.	DATE-WITHOUT-TZ SCHEMA
	49.	DATE-UTC-Z SCHEMA
	50.	DATE-GMT-Z SCHEMA
	51.	DATE-OFFSET-MINUTES SCHEMA
	52.	DATE-OFFSET-SECONDS SCHEMA
	53.	DATE-FIXED-TIMEZONE SCHEMA
	54.	DATE-ZONED-COERCIBLE SCHEMA
	55.	DATE-INVALID-TZ-REJECTING SCHEMA
	56.	DATE-ZONED-STRICT SCHEMA
	57.	DATE-TZ-ABBREVIATION SCHEMA (e.g., PST, EDT)

⸻

📈 SECTION 4 — BUSINESS / FINANCE DATE SCHEMAS
	58.	DATE-FISCAL-YEAR SCHEMA
	59.	DATE-FISCAL-QUARTER SCHEMA
	60.	DATE-QUARTER-OF-YEAR SCHEMA
	61.	DATE-PAYROLL-CYCLE SCHEMA
	62.	DATE-INVOICE-DUE SCHEMA
	63.	DATE-NET30 SCHEMA
	64.	DATE-TAX-YEAR SCHEMA
	65.	DATE-YEAR-END SCHEMA
	66.	DATE-STOCK-MARKET-CALENDAR SCHEMA
	67.	DATE-CUTOFF-SCHEDULE SCHEMA
	68.	DATE-RECURRING-BILLING SCHEMA
	69.	DATE-CAPITAL-GAINS SCHEMA
	70.	DATE-BUDGET-CYCLE SCHEMA
	71.	DATE-PRO-RATA-CUTOFF SCHEMA

⸻

🔁 SECTION 5 — DATE INTERVALS & RANGE SCHEMAS
	72.	DATE-RANGE SCHEMA (start, end)
	73.	DATE-RANGE-COERCIBLE SCHEMA
	74.	DATE-RANGE-INCLUSIVE SCHEMA
	75.	DATE-RANGE-EXCLUSIVE SCHEMA
	76.	DATE-WINDOW SCHEMA (e.g., past 30d)
	77.	DATE-ROLLING-WINDOW SCHEMA
	78.	DATE-PRECISE-INTERVAL SCHEMA
	79.	DATE-RECURRING-INTERVAL SCHEMA
	80.	DATE-INTERVAL-STRING SCHEMA (e.g., “2025-01-01/2025-01-31”)
	81.	DATE-VALID-SPAN SCHEMA
	82.	DATE-PERIOD SCHEMA (day, week, month)
	83.	DATE-LAGGING-RANGE SCHEMA
	84.	DATE-LOOKBACK-WINDOW SCHEMA
	85.	DATE-NEXT-WINDOW SCHEMA
	86.	DATE-ABSOLUTE-GAP SCHEMA
	87.	DATE-OVERLAP-CHECK SCHEMA
	88.	DATE-WITHIN-RANGE SCHEMA (validator only)

⸻

🛂 SECTION 6 — COMPLIANCE / AUDIT DATE SCHEMAS
	89.	DATE-GDPR-ERASURE SCHEMA
	90.	DATE-EXPIRATION SCHEMA
	91.	DATE-RETENTION-PERIOD SCHEMA
	92.	DATE-AUDIT-LOG SCHEMA
	93.	DATE-ISO27001-TIMESTAMP SCHEMA
	94.	DATE-ISO8601-STRICT SCHEMA
	95.	DATE-BANKING-AUDIT SCHEMA
	96.	DATE-FINRA-COMPLIANCE SCHEMA
	97.	DATE-SOC2-RETENTION SCHEMA
	98.	DATE-PROCESSING-WINDOW SCHEMA
	99.	DATE-DESTRUCTION-DEADLINE SCHEMA
	100.	DATE-MAX-LIFESPAN SCHEMA
	101.	DATE-MIN-STORAGE-DURATION SCHEMA

⸻

🧠 SECTION 7 — COERCION / GUARD / AUTO-FIX SCHEMAS
	102.	DATE-COERCE-STRING SCHEMA
	103.	DATE-COERCE-NUMBER SCHEMA
	104.	DATE-COERCE-OBJECT SCHEMA
	105.	DATE-DEFAULT-IF-INVALID SCHEMA
	106.	DATE-STRIP-TZ SCHEMA
	107.	DATE-NORMALIZE-TO-MIDNIGHT SCHEMA
	108.	DATE-AUTO-PARSE-FLEX SCHEMA
	109.	DATE-CORRECT-TO-START-OF-DAY SCHEMA
	110.	DATE-CORRECT-TO-END-OF-DAY SCHEMA
	111.	DATE-INVALID-NULLABLE SCHEMA
	112.	DATE-AUTO-ROUND SCHEMA
	113.	DATE-PARSE-WITH-FORMAT SCHEMA
	114.	DATE-SAFE-COERCE SCHEMA (fail on invalid)

⸻

🧪 SECTION 8 — TESTING / DEBUG / BOUNDARY DATE SCHEMAS
	115.	DATE-MAXIMUM-POSSIBLE SCHEMA
	116.	DATE-MINIMUM-POSSIBLE SCHEMA
	117.	DATE-JAN-1-1970 SCHEMA
	118.	DATE-2000-EPOCH SCHEMA
	119.	DATE-LEAP-YEAR SCHEMA
	120.	DATE-END-OF-MONTH SCHEMA
	121.	DATE-END-OF-YEAR SCHEMA
	122.	DATE-29-FEB SCHEMA
	123.	DATE-31ST-DAY SCHEMA
	124.	DATE-SAME-DAY-LAST-YEAR SCHEMA
	125.	DATE-NOW-MOCKABLE SCHEMA
	126.	DATE-RANDOMIZED-WINDOW SCHEMA

⸻

🧘 SECTION 9 — UX / UI / UX-DEV-FRIENDLY SCHEMAS
	127.	DATE-FOR-INPUT-ELEMENT SCHEMA (YYYY-MM-DD)
	128.	DATE-FOR-DATEPICKER SCHEMA
	129.	DATE-LOCALIZED-LABEL SCHEMA
	130.	DATE-SHORT-DISPLAY SCHEMA
	131.	DATE-LONG-DISPLAY SCHEMA
	132.	DATE-CALENDAR-VIEW SCHEMA
	133.	DATE-FORMATTED-STRING SCHEMA
	134.	DATE-ISO-FOR-BROWSER SCHEMA
	135.	DATE-RELATIVE-LABEL SCHEMA (e.g., “Today”, “Tomorrow”)
	136.	DATE-TIMELINE-POSITION SCHEMA
	137.	DATE-CHART-GROUPING SCHEMA
	138.	DATE-PAGINATION-KEY SCHEMA
	139.	DATE-SORTING-NORMALIZED SCHEMA
	140.	DATE-EDITABLE-INPUT SCHEMA
	141.	DATE-STEP-INCREMENT SCHEMA

⸻

🔭 SECTION 10 — ASTRONOMY / HISTORIC / SPECIALIZED DATE SCHEMAS
	142.	DATE-JULIAN SCHEMA
	143.	DATE-JD SCHEMA (Julian Day Number)
	144.	DATE-GREGORIAN-ONLY SCHEMA
	145.	DATE-ISO-WEEK SCHEMA
	146.	DATE-ASTRO-EPOCH SCHEMA
	147.	DATE-LUNAR-CALENDAR SCHEMA
	148.	DATE-HEBREW-CALENDAR SCHEMA
	149.	DATE-CHINESE-CALENDAR SCHEMA
	150.	DATE-ISLAMIC-CALENDAR SCHEMA
	151.	DATE-INDIAN-CALENDAR SCHEMA
	152.	DATE-BUDDHIST-CALENDAR SCHEMA
	153.	DATE-MAYAN-CALENDAR SCHEMA
	154.	DATE-HISTORICAL-PERIOD SCHEMA
	155.	DATE-ASTRONOMICAL-EVENT SCHEMA
	156.	DATE-EQUINOX-SCHEMA
	157.	DATE-SOLAR-NOON SCHEMA