✅ SECTION 1 — CORE PHYSICAL DENSITY SCHEMAS (UNIVERSAL)
	1.	DENSITY-KG-PER-M3 SCHEMA
	2.	DENSITY-G-PER-CM3 SCHEMA
	3.	DENSITY-G-PER-ML SCHEMA
	4.	DENSITY-KG-PER-L SCHEMA
	5.	DENSITY-LB-PER-FT3 SCHEMA
	6.	DENSITY-LB-PER-GAL SCHEMA
	7.	DENSITY-SI-COERCE SCHEMA
	8.	DENSITY-CANONICAL SCHEMA (kg/m³ output)

⸻

✅ SECTION 2 — MATERIALS / ENGINEERING DENSITY
	9.	MATERIAL-DENSITY SCHEMA (generic)
	10.	METAL-DENSITY SCHEMA
	11.	WOOD-DENSITY SCHEMA
	12.	PLASTIC-DENSITY SCHEMA
	13.	CONSTRUCTION-MATERIAL-DENSITY SCHEMA
	14.	SOIL-BULK-DENSITY SCHEMA
	15.	SOIL-PARTICLE-DENSITY SCHEMA
	16.	CONCRETE-WET-DENSITY SCHEMA
	17.	CONCRETE-DRY-DENSITY SCHEMA
	18.	GRAVEL-DENSITY SCHEMA
	19.	SAND-DENSITY SCHEMA

⸻

✅ SECTION 3 — CHEMISTRY DENSITY SCHEMAS
	20.	MOLAR-DENSITY SCHEMA (mol/L)
	21.	NUMBER-DENSITY SCHEMA (particles/m³)
	22.	ELECTRON-DENSITY SCHEMA
	23.	CHARGE-DENSITY SCHEMA (C/m³)
	24.	NUCLEAR-DENSITY SCHEMA

⸻

✅ SECTION 4 — FLUID DENSITY SCHEMAS
	25.	FLUID-DENSITY SCHEMA
	26.	WATER-DENSITY SCHEMA
	27.	OIL-DENSITY SCHEMA
	28.	FUEL-DENSITY SCHEMA
	29.	AEROSOL-PARTICLE-DENSITY SCHEMA
	30.	AIR-DENSITY SCHEMA
	31.	GAS-DENSITY SCHEMA
	32.	VAPOR-DENSITY SCHEMA

⸻

✅ SECTION 5 — ASTRONOMY / COSMOLOGY DENSITY SCHEMAS
	33.	COSMIC-MASS-DENSITY SCHEMA
	34.	GALACTIC-DENSITY SCHEMA
	35.	STELLAR-DENSITY SCHEMA
	36.	NEUTRON-STAR-DENSITY SCHEMA
	37.	BLACK-HOLE-AVERAGE-DENSITY SCHEMA
	38.	DARK-MATTER-DENSITY SCHEMA
	39.	BARYONIC-MATTER-DENSITY SCHEMA

⸻

✅ SECTION 6 — WEATHER / EARTH SCIENCE DENSITY SCHEMAS
	40.	ATMOSPHERIC-DENSITY SCHEMA
	41.	AIR-DENSITY-ALTITUDE SCHEMA
	42.	WATER-VAPOR-DENSITY SCHEMA
	43.	CLOUD-DROPLET-DENSITY SCHEMA
	44.	POLLEN-DENSITY SCHEMA
	45.	PARTICULATE-MATTER-DENSITY SCHEMA (PM2.5/PM10)
	46.	SMOKE-DENSITY SCHEMA

⸻

✅ SECTION 7 — MEDICAL / BIOLOGY DENSITY SCHEMAS
	47.	BONE-MINERAL-DENSITY SCHEMA (BMD)
	48.	BLOOD-CELL-DENSITY SCHEMA
	49.	PATHOGEN-DENSITY SCHEMA
	50.	BACTERIAL-COLONY-DENSITY SCHEMA (CFU/mL)
	51.	CELLS-PER-MM3 SCHEMA
	52.	PLASMA-PROTEIN-DENSITY SCHEMA

⸻

✅ SECTION 8 — FOOD / NUTRITION / COOKING DENSITY SCHEMAS
	53.	CALORIC-DENSITY SCHEMA (kcal/g)
	54.	MICRONUTRIENT-DENSITY SCHEMA
	55.	MACRONUTRIENT-DENSITY SCHEMA
	56.	FOOD-DENSITY SCHEMA (ingredient weight/volume)
	57.	INGREDIENT-PACKING-DENSITY SCHEMA (e.g., flour sifted vs packed)
	58.	LIQUID-DENSITY-COOKING SCHEMA (e.g., stock, syrup)
	59.	SWEETNESS-DENSITY SCHEMA (Brix)
	60.	DOUGH-DENSITY SCHEMA
	61.	BATTER-DENSITY SCHEMA

⸻

✅ SECTION 9 — PRODUCT / UX / GRAPHICS DENSITY SCHEMAS
	62.	PIXEL-DENSITY-DPI SCHEMA
	63.	PIXEL-DENSITY-PPI SCHEMA
	64.	SUBPIXEL-DENSITY SCHEMA
	65.	DISPLAY-DENSITY-BUCKET SCHEMA (ldpi/mdpi/hdpi/xhdpi/xxhdpi)
	66.	PRINT-DENSITY-DPI SCHEMA
	67.	DOT-DENSITY SCHEMA

⸻

✅ SECTION 10 — COMPUTING / DATA / STORAGE DENSITY
	68.	STORAGE-DENSITY SCHEMA (GB/mm² for NAND)
	69.	TRACK-DENSITY SCHEMA (HDD)
	70.	BIT-DENSITY SCHEMA (bits/cm²)
	71.	MEMORY-CELL-DENSITY SCHEMA
	72.	SERVER-RACK-DENSITY SCHEMA (kW per rack)
	73.	DATA-DENSITY SCHEMA (bytes per cm³)

⸻

✅ SECTION 11 — MISC / SPECIALIZED DENSITY
	74.	POPULATION-DENSITY SCHEMA (people/km²)
	75.	TRAFFIC-DENSITY SCHEMA (vehicles/km)
	76.	LIGHT-DENSITY SCHEMA (photons per m²/s)
	77.	ENERGY-DENSITY SCHEMA (J/m³ or Wh/kg)
	78.	POWER-DENSITY SCHEMA (W/m²)
	79.	MAGNETIC-FLUX-DENSITY SCHEMA (Tesla)
	80.	CHARGE-DENSITY-SURFACE SCHEMA (C/m²)
	81.	CURRENT-DENSITY SCHEMA (A/m²)
	1.	OPTICAL-POWER-DENSITY-SCHEMA — (W/cm²) for laser or LED safety calculations.
	2.	RADIATION-DOSE-DENSITY-SCHEMA — (Gy/cm³ or Sv/kg) for dosimetry contexts.
	3.	CURRENT-LINEAR-DENSITY-SCHEMA — (A/m) for conductors.
	4.	LINEAR-MASS-DENSITY-SCHEMA — (kg/m) for ropes, cables, fibers.
	5.	AREAL-MASS-DENSITY-SCHEMA — (kg/m²) for coatings, fabrics, solar panels.
