✅ SECTION 1 — CORE EMAIL ADDRESS SCHEMAS (SYNTAX + STRUCTURE)
	1.	EMAIL-ADDRESS SCHEMA (RFC 5321/5322 compliant)
	2.	EMAIL-ADDRESS-STRICT SCHEMA (rejects comments/obsolete forms)
	3.	EMAIL-ADDRESS-LENIENT SCHEMA (browser-style tolerance)
	4.	EMAIL-ADDRESS-ASCII-ONLY SCHEMA
	5.	EMAIL-ADDRESS-IDN SCHEMA (internationalized, punycode)
	6.	EMAIL-ADDRESS-LOCAL-PART SCHEMA
	7.	EMAIL-ADDRESS-DOMAIN-PART SCHEMA
	8.	EMAIL-ADDRESS-QUOTED-LOCAL SCHEMA
	9.	EMAIL-ADDRESS-ALIAS SCHEMA (“user+tag@example.com”)
	10.	EMAIL-ADDRESS-VALID-TLD SCHEMA (cross-checks IANA list)
	11.	EMAIL-ADDRESS-DISPOSABLE-FILTER SCHEMA
	12.	EMAIL-ADDRESS-TEMPORARY-FILTER SCHEMA
	13.	EMAIL-ADDRESS-MX-CHECK SCHEMA (DNS MX validation)
	14.	EMAIL-ADDRESS-SMTP-PING SCHEMA (RCPT TO verification)
	15.	EMAIL-ADDRESS-BLACKLIST-CHECK SCHEMA
	16.	EMAIL-ADDRESS-WHITELIST-CHECK SCHEMA
	17.	EMAIL-ADDRESS-RESERVED-DOMAIN SCHEMA (no “example.com”, “test.com”)
	18.	EMAIL-ADDRESS-LOCALHOST-BLOCK SCHEMA
	19.	EMAIL-ADDRESS-COERCE SCHEMA (normalize case, trim, IDN)
	20.	EMAIL-ADDRESS-NORMALIZED SCHEMA (canonical lowercase, punycode)

⸻

✅ SECTION 2 — USER / IDENTITY LAYER SCHEMAS
21. EMAIL-USERNAME-SCHEMA (pre-@ only)
22. EMAIL-DISPLAY-NAME-SCHEMA (“John Doe john@example.com￼”)
23. EMAIL-CONTACT-SCHEMA (display + address object)
24. EMAIL-USER-HANDLE-SCHEMA (aliases, vanity domains)
25. EMAIL-USER-INITIALS-SCHEMA
26. EMAIL-SIGNATURE-BLOCK-SCHEMA
27. EMAIL-AVATAR-HASH-SCHEMA (Gravatar MD5)
28. EMAIL-IDENTITY-MAP-SCHEMA (multiple aliases → one user)

⸻

✅ SECTION 3 — MESSAGE / HEADER SCHEMAS
29. EMAIL-MESSAGE-ID-SCHEMA
30. EMAIL-IN-REPLY-TO-SCHEMA
31. EMAIL-REFERENCES-SCHEMA
32. EMAIL-SUBJECT-SCHEMA
33. EMAIL-DATE-HEADER-SCHEMA
34. EMAIL-FROM-SCHEMA
35. EMAIL-TO-SCHEMA
36. EMAIL-CC-SCHEMA
37. EMAIL-BCC-SCHEMA
38. EMAIL-REPLY-TO-SCHEMA
39. EMAIL-RETURN-PATH-SCHEMA
40. EMAIL-HEADERS-MAP-SCHEMA (name/value map)
41. EMAIL-CONTENT-TYPE-SCHEMA (MIME)
42. EMAIL-BOUNDARY-SCHEMA
43. EMAIL-ENCODING-SCHEMA (base64, QP, 8bit)
44. EMAIL-PRIORITY-SCHEMA
45. EMAIL-THREAD-ID-SCHEMA (Gmail/Outlook threading)

⸻

✅ SECTION 4 — CONTENT / BODY SCHEMAS
46. EMAIL-BODY-TEXT-SCHEMA
47. EMAIL-BODY-HTML-SCHEMA
48. EMAIL-BODY-MULTIPART-SCHEMA
49. EMAIL-ATTACHMENT-SCHEMA
50. EMAIL-ATTACHMENT-METADATA-SCHEMA (filename, MIME, size)
51. EMAIL-INLINE-IMAGE-CID-SCHEMA
52. EMAIL-FOOTER-SCHEMA
53. EMAIL-TEMPLATE-SCHEMA (transactional layout)
54. EMAIL-PLACEHOLDER-SCHEMA (variables for templating)

⸻

✅ SECTION 5 — TRANSPORT / DELIVERY SCHEMAS
55. EMAIL-SMTP-ENVELOPE-SCHEMA
56. EMAIL-ENVELOPE-FROM-SCHEMA
57. EMAIL-ENVELOPE-TO-SCHEMA
58. EMAIL-QUEUE-MESSAGE-SCHEMA
59. EMAIL-DELIVERY-STATUS-SCHEMA (DSN)
60. EMAIL-BOUNCE-REASON-SCHEMA
61. EMAIL-BOUNCE-CODE-SCHEMA
62. EMAIL-DEFERRED-STATUS-SCHEMA
63. EMAIL-DELIVERABILITY-SCORE-SCHEMA
64. EMAIL-SPAM-SCORE-SCHEMA
65. EMAIL-SPAM-FLAG-SCHEMA
66. EMAIL-DELIVERED-TIMESTAMP-SCHEMA
67. EMAIL-OPEN-TRACK-SCHEMA
68. EMAIL-CLICK-TRACK-SCHEMA
69. EMAIL-UNSUBSCRIBE-LINK-SCHEMA

⸻

✅ SECTION 6 — SECURITY / AUTHENTICATION SCHEMAS
70. EMAIL-SPF-RECORD-SCHEMA
71. EMAIL-SPF-RESULT-SCHEMA
72. EMAIL-DKIM-SIGNATURE-SCHEMA
73. EMAIL-DKIM-VERIFIED-SCHEMA
74. EMAIL-DMARC-POLICY-SCHEMA
75. EMAIL-DMARC-RESULT-SCHEMA
76. EMAIL-ARC-CHAIN-SCHEMA (Authenticated Received Chain)
77. EMAIL-TLS-STATUS-SCHEMA
78. EMAIL-ENCRYPTION-STATUS-SCHEMA (PGP/SMIME)
79. EMAIL-HASH-INTEGRITY-SCHEMA (checksum validation)
80. EMAIL-PHISH-RISK-SCORE-SCHEMA
81. EMAIL-SENDER-REPUTATION-SCHEMA
82. EMAIL-BLACKLIST-ENTRY-SCHEMA

⸻

✅ SECTION 7 — DOMAIN / DNS RECORD SCHEMAS
83. EMAIL-MX-RECORD-SCHEMA
84. EMAIL-A-RECORD-SCHEMA
85. EMAIL-TXT-RECORD-SCHEMA
86. EMAIL-DMARC-RECORD-SCHEMA
87. EMAIL-DKIM-PUBLIC-KEY-SCHEMA
88. EMAIL-DNS-LOOKUP-SCHEMA
89. EMAIL-DNS-TTL-SCHEMA

⸻

✅ SECTION 8 — UX / APP / PRODUCTIVITY LAYER
90. EMAIL-LABEL-SCHEMA (folder/tags)
91. EMAIL-THREAD-GROUP-SCHEMA
92. EMAIL-READ-STATE-SCHEMA
93. EMAIL-IMPORTANCE-SCHEMA
94. EMAIL-PINNED-STATE-SCHEMA
95. EMAIL-ARCHIVED-STATE-SCHEMA
96. EMAIL-SNOOZE-STATE-SCHEMA
97. EMAIL-REMINDER-SCHEMA
98. EMAIL-SCHEDULED-SEND-SCHEMA
99. EMAIL-DRAFT-STATE-SCHEMA
100. EMAIL-COMPOSE-METADATA-SCHEMA

⸻

✅ SECTION 9 — COMPLIANCE / LEGAL / POLICY SCHEMAS
101. EMAIL-RETENTION-POLICY-SCHEMA
102. EMAIL-AUDIT-LOG-SCHEMA
103. EMAIL-ACCESS-PERMISSION-SCHEMA
104. EMAIL-DATA-CLASSIFICATION-SCHEMA
105. EMAIL-LEGAL-HOLD-SCHEMA
106. EMAIL-E-DISCOVERY-SCHEMA
107. EMAIL-REDACTION-SCHEMA
108. EMAIL-PII-MASK-SCHEMA

⸻

✅ SECTION 10 — ANALYTICS / PERFORMANCE SCHEMAS
109. EMAIL-SENT-COUNT-SCHEMA
110. EMAIL-OPEN-RATE-SCHEMA
111. EMAIL-CLICK-RATE-SCHEMA
112. EMAIL-DELIVERY-TIME-SCHEMA
113. EMAIL-RESPONSE-TIME-SCHEMA
114. EMAIL-A/B-VARIANT-SCHEMA
115. EMAIL-TEMPLATE-PERFORMANCE-SCHEMA
116. EMAIL-DEVICE-OPEN-DISTRIBUTION-SCHEMA

⸻

✅ SECTION 11 — INFRASTRUCTURE / SERVER SCHEMAS
117. EMAIL-SERVER-HOST-SCHEMA
118. EMAIL-SERVER-PORT-SCHEMA
119. EMAIL-SERVER-PROTOCOL-SCHEMA (IMAP, POP3, SMTP, EAS)
120. EMAIL-SERVER-AUTH-MODE-SCHEMA
121. EMAIL-SERVER-TLS-CERT-SCHEMA
122. EMAIL-SERVER-CAPABILITY-SCHEMA
123. EMAIL-SERVER-QUEUE-SIZE-SCHEMA
124. EMAIL-SERVER-RATE-LIMIT-SCHEMA

⸻

✅ SECTION 12 — INTEGRATION / AUTOMATION SCHEMAS
125. EMAIL-WEBHOOK-SCHEMA
126. EMAIL-FORWARD-RULE-SCHEMA
127. EMAIL-FILTER-RULE-SCHEMA
128. EMAIL-TRIGGER-SCHEMA (on send/open/reply)
129. EMAIL-NOTIFICATION-SCHEMA
130. EMAIL-WORKFLOW-STEP-SCHEMA
131. EMAIL-CRM-CONTACT-LINK-SCHEMA
132. EMAIL-TICKET-LINK-SCHEMA

⸻

✅ SECTION 13 — AI / CLASSIFICATION SCHEMAS
133. EMAIL-INTENT-SCHEMA (support/sales/personal)
134. EMAIL-SENTIMENT-SCHEMA
135. EMAIL-TOPIC-CLASSIFICATION-SCHEMA
136. EMAIL-AUTO-REPLY-SUGGESTION-SCHEMA
137. EMAIL-PRIORITY-PREDICTION-SCHEMA
138. EMAIL-SPAM-ML-SCORE-SCHEMA
139. EMAIL-ENTITY-EXTRACTION-SCHEMA

⸻

✅ SECTION 14 — COMPOSITE / STRUCTURED OBJECT SCHEMAS
140. EMAIL-CONTACT-OBJECT-SCHEMA
141. EMAIL-MESSAGE-OBJECT-SCHEMA
142. EMAIL-THREAD-OBJECT-SCHEMA
143. EMAIL-ACCOUNT-OBJECT-SCHEMA
144. EMAIL-DOMAIN-OBJECT-SCHEMA
145. EMAIL-SERVER-OBJECT-SCHEMA
146. EMAIL-DELIVERY-REPORT-OBJECT-SCHEMA
147. EMAIL-SECURITY-REPORT-OBJECT-SCHEMA

⸻

✅ SECTION 15 — TEST / MOCK / VALIDATION SCHEMAS
148. EMAIL-TEST-ADDRESS-SCHEMA (“example@”)
149. EMAIL-MOCK-MESSAGE-SCHEMA
150. EMAIL-FAKE-SMTP-EVENT-SCHEMA
151. EMAIL-SANDBOX-DOMAIN-SCHEMA
152. EMAIL-TEST-HARNESS-SCHEMA

⸻

✅ SECTION 16 — VISUAL / UX COMPONENT SCHEMAS
153. EMAIL-CARD-SCHEMA (UI preview)
154. EMAIL-SNIPPET-SCHEMA (excerpt/preview text)
155. EMAIL-AVATAR-SCHEMA
156. EMAIL-BADGE-SCHEMA (unread count)
157. EMAIL-COLOR-LABEL-SCHEMA
158. EMAIL-ICON-SCHEMA (provider logos)

⸻

✅ SECTION 17 — PROVIDER-SPECIFIC SCHEMAS
159. EMAIL-GMAIL-THREAD-SCHEMA
160. EMAIL-OUTLOOK-MESSAGE-SCHEMA
161. EMAIL-ICLOUD-MESSAGE-SCHEMA
162. EMAIL-YAHOO-HEADER-SCHEMA
163. EMAIL-EXCHANGE-EWS-SCHEMA
164. EMAIL-BREVO-SMTP-EVENT-SCHEMA
165. EMAIL-MAILGUN-WEBHOOK-SCHEMA
166. EMAIL-SENDGRID-EVENT-SCHEMA
167. EMAIL-AMAZON-SES-NOTIFICATION-SCHEMA

⸻

✅ SECTION 18 — HISTORICAL / ARCHIVAL SCHEMAS
168. EMAIL-ARCHIVE-ENTRY-SCHEMA
169. EMAIL-ARCHIVE-INDEX-SCHEMA
170. EMAIL-ARCHIVE-METADATA-SCHEMA
171. EMAIL-ARCHIVE-CHECKSUM-SCHEMA
172. EMAIL-ARCHIVE-TIMESTAMP-SCHEMA

⸻

✅ SECTION 19 — POLICY / CONSENT / PRIVACY SCHEMAS
173. EMAIL-CONSENT-STATUS-SCHEMA
174. EMAIL-UNSUBSCRIBE-STATUS-SCHEMA
175. EMAIL-OPT-IN-TIMESTAMP-SCHEMA
176. EMAIL-OPT-OUT-TIMESTAMP-SCHEMA
177. EMAIL-PREFERENCES-SCHEMA
178. EMAIL-MARKETING-PERMISSION-SCHEMA

⸻

✅ SECTION 20 — DERIVED / META
179. EMAIL-COERCE-SCHEMA
180. EMAIL-NORMALIZED-SCHEMA
181. EMAIL-HASH-SCHEMA (for indexing)
182. EMAIL-UNIQUE-SCHEMA (case-folded equality)
183. EMAIL-ANY-SCHEMA (union of all email types)

✅ SECTION 1 — CORE EMAIL ADDRESS SCHEMAS (SYNTAX + STRUCTURE)
	1.	EMAIL-ADDRESS SCHEMA (RFC 5321/5322 compliant)
	2.	EMAIL-ADDRESS-STRICT SCHEMA (rejects comments/obsolete forms)
	3.	EMAIL-ADDRESS-LENIENT SCHEMA (browser-style tolerance)
	4.	EMAIL-ADDRESS-ASCII-ONLY SCHEMA
	5.	EMAIL-ADDRESS-IDN SCHEMA (internationalized, punycode)
	6.	EMAIL-ADDRESS-LOCAL-PART SCHEMA
	7.	EMAIL-ADDRESS-DOMAIN-PART SCHEMA
	8.	EMAIL-ADDRESS-QUOTED-LOCAL SCHEMA
	9.	EMAIL-ADDRESS-ALIAS SCHEMA (“user+tag@example.com”)
	10.	EMAIL-ADDRESS-VALID-TLD SCHEMA (cross-checks IANA list)
	11.	EMAIL-ADDRESS-DISPOSABLE-FILTER SCHEMA
	12.	EMAIL-ADDRESS-TEMPORARY-FILTER SCHEMA
	13.	EMAIL-ADDRESS-MX-CHECK SCHEMA (DNS MX validation)
	14.	EMAIL-ADDRESS-SMTP-PING SCHEMA (RCPT TO verification)
	15.	EMAIL-ADDRESS-BLACKLIST-CHECK SCHEMA
	16.	EMAIL-ADDRESS-WHITELIST-CHECK SCHEMA
	17.	EMAIL-ADDRESS-RESERVED-DOMAIN SCHEMA (no “example.com”, “test.com”)
	18.	EMAIL-ADDRESS-LOCALHOST-BLOCK SCHEMA
	19.	EMAIL-ADDRESS-COERCE SCHEMA (normalize case, trim, IDN)
	20.	EMAIL-ADDRESS-NORMALIZED SCHEMA (canonical lowercase, punycode)

⸻

✅ SECTION 2 — USER / IDENTITY LAYER SCHEMAS
21. EMAIL-USERNAME-SCHEMA (pre-@ only)
22. EMAIL-DISPLAY-NAME-SCHEMA (“John Doe john@example.com￼”)
23. EMAIL-CONTACT-SCHEMA (display + address object)
24. EMAIL-USER-HANDLE-SCHEMA (aliases, vanity domains)
25. EMAIL-USER-INITIALS-SCHEMA
26. EMAIL-SIGNATURE-BLOCK-SCHEMA
27. EMAIL-AVATAR-HASH-SCHEMA (Gravatar MD5)
28. EMAIL-IDENTITY-MAP-SCHEMA (multiple aliases → one user)

⸻

✅ SECTION 3 — MESSAGE / HEADER SCHEMAS
29. EMAIL-MESSAGE-ID-SCHEMA
30. EMAIL-IN-REPLY-TO-SCHEMA
31. EMAIL-REFERENCES-SCHEMA
32. EMAIL-SUBJECT-SCHEMA
33. EMAIL-DATE-HEADER-SCHEMA
34. EMAIL-FROM-SCHEMA
35. EMAIL-TO-SCHEMA
36. EMAIL-CC-SCHEMA
37. EMAIL-BCC-SCHEMA
38. EMAIL-REPLY-TO-SCHEMA
39. EMAIL-RETURN-PATH-SCHEMA
40. EMAIL-HEADERS-MAP-SCHEMA (name/value map)
41. EMAIL-CONTENT-TYPE-SCHEMA (MIME)
42. EMAIL-BOUNDARY-SCHEMA
43. EMAIL-ENCODING-SCHEMA (base64, QP, 8bit)
44. EMAIL-PRIORITY-SCHEMA
45. EMAIL-THREAD-ID-SCHEMA (Gmail/Outlook threading)

⸻

✅ SECTION 4 — CONTENT / BODY SCHEMAS
46. EMAIL-BODY-TEXT-SCHEMA
47. EMAIL-BODY-HTML-SCHEMA
48. EMAIL-BODY-MULTIPART-SCHEMA
49. EMAIL-ATTACHMENT-SCHEMA
50. EMAIL-ATTACHMENT-METADATA-SCHEMA (filename, MIME, size)
51. EMAIL-INLINE-IMAGE-CID-SCHEMA
52. EMAIL-FOOTER-SCHEMA
53. EMAIL-TEMPLATE-SCHEMA (transactional layout)
54. EMAIL-PLACEHOLDER-SCHEMA (variables for templating)

⸻

✅ SECTION 5 — TRANSPORT / DELIVERY SCHEMAS
55. EMAIL-SMTP-ENVELOPE-SCHEMA
56. EMAIL-ENVELOPE-FROM-SCHEMA
57. EMAIL-ENVELOPE-TO-SCHEMA
58. EMAIL-QUEUE-MESSAGE-SCHEMA
59. EMAIL-DELIVERY-STATUS-SCHEMA (DSN)
60. EMAIL-BOUNCE-REASON-SCHEMA
61. EMAIL-BOUNCE-CODE-SCHEMA
62. EMAIL-DEFERRED-STATUS-SCHEMA
63. EMAIL-DELIVERABILITY-SCORE-SCHEMA
64. EMAIL-SPAM-SCORE-SCHEMA
65. EMAIL-SPAM-FLAG-SCHEMA
66. EMAIL-DELIVERED-TIMESTAMP-SCHEMA
67. EMAIL-OPEN-TRACK-SCHEMA
68. EMAIL-CLICK-TRACK-SCHEMA
69. EMAIL-UNSUBSCRIBE-LINK-SCHEMA

⸻

✅ SECTION 6 — SECURITY / AUTHENTICATION SCHEMAS
70. EMAIL-SPF-RECORD-SCHEMA
71. EMAIL-SPF-RESULT-SCHEMA
72. EMAIL-DKIM-SIGNATURE-SCHEMA
73. EMAIL-DKIM-VERIFIED-SCHEMA
74. EMAIL-DMARC-POLICY-SCHEMA
75. EMAIL-DMARC-RESULT-SCHEMA
76. EMAIL-ARC-CHAIN-SCHEMA (Authenticated Received Chain)
77. EMAIL-TLS-STATUS-SCHEMA
78. EMAIL-ENCRYPTION-STATUS-SCHEMA (PGP/SMIME)
79. EMAIL-HASH-INTEGRITY-SCHEMA (checksum validation)
80. EMAIL-PHISH-RISK-SCORE-SCHEMA
81. EMAIL-SENDER-REPUTATION-SCHEMA
82. EMAIL-BLACKLIST-ENTRY-SCHEMA

⸻

✅ SECTION 7 — DOMAIN / DNS RECORD SCHEMAS
83. EMAIL-MX-RECORD-SCHEMA
84. EMAIL-A-RECORD-SCHEMA
85. EMAIL-TXT-RECORD-SCHEMA
86. EMAIL-DMARC-RECORD-SCHEMA
87. EMAIL-DKIM-PUBLIC-KEY-SCHEMA
88. EMAIL-DNS-LOOKUP-SCHEMA
89. EMAIL-DNS-TTL-SCHEMA

⸻

✅ SECTION 8 — UX / APP / PRODUCTIVITY LAYER
90. EMAIL-LABEL-SCHEMA (folder/tags)
91. EMAIL-THREAD-GROUP-SCHEMA
92. EMAIL-READ-STATE-SCHEMA
93. EMAIL-IMPORTANCE-SCHEMA
94. EMAIL-PINNED-STATE-SCHEMA
95. EMAIL-ARCHIVED-STATE-SCHEMA
96. EMAIL-SNOOZE-STATE-SCHEMA
97. EMAIL-REMINDER-SCHEMA
98. EMAIL-SCHEDULED-SEND-SCHEMA
99. EMAIL-DRAFT-STATE-SCHEMA
100. EMAIL-COMPOSE-METADATA-SCHEMA

⸻

✅ SECTION 9 — COMPLIANCE / LEGAL / POLICY SCHEMAS
101. EMAIL-RETENTION-POLICY-SCHEMA
102. EMAIL-AUDIT-LOG-SCHEMA
103. EMAIL-ACCESS-PERMISSION-SCHEMA
104. EMAIL-DATA-CLASSIFICATION-SCHEMA
105. EMAIL-LEGAL-HOLD-SCHEMA
106. EMAIL-E-DISCOVERY-SCHEMA
107. EMAIL-REDACTION-SCHEMA
108. EMAIL-PII-MASK-SCHEMA

⸻

✅ SECTION 10 — ANALYTICS / PERFORMANCE SCHEMAS
109. EMAIL-SENT-COUNT-SCHEMA
110. EMAIL-OPEN-RATE-SCHEMA
111. EMAIL-CLICK-RATE-SCHEMA
112. EMAIL-DELIVERY-TIME-SCHEMA
113. EMAIL-RESPONSE-TIME-SCHEMA
114. EMAIL-A/B-VARIANT-SCHEMA
115. EMAIL-TEMPLATE-PERFORMANCE-SCHEMA
116. EMAIL-DEVICE-OPEN-DISTRIBUTION-SCHEMA

⸻

✅ SECTION 11 — INFRASTRUCTURE / SERVER SCHEMAS
117. EMAIL-SERVER-HOST-SCHEMA
118. EMAIL-SERVER-PORT-SCHEMA
119. EMAIL-SERVER-PROTOCOL-SCHEMA (IMAP, POP3, SMTP, EAS)
120. EMAIL-SERVER-AUTH-MODE-SCHEMA
121. EMAIL-SERVER-TLS-CERT-SCHEMA
122. EMAIL-SERVER-CAPABILITY-SCHEMA
123. EMAIL-SERVER-QUEUE-SIZE-SCHEMA
124. EMAIL-SERVER-RATE-LIMIT-SCHEMA

⸻

✅ SECTION 12 — INTEGRATION / AUTOMATION SCHEMAS
125. EMAIL-WEBHOOK-SCHEMA
126. EMAIL-FORWARD-RULE-SCHEMA
127. EMAIL-FILTER-RULE-SCHEMA
128. EMAIL-TRIGGER-SCHEMA (on send/open/reply)
129. EMAIL-NOTIFICATION-SCHEMA
130. EMAIL-WORKFLOW-STEP-SCHEMA
131. EMAIL-CRM-CONTACT-LINK-SCHEMA
132. EMAIL-TICKET-LINK-SCHEMA

⸻

✅ SECTION 13 — AI / CLASSIFICATION SCHEMAS
133. EMAIL-INTENT-SCHEMA (support/sales/personal)
134. EMAIL-SENTIMENT-SCHEMA
135. EMAIL-TOPIC-CLASSIFICATION-SCHEMA
136. EMAIL-AUTO-REPLY-SUGGESTION-SCHEMA
137. EMAIL-PRIORITY-PREDICTION-SCHEMA
138. EMAIL-SPAM-ML-SCORE-SCHEMA
139. EMAIL-ENTITY-EXTRACTION-SCHEMA

⸻

✅ SECTION 14 — COMPOSITE / STRUCTURED OBJECT SCHEMAS
140. EMAIL-CONTACT-OBJECT-SCHEMA
141. EMAIL-MESSAGE-OBJECT-SCHEMA
142. EMAIL-THREAD-OBJECT-SCHEMA
143. EMAIL-ACCOUNT-OBJECT-SCHEMA
144. EMAIL-DOMAIN-OBJECT-SCHEMA
145. EMAIL-SERVER-OBJECT-SCHEMA
146. EMAIL-DELIVERY-REPORT-OBJECT-SCHEMA
147. EMAIL-SECURITY-REPORT-OBJECT-SCHEMA

⸻

✅ SECTION 15 — TEST / MOCK / VALIDATION SCHEMAS
148. EMAIL-TEST-ADDRESS-SCHEMA (“example@”)
149. EMAIL-MOCK-MESSAGE-SCHEMA
150. EMAIL-FAKE-SMTP-EVENT-SCHEMA
151. EMAIL-SANDBOX-DOMAIN-SCHEMA
152. EMAIL-TEST-HARNESS-SCHEMA

⸻

✅ SECTION 16 — VISUAL / UX COMPONENT SCHEMAS
153. EMAIL-CARD-SCHEMA (UI preview)
154. EMAIL-SNIPPET-SCHEMA (excerpt/preview text)
155. EMAIL-AVATAR-SCHEMA
156. EMAIL-BADGE-SCHEMA (unread count)
157. EMAIL-COLOR-LABEL-SCHEMA
158. EMAIL-ICON-SCHEMA (provider logos)

⸻

✅ SECTION 17 — PROVIDER-SPECIFIC SCHEMAS
159. EMAIL-GMAIL-THREAD-SCHEMA
160. EMAIL-OUTLOOK-MESSAGE-SCHEMA
161. EMAIL-ICLOUD-MESSAGE-SCHEMA
162. EMAIL-YAHOO-HEADER-SCHEMA
163. EMAIL-EXCHANGE-EWS-SCHEMA
164. EMAIL-BREVO-SMTP-EVENT-SCHEMA
165. EMAIL-MAILGUN-WEBHOOK-SCHEMA
166. EMAIL-SENDGRID-EVENT-SCHEMA
167. EMAIL-AMAZON-SES-NOTIFICATION-SCHEMA

⸻

✅ SECTION 18 — HISTORICAL / ARCHIVAL SCHEMAS
168. EMAIL-ARCHIVE-ENTRY-SCHEMA
169. EMAIL-ARCHIVE-INDEX-SCHEMA
170. EMAIL-ARCHIVE-METADATA-SCHEMA
171. EMAIL-ARCHIVE-CHECKSUM-SCHEMA
172. EMAIL-ARCHIVE-TIMESTAMP-SCHEMA

⸻

✅ SECTION 19 — POLICY / CONSENT / PRIVACY SCHEMAS
173. EMAIL-CONSENT-STATUS-SCHEMA
174. EMAIL-UNSUBSCRIBE-STATUS-SCHEMA
175. EMAIL-OPT-IN-TIMESTAMP-SCHEMA
176. EMAIL-OPT-OUT-TIMESTAMP-SCHEMA
177. EMAIL-PREFERENCES-SCHEMA
178. EMAIL-MARKETING-PERMISSION-SCHEMA

⸻

✅ SECTION 20 — DERIVED / META
179. EMAIL-COERCE-SCHEMA
180. EMAIL-NORMALIZED-SCHEMA
181. EMAIL-HASH-SCHEMA (for indexing)
182. EMAIL-UNIQUE-SCHEMA (case-folded equality)
183. EMAIL-ANY-SCHEMA (union of all email types)