✅ SECTION 1 — CORE FORCE SCHEMAS (UNIVERSAL PHYSICS)

These are the foundational, SI-aligned schemas.
	1.	FORCE-NEWTON SCHEMA (N)
	2.	FORCE-KILONEWTON SCHEMA (kN)
	3.	FORCE-MILLNEWTON SCHEMA (mN)
	4.	FORCE-DYNE SCHEMA (dyn)
	5.	FORCE-POUND-FORCE SCHEMA (lbf)
	6.	FORCE-KIP SCHEMA (kip)
	7.	FORCE-KGF SCHEMA (kilogram-force)
	8.	FORCE-POUNDMASS-G SCHEMA (lbm·g)
	9.	FORCE-COERCE SCHEMA (any → N)
	10.	FORCE-CANONICAL SCHEMA (returns N)

⸻

✅ SECTION 2 — VECTOR FORCE SCHEMAS

For 2D/3D, robotics, gaming, physics engines.
	11.	FORCE-VECTOR-2D SCHEMA (Fx, Fy)
	12.	FORCE-VECTOR-3D SCHEMA (Fx, Fy, Fz)
	13.	FORCE-VECTOR-MAGNITUDE SCHEMA
	14.	FORCE-VECTOR-NORMALIZED SCHEMA
	15.	FORCE-VECTOR-AXIS SCHEMA (x|y|z discrete)
	16.	FORCE-VECTOR-TUPLE SCHEMA ([Fx, Fy, Fz])

⸻

✅ SECTION 3 — CONTACT & MECHANICAL FORCE SCHEMAS

Used in engineering, material science, product design.
	17.	CONTACT-FORCE SCHEMA
	18.	NORMAL-FORCE SCHEMA (Fn)
	19.	FRICTION-FORCE SCHEMA (Ff)
	20.	SHEAR-FORCE SCHEMA
	21.	TENSION-FORCE SCHEMA
	22.	COMPRESSION-FORCE SCHEMA
	23.	TORSION-FORCE SCHEMA
	24.	BUCKLING-FORCE SCHEMA
	25.	HARDNESS-FORCE SCHEMA (indentation force)
	26.	CLAMP-FORCE SCHEMA

⸻

✅ SECTION 4 — FORCE PER AREA / SURFACE / LENGTH

(Technically pressures or line loads, but functionally “derived force” quantities.)
	27.	LINE-LOAD-FORCE SCHEMA (N/m)
	28.	SURFACE-LOAD-FORCE SCHEMA (N/m²)
	29.	AXIAL-LOAD-FORCE SCHEMA
	30.	BEAM-SHEAR-FORCE SCHEMA
	31.	BENDING-FORCE SCHEMA

⸻

✅ SECTION 5 — MOTION / MOVEMENT FORCE SCHEMAS

For physics, sports analytics, robotics, vehicles.
	32.	APPLIED-FORCE SCHEMA
	33.	RESULTANT-FORCE SCHEMA
	34.	INERTIAL-FORCE SCHEMA
	35.	CENTRIFUGAL-FORCE SCHEMA
	36.	CENTRIPETAL-FORCE SCHEMA
	37.	CORIOLIS-FORCE SCHEMA
	38.	DRAG-FORCE SCHEMA
	39.	LIFT-FORCE SCHEMA
	40.	THRUST-FORCE SCHEMA
	41.	ROLLING-RESISTANCE-FORCE SCHEMA
	42.	SPRING-FORCE SCHEMA (Hooke’s law)
	43.	DAMPING-FORCE SCHEMA (viscous)

⸻

✅ SECTION 6 — ELECTROMAGNETIC FORCE SCHEMAS

Because forces aren’t just mechanical.
	44.	ELECTRIC-FORCE SCHEMA (Coulomb’s law)
	45.	MAGNETIC-FORCE SCHEMA (Lorentz)
	46.	LORENTZ-FORCE SCHEMA (q(E + v × B))
	47.	AMPERE-FORCE SCHEMA
	48.	MAXWELL-STRESS-FORCE SCHEMA
	49.	RADIATION-PRESSURE-FORCE SCHEMA

⸻

✅ SECTION 7 — GRAVITY-RELATED FORCE SCHEMAS
	50.	WEIGHT-FORCE SCHEMA (mg)
	51.	GRAVITATIONAL-FORCE SCHEMA (Newtonian)
	52.	PLANETARY-GRAVITY-FORCE SCHEMA
	53.	TIDAL-FORCE SCHEMA
	54.	BUOYANT-FORCE SCHEMA (Archimedes)

⸻

✅ SECTION 8 — VEHICLE / AVIATION / AUTOMOTIVE FORCE SCHEMAS
	55.	BRAKE-FORCE SCHEMA
	56.	ENGINE-FORCE SCHEMA
	57.	DOWNFORCE SCHEMA (aerodynamic)
	58.	CORNERING-FORCE SCHEMA (lateral G)
	59.	TYRE-FORCE SCHEMA
	60.	IMPACT-FORCE SCHEMA (crash physics)

⸻

✅ SECTION 9 — BIOMECHANICS / SPORTS SCIENCE FORCE SCHEMAS
	61.	MUSCLE-FORCE SCHEMA
	62.	GRIP-FORCE SCHEMA
	63.	PINCH-FORCE SCHEMA
	64.	IMPACT-FORCE-BODY SCHEMA (punch/kick/strike)
	65.	GROUND-REACTION-FORCE SCHEMA (GRF)
	66.	VERTICAL-GRF SCHEMA
	67.	HORIZONTAL-GRF SCHEMA
	68.	JUMP-FORCE SCHEMA
	69.	PUSHING-FORCE SCHEMA
	70.	PULLING-FORCE SCHEMA

⸻

✅ SECTION 10 — ROBOTICS FORCE SCHEMAS
	71.	ROBOT-ACTUATOR-FORCE SCHEMA
	72.	ROBOT-END-EFFECTOR-FORCE SCHEMA
	73.	ROBOT-TORQUE-FORCE SCHEMA
	74.	COLLISION-FORCE SCHEMA
	75.	HAPTIC-FORCE-FEEDBACK SCHEMA

⸻

✅ SECTION 11 — STRUCTURAL ENGINEERING FORCE SCHEMAS
	76.	LOAD-DISTRIBUTION-FORCE SCHEMA
	77.	DEAD-LOAD-FORCE SCHEMA
	78.	LIVE-LOAD-FORCE SCHEMA
	79.	IMPACT-LOAD-FORCE SCHEMA
	80.	SEISMIC-FORCE SCHEMA
	81.	WIND-FORCE SCHEMA
	82.	SNOW-FORCE SCHEMA

⸻

✅ SECTION 12 — ASTRONOMY / SPACE / COSMOLOGY FORCES
	83.	SOLAR-RADIATION-FORCE SCHEMA
	84.	YARKOVSKY-FORCE SCHEMA (thermal thrust)
	85.	GRAVITATIONAL-TENSOR-FORCE SCHEMA
	86.	ORBIT-PERTURBATION-FORCE SCHEMA
	✅ OPTIONAL SECTION 13 — ENERGY / POWER / DERIVED FORCE SCHEMAS
	(useful when coupling with work, momentum, impulse, pressure, etc.)
	87. FORCE-MOMENTUM-IMPULSE SCHEMA (Δp = F Δt)
	88. FORCE-WORK SCHEMA (W = F · d)
	89. FORCE-ENERGY-EQUIVALENT SCHEMA (F ↔ J/m)
	90. FORCE-PRESSURE-DERIVED SCHEMA (P = F/A)
	91. FORCE-TORQUE-EQUIVALENT SCHEMA (τ = r × F)
	92. FORCE-ANGULAR-MOMENTUM-TRANSFER SCHEMA
	93. FORCE-POWER-RATE SCHEMA (P = F v)
	
	⸻
	
	✅ OPTIONAL SECTION 14 — ELECTROMECHANICAL / COUPLED FIELD SCHEMAS
	94. MAGNETOMOTIVE-FORCE SCHEMA (MMF, Ampere-turns)
	95. ELECTROMOTIVE-FORCE SCHEMA (EMF, voltage as work per charge)
	96. PIEZOELECTRIC-FORCE SCHEMA (mech ↔ electrical stress)
	97. ELECTROSTATIC-ADHESION-FORCE SCHEMA (used in robot grippers)
	98. MAGNETIC-LEVITATION-FORCE SCHEMA (MagLev lift)
	
	⸻
	
	✅ OPTIONAL SECTION 15 — THERMAL / FLUID / PLASMA FORCE SCHEMAS
	99. THERMAL-EXPANSION-FORCE SCHEMA (constrained heating stress)
	100. THERMAL-BUOYANCY-FORCE SCHEMA (Boussinesq approximation)
	101. VISCOSITY-SHEAR-FORCE SCHEMA
	102. REYNOLDS-DRAG-FORCE SCHEMA (Re dependent)
	103. MAGNETOHYDRODYNAMIC-FORCE SCHEMA (J × B in plasma)
	104. RADIATIVE-RECOIL-FORCE SCHEMA (photon momentum transfer)
	
	⸻
	
	✅ OPTIONAL SECTION 16 — QUANTUM / PARTICLE / NUCLEAR FORCE SCHEMAS
	105. NUCLEAR-STRONG-FORCE SCHEMA
	106. NUCLEAR-WEAK-FORCE SCHEMA
	107. YUKAWA-FORCE SCHEMA (nucleon potential)
	108. CASIMIR-FORCE SCHEMA (vacuum quantum pressure)
	109. VAN-DER-WAALS-FORCE SCHEMA (intermolecular attraction)
	110. LONDON-DISPERSION-FORCE SCHEMA
	111. HYDROGEN-BOND-FORCE SCHEMA
	
	⸻
	
	✅ OPTIONAL SECTION 17 — COMPUTATIONAL / SIMULATION SCHEMAS
	112. FORCE-FIELD-VECTOR-SCHEMA (simulation array of F)
	113. FORCE-INTEGRATOR-SCHEMA (numerical step Δt F/m)
	114. FORCE-CONSTRAINT-SCHEMA (constraints in solver)
	115. FORCE-COLLISION-RESPONSE-SCHEMA
	116. FORCE-INTERPOLATED-SCHEMA (splines or mesh fields)
	117. FORCE-NOISE-MODEL-SCHEMA (random perturbations)
	
	⸻
	
	✅ OPTIONAL SECTION 18 — METROLOGY / INSTRUMENTATION SCHEMAS
	118. FORCE-SENSOR-SCHEMA (load cell metadata)
	119. FORCE-TRANSDUCER-SCHEMA (calibration curve)
	120. FORCE-GAUGE-SCHEMA (handheld measurement)
	121. FORCE-CALIBRATION-SCHEMA (standard masses → N)
	122. FORCE-UNCERTAINTY-SCHEMA (± ΔF)
	123. FORCE-RANGE-SCHEMA (min/max)
	124. FORCE-PRECISION-SCHEMA (resolution)
	
	⸻
	
	✅ OPTIONAL SECTION 19 — DATA MODEL / UTILITY SCHEMAS
	125. FORCE-ARRAY-SCHEMA
	126. FORCE-MAP-SCHEMA
	127. FORCE-SET-SCHEMA
	128. FORCE-OPTIONAL-SCHEMA
	129. FORCE-NULLABLE-SCHEMA
	130. FORCE-DEFAULT-SCHEMA
	131. FORCE-ANY-SCHEMA
	