✅ SECTION 1 — CORE GENDER REPRESENTATION SCHEMAS
	1.	GENDER-STRING-SCHEMA (generic string)
	2.	GENDER-ENUM-BINARY-SCHEMA (male/female only — legacy compliance)
	3.	GENDER-ENUM-THREE-SCHEMA (male/female/other — legacy HR)
	4.	GENDER-ENUM-EXTENDED-SCHEMA (male/female/nonbinary/trans/etc.)
	5.	GENDER-IDENTITY-SCHEMA (self-chosen identity)
	6.	GENDER-EXPRESSION-SCHEMA (presentation, non-classified)
	7.	GENDER-LABEL-CANONICAL-SCHEMA (normalized, but never inferred)
	8.	GENDER-COERCE-SCHEMA (strict input sanitization only, no inference)
	9.	GENDER-NULLABLE-SCHEMA
	10.	GENDER-OPTIONAL-SCHEMA
	11.	GENDER-UNKNOWN-SCHEMA (“unknown”, “not provided”)
	12.	GENDER-NOT-APPLICABLE-SCHEMA
	13.	GENDER-PREFER-NOT-TO-SAY-SCHEMA

⸻

✅ SECTION 2 — INTERNATIONAL/LEGAL/COMPLIANCE GENDER SCHEMAS
	14.	GENDER-LEGAL-MARKER-SCHEMA (M/F/X)
	15.	GENDER-ISO-IEC-5218-SCHEMA (0/1/2/9)
	16.	GENDER-PASSPORT-CODE-SCHEMA (M/F/X)
	17.	GENDER-DRIVERS-LICENSE-MARKER-SCHEMA (jurisdiction-based)
	18.	GENDER-GOVERNMENT-CENSUS-SCHEMA (varies per country)
	19.	GENDER-HEALTHCARE-ADMIN-SEX-SCHEMA (HL7 V2)
	20.	GENDER-HEALTHCARE-CLINICAL-SEX-SCHEMA (FHIR AdministrativeGender)
	21.	GENDER-EMPLOYMENT-HRIS-MARKER-SCHEMA
	22.	GENDER-EDUCATION-FORM-MARKER-SCHEMA
	23.	GENDER-CORRECTIONS-LEGAL-MARKER-SCHEMA
	24.	GENDER-LEGAL-DOCUMENT-CLASSIFICATION-SCHEMA

⸻

✅ SECTION 3 — HEALTH & MEDICAL CONTEXT (ALWAYS NON-INFERENTIAL)
	25.	SEX-ASSIGNED-AT-BIRTH-SCHEMA (if explicitly provided)
	26.	GENDER-CLINICAL-RELEVANT-FIELDS-SCHEMA (opt-in, medically contextual)
	27.	GENDER-RELEVANT-NOTES-SCHEMA (freeform, optional)
	28.	GENDER-TRANSITION-STATUS-SCHEMA (voluntary, non-required)
	29.	GENDER-PRONOUNS-SCHEMA
	30.	GENDER-MEDICAL-CONFIG-SCHEMA (FHIR GenderIdentity)
	31.	GENDER-HL7-CODED-VALUE-SCHEMA
	32.	GENDER-HEALTH-RESEARCH-CLASSIFICATION-SCHEMA (NIH standards)

⸻

✅ SECTION 4 — UX/UI FORMS & USER-PROVIDED FIELDS
	33.	GENDER-FORM-FIELD-SCHEMA
	34.	GENDER-FORM-CHOICE-LIST-SCHEMA
	35.	GENDER-FORM-FREE-TEXT-SCHEMA
	36.	GENDER-FORM-PREFERRED-LABEL-SCHEMA
	37.	GENDER-DISPLAY-LABEL-SCHEMA
	38.	GENDER-UI-PRONOUN-SELECTOR-SCHEMA
	39.	GENDER-UI-SELF-DESCRIPTION-SCHEMA
	40.	GENDER-PROFILE-FORM-SCHEMA (apps/accounts)
	41.	GENDER-PROFILE-OPTIONAL-FIELD-SCHEMA
	42.	GENDER-PUBLIC-VS-PRIVATE-FIELD-SCHEMA

⸻

✅ SECTION 5 — PRIVACY, ACCESS CONTROL & DATA GOVERNANCE
	43.	GENDER-PII-FLAG-SCHEMA
	44.	GENDER-SENSITIVE-DATA-CLASSIFICATION-SCHEMA
	45.	GENDER-DATA-CONSENT-SCHEMA
	46.	GENDER-ACCESS-SCOPE-SCHEMA (admin/user/system)
	47.	GENDER-AUDIT-LOG-SCHEMA (changes, reasons)
	48.	GENDER-REDACTION-SCHEMA (masking/deletion)
	49.	GENDER-RETENTION-POLICY-SCHEMA
	50.	GENDER-ANONYMIZED-DATA-SCHEMA
	51.	GENDER-STATISTICAL-ONLY-SCHEMA
	52.	GENDER-AGGREGATION-CATEGORY-SCHEMA

⸻

✅ SECTION 6 — INTERNATIONAL HUMAN RIGHTS / ORGANIZATIONAL STANDARDS
	53.	GENDER-UN-HUMAN-RIGHTS-REPORTING-CODE-SCHEMA
	54.	GENDER-OECD-DATA-CODE-SCHEMA
	55.	GENDER-WHO-CLINICAL-CATEGORIZATION-SCHEMA
	56.	GENDER-ILO-WORKFORCE-REPORTING-SCHEMA
	57.	GENDER-NGO-SURVEY-SCHEMA
	58.	GENDER-POPULATION-STUDY-SCHEMA
	59.	GENDER-LGBTQ-ALLY-ORG-STANDARDS-SCHEMA

⸻

✅ SECTION 7 — ENTERPRISE SYSTEM INTEGRATIONS
	60.	GENDER-HRIS-INTEGRATION-SCHEMA (Workday, BambooHR, ADP)
	61.	GENDER-IDP/OAUTH-SCHEMA (Okta, Auth0, Azure AD)
	62.	GENDER-CRM-SCHEMA (Salesforce, HubSpot)
	63.	GENDER-SUPPORT-TICKET-SCHEMA
	64.	GENDER-PAYROLL-SCHEMA (non-discriminatory placeholder only)
	65.	GENDER-ANALYTICS-ATTRIBUTE-SCHEMA (always aggregated/anonymized)
	66.	GENDER-ACCOUNT-PROFILE-SCHEMA
	67.	GENDER-MARKETING-COMPLIANCE-SCHEMA (never targeted)
	68.	GENDER-LOYALTY-PROGRAM-SCHEMA (non-inferential)

⸻

✅ SECTION 8 — CONTENT, SOCIAL, AND COMMUNITY APPS
	69.	GENDER-PROFILE-VISIBILITY-SCHEMA
	70.	GENDER-PROFILE-DISCLOSURE-PERMISSION-SCHEMA
	71.	GENDER-SOCIAL-PROFILE-LABEL-SCHEMA
	72.	GENDER-RELATIONSHIP-DYNAMICS-SCHEMA (self-described)
	73.	GENDER-SAFETY-FLAG-SCHEMA
	74.	GENDER-COMMUNITY-ROLE-SCHEMA
	75.	GENDER-COMMENT-MODERATION-METADATA-SCHEMA
	76.	GENDER-DATING-APP-FIELD-SCHEMA (matches industry practice)

⸻

✅ SECTION 9 — RESEARCH, SURVEYS, DEMOGRAPHICS
	77.	GENDER-SURVEY-MULTISELECT-SCHEMA
	78.	GENDER-SURVEY-FREETEXT-SCHEMA
	79.	GENDER-QUANTITATIVE-CATEGORY-SCHEMA
	80.	GENDER-LONGITUDINAL-TRACKING-SCHEMA
	81.	GENDER-DEIDENTIFIED-RECORD-SCHEMA
	82.	GENDER-STUDY-CODE-SCHEMA
	83.	GENDER-EXPERIMENT-GROUPING-SCHEMA
	84.	GENDER-CORRELATION-ANALYSIS-SCHEMA (no inference)
	85.	GENDER-SURVEY-REPORTING-CATEGORY-SCHEMA

⸻

✅ SECTION 10 — DEVELOPER / SYSTEM UTILITIES
	86.	GENDER-SCHEMA-COERCE-NORMALIZED-LABEL
	87.	GENDER-SCHEMA-VALID-ENUM-LIST
	88.	GENDER-SCHEMA-STRIP-UNSAFE-CONTENT
	89.	GENDER-SCHEMA-FIELD-DESCRIPTION
	90.	GENDER-SCHEMA-I18N-LOCALIZATION
	91.	GENDER-ALIAS-MAPPINGS-SCHEMA (e.g., “nb” → “nonbinary”)
	92.	GENDER-FIELD-TRANSFORM-SCHEMA
	93.	GENDER-SCHEMA-VERSIONED-DOC-SCHEMA
	94.	GENDER-SCHEMA-STRICT-MODE
	95.	GENDER-SCHEMA-LAX-MODE
	96.	GENDER-DISPLAY-NORMALIZER-SCHEMA
	97.	GENDER-DATA-MERGE-SCHEMA
	98.	GENDER-FIELD-UPDATE-PAYLOAD-SCHEMA
	99.	GENDER-API-PAYLOAD-SCHEMA
	100.	GENDER-DATABASE-COLUMN-SCHEMA (safe text)
