✅ SECTION 1 — CORE HAIR ATTRIBUTE SCHEMAS
	1.	HAIR-COLOR-SCHEMA
	2.	HAIR-TONE-SCHEMA (warm/cool/neutral)
	3.	HAIR-SHADE-SCHEMA (level 1–10)
	4.	HAIR-LENGTH-SCHEMA
	5.	HAIR-DENSITY-SCHEMA
	6.	HAIR-THICKNESS-SCHEMA
	7.	HAIR-TEXTURE-SCHEMA
	8.	HAIR-TYPE-SCHEMA (1A–4C)
	9.	HAIR-FORM-SCHEMA (straight/wavy/curly/coily)
	10.	HAIR-STATE-SCHEMA (natural/treated/damaged/etc.)
	11.	HAIR-SHEEN-SCHEMA (matte/normal/glossy)
	12.	HAIR-VOLUME-SCHEMA
	13.	HAIR-POROSITY-SCHEMA
	14.	HAIR-ELASTICITY-SCHEMA
	15.	HAIR-OILINESS-SCHEMA
	16.	HAIR-HYDRATION-SCHEMA
	17.	HAIR-HEALTH-STATUS-SCHEMA
	18.	HAIR-DAMAGE-LEVEL-SCHEMA
	19.	HAIR-FRIZZ-LEVEL-SCHEMA
	20.	HAIR-SCISSORING/END-CONDITION-SCHEMA

⸻

✅ SECTION 2 — HAIR COLORATION / CHEMICAL TREATMENT SCHEMAS
	21.	HAIR-DYE-TYPE-SCHEMA
	22.	HAIR-DYE-SHADE-SCHEMA
	23.	HAIR-DYE-BRAND-SCHEMA
	24.	HAIR-DYE-FORMULA-SCHEMA
	25.	HAIR-DYE-APPLICATION-METHOD-SCHEMA
	26.	HAIR-DYE-INTENSITY-SCHEMA
	27.	HAIR-ROOT-COLOR-SCHEMA
	28.	HAIR-TIPS-COLOR-SCHEMA
	29.	HAIR-HIGHLIGHTS-SCHEMA
	30.	HAIR-LOWLIGHTS-SCHEMA
	31.	HAIR-BALAYAGE-SCHEMA
	32.	HAIR-OMBRE-SCHEMA
	33.	HAIR-BLEACH-LEVEL-SCHEMA
	34.	HAIR-LIFT-LEVEL-SCHEMA
	35.	HAIR-COLOR-MAINTENANCE-SCHEMA
	36.	HAIR-COLOR-VIBRANCY-SCHEMA
	37.	HAIR-DYE-LONGEVITY-SCHEMA

⸻

✅ SECTION 3 — HAIR CUT / STYLE / SHAPE SCHEMAS
	38.	HAIR-CUT-SHAPE-SCHEMA
	39.	HAIR-CUT-LENGTH-ZONE-SCHEMA (top/back/sides/bangs)
	40.	HAIR-CUT-LAYERING-LEVEL-SCHEMA
	41.	HAIR-CUT-LINE-SCHEMA
	42.	HAIR-CUT-EDGE-SCHEMA
	43.	HAIR-CUT-BANGS-FRINGE-SCHEMA
	44.	HAIR-CUT-FACE-FRAMING-SCHEMA
	45.	HAIR-STYLE-NAME-SCHEMA
	46.	HAIR-STYLE-CATEGORY-SCHEMA (formal/casual/etc.)
	47.	HAIR-STYLE-COMPLEXITY-SCHEMA
	48.	HAIR-STYLE-HOLD-LEVEL-SCHEMA
	49.	HAIR-STYLE-ICONS-SCHEMA (ponytail/bun/braids/etc.)
	50.	HAIR-BRAID-TYPE-SCHEMA
	51.	HAIR-UPDO-TYPE-SCHEMA
	52.	HAIR-PARTING-SCHEMA (center/side/zigzag/etc.)
	53.	HAIR-FLOW-DIRECTION-SCHEMA
	54.	HAIR-STYLE-DURATION-SCHEMA

⸻

✅ SECTION 4 — HAIR ROOT / SCALP / FOLLICLE SCHEMAS
	55.	SCALP-CONDITION-SCHEMA
	56.	SCALP-OILINESS-SCHEMA
	57.	SCALP-SENSITIVITY-SCHEMA
	58.	SCALP-PH-SCHEMA
	59.	SCALP-HEALTH-SCHEMA
	60.	FOLLICLE-DENSITY-SCHEMA
	61.	FOLLICLE-SIZE-SCHEMA
	62.	HAIR-GROWTH-RATE-SCHEMA
	63.	HAIR-SHEDDING-LEVEL-SCHEMA
	64.	HAIR-REGROWTH-STATUS-SCHEMA
	65.	HAIRLINE-SHAPE-SCHEMA
	66.	HAIRLINE-DENSITY-SCHEMA
	67.	HAIRLINE-MATURATION-SCHEMA
	68.	HAIR-ROOT-STATE-SCHEMA
	69.	HAIR-ROOT-HEALTH-SCHEMA

⸻

✅ SECTION 5 — HAIR LOSS / MEDICAL SCHEMAS
	70.	ALOPECIA-TYPE-SCHEMA
	71.	HAIR-LOSS-PATTERN-SCHEMA
	72.	HAIR-LOSS-SEVERITY-SCHEMA
	73.	HAIR-LOSS-CAUSE-SCHEMA
	74.	HAIR-LOSS-PROGRESSION-SCHEMA
	75.	HAIR-LOSS-STABILITY-SCHEMA
	76.	HAIR-MINIOXIDIL-USE-SCHEMA
	77.	HAIR-FINASTERIDE-USE-SCHEMA
	78.	HAIR-TRANSPLANT-STATUS-SCHEMA
	79.	HAIR-TRANSPLANT-GRAFT-COUNT-SCHEMA
	80.	HAIR-TRANSPLANT-ZONE-SCHEMA
	81.	MEDICAL-HAIR-TREATMENT-SCHEMA
	82.	POST-PROCEDURE-AFTERCARE-SCHEMA

⸻

✅ SECTION 6 — HAIR PRODUCT / COSMETIC SCHEMAS
	83.	HAIR-PRODUCT-ID-SCHEMA
	84.	HAIR-PRODUCT-TYPE-SCHEMA
	85.	HAIR-SHAMPOO-SCHEMA
	86.	HAIR-CONDITIONER-SCHEMA
	87.	HAIR-MASK-SCHEMA
	88.	HAIR-SERUM-SCHEMA
	89.	HAIR-OIL-SCHEMA
	90.	HAIR-SPRAY-SCHEMA
	91.	HAIR-MOUSSE-SCHEMA
	92.	HAIR-GEL-SCHEMA
	93.	HAIR-CLAY-SCHEMA
	94.	HAIR-WAX-SCHEMA
	95.	HAIR-POMADE-SCHEMA
	96.	HAIR-MIST-SCHEMA
	97.	HAIR-LEAVE-IN-TREATMENT-SCHEMA
	98.	HAIR-STYLING-CREAM-SCHEMA
	99.	HAIR-PRODUCT-HOLD-LEVEL-SCHEMA
	100.	HAIR-PRODUCT-GLOSS-LEVEL-SCHEMA
	101.	HAIR-PRODUCT-PROTECTION-SCHEMA (UV/heat/anti-frizz/etc.)
	102.	HAIR-PRODUCT-INGREDIENTS-SCHEMA
	103.	HAIR-PRODUCT-SENSITIVITY-FLAGS-SCHEMA

⸻

✅ SECTION 7 — HAIR TOOLS / DEVICE SCHEMAS
	104.	HAIR-DRYER-SETTINGS-SCHEMA
	105.	HAIR-STRAIGHTENER-TEMP-SCHEMA
	106.	HAIR-CURLER-DIAMETER-SCHEMA
	107.	HAIR-CURLER-TEMP-SCHEMA
	108.	HAIR-ROLLER-SIZE-SCHEMA
	109.	HAIR-DIFFUSER-TYPE-SCHEMA
	110.	HAIR-COMB-TYPE-SCHEMA
	111.	HAIR-BRUSH-TYPE-SCHEMA
	112.	HAIR-CLIP-TYPE-SCHEMA
	113.	HAIR-TOOL-TECHNOLOGY-SCHEMA (ionic/ceramic/tourmaline/etc.)
	114.	HAIR-TOOL-HEAT-LEVEL-SCHEMA
	115.	HAIR-TOOL-WEAR-SCHEMA

⸻

✅ SECTION 8 — HAIR APPEARANCE / PRESENTATION
	116.	HAIR-SHINE-SCHEMA
	117.	HAIR-BOUNCE-SCHEMA
	118.	HAIR-DEFINITION-SCHEMA (curl/shape definition)
	119.	HAIR-MANAGEABILITY-SCHEMA
	120.	HAIR-SOFTNESS-SCHEMA
	121.	HAIR-MESSINESS-SCHEMA
	122.	HAIR-ASYMMETRY-SCHEMA
	123.	HAIR-FLYAWAY-LEVEL-SCHEMA
	124.	HAIR-COMBABILITY-SCHEMA
	125.	HAIR-MOTION-SCHEMA (animation/VR)

⸻

✅ SECTION 9 — HAIR FOR AVATARS / AR / VR / 3D
	126.	HAIR-MESH-TYPE-SCHEMA
	127.	HAIR-MESH-LOD-SCHEMA
	128.	HAIR-SHADER-TYPE-SCHEMA
	129.	HAIR-STRAND-COUNT-SCHEMA
	130.	HAIR-GROOM-PRESET-SCHEMA
	131.	HAIR-PHYSICS-PRESET-SCHEMA
	132.	HAIR-DYNAMICS-STIFFNESS-SCHEMA
	133.	HAIR-DYNAMICS-GRAVITY-SCHEMA
	134.	HAIR-DYNAMICS-DRAG-SCHEMA
	135.	HAIR-SIMULATION-FIDELITY-SCHEMA
	136.	HAIR-RENDER-QUALITY-SCHEMA
	137.	HAIR-STYLE-PRESET-SCHEMA
	138.	HAIR-COLOR-PRESET-SCHEMA
	139.	HAIR-AVATAR-COMPATIBILITY-SCHEMA
	140.	HAIR-AR-MARKER-OVERLAY-SCHEMA

⸻

✅ SECTION 10 — HAIR PERSONALIZATION / PROFILE
	141.	HAIR-PROFILE-ID-SCHEMA
	142.	HAIR-GOALS-SCHEMA (growth/strength/color/etc.)
	143.	HAIR-ROUTINE-SCHEMA
	144.	HAIR-HABITS-SCHEMA (heat use, washing frequency, etc.)
	145.	HAIR-ALLERGIES-SCHEMA
	146.	HAIR-PREFERENCES-SCHEMA
	147.	HAIR-TREATMENT-HISTORY-SCHEMA
	148.	HAIR-PROFILE-SNAPSHOT-SCHEMA
	149.	HAIR-PROGRESSION-SCHEMA
	150.	HAIR-CARE-RECOMMENDATIONS-SCHEMA
