✅ SECTION 1 — CORE HEXADECIMAL VALIDATION
	1.	HEX-BASIC SCHEMA (0–9, a–f, A–F)
	2.	HEX-STRICT SCHEMA (lowercase only)
	3.	HEX-UPPERCASE SCHEMA (A–F only)
	4.	HEX-CASE-INSENSITIVE SCHEMA
	5.	HEX-NULLABLE SCHEMA
	6.	HEX-OPTIONAL SCHEMA
	7.	HEX-DEFAULT SCHEMA
	8.	HEX-EMPTY-ALLOWED SCHEMA
	9.	HEX-NO-PREFIX SCHEMA
	10.	HEX-WITH-PREFIX SCHEMA (“0x”)

⸻

✅ SECTION 2 — HEX LENGTH & FORM CONSTRAINTS
	11.	HEX-LENGTH-EVEN SCHEMA
	12.	HEX-LENGTH-ODD SCHEMA
	13.	HEX-MIN-LENGTH SCHEMA
	14.	HEX-MAX-LENGTH SCHEMA
	15.	HEX-FIXED-LENGTH SCHEMA (N chars)
	16.	HEX-RANGE-LENGTH SCHEMA (N–M)
	17.	HEX-ZERO-PADDED SCHEMA
	18.	HEX-NO-LEADING-ZEROES SCHEMA
	19.	HEX-NORMALIZED-CASE SCHEMA
	20.	HEX-NORMALIZED-LENGTH SCHEMA (even pad)

⸻

✅ SECTION 3 — COERCION & CONVERSION
	21.	HEX-COERCE-STRING SCHEMA (string→validated)
	22.	HEX-COERCE-BUFFER SCHEMA (buffer→hex)
	23.	HEX-COERCE-ARRAYBUFFER SCHEMA
	24.	HEX-COERCE-TYPEDARRAY SCHEMA
	25.	HEX-COERCE-NUMBER SCHEMA (number→hex)
	26.	HEX-COERCE-BIGINT SCHEMA
	27.	HEX-COERCE-BYTEARRAY SCHEMA
	28.	HEX-COERCE-UTF8STRING SCHEMA (text→hex)
	29.	HEX-COERCE-JSON SCHEMA (base64/hex detection)
	30.	HEX-COERCE-AUTO-DETECT SCHEMA

⸻

✅ SECTION 4 — BINARY / BYTE INTEROPERABILITY
	31.	HEX-BYTE-ARRAY SCHEMA
	32.	HEX-BYTE-LENGTH SCHEMA
	33.	HEX-BYTE-COERCE SCHEMA (auto pad)
	34.	HEX-BYTE-COUNT SCHEMA
	35.	HEX-BYTE-MAP SCHEMA
	36.	HEX-BYTE-OFFSET SCHEMA
	37.	HEX-BYTE-CHUNK SCHEMA (split N bytes)
	38.	HEX-BYTE-BUFFER-VIEW SCHEMA
	39.	HEX-BYTE-ALIGNMENT SCHEMA
	40.	HEX-BYTE-ORDER-SCHEMA (LE/BE)

⸻

✅ SECTION 5 — NUMERIC REPRESENTATIONS
	41.	HEX-TO-INT SCHEMA
	42.	HEX-TO-FLOAT SCHEMA
	43.	HEX-TO-BIGINT SCHEMA
	44.	HEX-TO-DECIMAL-STRING SCHEMA
	45.	HEX-FROM-INT SCHEMA
	46.	HEX-FROM-FLOAT SCHEMA
	47.	HEX-FROM-BIGINT SCHEMA
	48.	HEX-ARITHMETIC-SAFE SCHEMA
	49.	HEX-NUMERIC-RANGE SCHEMA
	50.	HEX-NUMERIC-COERCE SCHEMA

⸻

✅ SECTION 6 — COLOR HEX FORMS
	51.	HEX-COLOR-3 SCHEMA (#abc)
	52.	HEX-COLOR-4 SCHEMA (#abcd rgba)
	53.	HEX-COLOR-6 SCHEMA (#aabbcc)
	54.	HEX-COLOR-8 SCHEMA (#aabbccdd)
	55.	HEX-COLOR-WITH-PREFIX SCHEMA
	56.	HEX-COLOR-WITHOUT-PREFIX SCHEMA
	57.	HEX-COLOR-SHORT-EXPAND SCHEMA (#abc→#aabbcc)
	58.	HEX-COLOR-NORMALIZE-CASE SCHEMA
	59.	HEX-COLOR-TO-RGB SCHEMA
	60.	HEX-COLOR-TO-RGBA SCHEMA
	61.	HEX-COLOR-TO-HSL SCHEMA
	62.	HEX-COLOR-TO-OKLCH SCHEMA
	63.	HEX-COLOR-VALIDATION SCHEMA
	64.	HEX-COLOR-COERCE SCHEMA
	65.	HEX-COLOR-CONTRAST SCHEMA
	66.	HEX-COLOR-ACCESSIBILITY SCHEMA
	67.	HEX-COLOR-THEME-TOKEN SCHEMA
	68.	HEX-COLOR-BRIGHTNESS SCHEMA
	69.	HEX-COLOR-SATURATION SCHEMA
	70.	HEX-COLOR-LIGHTNESS SCHEMA

⸻

✅ SECTION 7 — ENCODING / DECODING UTILITIES
	71.	HEX-ENCODE SCHEMA (bytes→hex)
	72.	HEX-DECODE SCHEMA (hex→bytes)
	73.	HEX-ENCODE-SAFE SCHEMA (no 0x)
	74.	HEX-DECODE-SAFE SCHEMA (validated)
	75.	HEX-ENCODE-URI-SAFE SCHEMA
	76.	HEX-DECODE-URI-SAFE SCHEMA
	77.	HEX-ESCAPE-STRING SCHEMA (\xNN)
	78.	HEX-UNESCAPE-STRING SCHEMA
	79.	HEX-DETECT-FORMAT SCHEMA (hex/base64/uuid)
	80.	HEX-CONVERT-AUTO SCHEMA

⸻

✅ SECTION 8 — CRYPTOGRAPHIC HASHES
	81.	HEX-SHA1 SCHEMA (40 chars)
	82.	HEX-SHA224 SCHEMA (56 chars)
	83.	HEX-SHA256 SCHEMA (64 chars)
	84.	HEX-SHA384 SCHEMA (96 chars)
	85.	HEX-SHA512 SCHEMA (128 chars)
	86.	HEX-MD5 SCHEMA (32 chars)
	87.	HEX-BLAKE2B SCHEMA
	88.	HEX-BLAKE3 SCHEMA
	89.	HEX-RIPEMD160 SCHEMA
	90.	HEX-CRC32 SCHEMA
	91.	HEX-HASH-GENERIC SCHEMA (length-bound)
	92.	HEX-HASH-COERCE SCHEMA
	93.	HEX-HASH-VERIFY SCHEMA
	94.	HEX-HMAC-KEY SCHEMA
	95.	HEX-SIGNATURE SCHEMA
	96.	HEX-DIGEST-PAIR SCHEMA (algo + hex)
	97.	HEX-CHECKSUM SCHEMA
	98.	HEX-INTEGRITY-TAG SCHEMA
	99.	HEX-CSRF-TOKEN SCHEMA
	100.	HEX-SECURITY-TOKEN SCHEMA

⸻

✅ SECTION 9 — IDENTIFIER & ADDRESS TYPES
	101.	HEX-UUID-DERIVED SCHEMA
	102.	HEX-ULID-DERIVED SCHEMA
	103.	HEX-OBJECT-ID SCHEMA (Mongo 24-char)
	104.	HEX-CUID-DERIVED SCHEMA
	105.	HEX-RESOURCE-ID SCHEMA
	106.	HEX-TRANSACTION-ID SCHEMA
	107.	HEX-SESSION-ID SCHEMA
	108.	HEX-REQUEST-ID SCHEMA
	109.	HEX-TRACE-ID SCHEMA
	110.	HEX-SPAN-ID SCHEMA
	111.	HEX-BLOCKCHAIN-ADDRESS SCHEMA (0x…)
	112.	HEX-ETH-ADDRESS-SCHEMA (40 chars)
	113.	HEX-BITCOIN-HASH160-SCHEMA
	114.	HEX-TX-HASH-SCHEMA
	115.	HEX-CONTRACT-ADDRESS SCHEMA
	116.	HEX-PUBLIC-KEY SCHEMA
	117.	HEX-PRIVATE-KEY SCHEMA
	118.	HEX-KEYPAIR-STRUCT SCHEMA
	119.	HEX-KEY-DERIVATION-SCHEMA
	120.	HEX-CHECKSUM-ADDRESS SCHEMA

⸻

✅ SECTION 10 — FILE / BINARY REPRESENTATION
	121.	HEX-FILE-HASH-SCHEMA
	122.	HEX-FILE-SIGNATURE-SCHEMA (magic bytes)
	123.	HEX-FILE-HEADER-SCHEMA
	124.	HEX-FILE-FOOTER-SCHEMA
	125.	HEX-FILE-CHECKSUM-SCHEMA
	126.	HEX-FILE-CONTENT-SCHEMA
	127.	HEX-FILE-PATCH-SCHEMA
	128.	HEX-FILE-OFFSET-SCHEMA
	129.	HEX-FILE-BLOCK-SCHEMA
	130.	HEX-FILE-DELTA-SCHEMA
	131.	HEX-FILE-CHUNK-SCHEMA
	132.	HEX-FILE-MERKLE-NODE SCHEMA
	133.	HEX-FILE-HASH-TREE SCHEMA
	134.	HEX-FILE-SIGNATURE-VERIFY SCHEMA
	135.	HEX-FILE-DIGEST-VERIFY SCHEMA
	136.	HEX-FILE-ENCODING-SCHEMA
	137.	HEX-FILE-METADATA-SCHEMA
	138.	HEX-FILE-RESOURCE-MAP SCHEMA
	139.	HEX-FILE-CACHE-KEY SCHEMA
	140.	HEX-FILE-ASSET-ID SCHEMA

⸻

✅ SECTION 11 — SECURITY / SANITIZATION
	141.	HEX-SAFE-INPUT-SCHEMA (no non-hex chars)
	142.	HEX-SAFE-OUTPUT-SCHEMA (sanitized)
	143.	HEX-SAFE-STRING-SCHEMA
	144.	HEX-SAFE-LENGTH-SCHEMA
	145.	HEX-SAFE-TOKEN-SCHEMA
	146.	HEX-SAFE-URL-PARAM-SCHEMA
	147.	HEX-SAFE-QUERY-SCHEMA
	148.	HEX-SAFE-HEADER-SCHEMA
	149.	HEX-SAFE-COOKIE-SCHEMA
	150.	HEX-SAFE-STORAGE-SCHEMA
	151.	HEX-SAFE-ENV-VAR-SCHEMA
	152.	HEX-SAFE-FILE-NAME-SCHEMA
	153.	HEX-SAFE-CSP-ATTRIBUTE-SCHEMA
	154.	HEX-SAFE-NO-CONTROL-CHARS-SCHEMA
	155.	HEX-SAFE-NO-NONPRINTABLE-SCHEMA
	156.	HEX-SAFE-ALPHABET-STRICT-SCHEMA
	157.	HEX-SAFE-NO-XSS-SCHEMA
	158.	HEX-SAFE-NO-INJECTION-SCHEMA
	159.	HEX-SAFE-INTEGRITY-SCHEMA
	160.	HEX-SAFE-CROSS-CONTEXT-SCHEMA

⸻

✅ SECTION 12 — ADVANCED / DERIVED TYPES
	161.	HEX-BITFIELD-SCHEMA
	162.	HEX-BITMASK-SCHEMA
	163.	HEX-FLAGS-SCHEMA
	164.	HEX-COLOR-PALETTE-ARRAY SCHEMA
	165.	HEX-COLOR-MAP-SCHEMA
	166.	HEX-COLOR-DICTIONARY SCHEMA
	167.	HEX-GENERIC-KEY-SCHEMA
	168.	HEX-RESOURCE-TAG-SCHEMA
	169.	HEX-TRACE-SPAN-PAIR SCHEMA
	170.	HEX-TX-BLOCK-PAIR SCHEMA
	171.	HEX-PAYLOAD-STRUCT SCHEMA
	172.	HEX-HEADER-STRUCT SCHEMA
	173.	HEX-FOOTER-STRUCT SCHEMA
	174.	HEX-CHUNK-STRUCT SCHEMA
	175.	HEX-VALIDATION-REPORT SCHEMA
	176.	HEX-PARSE-RESULT-SCHEMA
	177.	HEX-COMPARISON-SCHEMA
	178.	HEX-DIFF-SCHEMA
	179.	HEX-DELTA-SCHEMA
	180.	HEX-NORMALIZED-CANONICAL SCHEMA