✅ SECTION 1 — CORE SPEC METHOD SCHEMAS (RFC 7231 / 9110)
	1.	HTTP-METHOD-GET SCHEMA
	2.	HTTP-METHOD-POST SCHEMA
	3.	HTTP-METHOD-PUT SCHEMA
	4.	HTTP-METHOD-DELETE SCHEMA
	5.	HTTP-METHOD-PATCH SCHEMA (RFC 5789)
	6.	HTTP-METHOD-HEAD SCHEMA
	7.	HTTP-METHOD-OPTIONS SCHEMA
	8.	HTTP-METHOD-TRACE SCHEMA
	9.	HTTP-METHOD-CONNECT SCHEMA
	10.	HTTP-METHOD-STANDARD-ENUM SCHEMA (complete literal union)

⸻

✅ SECTION 2 — EXTENDED / ENTERPRISE METHODS
	11.	HTTP-METHOD-COPY SCHEMA (WebDAV / Cloud Storage)
	12.	HTTP-METHOD-MOVE SCHEMA
	13.	HTTP-METHOD-PROPFIND SCHEMA
	14.	HTTP-METHOD-PROPPATCH SCHEMA
	15.	HTTP-METHOD-MKCOL SCHEMA
	16.	HTTP-METHOD-LOCK SCHEMA
	17.	HTTP-METHOD-UNLOCK SCHEMA
	18.	HTTP-METHOD-SEARCH SCHEMA (WebDAV, Elasticsearch, Solr)
	19.	HTTP-METHOD-REPORT SCHEMA (CalDAV/CardDAV)
	20.	HTTP-METHOD-MKCALENDAR SCHEMA
	21.	HTTP-METHOD-BIND SCHEMA (WebDAV RFC 5842)
	22.	HTTP-METHOD-REBIND SCHEMA
	23.	HTTP-METHOD-UNBIND SCHEMA
	24.	HTTP-METHOD-ACL SCHEMA (WebDAV Access Control)
	25.	HTTP-METHOD-ORDERPATCH SCHEMA (RFC 3648)
	26.	HTTP-METHOD-LINK SCHEMA (RFC 2068, revived use)
	27.	HTTP-METHOD-UNLINK SCHEMA (RFC 2068 / GraphQL extensions)
	28.	HTTP-METHOD-PURGE SCHEMA (Varnish / CDN Cache Invalidate)
	29.	HTTP-METHOD-VIEW SCHEMA (Custom read-only REST)
	30.	HTTP-METHOD-LIST SCHEMA (Custom collection introspection)

⸻

✅ SECTION 3 — GRAPHQL / EDGE / SPECIALIZED METHODS
	31.	HTTP-METHOD-GRAPHQL-QUERY SCHEMA (often POST)
	32.	HTTP-METHOD-GRAPHQL-MUTATION SCHEMA
	33.	HTTP-METHOD-GRAPHQL-SUBSCRIPTION SCHEMA (usually WS/POST)
	34.	HTTP-METHOD-BATCH SCHEMA (Google Batch API)
	35.	HTTP-METHOD-FETCH SCHEMA (Edge/Workers Fetch proxy)
	36.	HTTP-METHOD-PING SCHEMA (health-check verbs)
	37.	HTTP-METHOD-ECHO SCHEMA (test or diagnostic)
	38.	HTTP-METHOD-SUBSCRIBE SCHEMA (Server-Sent Events / Webhook registrations)
	39.	HTTP-METHOD-NOTIFY SCHEMA (SIP / Webhook delivery)
	40.	HTTP-METHOD-MERGE SCHEMA (Microsoft Graph / Delta updates)

⸻

✅ SECTION 4 — CUSTOM / POLICY / CONTROL METHODS
	41.	HTTP-METHOD-EXEC SCHEMA (Remote procedure execution)
	42.	HTTP-METHOD-INVOKE SCHEMA (Lambda-style call)
	43.	HTTP-METHOD-DISPATCH SCHEMA (Event-bus routing)
	44.	HTTP-METHOD-RELOAD SCHEMA (Config refresh)
	45.	HTTP-METHOD-VALIDATE SCHEMA (Schema check / lint)
	46.	HTTP-METHOD-REINDEX SCHEMA (Search cluster ops)
	47.	HTTP-METHOD-ROLLBACK SCHEMA (Transaction control)
	48.	HTTP-METHOD-COMMIT SCHEMA
	49.	HTTP-METHOD-UPSERT SCHEMA
	50.	HTTP-METHOD-DIFF SCHEMA (Patch preview ops)

⸻

✅ SECTION 5 — UTILITY / MIXED VALIDATION SCHEMAS
	51.	HTTP-METHOD-COERCE SCHEMA (case-insensitive → upper canonical)
	52.	HTTP-METHOD-CANONICAL SCHEMA (standardized enum output)
	53.	HTTP-METHOD-ALLOW-LIST SCHEMA (approved verbs array)
	54.	HTTP-METHOD-DENY-LIST SCHEMA
	55.	HTTP-METHOD-POLICY-SCHEMA (read/write/admin access)
	56.	HTTP-METHOD-SAFE-FLAG-SCHEMA (idempotent = true/false)
	57.	HTTP-METHOD-IDEMPOTENT-FLAG-SCHEMA
	58.	HTTP-METHOD-CACHEABLE-FLAG-SCHEMA
	59.	HTTP-METHOD-BODY-ALLOWED-FLAG-SCHEMA
	60.	HTTP-METHOD-REQUIRES-AUTH-FLAG-SCHEMA
	61.	HTTP-METHOD-MUTATION-FLAG-SCHEMA (for security auditing)
	62.	HTTP-METHOD-ALLOWED-MATRIX-SCHEMA (resource → methods)
	63.	HTTP-METHOD-VALIDATION-RESULT-SCHEMA (status, reason)
	64.	HTTP-METHOD-FIELD-SCHEMA ({description, value: method})

⸻

✅ SECTION 6 — ENTERPRISE ANALYTICS / MONITORING SCHEMAS
	65.	HTTP-METHOD-METRIC-SCHEMA (request count by method)
	66.	HTTP-METHOD-RATE-LIMIT-SCHEMA (per-verb quotas)
	67.	HTTP-METHOD-LATENCY-SCHEMA (per-verb average)
	68.	HTTP-METHOD-ERROR-RATE-SCHEMA
	69.	HTTP-METHOD-THROUGHPUT-SCHEMA
	70.	HTTP-METHOD-AUDIT-EVENT-SCHEMA (method usage logs)
	71.	HTTP-METHOD-HEATMAP-SCHEMA (popularity distribution)
	72.	HTTP-METHOD-SUMMARY-SCHEMA (per-service breakdown)