✅ SECTION 1 — CORE MAC ADDRESS SCHEMAS
	1.	MAC-ADDRESS-STRICT SCHEMA (exact 6-byte / 12-hex format)
	2.	MAC-ADDRESS-CANONICAL SCHEMA (normalized AA:BB:CC:DD:EE:FF)
	3.	MAC-ADDRESS-LOWERCASE SCHEMA (aa:bb:cc:dd:ee:ff)
	4.	MAC-ADDRESS-UPPERCASE SCHEMA (AA:BB:CC:DD:EE:FF)
	5.	MAC-ADDRESS-NO-DELIMITER SCHEMA (AABBCCDDEEFF)
	6.	MAC-ADDRESS-WITH-HYPHEN SCHEMA (AA-BB-CC-DD-EE-FF)
	7.	MAC-ADDRESS-WITH-COLON SCHEMA (AA:BB:CC:DD:EE:FF)
	8.	MAC-ADDRESS-WITH-DOT SCHEMA (AABB.CCDD.EEFF)
	9.	MAC-ADDRESS-SHORT-FORM SCHEMA (EUI-48 compressed notation)
	10.	MAC-ADDRESS-COERCE SCHEMA (auto-normalizes to canonical)
	11.	MAC-ADDRESS-VALIDATE SCHEMA (regex-based strict validation)
	12.	MAC-ADDRESS-FIELD SCHEMA ({ description, value })

⸻

✅ SECTION 2 — EXTENDED FORMATS (EUI / IEEE)
13. MAC-ADDRESS-EUI48 SCHEMA (48-bit standard form)
14. MAC-ADDRESS-EUI64 SCHEMA (64-bit extended form)
15. MAC-ADDRESS-EUI64-EXPAND SCHEMA (EUI-48 → EUI-64)
16. MAC-ADDRESS-EUI64-COMPRESS SCHEMA (EUI-64 → EUI-48)
17. MAC-ADDRESS-EUI-CONVERT SCHEMA (bidirectional utility)
18. MAC-ADDRESS-EUI-COERCE SCHEMA (auto detect + normalize)
19. MAC-ADDRESS-EUI-VALIDATE SCHEMA (IEEE prefix rules)
20. MAC-ADDRESS-EUI-FIELD SCHEMA ({ description, eui64 })

⸻

✅ SECTION 3 — VALIDATION / NORMALIZATION LAYERS
21. MAC-ADDRESS-OPTIONAL SCHEMA (undefined allowed)
22. MAC-ADDRESS-NULLABLE SCHEMA (null allowed)
23. MAC-ADDRESS-PRESENT SCHEMA (must exist)
24. MAC-ADDRESS-ARRAY SCHEMA (list of MACs)
25. MAC-ADDRESS-RECORD SCHEMA (map<string, MAC>)
26. MAC-ADDRESS-ENUM SCHEMA (allowed literal set)
27. MAC-ADDRESS-UNIQUE-ARRAY SCHEMA (deduplicated)
28. MAC-ADDRESS-NORMALIZED SCHEMA (case + delimiter canonicalization)
29. MAC-ADDRESS-STRICT-HEX-PAIR SCHEMA (every pair validated)
30. MAC-ADDRESS-NO-MULTICAST SCHEMA (unicast only)
31. MAC-ADDRESS-NO-LOCAL SCHEMA (globally unique only)
32. MAC-ADDRESS-GLOBAL-SCHEMA (OUI bit check: 0)
33. MAC-ADDRESS-LOCAL-SCHEMA (OUI bit check: 1)

⸻

✅ SECTION 4 — NETWORK / DEVICE CONTEXT SCHEMAS
34. MAC-ADDRESS-DEVICE-ID SCHEMA
35. MAC-ADDRESS-NIC-IDENTIFIER SCHEMA
36. MAC-ADDRESS-INTERFACE-SCHEMA
37. MAC-ADDRESS-BRIDGE-SCHEMA
38. MAC-ADDRESS-ROUTER-SCHEMA
39. MAC-ADDRESS-ACCESS-POINT SCHEMA
40. MAC-ADDRESS-VIRTUAL-INTERFACE SCHEMA
41. MAC-ADDRESS-CONTAINER-NETWORK SCHEMA
42. MAC-ADDRESS-VLAN-ASSIGNMENT SCHEMA
43. MAC-ADDRESS-WIFI-CLIENT SCHEMA
44. MAC-ADDRESS-IOT-DEVICE SCHEMA
45. MAC-ADDRESS-PHYSICAL-PORT SCHEMA
46. MAC-ADDRESS-VIRTUAL-PORT SCHEMA
47. MAC-ADDRESS-DEVICE-MAP SCHEMA (MAC → metadata)
48. MAC-ADDRESS-DEVICE-PAIR SCHEMA (src/dst structure)

⸻

✅ SECTION 5 — SECURITY / AUDIT / TELEMETRY SCHEMAS
49. MAC-ADDRESS-WHITELIST SCHEMA
50. MAC-ADDRESS-BLACKLIST SCHEMA
51. MAC-ADDRESS-ALLOWLIST SCHEMA
52. MAC-ADDRESS-DENYLIST SCHEMA
53. MAC-ADDRESS-AUDIT-ENTRY SCHEMA (timestamped validation)
54. MAC-ADDRESS-LOG-EVENT SCHEMA ({ time, mac, action })
55. MAC-ADDRESS-ACCESS-HISTORY SCHEMA (connection log)
56. MAC-ADDRESS-AUTHORIZED-DEVICE SCHEMA
57. MAC-ADDRESS-UNAUTHORIZED-DEVICE SCHEMA
58. MAC-ADDRESS-SECURITY-FLAG SCHEMA (bit-encoded risk levels)
59. MAC-ADDRESS-DETECTION-SCHEMA (new MAC seen event)
60. MAC-ADDRESS-TELEMETRY-SCHEMA ({ mac, signal, ts })

⸻

✅ SECTION 6 — ENTERPRISE / CLOUD / ANALYTICS EXTENSIONS
61. MAC-ADDRESS-ANALYTICS SCHEMA (usage frequency, first_seen, last_seen)
62. MAC-ADDRESS-STATS-SCHEMA (count, distinct, unique ratio)
63. MAC-ADDRESS-DEVICE-SESSION SCHEMA
64. MAC-ADDRESS-EDGE-COLLECTOR SCHEMA (Cloudflare worker normalization)
65. MAC-ADDRESS-IOT-STREAM SCHEMA (edge telemetry ingest)
66. MAC-ADDRESS-ANONYMIZED SCHEMA (hashed or masked form)
67. MAC-ADDRESS-HASHED SCHEMA (SHA-256 normalization)
68. MAC-ADDRESS-MASKED SCHEMA (AA:BB:**:**:**:**)
69. MAC-ADDRESS-PRIVACY-PRESERVED SCHEMA (de-identified pipeline)
70. MAC-ADDRESS-PSEUDONYMIZED SCHEMA (stable hash key)
71. MAC-ADDRESS-LOOKUP-SCHEMA (OUI → vendor)
72. MAC-ADDRESS-VENDOR-METADATA SCHEMA (manufacturer data)
73. MAC-ADDRESS-VENDOR-VALIDATED SCHEMA (lookup-verified)
74. MAC-ADDRESS-ORGANIZATIONAL-UNIT SCHEMA (OUI prefix validation)
75. MAC-ADDRESS-TELEMETRY-FIELD SCHEMA ({ description, mac, timestamp })
76. MAC-ADDRESS-ANALYTICS-V2 SCHEMA (aggregated + vendor enriched)

⸻

✅ SECTION 7 — RESEARCH / SIMULATION / TESTING SCHEMAS
77. MAC-ADDRESS-RANDOM-GENERATOR SCHEMA (test-only)
78. MAC-ADDRESS-MOCK-DATA SCHEMA (factory/seeded generation)
79. MAC-ADDRESS-FUZZED SCHEMA (randomized for QA)
80. MAC-ADDRESS-COLLISION-TEST SCHEMA
81. MAC-ADDRESS-DUPLICATE-DETECTOR SCHEMA
82. MAC-ADDRESS-PATTERN-ANALYSIS SCHEMA
83. MAC-ADDRESS-GROUP-BROADCAST SCHEMA (multicast modeling)
84. MAC-ADDRESS-EMULATED-SCHEMA (virtual lab device identity)
85. MAC-ADDRESS-VALIDATION-STATS SCHEMA (pass/fail counts)
86. MAC-ADDRESS-COMPLIANCE-CHECK SCHEMA (IEEE rule conformance)
87. MAC-ADDRESS-ANALYZER-SCHEMA (frequency, distribution, OUI mix)
88. MAC-ADDRESS-RESOLVER-SCHEMA (reverse lookup API output)

⸻

✅ SECTION 8 — UTILITY / FIELD / VERSIONED WRAPPERS
89. MAC-ADDRESS-DEFAULT SCHEMA (if missing → undefined)
90. MAC-ADDRESS-NULLABLE-COERCE SCHEMA (empty → undefined)
91. MAC-ADDRESS-FIELD-V2 SCHEMA ({ description, mac, canonical })
92. MAC-ADDRESS-CANONICAL-V2 SCHEMA (normalized + vendor + flags)
93. MAC-ADDRESS-ARRAY-FIELD SCHEMA
94. MAC-ADDRESS-RECORD-FIELD SCHEMA
95. MAC-ADDRESS-MAP-ARRAY SCHEMA
96. MAC-ADDRESS-MULTI-UNIT-SCHEMA (MAC + EUI-48/64 union)
97. MAC-ADDRESS-METADATA-SCHEMA (with vendor, timestamp, locality)
98. MAC-ADDRESS-VERSIONED-SCHEMA (v1/v2 backward compatibility)
99. MAC-ADDRESS-FACTORY-SCHEMA (create/validate pipeline)
100. MAC-ADDRESS-COLLECTOR-SCHEMA (collector normalization entrypoint)