✅ SECTION 1 — BASE MEASUREMENT SCHEMAS (SI UNITS)
	1.	MEASUREMENT-LENGTH SCHEMA (m, cm, mm)
	2.	MEASUREMENT-MASS SCHEMA (kg, g, mg)
	3.	MEASUREMENT-TIME SCHEMA (s, ms, μs)
	4.	MEASUREMENT-ELECTRIC-CURRENT SCHEMA (A)
	5.	MEASUREMENT-TEMPERATURE SCHEMA (K, °C, °F)
	6.	MEASUREMENT-AMOUNT-OF-SUBSTANCE SCHEMA (mol)
	7.	MEASUREMENT-LUMINOUS-INTENSITY SCHEMA (cd)
	8.	MEASUREMENT-ANGLE SCHEMA (rad, deg, grad)

⸻

✅ SECTION 2 — DERIVED PHYSICAL MEASUREMENT SCHEMAS
9. MEASUREMENT-AREA SCHEMA (m², ft²)
10. MEASUREMENT-VOLUME SCHEMA (m³, L, mL)
11. MEASUREMENT-DENSITY SCHEMA (kg/m³)
12. MEASUREMENT-SPEED SCHEMA (m/s, km/h, mph)
13. MEASUREMENT-ACCELERATION SCHEMA (m/s², g)
14. MEASUREMENT-FORCE SCHEMA (N, lbf)
15. MEASUREMENT-PRESSURE SCHEMA (Pa, bar, psi)
16. MEASUREMENT-ENERGY SCHEMA (J, kWh, cal)
17. MEASUREMENT-POWER SCHEMA (W, kW, hp)
18. MEASUREMENT-MOMENTUM SCHEMA (kg·m/s)
19. MEASUREMENT-TORQUE SCHEMA (N·m)
20. MEASUREMENT-WORK SCHEMA (J)
21. MEASUREMENT-HEAT-FLUX SCHEMA (W/m²)
22. MEASUREMENT-VISCOSITY SCHEMA (Pa·s, cP)
23. MEASUREMENT-FREQUENCY SCHEMA (Hz, kHz, GHz)
24. MEASUREMENT-WAVELENGTH SCHEMA (nm, μm)
25. MEASUREMENT-CHARGE SCHEMA (C)
26. MEASUREMENT-VOLTAGE SCHEMA (V)
27. MEASUREMENT-RESISTANCE SCHEMA (Ω)
28. MEASUREMENT-CAPACITANCE SCHEMA (F)
29. MEASUREMENT-INDUCTANCE SCHEMA (H)
30. MEASUREMENT-MAGNETIC-FLUX SCHEMA (Wb)
31. MEASUREMENT-MAGNETIC-FLUX-DENSITY SCHEMA (T)
32. MEASUREMENT-LUMINANCE SCHEMA (cd/m²)
33. MEASUREMENT-ILLUMINANCE SCHEMA (lx)
34. MEASUREMENT-RADIANCE SCHEMA (W/sr·m²)
35. MEASUREMENT-SOUND-LEVEL SCHEMA (dB SPL)

⸻

✅ SECTION 3 — THERMODYNAMIC / ENVIRONMENTAL MEASUREMENTS
36. MEASUREMENT-THERMAL-CONDUCTIVITY SCHEMA
37. MEASUREMENT-SPECIFIC-HEAT SCHEMA
38. MEASUREMENT-RELATIVE-HUMIDITY SCHEMA (%)
39. MEASUREMENT-AIR-PRESSURE SCHEMA (hPa, atm)
40. MEASUREMENT-WIND-SPEED SCHEMA (m/s, knot)
41. MEASUREMENT-RAINFALL SCHEMA (mm)
42. MEASUREMENT-SOLAR-RADIATION SCHEMA (W/m²)
43. MEASUREMENT-UV-INDEX SCHEMA
44. MEASUREMENT-DEW-POINT SCHEMA (°C)
45. MEASUREMENT-VISIBILITY SCHEMA (km, mi)

⸻

✅ SECTION 4 — CHEMICAL / BIOLOGICAL / MEDICAL MEASUREMENTS
46. MEASUREMENT-PH SCHEMA
47. MEASUREMENT-CONCENTRATION SCHEMA (mg/L, ppm, %)
48. MEASUREMENT-MOLARITY SCHEMA (mol/L)
49. MEASUREMENT-MASS-FRACTION SCHEMA (%)
50. MEASUREMENT-BLOOD-PRESSURE SCHEMA (mmHg)
51. MEASUREMENT-BLOOD-SUGAR SCHEMA (mg/dL, mmol/L)
52. MEASUREMENT-BLOOD-OXYGEN SCHEMA (%)
53. MEASUREMENT-HEART-RATE SCHEMA (bpm)
54. MEASUREMENT-BODY-TEMPERATURE SCHEMA (°C)
55. MEASUREMENT-BODY-MASS-INDEX SCHEMA (BMI)
56. MEASUREMENT-RESPIRATORY-RATE SCHEMA (breaths/min)
57. MEASUREMENT-VITALS-PANEL SCHEMA (grouped)
58. MEASUREMENT-CELL-COUNT SCHEMA (cells/μL)
59. MEASUREMENT-DOSAGE SCHEMA (mg/kg)

⸻

✅ SECTION 5 — COMPUTING / DIGITAL MEASUREMENTS
60. MEASUREMENT-DATA-SIZE SCHEMA (B, KB, MB, GB, TB)
61. MEASUREMENT-DATA-RATE SCHEMA (bps, Mbps, Gbps)
62. MEASUREMENT-LATENCY SCHEMA (ms)
63. MEASUREMENT-CPU-USAGE SCHEMA (%)
64. MEASUREMENT-MEMORY-USAGE SCHEMA (%)
65. MEASUREMENT-DISK-IO SCHEMA (IOPS)
66. MEASUREMENT-NETWORK-THROUGHPUT SCHEMA (MB/s)
67. MEASUREMENT-REQUEST-RATE SCHEMA (req/s)
68. MEASUREMENT-ERROR-RATE SCHEMA (%)
69. MEASUREMENT-UPTIME SCHEMA (s, %)

⸻

✅ SECTION 6 — FINANCIAL / ACCOUNTING MEASUREMENTS
70. MEASUREMENT-CURRENCY-AMOUNT SCHEMA (USD, CAD, EUR)
71. MEASUREMENT-EXCHANGE-RATE SCHEMA
72. MEASUREMENT-INTEREST-RATE SCHEMA (%)
73. MEASUREMENT-INFLATION-RATE SCHEMA (%)
74. MEASUREMENT-YIELD SCHEMA (%)
75. MEASUREMENT-PRICE-INDEX SCHEMA
76. MEASUREMENT-ACCOUNT-BALANCE SCHEMA
77. MEASUREMENT-CREDIT-SCORE SCHEMA
78. MEASUREMENT-MONETARY-FLOW-RATE SCHEMA (currency / time)

⸻

✅ SECTION 7 — MANUFACTURING / INDUSTRIAL / ENGINEERING
79. MEASUREMENT-TOLERANCE SCHEMA (±mm)
80. MEASUREMENT-DIMENSIONAL-ACCURACY SCHEMA (%)
81. MEASUREMENT-ROTATIONAL-SPEED SCHEMA (rpm)
82. MEASUREMENT-FLOW-RATE SCHEMA (L/s, m³/h)
83. MEASUREMENT-VOLUMETRIC-FLOW SCHEMA (m³/s)
84. MEASUREMENT-MASS-FLOW SCHEMA (kg/s)
85. MEASUREMENT-LINEAR-EXPANSION SCHEMA (ΔL/L per °C)
86. MEASUREMENT-SURFACE-ROUGHNESS SCHEMA (Ra μm)
87. MEASUREMENT-STRESS SCHEMA (Pa)
88. MEASUREMENT-STRAIN SCHEMA (ΔL/L)
89. MEASUREMENT-EFFICIENCY SCHEMA (%)

⸻

✅ SECTION 8 — LIGHT / OPTICS / RADIATION MEASUREMENTS
90. MEASUREMENT-REFRACTIVE-INDEX SCHEMA
91. MEASUREMENT-OPTICAL-DENSITY SCHEMA
92. MEASUREMENT-RADIANT-FLUX SCHEMA (W)
93. MEASUREMENT-RADIANT-INTENSITY SCHEMA (W/sr)
94. MEASUREMENT-IRRADIANCE SCHEMA (W/m²)
95. MEASUREMENT-RADIANT-EXPOSURE SCHEMA (J/m²)
96. MEASUREMENT-RADIOACTIVITY SCHEMA (Bq, Ci)
97. MEASUREMENT-DOSE-EQUIVALENT SCHEMA (Sv)
98. MEASUREMENT-ALBEDO SCHEMA (%)

⸻

✅ SECTION 9 — GEO / ASTRONOMY / SPATIAL MEASUREMENTS
99. MEASUREMENT-ALTITUDE SCHEMA (m, ft)
100. MEASUREMENT-ELEVATION SCHEMA
101. MEASUREMENT-DEPTH SCHEMA (m)
102. MEASUREMENT-LATITUDE SCHEMA (deg)
103. MEASUREMENT-LONGITUDE SCHEMA (deg)
104. MEASUREMENT-DISTANCE SCHEMA (m, km, mi)
105. MEASUREMENT-ORBITAL-RADIUS SCHEMA
106. MEASUREMENT-GRAVITATIONAL-ACCELERATION SCHEMA (m/s²)
107. MEASUREMENT-PLANETARY-MASS SCHEMA
108. MEASUREMENT-ASTRONOMICAL-DISTANCE SCHEMA (AU, ly, pc)

⸻

✅ SECTION 10 — UTILITY / ABSTRACTION / MATH SCHEMAS
109. MEASUREMENT-UNIT-VECTOR SCHEMA
110. MEASUREMENT-DIMENSIONLESS-RATIO SCHEMA (%)
111. MEASUREMENT-UNCERTAINTY SCHEMA (±value + confidence)
112. MEASUREMENT-CONFIDENCE-INTERVAL SCHEMA
113. MEASUREMENT-STATISTICAL-ERROR SCHEMA
114. MEASUREMENT-SCALE-CONVERSION SCHEMA (unit ↔ unit)
115. MEASUREMENT-UNIT-NORMALIZATION SCHEMA (SI canonical)
116. MEASUREMENT-AGGREGATED-VALUE SCHEMA (mean, median, stdev)
117. MEASUREMENT-TIME-SERIES SCHEMA (value + timestamp)
118. MEASUREMENT-METADATA-FIELD SCHEMA ({ unit, precision, source })
119. MEASUREMENT-FIELD-FACTORY SCHEMA (createMeasurement(unit))

⸻

✅ SECTION 11 — UX / DATA / DISPLAY SCHEMAS
120. MEASUREMENT-FORMATTED-VALUE SCHEMA (“12 kg”)
121. MEASUREMENT-UNIT-LABEL SCHEMA (“kg”, “cm”, “°C”)
122. MEASUREMENT-SI-PREFIX SCHEMA (y, z, a, f, p, n, μ, m, c, d, da, h, k, M, G, T, P, E, Z, Y)
123. MEASUREMENT-UNIT-COERCE SCHEMA (any → canonical unit)
124. MEASUREMENT-DISPLAY-PRECISION SCHEMA (decimals)
125. MEASUREMENT-USER-PREFERENCE-SCHEMA (metric ↔ imperial)

⸻

✅ SECTION 12 — ENTERPRISE / OBSERVABILITY SCHEMAS
126. MEASUREMENT-METRIC-NAMESPACE SCHEMA (service, region)
127. MEASUREMENT-METRIC-NAME SCHEMA
128. MEASUREMENT-METRIC-TYPE SCHEMA (counter, gauge, histogram)
129. MEASUREMENT-METRIC-LABELS SCHEMA
130. MEASUREMENT-METRIC-SNAPSHOT SCHEMA
131. MEASUREMENT-PROMETHEUS-METRIC SCHEMA
132. MEASUREMENT-CLOUDWATCH-METRIC SCHEMA
133. MEASUREMENT-GRAFANA-TIMESERIES SCHEMA
134. MEASUREMENT-ALERT-THRESHOLD SCHEMA
135. MEASUREMENT-ANOMALY-DETECTION SCHEMA
136. MEASUREMENT-SLO SCHEMA (target / window)
137. MEASUREMENT-SLI SCHEMA (value / goal)
138. MEASUREMENT-SLA SCHEMA (contractual metric)

⸻
