✅ SECTION 1 — CORE FILESYSTEM PATH SCHEMAS
	1.	PATH-ABSOLUTE SCHEMA
	2.	PATH-RELATIVE SCHEMA
	3.	PATH-ROOTED SCHEMA
	4.	PATH-DIRECTORY SCHEMA
	5.	PATH-FILE SCHEMA
	6.	PATH-FILE-OR-DIR SCHEMA
	7.	PATH-NORMALIZED SCHEMA
	8.	PATH-RESOLVED SCHEMA
	9.	PATH-PORTABLE SCHEMA (cross-OS safe)
	10.	PATH-SAFE-CHARACTERS SCHEMA
	11.	PATH-WITHOUT-RESERVED-CHARS SCHEMA
	12.	PATH-WITHOUT-ILLEGAL-SEQUENCES SCHEMA
	13.	PATH-WITHOUT-DOTDOT SCHEMA
	14.	PATH-CANONICAL SCHEMA (resolves ., ..)
	15.	PATH-COERCE-STRING SCHEMA
	16.	PATH-COERCE-URL-TO-FS SCHEMA
	17.	PATH-STRICT-STRING SCHEMA
	18.	PATH-NON-EMPTY SCHEMA
	19.	PATH-EXISTS SCHEMA (filesystem check)
	20.	PATH-NONEXISTENT SCHEMA (must not exist)
	21.	PATH-SAFE-LENGTH SCHEMA
	22.	PATH-MAX-DEPTH SCHEMA
	23.	PATH-MIN-DEPTH SCHEMA

⸻

✅ SECTION 2 — OS-SPECIFIC PATH SCHEMAS
	24.	PATH-WINDOWS SCHEMA
	25.	PATH-WINDOWS-ABSOLUTE SCHEMA
	26.	PATH-WINDOWS-RELATIVE SCHEMA
	27.	PATH-WINDOWS-UNC SCHEMA (\\server\share)
	28.	PATH-WINDOWS-DRIVE-LETTER SCHEMA
	29.	PATH-WINDOWS-LONGPATH SCHEMA (\\?\)
	30.	PATH-WINDOWS-SHORTNAME SCHEMA (8.3)
	31.	PATH-POSIX SCHEMA
	32.	PATH-POSIX-ABSOLUTE SCHEMA
	33.	PATH-POSIX-RELATIVE SCHEMA
	34.	PATH-LINUX-FHS SCHEMA (FHS compliance)
	35.	PATH-MACOS-VFS SCHEMA
	36.	PATH-BSD-PATH SCHEMA
	37.	PATH-ANDROID-FS SCHEMA
	38.	PATH-IOS-FS SCHEMA

⸻

✅ SECTION 3 — COMPONENT-LEVEL PATH SCHEMAS
	39.	PATH-FILENAME SCHEMA
	40.	PATH-BASENAME SCHEMA
	41.	PATH-EXTENSION SCHEMA
	42.	PATH-EXTENSION-ALLOWED SCHEMA
	43.	PATH-DIRECTORYNAME SCHEMA
	44.	PATH-PATHSEGMENT SCHEMA
	45.	PATH-PATHSEGMENT-SAFE SCHEMA
	46.	PATH-NUMERIC-SEGMENT SCHEMA
	47.	PATH-ALPHANUMERIC-SEGMENT SCHEMA
	48.	PATH-UUID-BASED-SEGMENT SCHEMA
	49.	PATH-ULID-BASED-SEGMENT SCHEMA
	50.	PATH-SLUG-SEGMENT SCHEMA
	51.	PATH-SEGMENT-NO-DOTS SCHEMA
	52.	PATH-SEGMENT-NO-SLASHES SCHEMA
	53.	PATH-NO-EMPTY-SEGMENTS SCHEMA
	54.	PATH-TRAILING-SLASH SCHEMA
	55.	PATH-NO-TRAILING-SLASH SCHEMA
	56.	PATH-WITHOUT-LEADING-SLASH SCHEMA

⸻

✅ SECTION 4 — WEB / URL PATH SCHEMAS
	57.	URL-PATH SCHEMA (/api/v1/users)
	58.	URL-PATH-NORMALIZED SCHEMA
	59.	URL-PATH-STRICT SCHEMA
	60.	URL-PATH-PARAM SCHEMA (/user/:id)
	61.	URL-PATH-PARAMS-EXTRACTOR SCHEMA
	62.	URL-PATH-SEGMENT SCHEMA
	63.	URL-PATH-ENCODED SCHEMA
	64.	URL-PATH-DECODED SCHEMA
	65.	URL-PATH-QUERYLESS SCHEMA
	66.	URL-PATH-FRAGMENTLESS SCHEMA
	67.	URL-PATH-ROUTE-TEMPLATE SCHEMA
	68.	URL-PATH-STATIC SCHEMA
	69.	URL-PATH-DYNAMIC SCHEMA
	70.	URL-PATH-GLOB SCHEMA (/assets/**)

⸻

✅ SECTION 5 — APPLICATION / DOMAIN PATH SCHEMAS
	71.	PATH-PROJECT-ROOT SCHEMA
	72.	PATH-SRC-DIRECTORY SCHEMA
	73.	PATH-BUILD-DIRECTORY SCHEMA
	74.	PATH-DIST-DIRECTORY SCHEMA
	75.	PATH-CONFIG-DIRECTORY SCHEMA
	76.	PATH-LOG-DIRECTORY SCHEMA
	77.	PATH-TMP-DIRECTORY SCHEMA
	78.	PATH-CACHE-DIRECTORY SCHEMA
	79.	PATH-STATIC-ASSETS SCHEMA
	80.	PATH-MIGRATIONS-DIR SCHEMA
	81.	PATH-ENV-FILE SCHEMA
	82.	PATH-DOTFILE SCHEMA
	83.	PATH-MODULE-IMPORT SCHEMA
	84.	PATH-MONOREPO-PACKAGE SCHEMA

⸻

✅ SECTION 6 — SECURITY / SANDBOX / RESTRICTION PATH SCHEMAS
	85.	PATH-NO-DIRECTORY-TRAVERSAL SCHEMA
	86.	PATH-NO-ESCAPE-ROOT SCHEMA
	87.	PATH-SANDBOXED-UNDER SCHEMA
	88.	PATH-READ-ONLY-ALLOWED SCHEMA
	89.	PATH-WRITABLE-ALLOWED SCHEMA
	90.	PATH-BLOCKED-DIRECTORIES SCHEMA
	91.	PATH-PERMITTED-DIRECTORIES SCHEMA
	92.	PATH-PRIVILEGED-DIRECTORIES SCHEMA
	93.	PATH-NO-RESERVED-DEVICE-NAMES SCHEMA (Windows: CON, AUX, NUL, etc.)
	94.	PATH-STRICT-SANITIZED SCHEMA
	95.	PATH-SAFE-FOR-UPLOADS SCHEMA
	96.	PATH-SAFE-FOR-DOWNLOADS SCHEMA

⸻

✅ SECTION 7 — MEDIA / CONTENT / DOMAIN-SPECIFIC PATH SCHEMAS
	97.	PATH-IMAGE-ASSET SCHEMA
	98.	PATH-VIDEO-ASSET SCHEMA
	99.	PATH-AUDIO-ASSET SCHEMA
	100.	PATH-FONT-ASSET SCHEMA
	101.	PATH-DOCUMENT-ASSET SCHEMA
	102.	PATH-SPRITE-SHEET SCHEMA
	103.	PATH-STORYBOARD SCHEMA
	104.	PATH-TEMPLATE-FILE SCHEMA
	105.	PATH-MARKDOWN-FILE SCHEMA
	106.	PATH-RICH-TEXT-FILE SCHEMA

⸻

✅ SECTION 8 — CLOUD / SERVERLESS / DISTRIBUTED PATH SCHEMAS
	107.	PATH-S3-KEY SCHEMA
	108.	PATH-S3-DIRECTORY SCHEMA
	109.	PATH-S3-BUCKETPATH SCHEMA
	110.	PATH-R2-OBJECT SCHEMA
	111.	PATH-GCS-BLOB SCHEMA
	112.	PATH-AZURE-BLOB SCHEMA
	113.	PATH-CLOUDFLARE-ASSET SCHEMA
	114.	PATH-CDN-ROUTE SCHEMA
	115.	PATH-EDGE-FUNCTION-ROUTE SCHEMA
	116.	PATH-KV-NAMESPACE-KEY SCHEMA
	117.	PATH-QUEUE-DEDUPE-KEY SCHEMA

⸻

✅ SECTION 9 — BUILD TOOL / PACKAGER / GRAPH PATH SCHEMAS
	118.	PATH-VITE-ENTRY SCHEMA
	119.	PATH-WEBPACK-ENTRY SCHEMA
	120.	PATH-TSCONFIG-PATH SCHEMA
	121.	PATH-SOURCE-MAP SCHEMA
	122.	PATH-NODE-MODULE SCHEMA
	123.	PATH-MONOREPO-WORKSPACE SCHEMA
	124.	PATH-BUNDLE-OUTPUT SCHEMA
	125.	PATH-CHUNK-NAME SCHEMA
	126.	PATH-DEPENDENCY-GRAPH-NODE SCHEMA
	127.	PATH-IMPORT-RESOLUTION SCHEMA
	128.	PATH-ALIAS-PATH SCHEMA

⸻

✅ SECTION 10 — TESTING / MOCK / TEMP PATH SCHEMAS
	129.	PATH-MOCK-FILE SCHEMA
	130.	PATH-MOCK-DIRECTORY SCHEMA
	131.	PATH-MOCK-FS-VIRTUAL SCHEMA
	132.	PATH-TEST-FIXTURE SCHEMA
	133.	PATH-TEST-OUTPUT SCHEMA
	134.	PATH-TEMP-FILE SCHEMA
	135.	PATH-TEMP-DIR SCHEMA
	136.	PATH-ISOLATED-SANDBOX SCHEMA
	137.	PATH-PSEUDO-FS SCHEMA
