✅ SECTION 1 — SI BASE & DERIVED POWER SCHEMAS
1.	POWER-WATT SCHEMA (W)
2.	POWER-MILLIWATT SCHEMA (mW)
3.	POWER-KILOWATT SCHEMA (kW)
4.	POWER-MEGAWATT SCHEMA (MW)
5.	POWER-GIGAWATT SCHEMA (GW)
6.	POWER-TERAWATT SCHEMA (TW)
7.	POWER-PICOSCHEMA (pW → TW range, all SI prefixes)
8.	POWER-SI-COERCE SCHEMA (any → W)
9.	POWER-CANONICAL SCHEMA (output normalized W)
10.	POWER-RANGE SCHEMA (min/max W)
11.	POWER-DEFAULT SCHEMA (optional default W)

⸻

✅ SECTION 2 — IMPERIAL / LEGACY / NON-SI SCHEMAS
12.	POWER-HORSEPOWER-MECHANICAL SCHEMA (hp)
13.	POWER-HORSEPOWER-METRIC SCHEMA (ps / cv)
14.	POWER-HORSEPOWER-ELECTRIC SCHEMA (hpₑ)
15.	POWER-BTU-PER-HOUR SCHEMA (BTU/h)
16.	POWER-FOOT-POUND-PER-SECOND SCHEMA (ft lb/s)
17.	POWER-TON-OF-REFRIGERATION SCHEMA (TR = 3.517 kW)
18.	POWER-ERG-PER-SECOND SCHEMA (erg/s)
19.	POWER-KCAL-PER-HOUR SCHEMA (kcal/h)
20.	POWER-LEGACY-COERCE SCHEMA (HP/BTU ↔ W)
21.	POWER-LEGACY-CANONICAL SCHEMA

⸻

✅ SECTION 3 — ELECTRICAL POWER SCHEMAS
22.	POWER-ELECTRICAL-ACTIVE SCHEMA (W = V × A × PF)
23.	POWER-ELECTRICAL-APPARENT SCHEMA (VA)
24.	POWER-ELECTRICAL-REACTIVE SCHEMA (var)
25.	POWER-ELECTRICAL-THREE-PHASE SCHEMA (√3 V I PF)
26.	POWER-ELECTRICAL-LINE-LOSS SCHEMA
27.	POWER-ELECTRICAL-INVERTER-OUTPUT SCHEMA
28.	POWER-ELECTRICAL-EFFICIENCY SCHEMA (%)
29.	POWER-ELECTRICAL-COERCE SCHEMA (any → W)
30.	POWER-ELECTRICAL-CANONICAL SCHEMA

⸻

✅ SECTION 4 — THERMAL / HVAC POWER SCHEMAS
31.	POWER-THERMAL-WATT SCHEMA (Wₜₕ)
32.	POWER-THERMAL-BTU-PER-HOUR SCHEMA (BTU/h)
33.	POWER-THERMAL-KCAL-PER-HOUR SCHEMA (kcal/h)
34.	POWER-THERMAL-TON-OF-REFRIGERATION SCHEMA (TR)
35.	POWER-THERMAL-HEAT-FLOW-RATE SCHEMA (Q̇)
36.	POWER-THERMAL-RADIANT-FLUX SCHEMA (W/m²)
37.	POWER-THERMAL-SOLAR-IRRADIANCE SCHEMA (W/m²)
38.	POWER-THERMAL-COERCE SCHEMA (any → W)
39.	POWER-THERMAL-CANONICAL SCHEMA

⸻

✅ SECTION 5 — MECHANICAL / ROTATIONAL POWER SCHEMAS
40.	POWER-MECHANICAL-TORQUE-RPM SCHEMA (P = 2π n T)
41.	POWER-MECHANICAL-LINEAR-FORCE-VELOCITY SCHEMA (P = F × v)
42.	POWER-MECHANICAL-HYDRAULIC-SCHEMA (P = p × Q)
43.	POWER-MECHANICAL-PNEUMATIC-SCHEMA
44.	POWER-MECHANICAL-SHAFT-SCHEMA
45.	POWER-MECHANICAL-BRAKE-SCHEMA (BHP)
46.	POWER-MECHANICAL-EFFICIENCY-SCHEMA
47.	POWER-MECHANICAL-COERCE SCHEMA
48.	POWER-MECHANICAL-CANONICAL SCHEMA

⸻

✅ SECTION 6 — RENEWABLE / GENERATION / GRID SCHEMAS
49.	POWER-SOLAR-ARRAY-SCHEMA (kWₚ)
50.	POWER-SOLAR-IRRADIANCE-SCHEMA (W/m²)
51.	POWER-WIND-TURBINE-SCHEMA (P = ½ ρ A v³ Cp)
52.	POWER-HYDRO-GENERATION-SCHEMA (P = ρ g h Q)
53.	POWER-GEOTHERMAL-SCHEMA
54.	POWER-NUCLEAR-THERMAL-SCHEMA
55.	POWER-BATTERY-OUTPUT-SCHEMA (W or VA)
56.	POWER-DATA-CENTER-LOAD-SCHEMA (kW per rack)
57.	POWER-RENEWABLE-CAPACITY-SCHEMA
58.	POWER-GRID-SUPPLY-SCHEMA (kVA)
59.	POWER-DISTRIBUTION-LOSS-SCHEMA

⸻

✅ SECTION 7 — COMPUTE / DIGITAL / INFORMATIONAL POWER SCHEMAS
60.	POWER-CPU-TDP-SCHEMA (W)
61.	POWER-GPU-CONSUMPTION-SCHEMA (W)
62.	POWER-SERVER-RACK-SCHEMA (kW/rack)
63.	POWER-DATA-CENTER-PUE-SCHEMA (Power Usage Effectiveness)
64.	POWER-STORAGE-DENSITY-SCHEMA (W per TB)
65.	POWER-NETWORK-DEVICE-SCHEMA (W per port)
66.	POWER-AI-JOB-CONSUMPTION-SCHEMA (kWh/run)
67.	POWER-IT-LOAD-SCHEMA (W avg per VM)
68.	POWER-DIGITAL-EFFICIENCY-SCHEMA (W/FLOP)
69.	POWER-CLOUD-SERVICE-BILLING-SCHEMA ($/kWh)

⸻

✅ SECTION 8 — TRANSPORT / AUTOMOTIVE / AEROSPACE SCHEMAS
70.	POWER-ENGINE-OUTPUT-SCHEMA (kW / hp)
71.	POWER-PROPULSION-SCHEMA (kN × m/s)
72.	POWER-THRUST-SPECIFIC-SCHEMA (kW / kg)
73.	POWER-FUEL-CELL-SCHEMA (kW)
74.	POWER-REGENERATIVE-BRAKING-SCHEMA (kW recovered)
75.	POWER-ELECTRIC-VEHICLE-CHARGER-SCHEMA (kW)
76.	POWER-CHARGING-RATE-SCHEMA (kW / time)
77.	POWER-AIRCRAFT-ENGINE-SCHEMA (MW)
78.	POWER-ROCKET-THRUST-SCHEMA (MW eq.)
79.	POWER-TRANSPORT-COERCE SCHEMA (any → kW)

⸻

✅ SECTION 9 — CHEMICAL / THERMODYNAMIC / BIOLOGICAL POWER SCHEMAS
80.	POWER-CHEMICAL-REACTION-RATE-SCHEMA (W/mol)
81.	POWER-BIOLOGICAL-METABOLIC-RATE-SCHEMA (W)
82.	POWER-CALORIMETRIC-SCHEMA (W)
83.	POWER-RESPIRATORY-ENERGY-EXPENDITURE-SCHEMA (kcal/h)
84.	POWER-PHOTOSYNTHETIC-FLUX-SCHEMA (W/m²)
85.	POWER-THERMOCHEMICAL-SCHEMA (W/kg fuel)
86.	POWER-FUEL-BURN-RATE-SCHEMA (W eq.)
87.	POWER-BIOENERGETIC-EFFICIENCY-SCHEMA (%)
88.	POWER-CHEMICAL-COERCE SCHEMA
89.	POWER-CHEMICAL-CANONICAL SCHEMA

⸻

✅ SECTION 10 — UTILITY / VALIDATION / MIXED SCHEMAS
90.	POWER-UNIT-PARSE-SCHEMA (string → unit)
91.	POWER-VALUE-COERCE-SCHEMA (any → number)
92.	POWER-ARRAY-SCHEMA (power[])
93.	POWER-RECORD-SCHEMA ({source: power})
94.	POWER-FIELD-SCHEMA ({description, value})
95.	POWER-UNCERTAINTY-SCHEMA (±σ W)
96.	POWER-RANGE-LIMIT-SCHEMA (threshold alarms)
97.	POWER-ANOMALY-SCHEMA (spike, drop, loss)
98.	POWER-EFFICIENCY-SCHEMA (input/output %)
99.	POWER-INTENSITY-SCHEMA (W/m²)
100.	POWER-FACTOR-SCHEMA (PF = cos φ)
101. POWER-SPECTRAL-DENSITY-SCHEMA (W/Hz)
102. POWER-NOISE-DENSITY-SCHEMA (dBm/Hz)
103. POWER-DYNAMIC-LOAD-SCHEMA (time-varying P(t))
104. POWER-AVERAGE-AND-PEAK-SCHEMA (Pavg, Pmax)
105. POWER-THERMODYNAMIC-EFFICIENCY-SCHEMA (ηCarnot)
106. POWER-LOGARITHMIC-LEVEL-SCHEMA (dBW, dBm)