✅ SECTION 1 — CORE SI PRESSURE SCHEMAS
1.	PRESSURE-PASCAL SCHEMA (Pa)
2.	PRESSURE-KILOPASCAL SCHEMA (kPa)
3.	PRESSURE-MEGAPASCAL SCHEMA (MPa)
4.	PRESSURE-GIGAPASCAL SCHEMA (GPa)
5.	PRESSURE-MICROPASCAL SCHEMA (µPa)
6.	PRESSURE-MILLIPASCAL SCHEMA (mPa)
7.	PRESSURE-HECTOPASCAL SCHEMA (hPa)
8.	PRESSURE-BARYE SCHEMA (Ba = 0.1 Pa)
9.	PRESSURE-NEWTON-PER-M2 SCHEMA (N/m² alias Pa)
10.	PRESSURE-SI-COERCE SCHEMA (any → Pa)
11.	PRESSURE-CANONICAL SCHEMA (normalized Pa output)

⸻

✅ SECTION 2 — IMPERIAL / U.S. CUSTOMARY PRESSURE SCHEMAS
12. PRESSURE-PSI SCHEMA (pounds per square inch)
13. PRESSURE-PSF SCHEMA (pounds per square foot)
14. PRESSURE-INCH-OF-MERCURY SCHEMA (inHg)
15. PRESSURE-MILLIMETER-OF-MERCURY SCHEMA (mmHg = torr)
16. PRESSURE-ATMOSPHERE SCHEMA (atm)
17. PRESSURE-BAR SCHEMA (bar)
18. PRESSURE-MILLIBAR SCHEMA (mbar)
19. PRESSURE-TORR SCHEMA (Torr = mmHg)
20. PRESSURE-INCH-OF-WATER SCHEMA (inH₂O)
21. PRESSURE-FOOT-OF-WATER SCHEMA (ftH₂O)
22. PRESSURE-IMPERIAL-COERCE SCHEMA (any → Pa)

⸻

✅ SECTION 3 — FLUID / HYDRAULIC / PNEUMATIC PRESSURES
23. PRESSURE-HYDRAULIC-LINE SCHEMA
24. PRESSURE-PNEUMATIC-SYSTEM SCHEMA
25. PRESSURE-PIPELINE SCHEMA
26. PRESSURE-PUMP-OUTLET SCHEMA
27. PRESSURE-VALVE-INLET SCHEMA
28. PRESSURE-VALVE-DIFFERENTIAL SCHEMA (ΔP)
29. PRESSURE-HEAD-WATER-COLUMN SCHEMA
30. PRESSURE-VAPOR-PRESSURE SCHEMA
31. PRESSURE-SATURATION-SCHEMA
32. PRESSURE-ABSOLUTE SCHEMA (Pabs)
33. PRESSURE-GAUGE SCHEMA (Pg = Pabs – Patm)
34. PRESSURE-DIFFERENTIAL SCHEMA (PΔ)

⸻

✅ SECTION 4 — ATMOSPHERIC / METEOROLOGICAL PRESSURE
35. PRESSURE-ATMOSPHERIC SCHEMA (sea-level hPa)
36. PRESSURE-SURFACE-LEVEL SCHEMA
37. PRESSURE-BAROMETRIC SCHEMA
38. PRESSURE-ALTITUDE-CORRECTED SCHEMA
39. PRESSURE-WEATHER-STATION SCHEMA
40. PRESSURE-TROPOSPHERIC PROFILE SCHEMA
41. PRESSURE-STRATOSPHERIC SCHEMA
42. PRESSURE-METEOROLOGICAL-FIELD SCHEMA
43. PRESSURE-STORM-CENTER SCHEMA
44. PRESSURE-WIND-CORRECTED SCHEMA

⸻

✅ SECTION 5 — INDUSTRIAL / ENGINEERING PRESSURE
45. PRESSURE-BOILER SCHEMA
46. PRESSURE-VACUUM CHAMBER SCHEMA
47. PRESSURE-REFRIGERATION-CYCLE SCHEMA
48. PRESSURE-COMPRESSOR-OUTLET SCHEMA
49. PRESSURE-MANIFOLD SCHEMA
50. PRESSURE-TANK SCHEMA
51. PRESSURE-VESSEL SCHEMA
52. PRESSURE-PIPE-FLANGE SCHEMA
53. PRESSURE-SPRINKLER-SYSTEM SCHEMA
54. PRESSURE-INDUSTRIAL-GAUGE SCHEMA
55. PRESSURE-SAFETY-VALVE-SETPOINT SCHEMA
56. PRESSURE-RELIEF-VALVE-OPENING SCHEMA
57. PRESSURE-CALIBRATION-POINT SCHEMA

⸻

✅ SECTION 6 — SCIENTIFIC / PHYSICS / CHEMISTRY PRESSURE
58. PRESSURE-IDEAL-GAS-LAW SCHEMA (PV = nRT)
59. PRESSURE-PLASMA-PRESSURE SCHEMA
60. PRESSURE-EQUATION-OF-STATE SCHEMA
61. PRESSURE-VACUUM-ULTRAHIGH SCHEMA (< 10⁻⁹ Torr)
62. PRESSURE-BULK-MODULUS-DERIVED SCHEMA
63. PRESSURE-SOUND-WAVE-AMPLITUDE SCHEMA
64. PRESSURE-ACOUSTIC-RMS SCHEMA
65. PRESSURE-DYNAMIC-FLUID SCHEMA
66. PRESSURE-STATIC-FLUID SCHEMA
67. PRESSURE-ISENTROPIC-RELATION SCHEMA
68. PRESSURE-ENTHALPY-PAIR SCHEMA

⸻

✅ SECTION 7 — MEDICAL / BIOPHYSIOLOGICAL PRESSURE
69. PRESSURE-BLOOD-SYSTOLIC SCHEMA (mmHg)
70. PRESSURE-BLOOD-DIASTOLIC SCHEMA (mmHg)
71. PRESSURE-INTRACRANIAL SCHEMA (mmHg / kPa)
72. PRESSURE-INTRAOCULAR SCHEMA (mmHg)
73. PRESSURE-INTRATHORACIC SCHEMA
74. PRESSURE-PULMONARY-ARTERY SCHEMA
75. PRESSURE-VENOUS-CENTRAL SCHEMA
76. PRESSURE-RESPIRATORY-AIRWAY SCHEMA
77. PRESSURE-BLOOD-DIFFERENTIAL SCHEMA (pulse pressure)
78. PRESSURE-CUFF-MEASUREMENT SCHEMA
79. PRESSURE-CATHETER-SENSOR SCHEMA

⸻

✅ SECTION 8 — AEROSPACE / AUTOMOTIVE / MARINE PRESSURE
80. PRESSURE-TIRE SCHEMA (psi / kPa)
81. PRESSURE-ENGINE-OIL SCHEMA
82. PRESSURE-FUEL-LINE SCHEMA
83. PRESSURE-BRAKE-SYSTEM SCHEMA
84. PRESSURE-COOLANT-SYSTEM SCHEMA
85. PRESSURE-CABIN-ALTITUDE SCHEMA
86. PRESSURE-AIRFRAME-DIFFERENTIAL SCHEMA
87. PRESSURE-HYDRAULIC-BRAKE-SCHEMA
88. PRESSURE-BOOST-TURBOCHARGER SCHEMA
89. PRESSURE-INTAKE-MANIFOLD SCHEMA (MAP)
90. PRESSURE-EXHAUST-BACKPRESSURE SCHEMA
91. PRESSURE-FUEL-RAIL SCHEMA
92. PRESSURE-ALTIMETER-SENSOR SCHEMA
93. PRESSURE-STATIC-PORT SCHEMA
94. PRESSURE-PITOT-TUBE SCHEMA
95. PRESSURE-MARINE-DEPTH-GAUGE SCHEMA

⸻

✅ SECTION 9 — DATA MODELING / UTILITY LAYERS
96. PRESSURE-STRICT SCHEMA
97. PRESSURE-OPTIONAL SCHEMA
98. PRESSURE-NULLABLE SCHEMA
99. PRESSURE-PRESENT SCHEMA
100. PRESSURE-COERCE SCHEMA
101. PRESSURE-ARRAY SCHEMA
102. PRESSURE-RECORD SCHEMA
103. PRESSURE-FIELD SCHEMA ({ description, value })
104. PRESSURE-DEFAULT SCHEMA (with fallback kPa)
105. PRESSURE-RANGE SCHEMA (min–max validation)
106. PRESSURE-STEP SCHEMA (incremental precision)
107. PRESSURE-CALIBRATION-FIELD SCHEMA
108. PRESSURE-CANONICAL-V2 SCHEMA (normalized unit + metadata)

⸻

✅ SECTION 10 — ANALYTICS / MONITORING / TELEMETRY
109. PRESSURE-SENSOR-RAW SCHEMA
110. PRESSURE-SENSOR-CALIBRATED SCHEMA
111. PRESSURE-SENSOR-SERIALIZED SCHEMA
112. PRESSURE-TIME-SERIES SCHEMA
113. PRESSURE-ALERT-THRESHOLD SCHEMA
114. PRESSURE-ALERT-EVENT SCHEMA
115. PRESSURE-AGGREGATE-STATISTICS SCHEMA
116. PRESSURE-TELEMETRY-PAYLOAD SCHEMA
117. PRESSURE-EDGE-COLLECTOR SCHEMA (Cloudflare Worker edge metric)
118. PRESSURE-PROMETHEUS-EXPORT SCHEMA
119. PRESSURE-ANALYTICS-SUMMARY SCHEMA

⸻

✅ SECTION 11 — RESEARCH / SIMULATION / EDUCATIONAL
120. PRESSURE-SIMULATION-BOUNDARY SCHEMA
121. PRESSURE-CFD-CELL-SCHEMA (flow field Pa)
122. PRESSURE-REYNOLDS-PRESSURE-TERM SCHEMA
123. PRESSURE-SONIC-BOOM-WAVEFRONT SCHEMA
124. PRESSURE-EXPERIMENTAL-DATA-POINT SCHEMA
125. PRESSURE-UNCERTAINTY-ESTIMATE SCHEMA
126. PRESSURE-ERROR-PROPAGATION SCHEMA
127. PRESSURE-NOISE-FLOOR SCHEMA
128. PRESSURE-SENSOR-DRIFT-MODEL SCHEMA
129. PRESSURE-LAB-INSTRUMENT-READING SCHEMA

⸻

✅ SECTION 12 — FIELD / FACTORY / VERSIONED WRAPPERS
130. PRESSURE-FACTORY SCHEMA (create Pa/kPa/bar validators)
131. PRESSURE-VERSIONED SCHEMA (v1/v2 back-compat)
132. PRESSURE-METADATA SCHEMA (unit, sensor, timestamp)
133. PRESSURE-MULTI-UNIT SCHEMA (Pa ↔ bar ↔ psi)
134. PRESSURE-CANONICAL-FIELD-V2 SCHEMA ({ desc, unit, Pa })
135. PRESSURE-COLLECTOR-SCHEMA (normalized intake endpoint)
136.	PRESSURE-DELTA-ALTITUDE-SCHEMA (Pa ↔ m conversion for avionics)
137.	PRESSURE-SEA-LEVEL-REDUCED-SCHEMA (meteorological normalization)
138.	PRESSURE-SATURATION-STEAM-TABLE-SCHEMA (thermo lookup)
139.	PRESSURE-LEAK-TEST-SCHEMA (ΔP vs time)
140.	PRESSURE-FAILURE-THRESHOLD-SCHEMA (safety margin spec)