✅ SECTION 1 — SI BASE AND DERIVED RADIOACTIVITY SCHEMAS
1.	RADIOACTIVITY-BECQUEREL SCHEMA (Bq)
2.	RADIOACTIVITY-KILOBECQUEREL SCHEMA (kBq)
3.	RADIOACTIVITY-MEGABECQUEREL SCHEMA (MBq)
4.	RADIOACTIVITY-GIGABECQUEREL SCHEMA (GBq)
5.	RADIOACTIVITY-TERABECQUEREL SCHEMA (TBq)
6.	RADIOACTIVITY-PETABECQUEREL SCHEMA (PBq)
7.	RADIOACTIVITY-COERCE SCHEMA (any → Bq)
8.	RADIOACTIVITY-CANONICAL SCHEMA (normalized output Bq)
9.	RADIOACTIVITY-RANGE SCHEMA (min / max Bq)
10.	RADIOACTIVITY-DEFAULT SCHEMA (optional Bq default 0)

⸻

✅ SECTION 2 — LEGACY / IMPERIAL / NON-SI SCHEMAS
11.	RADIOACTIVITY-CURIE SCHEMA (Ci)
12.	RADIOACTIVITY-MILLICURIE SCHEMA (mCi)
13.	RADIOACTIVITY-MICROCURIE SCHEMA (µCi)
14.	RADIOACTIVITY-NANOCURIE SCHEMA (nCi)
15.	RADIOACTIVITY-PICOCURIE SCHEMA (pCi)
16.	RADIOACTIVITY-DISINTEGRATIONS-PER-SECOND SCHEMA (dps)
17.	RADIOACTIVITY-DISINTEGRATIONS-PER-MINUTE SCHEMA (dpm)
18.	RADIOACTIVITY-LEGACY-COERCE SCHEMA (Ci ↔ Bq)
19.	RADIOACTIVITY-LEGACY-CANONICAL SCHEMA

⸻

✅ SECTION 3 — DOSE AND EXPOSURE RELATED SCHEMAS
20.	RADIATION-ABSORBED-DOSE-GRAY SCHEMA (Gy = J/kg)
21.	RADIATION-ABSORBED-DOSE-RAD SCHEMA (rad)
22.	RADIATION-EQUIVALENT-DOSE-SIEVERT SCHEMA (Sv)
23.	RADIATION-DOSE-RATE-SCHEMA (Sv/h or µSv/h)
24.	RADIATION-EXPOSURE-COULOMB-PER-KG SCHEMA (C/kg)
25.	RADIATION-EXPOSURE-ROENTGEN SCHEMA (R)
26.	RADIATION-KERMA-SCHEMA (kinetic energy released per mass)
27.	RADIATION-FLUENCE-RATE-SCHEMA (particles cm⁻² s⁻¹)
28.	RADIATION-DOSE-COERCE SCHEMA (any → Sv)
29.	RADIATION-DOSE-CANONICAL SCHEMA

⸻

✅ SECTION 4 — TEMPORAL / DECAY SCHEMAS
30.	RADIOACTIVITY-HALF-LIFE-SCHEMA (seconds / years)
31.	RADIOACTIVITY-DECAY-CONSTANT-SCHEMA (λ = ln 2 / t½)
32.	RADIOACTIVITY-DECAY-RATE-SCHEMA (dN/dt)
33.	RADIOACTIVITY-ACTIVITY-AT-TIME-SCHEMA (A = A₀e⁻λt)
34.	RADIOACTIVITY-PARENT-DAUGHTER-CHAIN-SCHEMA
35.	RADIOACTIVITY-EQUILIBRIUM-SCHEMA (secular/transient)
36.	RADIOACTIVITY-TEMPORAL-SERIES-SCHEMA (activity vs time)
37.	RADIOACTIVITY-DECAY-SIMULATION-SCHEMA

⸻

✅ SECTION 5 — MATERIAL / SAMPLE / CONCENTRATION SCHEMAS
38.	RADIOACTIVITY-CONCENTRATION-SCHEMA (Bq/m³)
39.	RADIOACTIVITY-MASSIC-ACTIVITY-SCHEMA (Bq/kg)
40.	RADIOACTIVITY-SPECIFIC-ACTIVITY-SCHEMA (Bq/g)
41.	RADIOACTIVITY-VOLUMETRIC-ACTIVITY-SCHEMA (Bq/L)
42.	RADIOACTIVITY-SURFACE-ACTIVITY-SCHEMA (Bq/m²)
43.	RADIOACTIVITY-PARTICULATE-ACTIVITY-SCHEMA (Bq/particle)
44.	RADIOACTIVITY-RADON-CONCENTRATION-SCHEMA (Bq/m³)
45.	RADIOACTIVITY-SOIL-ACTIVITY-SCHEMA (Bq/kg)
46.	RADIOACTIVITY-WATER-ACTIVITY-SCHEMA (Bq/L)
47.	RADIOACTIVITY-AIR-ACTIVITY-SCHEMA (Bq/m³)

⸻

✅ SECTION 6 — DETECTION / INSTRUMENTATION SCHEMAS
48.	RADIATION-COUNT-RATE-SCHEMA (cps / cpm)
49.	RADIATION-DETECTOR-EFFICIENCY-SCHEMA (ε)
50.	RADIATION-ENERGY-WINDOW-SCHEMA (keV range)
51.	RADIATION-DOSE-METER-SCHEMA
52.	RADIATION-SURVEY-METER-SCHEMA
53.	RADIATION-SPECTRUM-SCHEMA (channel → counts)
54.	RADIATION-DETECTOR-CALIBRATION-SCHEMA
55.	RADIATION-DETECTION-UNCERTAINTY-SCHEMA
56.	RADIATION-COUNT-STATISTICS-SCHEMA (Poisson)
57.	RADIATION-INSTRUMENT-METADATA-SCHEMA

⸻

✅ SECTION 7 — BIOLOGICAL / MEDICAL APPLICATION SCHEMAS
58.	RADIATION-THERAPY-DOSE-SCHEMA (Gy)
59.	RADIATION-DIAGNOSTIC-DOSE-SCHEMA (CT / X-ray mSv)
60.	RADIATION-NUCLEAR-MEDICINE-ACTIVITY-SCHEMA (MBq)
61.	RADIATION-ORGAN-DOSE-SCHEMA
62.	RADIATION-EFFECTIVE-DOSE-SCHEMA
63.	RADIATION-EQUIVALENT-TISSUE-WEIGHT-SCHEMA (wᵀ)
64.	RADIATION-EXPOSURE-EVENT-SCHEMA (date, activity, dose)
65.	RADIATION-THERAPY-PLAN-SCHEMA (fractions, Gy/fx)
66.	RADIATION-DOSE-RESPONSE-SCHEMA
67.	RADIATION-BIOLOGICAL-EFFECT-SCHEMA (RBE / QF)

⸻

✅ SECTION 8 — ENVIRONMENTAL / SAFETY SCHEMAS
68.	RADIATION-AREA-MONITOR-SCHEMA
69.	RADIATION-SHIELDING-THICKNESS-SCHEMA (mm Pb / concrete)
70.	RADIATION-ALARA-LIMIT-SCHEMA (mSv/y)
71.	RADIATION-BACKGROUND-LEVEL-SCHEMA (Bq/m³ or µSv/h)
72.	RADIATION-WORKER-DOSE-LIMIT-SCHEMA
73.	RADIATION-PUBLIC-DOSE-LIMIT-SCHEMA
74.	RADIATION-EMERGENCY-THRESHOLD-SCHEMA
75.	RADIATION-CONTAMINATION-LEVEL-SCHEMA
76.	RADIATION-DECONTAMINATION-FACTOR-SCHEMA
77.	RADIATION-WASTE-ACTIVITY-SCHEMA (Bq/kg)
78.	RADIATION-TRANSPORT-INDEX-SCHEMA (TI)

⸻

✅ SECTION 9 — COERCION / VALIDATION / UTILITY SCHEMAS
79.	RADIOACTIVITY-UNIT-PARSE-SCHEMA (string → canonical unit)
80.	RADIOACTIVITY-VALUE-COERCE-SCHEMA (any → number)
81.	RADIOACTIVITY-CANONICAL-SCHEMA (normalize → Bq)
82.	RADIOACTIVITY-ARRAY-SCHEMA (activity[])
83.	RADIOACTIVITY-RECORD-SCHEMA ({isotope: activity})
84.	RADIOACTIVITY-FIELD-SCHEMA ({description, value})
85.	RADIOACTIVITY-VALIDATION-RESULT-SCHEMA (status, reason)
86.	RADIOACTIVITY-UNCERTAINTY-SCHEMA (± σ)
87.	RADIOACTIVITY-RANGE-LIMIT-SCHEMA (thresholds for alarms)
88.	RADIOACTIVITY-ANOMALY-SCHEMA (detector spike flag)

⸻

✅ SECTION 10 — NUCLEAR / PARTICLE PHYSICS SCHEMAS
89.	RADIOACTIVITY-CROSS-SECTION-SCHEMA (barn)
90.	RADIOACTIVITY-FLUX-DENSITY-SCHEMA (particles cm⁻² s⁻¹)
91.	RADIOACTIVITY-REACTION-RATE-SCHEMA (R = ΦσN)
92.	RADIOACTIVITY-ENERGY-SPECTRUM-SCHEMA (MeV range)
93.	RADIOACTIVITY-NEUTRON-YIELD-SCHEMA
94.	RADIOACTIVITY-GAMMA-YIELD-SCHEMA
95.	RADIOACTIVITY-FISSION-RATE-SCHEMA
96.	RADIOACTIVITY-NEUTRON-FLUX-SCHEMA
97.	RADIOACTIVITY-DOSE-EQUIVALENT-RATE-SCHEMA (H*(10))
98.	RADIOACTIVITY-PARTICLE-ENERGY-TRANSFER-SCHEMA (LET)
99.	RADIOACTIVITY-NUCLEAR-REACTION-SCHEMA (reaction notation)
100.	RADIOACTIVITY-ISOTOPE-IDENTIFIER-SCHEMA (IAEA symbol)
101. RADIOACTIVITY-ALPHA-SPECTRUM-SCHEMA
102. RADIOACTIVITY-BETA-SPECTRUM-SCHEMA
103. RADIOACTIVITY-GAMMA-SPECTRUM-SCHEMA
104. RADIOACTIVITY-NEUTRON-SPECTRUM-SCHEMA
105. RADIOACTIVITY-RADIATION-WEIGHTING-FACTOR-SCHEMA (wᵣ tables)
106. RADIOACTIVITY-BIOLOGICAL-WEIGHTING-FACTOR-SCHEMA (wᵀ tables)
107. RADIOACTIVITY-NUCLEAR-DECAY-DATA-SCHEMA (ENSDF-style)
108. RADIOACTIVITY-NUCLIDE-LIBRARY-SCHEMA (IAEA-Reference)