✅ SECTION 1 — CORE SI / METRIC SPEED SCHEMAS
1.	SPEED-METER-PER-SECOND SCHEMA (m/s)
2.	SPEED-KILOMETER-PER-HOUR SCHEMA (km/h)
3.	SPEED-CENTIMETER-PER-SECOND SCHEMA (cm/s)
4.	SPEED-MILLIMETER-PER-SECOND SCHEMA (mm/s)
5.	SPEED-MICROMETER-PER-SECOND SCHEMA (µm/s)
6.	SPEED-METER-PER-MINUTE SCHEMA (m/min)
7.	SPEED-METER-PER-HOUR SCHEMA (m/h)
8.	SPEED-KNOT-METRIC-EQUIVALENT SCHEMA (1 kt ≈ 0.5144 m/s)
9.	SPEED-MACH-SCHEMA (M = local speed of sound)
10.	SPEED-LIGHT-SPEED-FRACTION SCHEMA (c-ratio)
11.	SPEED-SI-COERCE SCHEMA (any → m/s)
12.	SPEED-CANONICAL SCHEMA (normalized SI base = m/s)

⸻

✅ SECTION 2 — IMPERIAL / U.S. CUSTOMARY SPEED SCHEMAS
13. SPEED-MILE-PER-HOUR SCHEMA (mph)
14. SPEED-FOOT-PER-SECOND SCHEMA (ft/s)
15. SPEED-YARD-PER-SECOND SCHEMA (yd/s)
16. SPEED-INCH-PER-SECOND SCHEMA (in/s)
17. SPEED-NAUTICAL-MILE-PER-HOUR SCHEMA (knot)
18. SPEED-IMPERIAL-COERCE SCHEMA (any → mph)
19. SPEED-IMPERIAL-CANONICAL SCHEMA (normalized → mph)

⸻

✅ SECTION 3 — CONVERSION & NORMALIZATION SCHEMAS
20. SPEED-CONVERT-KMH-TO-MS SCHEMA
21. SPEED-CONVERT-MS-TO-KMH SCHEMA
22. SPEED-CONVERT-MPH-TO-KMH SCHEMA
23. SPEED-CONVERT-KMH-TO-MPH SCHEMA
24. SPEED-CONVERT-KT-TO-MS SCHEMA
25. SPEED-CONVERT-MS-TO-KT SCHEMA
26. SPEED-CONVERT-ANY SCHEMA (auto-detect units → canonical)
27. SPEED-PRECISION SCHEMA (round/clamp decimals)
28. SPEED-RANGE SCHEMA ([min,max])
29. SPEED-RANGE-STRICT SCHEMA (enforces min ≤ max)

⸻

✅ SECTION 4 — VALIDATION / COERCION LAYERS
30. SPEED-STRICT SCHEMA (number only)
31. SPEED-OPTIONAL SCHEMA (number or undefined)
32. SPEED-NULLABLE SCHEMA (number or null)
33. SPEED-PRESENT SCHEMA (required)
34. SPEED-POSITIVE SCHEMA (> 0)
35. SPEED-NON-NEGATIVE SCHEMA (≥ 0)
36. SPEED-MAX SCHEMA (≤ threshold)
37. SPEED-MIN SCHEMA (≥ threshold)
38. SPEED-SAFE-BOUNDS SCHEMA (≤ speed of light)
39. SPEED-REALISTIC-VEHICLE SCHEMA (0–600 km/h)
40. SPEED-REALISTIC-AIRCRAFT SCHEMA (0–3 Mach)

⸻

✅ SECTION 5 — TRANSPORT / AUTOMOTIVE SPEEDS
41. SPEED-VEHICLE-SCHEMA
42. SPEED-HIGHWAY-LIMIT SCHEMA
43. SPEED-CITY-AVERAGE SCHEMA
44. SPEED-TRAFFIC-FLOW SCHEMA
45. SPEED-WHEEL-ROTATIONAL SCHEMA (rad/s → linear)
46. SPEED-ODOMETER-SCHEMA
47. SPEED-SPEEDOMETER-DISPLAY SCHEMA
48. SPEED-CRUISE-CONTROL-TARGET SCHEMA
49. SPEED-BRAKE-THRESHOLD SCHEMA
50. SPEED-ACCELERATION-DERIVED SCHEMA (dv/dt)

⸻

✅ SECTION 6 — AEROSPACE / FLIGHT DYNAMICS SPEEDS
51. SPEED-AIRSPEED-INDICATED SCHEMA (IAS)
52. SPEED-TRUE-AIRSPEED SCHEMA (TAS)
53. SPEED-GROUND-SPEED SCHEMA (GS)
54. SPEED-VERTICAL-SPEED SCHEMA (VS = climb rate)
55. SPEED-WIND-SPEED SCHEMA
56. SPEED-JET-NOZZLE-EXIT SCHEMA
57. SPEED-SOUND-LOCAL SCHEMA (Mach 1)
58. SPEED-RE-ENTRY-VELOCITY SCHEMA
59. SPEED-ORBITAL-VELOCITY SCHEMA
60. SPEED-ESCAPE-VELOCITY SCHEMA

⸻

✅ SECTION 7 — MARINE / NAUTICAL SPEEDS
61. SPEED-WATER-FLOW SCHEMA
62. SPEED-CURRENT-SCHEMA
63. SPEED-SHIP-OVER-GROUND SCHEMA (SOG)
64. SPEED-SHIP-THROUGH-WATER SCHEMA (STW)
65. SPEED-KNOTS-SCHEMA (nautical unit)
66. SPEED-WAVE-PHASE-VELOCITY SCHEMA
67. SPEED-SUBMERSIBLE-SCHEMA
68. SPEED-MARINE-COERCE SCHEMA

⸻

✅ SECTION 8 — HUMAN / ATHLETIC SPEEDS
69. SPEED-RUNNING SCHEMA
70. SPEED-SPRINT-SCHEMA
71. SPEED-CYCLING SCHEMA
72. SPEED-WALKING SCHEMA
73. SPEED-SWIMMING SCHEMA
74. SPEED-ROWING SCHEMA
75. SPEED-SKIING SCHEMA
76. SPEED-MARATHON-PACE SCHEMA (min/km)
77. SPEED-PACE-CONVERT SCHEMA (pace ↔ speed)

⸻

✅ SECTION 9 — INDUSTRIAL / MANUFACTURING SPEEDS
78. SPEED-CONVEYOR-BELT SCHEMA
79. SPEED-MOTOR-SHAFT SCHEMA
80. SPEED-TURBINE-BLADE-TIP SCHEMA
81. SPEED-PUMP-FLOW-VELOCITY SCHEMA
82. SPEED-ROBOT-JOINT SCHEMA
83. SPEED-CUTTING-TOOL SCHEMA
84. SPEED-LATHE-SURFACE SCHEMA
85. SPEED-ROLLING-LINE SCHEMA
86. SPEED-TEXTILE-MACHINE SCHEMA
87. SPEED-PRESS-LINEAR-SCHEMA

⸻

✅ SECTION 10 — SCIENTIFIC / PHYSICS SPEEDS
88. SPEED-PARTICLE-VELOCITY SCHEMA
89. SPEED-GROUP-VELOCITY SCHEMA
90. SPEED-PHASE-VELOCITY SCHEMA
91. SPEED-ELECTRON-DRIFT SCHEMA
92. SPEED-SOUND-IN-MEDIUM SCHEMA
93. SPEED-LIGHT-IN-VACUUM SCHEMA (c)
94. SPEED-LIGHT-IN-MEDIUM SCHEMA (n-adjusted)
95. SPEED-PLASMA-WAVE SCHEMA
96. SPEED-ASTRONOMICAL-OBJECT SCHEMA (orbital)
97. SPEED-GALACTIC-ROTATION SCHEMA
98. SPEED-COSMIC-EXPANSION-SCHEMA (Hubble v = Hd)

⸻

✅ SECTION 11 — FIELD / FACTORY UTILITIES
99. SPEED-FIELD SCHEMA ({ description, value })
100. SPEED-FIELD-STRICT SCHEMA
101. SPEED-FIELD-OPTIONAL SCHEMA
102. SPEED-FIELD-NULLABLE SCHEMA
103. SPEED-FIELD-COERCE SCHEMA
104. SPEED-FIELD-CANONICAL SCHEMA
105. SPEED-FIELD-DEFAULT SCHEMA
106. SPEED-FIELD-ARRAY SCHEMA
107. SPEED-FIELD-RECORD SCHEMA
108. SPEED-FIELD-METADATA SCHEMA ({ unit, timestamp })

⸻

✅ SECTION 12 — ANALYTICS / TELEMETRY / ML
109. SPEED-METRIC SCHEMA (normalized for telemetry)
110. SPEED-TIMESERIES SCHEMA ([t,v])
111. SPEED-DELTA SCHEMA (Δv)
112. SPEED-ACCELERATION-PAIR SCHEMA (dv/dt)
113. SPEED-AGGREGATED-METRIC SCHEMA (avg/min/max/stddev)
114. SPEED-ANOMALY-SCHEMA (deviation from baseline)
115. SPEED-PREDICTION-SCHEMA (ML forecast)
116. SPEED-CONTROL-STATE SCHEMA (current vs target)
117. SPEED-ALERT-CONDITION SCHEMA (rule-based)
118. SPEED-AUDIT-ENTRY SCHEMA (change tracking)

⸻

✅ SECTION 13 — ENTERPRISE / IoT / EDGE EXTENSIONS
119. SPEED-SENSOR-SCHEMA (raw + calibrated)
120. SPEED-SENSOR-CALIBRATION SCHEMA
121. SPEED-SENSOR-UNCERTAINTY SCHEMA
122. SPEED-NETWORK-PACKET-RATE SCHEMA (bytes/s ↔ speed)
123. SPEED-DATA-THROUGHPUT SCHEMA (bit/s ↔ m/s analog)
124. SPEED-MACHINE-AXIS-SCHEMA (X/Y/Z linear velocity)
125. SPEED-SPATIAL-VECTOR SCHEMA (3D vx, vy, vz)
126. SPEED-MULTIUNIT-SCHEMA (stores m/s, km/h, mph)
127. SPEED-CANONICAL-V2 SCHEMA (metadata + unit)
128. SPEED-FIELD-V2 SCHEMA ({ description, value })
129. SPEED-TELEMETRY-V2 SCHEMA ({ deviceId, timestamp, speed })
130. SPEED-ANALYTICS-V2 SCHEMA (enterprise normalized metric)

⸻

✅ SECTION 14 — ADVANCED / OPTIONAL RESEARCH EXTENSIONS
131. SPEED-VECTOR-FIELD SCHEMA (flow field map)
132. SPEED-DISTRIBUTION SCHEMA (probability density)
133. SPEED-TURBULENCE-VARIANCE SCHEMA (RMS fluctuation)
134. SPEED-CURL-DIVERGENCE SCHEMA (∇×v / ∇·v)
135. SPEED-SPATIAL-GRADIENT SCHEMA (∂v/∂x)
136. SPEED-CORRELATION-MATRIX SCHEMA (covariance of sensors)
137. SPEED-UNCERTAINTY-SCHEMA (±σ fields)
138. SPEED-CALIBRATION-COEFFICIENT SCHEMA (scale/offset)
139. SPEED-BOUNDARY-CONDITION SCHEMA (flow at walls)
140. SPEED-REYNOLDS-NUMBER-SCHEMA (derived dimensionless quantity)

41.	SPEED-ANGULAR-VELOCITY SCHEMA (rad/s)
	142.	SPEED-ANGULAR-VELOCITY-COERCE SCHEMA
	143.	SPEED-ANGULAR-MOMENTUM-DERIVED SCHEMA
