✅ SECTION 1 — CORE PHYSICAL WATER QUANTITY SCHEMAS
	1.	WATER-MASS-KG SCHEMA
	2.	WATER-VOLUME-LITER SCHEMA
	3.	WATER-VOLUME-MILLILITER SCHEMA
	4.	WATER-VOLUME-M³ SCHEMA
	5.	WATER-VOLUME-COERCE SCHEMA
	6.	WATER-VOLUME-CANONICAL SCHEMA
	7.	WATER-DENSITY-SCHEMA (kg/m³)
	8.	WATER-SPECIFIC-HEAT-CAPACITY SCHEMA
	9.	WATER-HEAT-CONTENT SCHEMA (kJ based on mass & ΔT)
	10.	WATER-TEMPERATURE-C SCHEMA
	11.	WATER-TEMPERATURE-F SCHEMA
	12.	WATER-TEMPERATURE-K SCHEMA
	13.	WATER-TEMPERATURE-DEWPOINT SCHEMA
	14.	WATER-TEMPERATURE-WETBULB SCHEMA
	15.	WATER-FREEZING-POINT SCHEMA
	16.	WATER-BOILING-POINT SCHEMA (pressure-corrected)
	17.	WATER-ENTHALPY SCHEMA
	18.	WATER-ENTROPY SCHEMA
	19.	WATER-PHASE-STATE SCHEMA (solid/liquid/gas)
	20.	WATER-PHYSICAL-PROPERTIES-CANONICAL SCHEMA

⸻

✅ SECTION 2 — WATER QUALITY & CHEMISTRY SCHEMAS
	21.	WATER-PH SCHEMA
	22.	WATER-TURBIDITY-NTU SCHEMA
	23.	WATER-HARDNESS-GPG SCHEMA
	24.	WATER-HARDNESS-MG/L SCHEMA (CaCO₃)
	25.	WATER-ALKALINITY SCHEMA
	26.	WATER-CONDUCTIVITY-SIEMENS SCHEMA
	27.	WATER-TDS-PARTS-PER-MILLION SCHEMA
	28.	WATER-TOTAL-CHLORINE SCHEMA
	29.	WATER-FREE-CHLORINE SCHEMA
	30.	WATER-CHLORAMINE SCHEMA
	31.	WATER-NITRATES SCHEMA
	32.	WATER-NITRITES SCHEMA
	33.	WATER-FLUORIDE SCHEMA
	34.	WATER-IRON-PPM SCHEMA
	35.	WATER-MANGANESE-PPM SCHEMA
	36.	WATER-LEAD-PPB SCHEMA
	37.	WATER-COPPER-PPM SCHEMA
	38.	WATER-ARSENIC-PPB SCHEMA
	39.	WATER-PFAS-SCHEMA
	40.	WATER-MICROBIOLOGICAL-CONTAMINANT SCHEMA
	41.	WATER-E-COLI SCHEMA
	42.	WATER-COLIFORM SCHEMA
	43.	WATER-LEGIONELLA SCHEMA
	44.	WATER-CRYPTOSPORIDIUM SCHEMA
	45.	WATER-GIARDIA SCHEMA
	46.	WATER-CHEMICAL-CONTAMINANT-LIMITS SCHEMA
	47.	WATER-SAFETY-RATING SCHEMA

⸻

✅ SECTION 3 — HYDROLOGY / NATURAL WATER SYSTEM SCHEMAS
	48.	WATERFLOW-RATE-M³S SCHEMA
	49.	WATERFLOW-RATE-LS SCHEMA
	50.	STREAMFLOW-DISCHARGE-SCHEMA
	51.	RIVER-DEPTH SCHEMA
	52.	RIVER-WIDTH SCHEMA
	53.	RIVER-CROSS-SECTION-AREA SCHEMA
	54.	RUNOFF-COEFFICIENT SCHEMA
	55.	PRECIPITATION-RATE-MM-HR SCHEMA
	56.	EVAPOTRANSPIRATION-RATE SCHEMA
	57.	EVAPORATION-RATE SCHEMA
	58.	INFILTRATION-RATE SCHEMA
	59.	HYDRAULIC-HEAD SCHEMA
	60.	AQUIFER-DEPTH SCHEMA
	61.	GROUNDWATER-LEVEL SCHEMA
	62.	WATER-TABLE-DEPTH SCHEMA
	63.	FLOOD-STAGE SCHEMA
	64.	DROUGHT-SEVERITY SCHEMA
	65.	HYDROLOGIC-RETURN-PERIOD SCHEMA
	66.	WATERSHED-AREA SCHEMA
	67.	STREAM-GAUGE-HEIGHT SCHEMA

⸻

✅ SECTION 4 — WATER PRESSURE & HYDRAULICS SCHEMAS
	68.	WATER-PRESSURE-PSI SCHEMA
	69.	WATER-PRESSURE-KPA SCHEMA
	70.	WATER-PRESSURE-BAR SCHEMA
	71.	WATER-PRESSURE-HEAD-METERS SCHEMA
	72.	WATER-STATIC-PRESSURE SCHEMA
	73.	WATER-DYNAMIC-PRESSURE SCHEMA
	74.	WATER-FLOW-VELOCITY SCHEMA
	75.	WATER-PIPE-DIAMETER SCHEMA
	76.	WATER-PIPE-LENGTH SCHEMA
	77.	WATER-FRICTION-LOSS SCHEMA
	78.	WATER-HYDRAULIC-GRADE-LINE SCHEMA
	79.	WATER-ENERGY-GRADE-LINE SCHEMA
	80.	WATER-PUMP-HEAD SCHEMA
	81.	WATER-PUMP-CURVE SCHEMA
	82.	WATER-VALVE-KV-SCHEMA
	83.	WATER-ORIFICE-FLOW SCHEMA
	84.	WATER-CAVITATION-INDEX SCHEMA

⸻

✅ SECTION 5 — WATER TREATMENT & PURIFICATION SCHEMAS
	85.	WATER-FILTER-MICRON-RATING SCHEMA
	86.	WATER-FILTRATION-TYPE SCHEMA (RO/UV/carbon/etc.)
	87.	WATER-TREATMENT-STAGE SCHEMA
	88.	WATER-SANITIZATION-METHOD SCHEMA
	89.	WATER-DISINFECTION-LOG-REDUCTION SCHEMA
	90.	WATER-CLARITY-SCHEMA
	91.	WATER-SOFTENER-CAPACITY SCHEMA
	92.	WATER-ION-EXCHANGE-RESIN-SCHEMA
	93.	WATER-REVERSE-OSMOSIS-RECOVERY-RATIO SCHEMA
	94.	WATER-RO-MEMBRANE-TDS-REJECTION SCHEMA
	95.	WATER-UV-DOSAGE SCHEMA
	96.	WATER-OZONE-CONCENTRATION SCHEMA
	97.	WATER-FILTRATION-FLOWRATE SCHEMA
	98.	WATER-PRETREATMENT-SCHEMA
	99.	WATER-POSTTREATMENT-SCHEMA

⸻

✅ SECTION 6 — MARINE / OCEANOGRAPHY WATER SCHEMAS
	100.	SEAWATER-SALINITY-PSU SCHEMA
	101.	SEAWATER-DENSITY SCHEMA
	102.	OCEAN-DEPTH-METERS SCHEMA
	103.	WAVE-HEIGHT SCHEMA
	104.	WAVE-PERIOD SCHEMA
	105.	WATER-CURRENT-SPEED SCHEMA
	106.	WATER-CURRENT-DIRECTION SCHEMA
	107.	WATER-SURFACE-TEMPERATURE SCHEMA
	108.	WATER-DEEP-TEMPERATURE SCHEMA
	109.	TIDE-HEIGHT SCHEMA
	110.	TIDE-PHASE SCHEMA
	111.	SEA-ICE-THICKNESS SCHEMA
	112.	SEA-SURFACE-SALINITY SCHEMA
	113.	CHLOROPHYLL-CONCENTRATION SCHEMA
	114.	DISSOLVED-OXYGEN SCHEMA
	115.	OCEAN-ACIDIFICATION-PH SCHEMA

⸻

✅ SECTION 7 — METEOROLOGICAL WATER SCHEMAS
	116.	HUMIDITY-RELATIVE SCHEMA
	117.	HUMIDITY-ABSOLUTE SCHEMA
	118.	HUMIDITY-SPECIFIC SCHEMA
	119.	CLOUD-WATER-CONTENT SCHEMA
	120.	RAINFALL-INTENSITY SCHEMA
	121.	SNOWFALL-INTENSITY SCHEMA
	122.	SNOW-WATER-EQUIVALENT SCHEMA
	123.	HAIL-SIZE SCHEMA
	124.	ICE-ACCUMULATION SCHEMA
	125.	VISIBILITY-IN-FOG-WATER SCHEMA
	126.	ATMOSPHERIC-WATER-VAPOR-MIXING-RATIO SCHEMA
	127.	PWAT-PRECIPITABLE-WATER SCHEMA

⸻

✅ SECTION 8 — WATER IN AGRICULTURE SCHEMAS
	128.	IRRIGATION-RATE SCHEMA
	129.	IRRIGATION-SCHEDULE SCHEMA
	130.	IRRIGATION-EFFICIENCY SCHEMA
	131.	SOIL-MOISTURE-VWC SCHEMA
	132.	SOIL-MOISTURE-TENSION SCHEMA
	133.	CROP-WATER-REQUIREMENT SCHEMA
	134.	CROP-CANOPY-EVAPOTRANSPIRATION SCHEMA
	135.	WATER-DEFICIT-INDEX SCHEMA
	136.	WATER-LEACHING-REQUIREMENT SCHEMA
	137.	WATER-USE-EFFICIENCY SCHEMA
	138.	LIVESTOCK-WATER-CONSUMPTION SCHEMA
	139.	HYDROPONICS-NUTRIENT-SOLUTION-SCHEMA

⸻

✅ SECTION 9 — WATER FOR HVAC / BUILDINGS SCHEMAS
	140.	CHILLED-WATER-SUPPLY-TEMP SCHEMA
	141.	CHILLED-WATER-RETURN-TEMP SCHEMA
	142.	HOT-WATER-SUPPLY-TEMP SCHEMA
	143.	HOT-WATER-RETURN-TEMP SCHEMA
	144.	WATER-FLOW-GPM SCHEMA
	145.	WATER-FLOW-LPS SCHEMA
	146.	COOLING-TOWER-MAKEUP-WATER SCHEMA
	147.	COOLING-TOWER-BLOWDOWN SCHEMA
	148.	HVAC-WATER-CHEMISTRY SCHEMA
	149.	WATER-LOOP-DELTA-T SCHEMA
	150.	GLYCOL-MIX-PERCENT SCHEMA
	151.	BOILER-FEEDWATER-QUALITY SCHEMA
	152.	STEAM-CONDENSATE-RETURN SCHEMA

⸻

✅ SECTION 10 — INDUSTRIAL / MANUFACTURING WATER SCHEMAS
	153.	PROCESS-WATER-FLOW SCHEMA
	154.	COOLANT-WATER-FLOW SCHEMA
	155.	COOLING-WATER-TEMPERATURE SCHEMA
	156.	BOILER-WATER-TDS SCHEMA
	157.	STEAM-QUALITY SCHEMA
	158.	DISTILLED-WATER-PURITY SCHEMA
	159.	DEMINERALIZED-WATER-RESISTIVITY SCHEMA
	160.	WATER-INJECTION-RATE SCHEMA
	161.	WATER-SEPARATION-EFFICIENCY SCHEMA
	162.	WASTEWATER-INFLOW SCHEMA
	163.	WASTEWATER-OUTFLOW SCHEMA
	164.	WASTEWATER-BOD SCHEMA
	165.	WASTEWATER-COD SCHEMA
	166.	WASTEWATER-TSS SCHEMA
	167.	WATER-RECOVERY-YIELD SCHEMA

⸻

✅ SECTION 11 — UX / UI / APP-LEVEL WATER SCHEMAS
	168.	WATER-INTAKE-TRACKING-DAY SCHEMA
	169.	WATER-INTAKE-TRACKING-LOG SCHEMA
	170.	WATER-CONSUMPTION-GOAL SCHEMA
	171.	WATER-REMINDER-INTERVAL SCHEMA
	172.	WATER-BOTTLE-SIZE SCHEMA
	173.	WATER-LOG-UNIT SCHEMA (mL / oz)
	174.	POOL-VOLUME-CALCULATOR-SCHEMA
	175.	WATER-QUALITY-UI-RANGE SCHEMA
	176.	WATER-FILTER-STATUS-PERCENT SCHEMA
	177.	WATER-DEVICE-STATE SCHEMA (humidifier, purifier…)